### ISSUE TITLE
Wrong and missing Sound

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#10]
MC-Version: 1.10.2
   not tested for 1.9.x

Laser Rifle sound is missing

Granade Luncher plays wrong Sound (only in multiplayer)

**Comment by mcenderdragon** [comment]
what is with:
- E-magent
- optibench
- jump sound
- generator
- laser riffle shot

**Comment by mcenderdragon** [comment]
maybe fixed

**Comment by Wugand** [comment]
generator: OK
laser riffle shot: No Sound
E-magnet: OK
optibench: OK
jump sound: No Sound (we will Test it again)

**Comment by mcenderdragon** [comment]
Test it AS teleportet player. Player in base and target Dimension.

**Comment by Wugand** [comment]
Laser Rifle: Fixed
Granade Launcher: Failed - Cave Sound

**Comment by mcenderdragon** [comment]
pls test it again in mp
