### ISSUE TITLE
Crash by font rendering?

### ISSUE THREAD

**Issue by SerialCrasher23** [mcenderdragon/Futurepack-API#101]
Hi, new to github and issue reporting in general. The game crashes whenever i try to use the e-scanner. Sure conflict with digimobs, because removing the mod seems to resolve the issue. Just to be aware of the possible incompatibility. Below the crash report
http://pastebin.com/W34k6iT8
Edit: I was wrong, the crash seems to be linked to the e-scanner scanning the player

**Comment by mcenderdragon** [comment]
Yep, this is a bug that is very nasty and not real fixable ( I have not yet an idea how to fix it). THis occurse because an Item have an insanly huge NBT tag, and if I try to display that somehow the FontManager from Minecraft dies. This also happens with full bee-backpacks from Forestry

**Comment by mcenderdragon** [comment]
@Wugand plz test.

**Comment by Divineaspect** [comment]
Getting an identical crash with a different pack.

https://gist.github.com/Divineaspect/06606837aa54a56d905e2f9411eb5b0c

**Comment by mcenderdragon** [comment]
does this also happen with (this version)[http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.61]

**Comment by mcenderdragon** [comment]
I will close this issue as it seem to be fixed.
