### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#103]
http://pastebin.com/90eWCF8f

https://minecraft.curseforge.com/projects/futurepack?gameCategorySlug=mc-mods&projectID=237333#c151

Also this should be solved by 25.2.61

**Comment by P3rf3ctXZer0** [comment]
Confirmed bug.

1.10.2 Crash on world load.
https://gist.github.com/P3rf3ctXZer0/ba60698db7f2e189f3ceb9981a6ac750

**Comment by mcenderdragon** [comment]
@P3rf3ctXZer0 this is a completly different crash.

**Comment by mcenderdragon** [comment]
Ok main crash is solved.
