### ISSUE TITLE
[Q] 1.11.2 update?

### ISSUE THREAD

**Issue by mrAppleXZ** [mcenderdragon/Futurepack-API#104]
Hello! Can this mod be updated to 1.11.2?

**Comment by mcenderdragon** [comment]
I have already an instable 1.11 update but I'd like to wait for an recomended forge build for 1.11.2 (currently their are only 2 1.11.2 forge versions)

**Comment by mrAppleXZ** [comment]
OK, thanks =)!

**Comment by MechWarrior99** [comment]
Any update on this? Not looking for an ETA, just checking to see how it is going on the update :)

**Comment by mcenderdragon** [comment]
we have currently a test build on our server running so expect a at leat beta and the end of this week ;)

**Comment by MechWarrior99** [comment]
Oh cool! Looking forward to it thanks! :)

**Comment by mcenderdragon** [comment]
https://minecraft.curseforge.com/projects/futurepack/files/2406648
