### ISSUE TITLE
FTL textures are wrong

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#11]
Textures on FTL-Drive are incorrect or missing, if it connected to multi-block structure

**Comment by mcenderdragon** [comment]
can not confirm

**Comment by Wugand** [comment]
Only in Multiplayer

**Comment by mcenderdragon** [comment]
Do Block updates fix the Problem

**Comment by Wugand** [comment]
No
![bug](https://cloud.githubusercontent.com/assets/11357199/19015542/e0ebf3d2-8806-11e6-8de6-d768376adfef.png)

**Comment by mcenderdragon** [comment]
Im F3 what Stade is used?

**Comment by mcenderdragon** [comment]
In local multiplayer (server hosting on local machine) it works great

**Comment by mcenderdragon** [comment]
This is an issue only ocruse with other mods. (SEM, ic2, forestry, jei, journeymap, morebees) , and only IC2 has a coremod. The blocks are on the server correct, but on the client the top flaf is always false. Dunno why.

**Comment by mcenderdragon** [comment]
THIS is a forge problem!

in version 2014 it works. In forge 2094 it did not. But only in multiplayer.

**Comment by mcenderdragon** [comment]
Working FTL block
![2019-02-04_09 57 30](https://user-images.githubusercontent.com/6342933/52198498-584faa00-2863-11e9-8772-39f636145ee4.png)
