### ISSUE TITLE
Crash while initializing (most likely mod conflict)

### ISSUE THREAD

**Issue by Icebelly** [mcenderdragon/Futurepack-API#110]
Just as stated in the title.

It does manage to boot and start loading, but once it gets into the later stages of loading the mods it crashes.

http://www.mediafire.com/file/zt5cdni5adm6awq/fml-client-latest.log

The log was too long to copy in pastebin, I apologize.

**Comment by mcenderdragon** [comment]
You are using a (sorry but this crash happens far to often and it is realy annyoing and I am also stressed) crappy launcher. Just use the vanilla one and this crash will disappear.  Also I am curious

**Comment by Icebelly** [comment]
I'm using the old FTB launcher from before they switched to the curse launcher.

**Comment by mcenderdragon** [comment]
Hmm that is new... are you using a custom JVM ? And does this also happen with the vanilla launcher

**Comment by Icebelly** [comment]
Nope, no custom JVM arguments. Just tried to use a different launcher. In this case MultiMC and it booted fine with no issue while using the same modpack.

**Comment by mcenderdragon** [comment]
Yeah somehow the other launcher are not including all required classes so this error happens:
`java.lang.ClassNotFoundException: jline.internal.InputStreamReader`
