### ISSUE TITLE
[v24.2.58] Minecraft 1.10.2 Optibench Dupe Bug

### ISSUE THREAD

**Issue by kingofrunes** [mcenderdragon/Futurepack-API#111]
I've discovered a dupe bug with the optibench when you have a repeat loop between two optibenches.

Reproduction Steps
1) Setup an optibench that takes 9 iron ingots and make it into an iron block
2) Setup another optibench that turns an iron block into 9 ingots
3) Hookup the optibenches so they output to each other in a continious loop
4) Chunk load it (unsure if me chunkloading it is what caused the problem or not) and come back to it later

Came back to my setup several times to see 9 iron ingots suddenly being 9 stacks of iron ingots instead

**Comment by mcenderdragon** [comment]
are you shure :P
