### ISSUE TITLE
Future Pack Compatibility

### ISSUE THREAD

**Issue by Liinche** [mcenderdragon/Futurepack-API#113]
If ProjectE is installed with Futurepack the repair talisman from ProjectE increase the Support point on the Flash Memory i think it should not do this so you could make Flash Memory use something else than durability to stock the point
PS:Sry for my english im from France 

But i love your mod keep it up <3

**Comment by mcenderdragon** [comment]
If i fix this, it will cause a major break of many items (as all NE or SP containing items are effected)
This will be fixed in the 1.11. But PorjectE should porbeblx check if the itewm is a tool or sword and not just repair everything.

**Comment by mcenderdragon** [comment]
@Wugand.
we need to remove the big batterys in 1.11, cause damage value uses short, but only the positiv ones, so maximal 32767. and not 100.000 (which is IMO too much anyway)

**Comment by mcenderdragon** [comment]
Does this still happening in the 1.11?
