### ISSUE TITLE
Centrifuge not working

### ISSUE THREAD

**Issue by Imaginativesoul** [mcenderdragon/Futurepack-API#115]
After logging in the centrifuge is not working.  It is fully powered and the computer components are all in good order, yet when I put a resource in the machine it does not work.

**Comment by mcenderdragon** [comment]
wich version ? (forge & fp)

**Comment by mcenderdragon** [comment]
And have you enough of that research. Also some recipes need support points.

**Comment by Imaginativesoul** [comment]
Whoops! Apologies, here are the details:
Minecraft version: 1.10.2
Forge: 12.18.3.2221
FP: 24.2.58 pre

I have all of the necessary research.  In fact, the centrifuge was working, I logged in after playing and the centrifuge did not work (it had power). I was trying to decompose cobblestone (which had worked before) and suddenly the centrifuge just stopped working.  Please let me know if you need more data.

Just want to say that this is a fantastic mod with tremendous potential, thank you for building this!

Is there any way to determine what the power output (RF/tick, etc?) of the generators are?  I know the batteries get charged, but it would be nice to see some metrics from solar panels, water turbine, infusion generators, generators, and especially the neon engine.  I know they are working by the texture change, but I'd like to know how much energy I get from the device (thus determining whether to make an opti-bench recipe and mass produce them).  Right now I can't quite tell if the neon engine or the solar panels are really charging anything (or worth building).  

{WAILA (What am I looking at) support in regards to energy values would be appreciated, if this is an easy developer addition. I know you all have a large queue of priorities in your queue}

Anyway, thanks for a great mod, it has kept me busy and bedeviled me for many hours of fun researching, and dimension traveling. keep up the excellent work!

**Comment by mcenderdragon** [comment]
In the Overtune GUi (rightclick with Scrench at a machine) you see the current neon use / production, per machine tick. The Neon Engine uses 1NE and makes 2RF and the more NE is opumped in the more RF is coming out. 

I think maybe some part got burned but you checked that... I will test around and try to reproduce that.

**Comment by mcenderdragon** [comment]
I this still happening or is it working now ?

**Comment by mcenderdragon** [comment]
seems like its working...
