### ISSUE TITLE
assorted research problems

### ISSUE THREAD

**Issue by Zygus42** [mcenderdragon/Futurepack-API#117]
v. Futurepack-1.10.2-24.2.58, forge-1.10.2-12.18.3.2185
- [x] SpaceTravel:Teleporter research is not quite right.  When you activate the research, the bar underneath the empty large batteries goes blue immediately, then the bar under the minecart fills up with SP, then nothing else happens for about 15-20 minutes and then the research finishes eventually.  Have tried removing the recipe and restarting, using a different researcher machine, etc.
- [x] Tools:Neon Sword and Tools:E-Scanner research have no entries.  Both say to contact the mod developer.
- [x] (not 100% verified) at an early point in the research, there are a number of researches that you need empty flash memory as components for.  In JEI, all 5 types of empty flash memory are called empty flash memory, but the researches will only accept the 2nd type, which is the empty improved redstone flashdrive made using obsidian.  We're pretty sure that it's not possible to have the research for that type of drive before doing the researches, and thus the researches should be using the empty simple redstone flashdrigve instead, but as we got the server to hand us some of those drives, we then did all those researches and were then able to build the empty improved redstone flashdrives, so we're not sure which research opened it up.
- [x]  (not certain this is a problem) Story:??? need Neon Crystal research has never opened up, despite scanning Neon Crystals, Neon Sand and Neon Crystal Blocks.
- [x] Futurepack Bauxite Ore blocks are not equivalent on the ore dictionary with other mods Aluminium ores or Bauxite ores.  Specifically, we're using Immersive Engineering Bauxite ore and also have Base Metal Aluminium.  The ingots are all compatible, and the other ores are with each other, but not with Futurepack Bauxite Ore.  This makes the research for aluminium impossible to do in our world without cheating in some ore.

Please let me know if you need any further data / clarification.

**Comment by mcenderdragon** [comment]
@Wugi please look into this.

**Comment by Wugand** [comment]
OK:

1. We currently don't know why this happens, but we have reproduced the bug ... we try to fix it.

2. Yes this texts are currently unfinished, we try to complete them until the next release.

3. We already fix that, but it's currently not in the release builds. (There was an translation fault.) Also the research flow around the T2-Module is changed.

4. The entry which depends Neon Crystal is unlocked very late (~Spaceship Thrusters). Theoretically it should work ... 

5. Ok, we forget it or use a diffrent spelling. We going to fix it.

Thank you for feedback!

**Comment by Wugand** [comment]
to 5.
We added "oreAluminum" as an alternative for the Research. But note that this don't make the ores compatible, you only get the chanche to unlock all content, without having Bauxite from our mod. (in other words you don't need our ore)

**Comment by Zygus42** [comment]
Thanks for your prompt response, and the fun mod.

We did find one more item since posting above, also to do with oreDictionary I'm guessing.  When you process Alutine crystals in the Industrial Neon Furnace, you get an Aluminium Plate from FuturePack, but you also get an Aluminium Ingot from ImmersiveEngineering and an Aluminium Ingot from TechReborn, and I'm guessing that if the machine had another slot you would also get an Aluminium Ingot from BaseMetals, which is the other mod that adds Aluminium Ingots.  So effectively instead of making 1 aluminium, it makes 3 for each crystal of Alutine.

**Comment by mcenderdragon** [comment]
lol, this shoould not happen ^^

**Comment by savosdarkran** [comment]
In regards to item #3 in the list above, any updates on that?  I'm currently in the predicament where I'm in need of improved flash drives for research but do not have the ability to actually craft them or unlock them.  I'm also finding that fluid tubes are not available either for crafting/research.  I tested this in the latest 1.11.2 release.

**Comment by mcenderdragon** [comment]
#3 is and never was a problem

**Comment by savosdarkran** [comment]
Well I don't have fluid tube research available and nothing else in order to move forward.  Don't know what to say here.

**Comment by Wugand** [comment]
#3 is fully fixed:
- empty flash drives has unique names (1.10.2) AND have been removed later (1.11.2)
- "improved flash drives" is researchable
but at the point of "improved flash drives" and "AI-chip" there are some paths which ends in "you need the flash drive", so for the next release we add some extra "dependenies", to guide the player the right way.

Solution:
1. From "Renewable Energy" you can resesrch "Upgraded AI-Memory" (Basic - Tab)
2. From "Simple R. Flash Drive" you can resesrch "improved flash drives"   (Logistics - Tab)

Fluid system is not completed yet, but we work on it.

**Comment by savosdarkran** [comment]
That makes total sense.  I just need fluid tubes in order to research renewable energy.  Please see images attached:

![image](https://cloud.githubusercontent.com/assets/26523998/25350808/56dd9ea4-28f4-11e7-8e7e-3ec291e673ec.png)
![image](https://cloud.githubusercontent.com/assets/26523998/25350821/6552723e-28f4-11e7-87ef-fcc818dfdc20.png)

**Comment by Wugand** [comment]
Mh...
Sorry, I am missunderstoud it.
Yes this is totaly wrong! I going to fix it, wait an moment. We tell you if the fix is ready.

**Comment by savosdarkran** [comment]
No worries.  Thank you for being patient.  I really appreciate it.  This mod is awesome.  I just don't want to miss anything.

**Comment by mcenderdragon** [comment]
After this files gets reviewed the fix is finished https://minecraft.curseforge.com/projects/futurepack/files/2411410

**Comment by savosdarkran** [comment]
Thank you !!  Awesome support!

**Comment by mcenderdragon** [comment]
Ok the first issue with the neon bar doing weird stuff should also be fixed. at least in 1.11.

**Comment by mcenderdragon** [comment]
yeah by now this should be fixed
