### ISSUE TITLE
Support pipe and Redstone pipe look the same

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#12]
Both pipes got the same "off" texture.
The Redstone pipe sould get an other one with an red stripe

**Comment by mcenderdragon** [comment]
is there already a new one?

**Comment by Wugand** [comment]
-Textures Comitted & Pushed to 1.9.4-
Pipe2_redstone_off.png
Pipe2_support_off.png

**Comment by mcenderdragon** [comment]
Kay
