### ISSUE TITLE
E-Scanner crashes Minecraft when scanning air 

### ISSUE THREAD

**Issue by frenzye** [mcenderdragon/Futurepack-API#121]
I can right click on blocks with the E-Scanner just fine, but if I right click with the E-Scanner in the air it crashes the client 

http://pastebin.com/pYKqX3Nt
http://pastebin.com/FKKsr9HP

**Comment by mcenderdragon** [comment]
you have something in you Inventory that has an insane huge NBT tag, very often its something like an full bee backpack from forestry. Does this still happen in (this)[http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.107] version ?

**Comment by mcenderdragon** [comment]
Did the version I gave yu fixed the problem ?

**Comment by frenzye** [comment]
I want to stay on Curse because it would make it easier for me to push the updated jar, I see version 24.2.113 and 24.2.118 would either work to test?

**Comment by mcenderdragon** [comment]
yeah the curse version (118) in newer

**Comment by frenzye** [comment]
I used 24.2.118 and issue seems to be gone, though I lost the inventory that was originally giving the crash. I put a few items that I thought might have big NBT values like an iron backpacks fully upgraded backpack in the inventory and didn't get a crash so it seems good so far.
