### ISSUE TITLE
Sharing Knowledge

### ISSUE THREAD

**Issue by kremnev8** [mcenderdragon/Futurepack-API#122]
Is there any method to share my knowledge to other player?

**Comment by mcenderdragon** [comment]
Currently not, but I let all doors open for other mods to do this.

**Comment by kremnev8** [comment]
If i copy my file from FP_Research folder and rename it to player UUID will he get my knowledge?

**Comment by mcenderdragon** [comment]
yes

**Comment by kremnev8** [comment]
How this files encoded? I tried to open it with NBTExplorer, but he can't.

**Comment by mcenderdragon** [comment]
I use my own combination of formats, but 7zip and WinRar should be able to open it.
