### ISSUE TITLE
Crash when opening AirBrush GUI

### ISSUE THREAD

**Issue by kremnev8** [mcenderdragon/Futurepack-API#124]
Imminently after opening Airbrush i got this crash:
http://pastebin.com/F4xpEc7s

**Comment by mcenderdragon** [comment]
It should be fixed [here](http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.118)

**Comment by mcenderdragon** [comment]
Does it work ?

**Comment by kremnev8** [comment]
Yes.
