### ISSUE TITLE
Syncronisation Problem with WaterCooler

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#127]
Happens only with Dedicated Server (last test).
Using the following (often used) construction:
![aufbau](https://cloud.githubusercontent.com/assets/11357199/23335215/78de9ad8-fbb0-11e6-8388-901c998ea7d1.png)
*A highly overclocked machine is cooled by an WaterCooler; which is automaticly refilled with water buckets (this part works correctly).

At Server side anything is correct and the System works.

But at client side: 
You have the last known state of the WaterCooler, normaly by looking into the GUI. So its smoking a while and consume the water (**client is never informed about the automatic refilling**). At this point no big problem, but if you look into the GUI or Upgrade GUI the system burns down in some seconds and it seems the machine is inoperable (also in normal GUI). So at all you are not able to work with the overclocked machine, unless you look into the WaterCooler every ~ 30 Seconds.

**Comment by mcenderdragon** [comment]
Also found out why the mecanism steam is not working.
https://github.com/aidancbrady/Mekanism/blob/81e810794581cabba8925634f93f1323400014cb/src/main/java/mekanism/common/MekanismFluids.java#L33
https://github.com/CovertJaguar/Railcraft/blob/c4b1f8531a11e7b0517169135f852b2f86970326/src/main/java/mods/railcraft/common/fluids/RailcraftFluids.java#L35

**Comment by mcenderdragon** [comment]
The only real problem is the items ore gone at client in Chipset Gui and nothing more ?

**Comment by Wugand** [comment]
Ok add to the problem, that it schould allways smoking, if it cools a machine.

So Other Idea: We don't need the amout of fluid, only on and off.
So we can use a meta state for on (can cool and is smoking) and off (no smoke, empty, no cool).
The state is changing if the watercooler gets empty(0mB) and full(>=1mB)

**Comment by mcenderdragon** [comment]
I dont like this way of "fixing" at all., because if a fluid mod is installed stil whould no longer work or result in an blockstate update spamming.

**Comment by mcenderdragon** [comment]
solved in 123
