### ISSUE TITLE
[Request] Crafttweaker/minetweaker support

### ISSUE THREAD

**Issue by meelock** [mcenderdragon/Futurepack-API#131]
First of all, I know this might use some reworking, but I think the mod has reached a point of popularity that crafttweaker support is needed for the mod to be added to more modpacks.

I hope you consider adding support for crafttweaker, also, because I am working on a modpack that will be heavily tweaked, and want to tweak futurepack to fit the progression!

thanks!

**Comment by mcenderdragon** [comment]
what is Crafttweaker/minetweaker? Never realy heard of it. If its about changing recipes and stuff then this is already possible.

**Comment by mcenderdragon** [comment]
they dont have support for it, but it is possible to change the recipes and adding/removing them, also researches are change/remove/addable

**Comment by meelock** [comment]
Well, as long as your way of changing is intuitive, and supports modded items, this is as good as closed. But full crafttweaker would be super nice, as I know it well, and prefer if all reipes were in the same place.

Ps. This was writen from my phone.

**Comment by mcenderdragon** [comment]
everything is made via json inside the jar, and I dont have hash checks or something like that so the eddited versions gets accepted

**Comment by meelock** [comment]
Can you please at least add config based recipes, so that people don't have to modify your jar for every version of their modpack. (What kind of person would modify one of the mods to change recipes, that's just ludicrous in the current age of modding.)

**Comment by meelock** [comment]
I know that this change might require a major refactor, but I feel that I can speak for the sake of others that some sort of way of easily changing parts of this kind of mod is needed for major scale adoption.

**Comment by meelock** [comment]
I hope you understand this request and take it seriously, I also do not mean to sound intrusive, if what I am requesting is going against the initial idea of futurepack.

thanks.

- meelock

**Comment by mcenderdragon** [comment]
Ok I donst understand Crafttweaker at all. And the APi is weird, I cant find any usefull structure in there. What does Crafttweaker besides from changing recipes and hiding items. The APi looks like it can write complete mods with these scripts.

**Comment by meelock** [comment]
The point of crafttweaker is to change/remove/add recipes to mods/Minecraft. Crafttweaker is basically minetweaker, but updated, and if you look at any large modpack in 1.7, most of the content changed is minetweaker scripts.

thanks.

meelock

**Comment by mcenderdragon** [comment]
Ok it seems like i first need to leran the script thingy to understant what it does but it seems heaviliy overloaded and the script resembles java very mush. IMO they could just write java code but yeah I will try to implemente it. In wich version do you need it 1.10 or 1.11 ?

**Comment by meelock** [comment]
1.10 preferably, also crafttweaker is meant as a TWEAKER not as a MOD MAKER, it was never meant as a mod maker and if you use it for that your doing it wrong.

**Comment by meelock** [comment]
recipes.remove(<betterwithmods:single_machine:3>);
recipes.addShaped(<betterwithmods:single_machine:3>,
		[[<primal:iron_sheet>, <minecraft:bone>, <primal:iron_sheet>],
		[<primal:iron_sheet>, <minecraft:water_bucket>, <primal:iron_sheet>],
		[<primal:iron_sheet>, <primal:iron_sheet>, <primal:iron_sheet>]]);

this script changes a recipe, it is 100* simpler than writing a mod to do this.

**Comment by meelock** [comment]
mods.betterwithmods.Cauldron.add(<embers:nuggetIron> * 3, <primal:carbonate_ferro_slack> * 5,
		[<plastitech:ItemSlag_iron_dust> * 3]);

this script changes a modded recipe, if you were to try to do this in java it would take hours, but better with mods has crafttweaker support, and as such is easy to configure.
[Better with mods](https://github.com/BeetoGuy/BetterWithMods) is a great example of crafttweaker intergration.

**Comment by mcenderdragon** [comment]
Ok I am not shure if I am able to add support for altering resaerches or make new ones but recipes for the machines should work. 
And yeah the scripts are reduced to the code that is actualy doing the modfication, and not the huge stuff around needed for it to work.

**Comment by meelock** [comment]
That sounds good to me! If it is not too hard to implement... thanks for your consideration!

**Comment by meelock** [comment]
also, hear me out... I think if would be much better if futurepack created files outside of the jar where researchers can be changed. Why i say this is because, for most mods, users are highly discouraged from editing files inside of the compiled jar file for a mod, and if they do, it will be treated as if they are making the mod their own and violating all sorts of licences, if they were to ever release the changed mod in a modpack.

**Comment by mcenderdragon** [comment]
I have written the implemnentation so far, but it seems like the api code from crafttweaker is faulty so gradlew wont build the project.

**Comment by mcenderdragon** [comment]
Ok its was some fault wiht the java version...
Anyway can you try [this](http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.128) version, there a basic minetweaker support is implemented.
