### ISSUE TITLE
Pumpe drops with wrong meta

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#133]
Destrying the fluid pump will drop the wrong meta (the rotation depend value, but it should be 0)

**Comment by mcenderdragon** [comment]
1.10 or 1.11?

**Comment by Wugand** [comment]
1.10

**Comment by mcenderdragon** [comment]
Pump add sound: https://www.freesound.org/people/mickfire/sounds/326424/ and also ix sounds for other machines
