### ISSUE TITLE
Redstonecable is not powered by Redstone

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#136]
In some setups the redstone visually connect, but the redstonecable don't get powered.

![redpipe](https://cloud.githubusercontent.com/assets/11357199/24076282/17cffa24-0c2d-11e7-81aa-30b2aef68375.png)

Testet in 1.11

**Comment by mcenderdragon** [comment]
Yeah and this is intended, and was also in 1.10.2 and before
