### ISSUE TITLE
[feature request] config option to adjust wardrobe(Dungeons) loot

### ISSUE THREAD

**Issue by Zygus42** [mcenderdragon/Futurepack-API#140]
Would it be possible to add a config setting for how much metal loot is found in wardrobes in spawned bases ?  In the game we just had, no one ever made a bar of Composite Metal or Magnet Ingot because we found so many in wardrobes.

**Comment by Zygus42** [comment]
well, consider this as an option to any dungeons you make, as different servers have different loot levels they're comfortable with.

**Comment by mcenderdragon** [comment]
well check out the new dungeons, I hope we have adressed all your conserns.
