### ISSUE TITLE
[ suggestion] use for toasted chips & cores

### ISSUE THREAD

**Issue by Zygus42** [mcenderdragon/Futurepack-API#141]
Would be cool to have a use for all the toasted chips & cores found in bases.  Maybe recycle them in one of the machines and extract something useful from them ?

**Comment by mcenderdragon** [comment]
a recycler is allready in progress :P, but it needs further testing

**Comment by mcenderdragon** [comment]
the recylcer is done and implemented an dresearch able. I will close this :)
