### ISSUE TITLE
ItemSpaceShip changes to Konstruktionskopierer

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#144]
In many situations: Inventory, Crafting, Research discription, ... 
Some items of "ItemSpaceShip" change their texture to "Konstruktionskopierer" for a short while or semi-permanently

**Comment by mcenderdragon** [comment]
Propably related to this https://github.com/mcenderdragon/Futurepack-API/issues/82

**Comment by mcenderdragon** [comment]
it seems like ev erytime a packet is send for 1 frame the fp:spaeshipo is rendered as if it has meta data 0

**Comment by mcenderdragon** [comment]
https://media-minecraftforum.cursecdn.com/attachments/290/254/636776459206827764.png

**Comment by mcenderdragon** [comment]
This happenns on network activity (e.g. you click a slot) and only for the first item fp:spaceship in any inventory.
