### ISSUE TITLE
[1.11.2] Holding shift while hovering mouse over block breaker results in crash

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#149]
Hello,

I have an issue where I put my mouse over a block breaker and hold shift it crashes the game.  There's a tooltip on the block breaker that says this functionality is available.

I have attached my crash reports.  I am able to reproduce this.

[crash-2017-04-19_20.06.23-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/938933/crash-2017-04-19_20.06.23-client.txt)
[crash-2017-04-19_19.40.33-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/938934/crash-2017-04-19_19.40.33-client.txt)

**Comment by mcenderdragon** [comment]
Does [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.1) fix the Bug ?

**Comment by savosdarkran** [comment]
Works great!  I see you removed the "shift" part.  I guess block breakers don't actually have an inventory of sorts?

**Comment by mcenderdragon** [comment]
no I have not removed the shift part, every block of the futurepack drops with its items inside, if there are items or other setting saved, the tooltip turn green and the shift option is displayed.
