### ISSUE TITLE
Machines should on accept usefull Items

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#15]
Machines, like Super Crusher, Furnace, ... sould only accept Items that are prcessable by the machine.

**Comment by mcenderdragon** [comment]
someone could add a dirt recipe. This is trivial, players should decide what they are putting into a machine

**Comment by Wugand** [comment]
Whats the problem to check, if their an smelting recipe. Or an Recepie in the corresponding RecepieManager?

**Comment by mcenderdragon** [comment]
It will result in an performance issue. Besides it is unlogical.

**Comment by mcenderdragon** [comment]
make a list of not working blocks:

**Comment by Wugand** [comment]
Also nice for:
Centrifuge!
Neon Industrial Furnace (if possible)
Industrial Furnace (i don't know)

**Comment by mcenderdragon** [comment]
pls test in curent version.
