### ISSUE TITLE
[1.11.2][25.2.1] Question: The research for the redstone pipe

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#150]
Hello,

I am in the process of researching redstone pipe and find that the progress doesn't increase.  I have included a screenshot of the gui.

![image](https://cloud.githubusercontent.com/assets/26523998/25259840/86c8045a-2616-11e7-925c-7c167f84c90f.png)

My question is:  Is that the right configuration for the research recipe?  It is 8 redstone dust and 2 normal pipe as per the blueprint.

**Comment by savosdarkran** [comment]
Happening with Neon Engine too.

**Comment by mcenderdragon** [comment]
THis is correcty but second bar is gray wich means you have not enough neon energy in your T1 modul

**Comment by savosdarkran** [comment]
AH HA!

Thank you so much!  Having a blast with the mod by the way.  Keep up the great work.
