### ISSUE TITLE
[1.11.2] Optibench results in crash when holding shift while mouse is over

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#151]
Hello,

I originally got this crash with 25.2.1 so I updated to .2 and still received the client to desktop crash.  I have attached my crash-reports for both versions.

[crash-2017-04-21_13.21.12-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/947807/crash-2017-04-21_13.21.12-client.txt)
[crash-2017-04-21_13.13.31-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/947808/crash-2017-04-21_13.13.31-client.txt)

Appreciate your help.

**Comment by savosdarkran** [comment]
This is happening with the Neon Furnace as well.

[crash-2017-04-22_08.19.28-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/948956/crash-2017-04-22_08.19.28-client.txt)

**Comment by mcenderdragon** [comment]
Does this also happen in the 25.2.3 ?

**Comment by savosdarkran** [comment]
Seems to be working good now for both.
