### ISSUE TITLE
[Feature Request] TechTable and question

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#152]
Hello,

I have a couple of ideas that might make the techtable even better.

1. plus sign to techtable for crafting via JEI.
2. minus sign or arrow button to deposit/merge items into internal inventory.

Really enjoying the mod.  Thank you for all your work.  Is there a place for people to discuss the mod?  Discord or Curse group?

**Comment by mcenderdragon** [comment]
We have a TeamSpeak

**Comment by savosdarkran** [comment]
So let's say you have items in the crafting grid and you want to take them out.  Instead of taking individual items out one by one or stacking and then taking them out, you just press a button on the interface and they go back into the internal inventory of the Techtable.

Also, how do I collect SP?

**Comment by mcenderdragon** [comment]
The Optibench and the E-Furnace produce them, by crafting/smelting items.

**Comment by mcenderdragon** [comment]
In the next build for 1.11 we will support the JEI plus button In all machines!

**Comment by mcenderdragon** [comment]
since + button support is implemented I will close this.
