### ISSUE TITLE
[1.11.2] Neon Furnace and Super Crusher stop half way through operation

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#155]
Hello,

I have a Neon Furnace and Super Crusher setup and powered.  Neither one seem to finish their operation and I'm getting the following error in the server console.

https://pastebin.com/smy6Uegg

Many thanks.

**Comment by savosdarkran** [comment]
Here are images of the gui and setup.

![image](https://cloud.githubusercontent.com/assets/26523998/25304736/5541c1ac-273b-11e7-9f40-e571fb615905.png)
![image](https://cloud.githubusercontent.com/assets/26523998/25304741/653b9ef2-273b-11e7-8dee-b5e42a4c57d1.png)
![image](https://cloud.githubusercontent.com/assets/26523998/25304748/7e4f73fa-273b-11e7-8c63-29baae8e651e.png)

**Comment by mcenderdragon** [comment]
Have you checked if the parts are still working?

**Comment by savosdarkran** [comment]
still going at the same spot.

**Comment by mcenderdragon** [comment]
No I means the computer omponents, the chips/rams/core are they still fine or have they burned?

**Comment by savosdarkran** [comment]
The super crusher doesn't take components, does it?  If so, where would I find that the gui doesn't have a spot for it.

**Comment by savosdarkran** [comment]
I've sat here for three hours with no change in progress.

**Comment by mcenderdragon** [comment]
just use the scrench to open the modification gui and make pictures.

**Comment by savosdarkran** [comment]
Wow, I'm an idiot.  I totally get it now.  Cheers.
