### ISSUE TITLE
NPE when opening AirBrush inventory

### ISSUE THREAD

**Issue by Dykam** [mcenderdragon/Futurepack-API#156]
A NullPointerException when trying to open the AirBrush to set the tank/color.

#### Versions
Minecraft 1.11.2
Forge 13.20.0.2282
FuturePack 25.2.2 pre

#### Crashlog
https://gist.github.com/Dykam/739c3a62205c714de0e9b04cf8545f2e

**Comment by mcenderdragon** [comment]
I can not reproduce this crash... you crafted a new airbrush and as you tried to open it, the game crashed ?

**Comment by mcenderdragon** [comment]
Ok I was able to fix the bug, this only happens if the NBT tag from the airbrush is corrupted.

**Comment by Dykam** [comment]
It was a freshly created air brush, but I'll wait for the release to see if that fixed it.

Checking the NBT data, it appears alright: 
![image](https://cloud.githubusercontent.com/assets/63073/25383911/6245e448-29be-11e7-9ad9-fff4ed500b5b.png)

**Comment by mcenderdragon** [comment]
the tag should be missing in new created items. But maybe a mod is changing that.

**Comment by mcenderdragon** [comment]
Can you test if [this version](redsnake-games.de/Downloads/fp/fp.php?version=25.2.4) fixes that?

**Comment by Dykam** [comment]
Perfect, that fixed it.
