### ISSUE TITLE
[1.11.2][25.2.3] Penton Memory recipe not working.

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#157]
You're probably getting sick of me but, I am trying to craft Penton Memory but it's not actually showing up in the assembly table.

I have 3 Silicon Wafers, 3 Neonparts, and 1 improved redstone flashdrive.    I even tried with support points in the table.

Image attached without SP.

![image](https://cloud.githubusercontent.com/assets/26523998/25371585/8026043e-295f-11e7-87d1-4e419a365009.png)

**Comment by mcenderdragon** [comment]
and no, it is in fact great that you report the bug, and not just complain without notifying use what is realy happening :)

**Comment by mcenderdragon** [comment]
Can you test if [this version](redsnake-games.de/Downloads/fp/fp.php?version=25.2.4) fixes that?

**Comment by savosdarkran** [comment]
This is resolved in .4
