### ISSUE TITLE
[1.11.2][25.2.3] Missing Texture for Plasma Cutter

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#158]
The plasma cutter is showing up as a black and magenta checkerboard.

Please see attached image:
![image](https://cloud.githubusercontent.com/assets/26523998/25371732/22099f22-2960-11e7-9841-fb8bea97f208.png)

**Comment by mcenderdragon** [comment]
The interesting thing is, the plasma cutter from the creativ inv has a texture...

**Comment by savosdarkran** [comment]
It's fine in the creative menu for me as well.

**Comment by savosdarkran** [comment]
Oh...you solved it ;)  Thank you !  It was fine in the creative menu for me now that I look.  Thanks again.

**Comment by mcenderdragon** [comment]
the 25.2.4 fixing this is on the go...

**Comment by mcenderdragon** [comment]
Can you test if [this version](redsnake-games.de/Downloads/fp/fp.php?version=25.2.4) fixes that?

**Comment by savosdarkran** [comment]
I'm still seeing the broken texture.  Let me check on this a bit later.  I have a meeting to get ready for.  I will let you know.  Thanks for helping out with this.

**Comment by mcenderdragon** [comment]
well if you craft that item again it should be fixed. (This is the fault of the json model shit that was introduced with 1.8)

**Comment by savosdarkran** [comment]
Awesome.  It's working!
