### ISSUE TITLE
[1.11.2] Generation Question -- Dungeons

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#159]
I read something about the dungeons in the 25.2.2 update that -disabled huge dungeons ( the large complexes ).

Does that mean that they no longer spawn?  We've been 10000 blocks away from spawn in all directions without seeing one.

Please let me know

**Comment by mcenderdragon** [comment]
yeah they are gone.

**Comment by Wugand** [comment]
A new version of them is in progess. But this will need some more time. 
The old was currently removed, because of issues with the preperation for the new ones. 
(And some critism about the resource overkill of them)

**Comment by kleshchevand** [comment]
They were nice) may be just let them spawn much rarer and add some defenses?

**Comment by Wugand** [comment]
The plan is an fully protected and very rare dungeon with multiple layeres and bosses, where you can come back again at diffrent technologie states to reach deeper. So only in the very late game you can finally clear them (and remove protection)
