### ISSUE TITLE
[1.11.2] Grappling slime asking for XP to research

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#160]
The Grappling Slime is asking for xp in order to research it.  Is this right?

![image](https://cloud.githubusercontent.com/assets/26523998/25457416/34cf9194-2aa4-11e7-920f-30088904ee98.png)

![image](https://cloud.githubusercontent.com/assets/26523998/25457393/1cb49730-2aa4-11e7-9596-ebcc8f4b8828.png)

**Comment by mcenderdragon** [comment]
it want's item air...

**Comment by savosdarkran** [comment]
I air ya.

**Comment by mcenderdragon** [comment]
[This version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.8) should fix that.

**Comment by savosdarkran** [comment]
This works, thank you!
