### ISSUE TITLE
[1.11.2] Assembly table not using oredict? - Mekanism

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#161]
When I go to craft a logic circuit and try to use a mekanism ingot ( as per the e-scanner ) it doesn't allow me to.  I have to use an fp ingot.

![image](https://cloud.githubusercontent.com/assets/26523998/25457476/796516f8-2aa4-11e7-970e-ca03f113ae9a.png)

![image](https://cloud.githubusercontent.com/assets/26523998/25457488/897407b6-2aa4-11e7-8327-c98329bba656.png)

**Comment by mcenderdragon** [comment]
no we support ore dict.... it should work.....

**Comment by mcenderdragon** [comment]
it is possible mekanism registers their items to late, so our recipes dont work, does jei show a recipe with the mekanism ingot?

**Comment by savosdarkran** [comment]
That's possible.  I see Forestry, Embers and FP ingots.

**Comment by mcenderdragon** [comment]
yep then somehow they doing it after our init, this is something I cant realy change...

**Comment by savosdarkran** [comment]
I'll open an issue with them.

Thanks again!
