### ISSUE TITLE
[1.11.2][25.2.4] Flash Server Research

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#163]
Requires 4 glowstone flashdrives, but you cannot stack them.

Also, I think there might be a typo in flashdrive for this particular item.

**Comment by mcenderdragon** [comment]
ans the old system is tryking again :/ @Wugand any ideas how to fix that ?

**Comment by savosdarkran** [comment]
All good.  Let me know if there is anything I can do to help with it.

**Comment by Wugand** [comment]
It's much cheaper, but the best solution is to set the stacksize to 1.

(change is allready pushed)

**Comment by mcenderdragon** [comment]
[This version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.8) should fix that.

**Comment by savosdarkran** [comment]
Trying now

**Comment by savosdarkran** [comment]
This works.  Thank you.
