### ISSUE TITLE
Wiki Discussion

### ISSUE THREAD

**Issue by meelock** [mcenderdragon/Futurepack-API#164]
I have made a new version of the wiki explaining CraftTweaker integration, it is based on @betterwithmods' wiki.

link: https://pastebin.com/UcUvcBTd

**Comment by mcenderdragon** [comment]
Ohh thanks.
Updated!

**Comment by mcenderdragon** [comment]
But it seems like the @param dont work.

**Comment by meelock** [comment]
I'll look for a fix when I have the time, thanks!

**Comment by meelock** [comment]
If you could turn on wiki editing, that would be appreciated. thanks!

**Comment by meelock** [comment]
ok i think you just need to add <pre><code></code></pre> to the start of the wiki.

**Comment by meelock** [comment]
ok i think you just need to at ><pre><code></code></pre> to the start to fix the wiki.

**Comment by meelock** [comment]
ok try this instead: https://pastebin.com/CAf5994F

**Comment by mcenderdragon** [comment]
I have edited it, the @param stuff seems to still have problems. Unfortunetly I dont know to to enable the edit mode on wikis, there are is only an on/off switch in the settings :/

**Comment by mcenderdragon** [comment]
ok the line break is fixed with <br>, and I made all params bold for better eadability. thank you for the great entry :)

**Comment by meelock** [comment]
uncheck this: 

https://drive.google.com/file/d/0B4qiuAniKLfHbWFmd0JNc0JNSkk/view?usp=sharing

**Comment by mcenderdragon** [comment]
I am blind ._.

**Comment by meelock** [comment]
Ok thanks, now just make sure to backup the wiki just in case...

**Comment by meelock** [comment]
I changed the wiki a good bit, what do you think?

**Comment by mcenderdragon** [comment]
Backup is done. Yeah this looks very nice.

**Comment by meelock** [comment]
Heya, I was thinking that the GitHub wiki might be a good way of documenting the mod, outside of the game... what do you think?

**Comment by mcenderdragon** [comment]
Yeah this is a good idea, it is kind of an official place and it is directly linked to us, also questions are easy to question/answer. And here was someone who also ussgested a wiki and I dont know if has already started one.

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/137
