### ISSUE TITLE
[1.11.2] [25.2.24] Forstmaster

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#165]
Good day ! :D

- [ ] Description is off
- [ ] Doesn't recognize the Composite Axe in the researcher.

**Comment by mcenderdragon** [comment]
you need an axe with a non existing meta...., you can research that is you carefully try every meta by picking one block ^^.
(Yes we will fix this ^^)

**Comment by mcenderdragon** [comment]
[This version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.8) should fix the compsite axe issue

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/135
