### ISSUE TITLE
[1.11.2][25.2.8]  Question on Research ( Spoilers )

### ISSUE THREAD

**Issue by savosdarkran** [mcenderdragon/Futurepack-API#166]
Hey,

So I believe that I have researched everything I can.  All of the research is complete, right?  I'm stuck on circuits.  I can make the flash server, but not the support chipsets.

**Comment by Wugand** [comment]
Do you travel to Menelaus yet?
The first arrive on Menelaus (Achievement) is the condition for some researches (to example the support chipset)
If you didn't do that yet, have you the researches to build your spaceship?

**Comment by savosdarkran** [comment]
I have the board computer researched and everything except the three swords and another one in the .  I will build a small spaceship and travel to another dimension.  I just wanted to make sure that I wasn't doing something wrong.  I have attached my research so far in the space tab.

![2017-05-01_11 22 21](https://cloud.githubusercontent.com/assets/26523998/25583598/81f894f6-2e60-11e7-9aff-7c73f586914e.png)

**Comment by mcenderdragon** [comment]
yeah now you need the new resources from menelaus.
