### ISSUE TITLE
In Main Menu Mod Scroll List Glitch (1.11.2)

### ISSUE THREAD

**Issue by CosmicjLightning** [mcenderdragon/Futurepack-API#168]
When i load the game and I edit the mods config files by going to preview mods, if I click on futurepack it crashes the game. But if I scroll past it, and don't do anything I'm good. Just figured I'd let you know. I'm in no hurry for a fix, it's not that bad. Just like to edit mob spawn rates and ore spawn rates in the mod if I can, as ore generation and editor is not out for 1.11.2...

**Comment by mcenderdragon** [comment]
You mean in th main menu the forge mods list?

**Comment by CosmicjLightning** [comment]
Yes

**Comment by mcenderdragon** [comment]
Yeah, does [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.12) fix the problem ?

**Comment by CosmicjLightning** [comment]
I'll let you know asap

**Comment by CosmicjLightning** [comment]
yep it does, thank you...
