### ISSUE TITLE
[1.11.2]Weird nullpointer on startup

### ISSUE THREAD

**Issue by SpatiumPrinceps** [mcenderdragon/Futurepack-API#169]
Hello, 

I'm using the latest version 25.2.9 of Futurepack and theres a weird Nullpointer about Minetweaker. 
I tried to add Minetweaker mod, but its stuck on 1.8...

error: https://gist.github.com/mcenderdragon/04885a956679a1cdc5192d20522ca716

Just wanted to let you know ;)
Greetings,
Spatium

**Comment by mcenderdragon** [comment]
THis is pretty normal and Intended.

**Comment by SpatiumPrinceps** [comment]
I dont think a mod in 1.11 should depend on a deprecated abonded mod, should it?
https://github.com/stanhebben/MineTweaker3
The nullpointer didnt show up in older versions of futurepack. Probably I'm doing something wrong? I'm on lateste forge 2294

If you say, it is ok, I will believe you. It's just not a "nice" thing installing a mod and the first thing you see is a huge nullpointer xD 

Greetings, 
Spatium

**Comment by mcenderdragon** [comment]
Minetweaker/Crafttweaker is still a thing in 1.10/1.11 and  soft dependencies kind of work like this. But sure I can prevnt this from showing up since it is not important ^^

**Comment by SpatiumPrinceps** [comment]
Oh didnt know, that Crafttweaker is the new Minetweaker :D Thank you anyway :) Really enjoy futurepack, its one of the best mods around.
