### ISSUE TITLE
industrial neon furnace not getting power

### ISSUE THREAD

**Issue by LocoMinerDad** [mcenderdragon/Futurepack-API#173]
I have connected it to a cable which is connected to a infusion generator. It is not getting any power. I also have a centrifuge and a super grinder attached to the same cable and they are getting power. I am using latest version of your mod and minecraft, forge

please help.

**Comment by mcenderdragon** [comment]
Is the infusion generator full, are the other machines full?

**Comment by LocoMinerDad** [comment]
Yes they are full.

**Comment by mcenderdragon** [comment]
have you checked with the logistics editor if the side is an neon input ?

**Comment by LocoMinerDad** [comment]
I have a editor. What it look like when set? Neo blue?

**Comment by mcenderdragon** [comment]
yes neon blue.

**Comment by LocoMinerDad** [comment]
It has power. But wont process ore dust

**Comment by mcenderdragon** [comment]
it has special recipes, it needs a minimal amount for ores to work and also some recipes need support points. All recipes are listed in JEI.

**Comment by LocoMinerDad** [comment]
Um ok..all i want to do is spelt my ores. I made a neon industrial furnace so i wouldnt have to keep adding lava to my regular one. What can do that? I will check your recipes later when i can play.

Thank you

**Comment by mcenderdragon** [comment]
no sorry I was confusing it with the centrifuge my bad, the machnies has full neon but doesnt do anything ? Have you checked if the cores/rams/chips are well (and not burned)

**Comment by LocoMinerDad** [comment]
I don't know how to do that.  I have never used it before.  Why would it be damaged?

**Comment by Wugand** [comment]
You craft Core/Ram/Chip into the Mainboard, and their values ar passed to the machine at crafting. If the core is to weak the system burns down. 
Take a Scrench, hold down shift(or your choosen key to sneak) and rightclick (open) the machine. So you should get an new Window (The Modification GUI). In ther center slot you see the core, right the ram and left the chip. To make the machine working nothing should be named "Toasted ..." and the Chip have to be an logic-chipset. 

More informnation can be found at the "Overclocking" entry of the Tec-Tree. 

Note: This GUI is e essential part of the mod, here you can add functions to the machine and able to speed them up extremely. But you can also build and unstable setting that burn down.

**Comment by LocoMinerDad** [comment]
still confused. I opened it and found nothing inside. I added a standard ram and core, with a logistics chip. Nothing is fried. I am at full power. I have a stack of dust in one of the three spots and the bottom icon changed to a lighter color. Nothing is processing.

**Comment by LocoMinerDad** [comment]
issue resolved, cant smelt magnetite dust.

thank you
