### ISSUE TITLE
Monocart page in German

### ISSUE THREAD

**Issue by Knighthawker1** [mcenderdragon/Futurepack-API#175]
When looking at the page for the monocart and related research on the e-scanner, it all appears to be in German. Is this intended?

**Comment by mcenderdragon** [comment]
wich version do you use ?

**Comment by Knighthawker1** [comment]
I'm using Futurepack (v.25.2.9) on 1.11.2

**Comment by mcenderdragon** [comment]
THis is strange we have translated them...

**Comment by Knighthawker1** [comment]
![2017-05-09_12 10 07](https://cloud.githubusercontent.com/assets/27993115/25863237/ac042b24-34b0-11e7-83c4-2330ce2c0d65.png)
Figured I should attach a screenshot.

**Comment by mcenderdragon** [comment]
can you send the last ~20 lines of the log ?

**Comment by Knighthawker1** [comment]
![2017-05-09_15 02 37](https://cloud.githubusercontent.com/assets/27993115/25870130/9f29c0e0-34c8-11e7-8249-e02cfa1aa239.png)
I also noticed this on the page for the e-Scanner
![2017-05-09_15 02 59](https://cloud.githubusercontent.com/assets/27993115/25870144/aaf04304-34c8-11e7-88e9-003698c3da71.png)

**Comment by mcenderdragon** [comment]
No the game log after zou opened the monocart research.

**Comment by Knighthawker1** [comment]
How exactly do I find that?

**Comment by mcenderdragon** [comment]
Does [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.14)
resolve the issue?.

The log is in the minecraft lauchner and also under your minecraft dir/logs/fml-client-latest.log and FP--Latest.log. 
Make a hastebin or a github gist with these files and just link theme here.

**Comment by Knighthawker1** [comment]
https://hastebin.com/olujayohel.md

**Comment by mcenderdragon** [comment]
This issue is very interesting, because it works on my end and I have no idea why the germany version works, but the english one not.

**Comment by mcenderdragon** [comment]
Ok I found the bug. Windows is ignoring upper and lowercase differences so on the repo the files were in the wrong folder, by local they were right. Unfortunetly gitlab is kind of down right now (sopme srtrange missing repos bug) so it will take longer to build this.

**Comment by mcenderdragon** [comment]
Does [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.17) fix it ?

**Comment by Knighthawker1** [comment]
Yep! All pages that were in German are now in English. Thanks!
