### ISSUE TITLE
neon engine

### ISSUE THREAD

**Issue by LocoMinerDad** [mcenderdragon/Futurepack-API#177]
Hi There,

The scanner says its powered by redstone. Does that mean a lever? I have a lever on it in the on position and its not moving or powering anything. I also have redstone on the ground to a lever in the on position, the redstone is lite but still nothing.

Thank you

**Comment by mcenderdragon** [comment]
the neon engine is a RF to NE converter, and yes this means a lever or redstone torch is needed.

**Comment by LocoMinerDad** [comment]
Ok so are you saying it turns RF into Neon? I thought it turned Neon into RF.  The lever in the on position isnt doing anything. ill try the torch

**Comment by mcenderdragon** [comment]
yeah NE -> RF not the other way around.

**Comment by LocoMinerDad** [comment]
Ok. The engine isnt doing anything with a lever or red torch. Is there a graphic change when its working?

**Comment by mcenderdragon** [comment]
there should be but apprently it seems like they work but dont display it correctly...

**Comment by LocoMinerDad** [comment]
Ok can u send a pic or something? How long does it take to generate power? Mine is dead.

**Comment by LocoMinerDad** [comment]
I am using your Futurepak and RFTools, neither comes with RF power cable. I am using fluxed redstone mod for power cables. These cables don't seem to transmit rf from your engine or their coal generator. Any suggestions on other way to transmit the RF?

**Comment by mcenderdragon** [comment]
try to directly power the machines with engine without wires, and also a redstone signal. The conversation is instand so the more NE the more RF you get.

**Comment by mcenderdragon** [comment]
was it wokring or why have you closed the issue?

**Comment by LocoMinerDad** [comment]
the neon engine is working when directly connected to a RF machine. I am not sure on its output. Turns out the issue was with the mod I was using for power transfer.  Thank you

**Comment by mcenderdragon** [comment]
ohh ok

**Comment by mcenderdragon** [comment]
Does the Neon Engine Move and change color while it is working?

**Comment by LocoMinerDad** [comment]
Yes it does
