### ISSUE TITLE
[1.10.2]Few research issues

### ISSUE THREAD

**Issue by Zygus42** [mcenderdragon/Futurepack-API#179]
- [x] Neon Sword research entry is missing (tools.sword.neon).
- [x] E-scanner research entry is missing (tools.escanner).
- [ ] Vent - name of item when you look at it is in german.
- [ ] Vent Slab Research Blueprint - name of needed block (Vent) is in german.

**Comment by mcenderdragon** [comment]
How do you mean "name of item when you look at it is in german." If I look at the Item tooltip it shows "White Colored Ventilation"

**Comment by kleshchevand** [comment]
In "research bleuprint" name of vent (needed resource) is unreadable, I think that's the one Zygus42 means, might be in german once inserted into researcher.
Also:
- "Advanced board computer" description in research table is in German
- Ore extraction (production.zent.extraction2) is missing description
- Color production (production.zent.color) is missing description

P.S. Any hint what item to research to get pest quantum tech to ion and laser2 ?))

**Comment by Zygus42** [comment]
Once you color the Vent, then the name is in English, only the uncolored variant is in German.

**Comment by Zygus42** [comment]
A few more later in the piece:
(1) Glowstone Flashdrive has an extra S in it (Flashsdrive)
(2) Retium Sword description is missing (tools.sword.retium)
(3) Glowtite Sword description is missing (tools.sword.glowtite)
(4) Researching Magnetite Block and selecting no research tabs gives you a research for a Gravity-Pulser, but the details are all blank, including needed resources.  Putting it in the Researched finishes the research instantly at no cost.
(5) The Laser Rifle pops up quite early in the research process, but you need 2 Construction Replicators to build one, and you can't get those until you find bases on Menelaus - would make a lot more sense if researching a Construction Replicators is what gave you the research for Laser Rifles.

**Comment by mcenderdragon** [comment]
I still cant reproduce that the uncolored Ventilation is named as "Vantilation" and the slab is named "Vent slab"

**Comment by Zygus42** [comment]
Perhaps you're trying 1.11 version ?  Using Futurepack-1.10.2-24.2.144, I looted a Construction Replicator from a Wardrobe on Menelaus and have it in a chest, and it looks like the picture of the items needed to make the Laser Rifle.
And the uncoloured vents are as above.
And:
(6) Purple Focus Lens - production.nind.linse.1 not found

**Comment by Wugand** [comment]
The Construction Replicator is an Debug-Item, you should never see one them. Sometime it's apear if an "dp:spaceship"-Item loose it's meta-data.
Say short: This Item says always "here is an Bug!"

**Comment by Zygus42** [comment]
Construction Replicator - there's always one in a wardrobe in every Futurepack base you find on Menelaus.  Not only that, but it's part of the recipe for Laser Rifles, which you cannot therefore make without 2 of them.
