### ISSUE TITLE
[1.11] Electricity Achievement Not Triggering

### ISSUE THREAD

**Issue by kingofrunes** [mcenderdragon/Futurepack-API#183]
Something appears to be up with the electricity achievement or I'm missing something obvious. It's not triggering in a server environment

Using Futurepack v.25.2.9

I have NE generating and storing in a battery box, batteries. I've tried taking out batteries that were filled up, I've tried scanning them with an e-scanner. Even tried charging up a grenade launcher. All of this to no avail. It won't detect that I'm generating NE for the achievement.

I have the pre-req Research Laboratory achievement. I also have the My first computer, I need buckets, Composite Metal, Technology of the Unreachable, It's not a Diamond, Neon Crystal,  Erse for the World, Alutine Crystal, and I like Sushi? achievements

**Comment by mcenderdragon** [comment]
you need to craft a t0 generator as far as I remember

**Comment by kingofrunes** [comment]
That's the one that uses lava right? I've crafted that and the Infusion Generator but it didn't activate. I will try again tonight

**Comment by mcenderdragon** [comment]
no the one using lavala is the Industrial Furnace

**Comment by kingofrunes** [comment]
Okay ya. I'm guessing because I didn't craft the researcher/scanner back to back and have both in my inventory until after I craft that is the reason why I missed it. Thanks
