### ISSUE TITLE
[1.11] Magnetic Ingot Compatability Issue with Blood Magic Mod [Wrong Research Entry]

### ISSUE THREAD

**Issue by kingofrunes** [mcenderdragon/Futurepack-API#184]
Finding myself short on magnet ingots I tried following what it said in the e-scanner but it's not doing anything. This is with Futurepack v. 25.2.9

Attached are some screenshots of the setup.

https://puu.sh/vVPou/0fd9bec248.png
https://puu.sh/vVPp5/c1c10caf69.png
http://puu.sh/vVPqo/114ea7f9c0.png

**Comment by mcenderdragon** [comment]
this recipe entry is wrong, but it JEI its correct, you need. The dust is magnetite dust and the pink emerald thingy is neodynium.
![futurepack_magnetingots](https://cloud.githubusercontent.com/assets/6342933/26276344/f567247e-3d75-11e7-9c97-0149859e1bff.jpg)

**Comment by kingofrunes** [comment]
Looks like this version doesn't have that dust. I guess that dust will be available in the more recent versions?

**Comment by mcenderdragon** [comment]
it was also available in prevois versions, if it is not availbel another mod provides magnetite dust. Have searched in JEI?

**Comment by kingofrunes** [comment]
Nope. It's not showing anything :(

JEI isn't showing the recipe at all either. I hope Industrialcraft 2 isn't interferring with this

**Comment by mcenderdragon** [comment]
in creative mode, what dust are all listed in our items tab? ANd what other mods are you using?

**Comment by kingofrunes** [comment]
Glowstone Dust
Crushed Iron (Actual Additions)
Crushed Gold (Actual Additions)
Crushed Diamond (Actual Additions)
Crushed Emerald (Actual Additions)
Crushed Lapis (Actual Additions)
Crushed Quartz (Actual Additions)
Crushed Coal (Actual Additions)
Crushed Black Quartz (Actual Additions)
Stardust (Astral Sorcery)
Chalk Dust (Earthworks)
Ash Pile (Embers)
Bronze Dust (IC2)
Clay Dust (IC2)
Coal Dust (IC2)
Hydrated Coal Dust (IC2)
Copper Dust (IC2)
Diamond Dust (IC2)
Energium Dust (IC2)
Gold Dust (IC2)
Iron Dust (IC2)
Lapis Lazuli Dust (IC2)
Lead Dust (IC2)
Lithium Dust (IC2)
Obsidian Dust (IC2)
Silicon Dioxide (IC2)
Silver Dust (IC2)
Stone Dust (IC2)
Sulfur Dust (IC2)
Tin Dust (IC2)
Pulsating Dust (Forestry)
Obsidian Dust (Futurepack)
There's a bunch of ones just called dust with the following more descriptive names
dustWakurum
dustEbonyPsi (This is from PSI)
dustElvenElementium (Botania)
dustTerrasteel (Botania)
dustDawnstone (Embers)
dustDemonicMetal (Extra Utils 2)
dustKnightslime (Tinkerer's Construct)
dustEnchantedMetal
dustBioterium
dustRareEarthMetal
dustQuantanium
dustQuartzEnrichedIron (Refined Storage)
dustNeodymium
dustNeon
dustIvoryPsi (PSI)
dustGadolinium
dustGlowtite
dustAlubrass (Tinker's Construct)
dustManyullyn (Tinker's Construct)
dustManasteel (Botania)
dustPigiron (Tinker's Construct)
dustRetium
dustElectrum (Embers)

Then there is:
Fairy Dust (Roots 2)
Petal Dust (Roots 2)
Dwidle Dust (Roots 2)
Ender Dust (Tiny Progressions)

Mod wise I have:
Roots 2
Tiny Progressions
Industrial Craft 2
Forestry
Futurepack
Actual Additions
Astral Sorcery
Earthworks
Chisel
Botania
PSI
Quark
Extra Utils 2
Tinker's Construct
Embers

Going to try narrowing down which of these mods is interferring :/

**Comment by mcenderdragon** [comment]
This is odd, but the magnetite ingot is there ?

**Comment by kingofrunes** [comment]
Yep Magnetite ingot is there but only recipe for it in JEI is the Magnetite Block

**Comment by kingofrunes** [comment]
Okay I pinned down the culprit. Blood Magic is causing this mod to be unable to add Magnetite Dust for some odd reason which then makes it so the recipes don't register in NEI. The strange thing is that Blood Magic has no dusts of it's own and no magnetic ingots.

**Comment by mcenderdragon** [comment]
I can not reproduce this bug myself, does this also happen in [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.33) ?

**Comment by kingofrunes** [comment]
Yes, it is happening in that version as well unfortunately.

**Comment by mcenderdragon** [comment]
can you provide the config files for both mods ?

**Comment by kingofrunes** [comment]
Sure and just in case here is the forge version if that matters any: 13.20.0.2296

http://puu.sh/vWmIK/44a2739e2c.png

[mod_configs.zip](https://github.com/mcenderdragon/Futurepack-API/files/1016536/mod_configs.zip)

**Comment by kingofrunes** [comment]
I also tried setting:

common {
    # Should smelt recipes allways be added for Futurepack materials. Only use this if Dust to Ingot recipes are missing! [default: false]
    B:forceSmeltRecipes=true

but for some reason that didn't work.

**Comment by mcenderdragon** [comment]
As I am currently dont know why it works for me but not for you, can sou try to down grade to forge 13.20.0.2282 ?

**Comment by kingofrunes** [comment]
Still no dice. Tried downgrading to no avail. I don't get this mystery.

**Comment by mcenderdragon** [comment]
You can also try [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.38) with the newer forge version and provide the FP_latest.log, I added alot of hopefully helpfull informations (use github gist or hastebin.com because the log will be huge)

**Comment by kingofrunes** [comment]
https://pastebin.com/YYMknkAC

**Comment by kingofrunes** [comment]
Okay it shows up fine in that version

**Comment by mcenderdragon** [comment]
Does it fail in [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.37) ?

**Comment by kingofrunes** [comment]
Yes it does fail for that version for me

**Comment by mcenderdragon** [comment]
it seems like forge did something change.. I not really get why that one veriosn works but yeah works so ... we are happy :S
