### ISSUE TITLE
[1.10.2]Support points can't transfer via support cables or support pipes.

### ISSUE THREAD

**Issue by SOL3675** [mcenderdragon/Futurepack-API#185]
Using Version of futurepack: 24.2.145
I tried to use the machine using support points, but can't receive that. I checked the machine sides with Logistics Editor.
Is something wrong this setup or is this a bug?
![2017-05-21_10 05 09](https://cloud.githubusercontent.com/assets/16431933/26280420/fa3b1e36-3e0d-11e7-8b19-aaeb72f2b1d8.png)
![2017-05-21_10 16 08](https://cloud.githubusercontent.com/assets/16431933/26280428/8aca221c-3e0e-11e7-9569-2a13a1bfac11.png)

**Comment by mcenderdragon** [comment]
Have you instakked a support chi in the Neon Furnace ?

**Comment by SOL3675** [comment]
Yes, of course. Just smelted cobbles.

**Comment by mcenderdragon** [comment]
If the Neon Furnace has red arrow (so output) at the front then this is a bug :/

**Comment by SOL3675** [comment]
Oh...
So this is a bug since I checked the both of machines sides.
Checked the Neon Furnace with the logistics editor (support), red arrow appeared the front of side.

**Comment by mcenderdragon** [comment]
How much SP has the Neon Furnace ?

**Comment by mcenderdragon** [comment]
YOu can try to remove the support cable and place it again, in very weird cases this helps

**Comment by SOL3675** [comment]
My mods directory has updated, and I tried it in a new world.
If I re-place the support cable, it still won't work.
Here's some images.
http://imgur.com/a/6muuM
Does it have a chance affected this system by other mods?
I checked the log file, but nothing found about this problem.
Mod List: https://docs.google.com/spreadsheets/d/1J6incDhKhPYaxUid8kYjBgnP4jyjshdsaXL0g6Ztpeo/edit?usp=sharing

**Comment by mcenderdragon** [comment]
How does the chipset of both machines look like ? And normaly other mods cant interfere, but wll ASM exists so I dont know.

**Comment by SOL3675** [comment]
Ahhh, it's my bad.
I didn't know about futurepack machine system well. My checked video tutorials do not mention about chipsets system.
I added support chipset, it works. I didn't know it can't transfer support points in default.
I think the Logistics Editor should not show support output without a support chipset.
Anyway, thanks your supporting.

**Comment by 7eggert** [comment]
For n00bs like me, the chipset system needs a hint, e.g. in the instructions about the support cable.
