### ISSUE TITLE
[1.11.2] Shift Clicking Product in Assembly Table not subtracking resources

### ISSUE THREAD

**Issue by kingofrunes** [mcenderdragon/Futurepack-API#186]
Noticed a bug in the most recent version of Futurepack v. 25.3.39

When you Shift + Left Click on the finished product in the bottom slot of the GUI it does not subtract the resources from the top slot. Thus making it so you can get free CPU parts.

**Comment by mcenderdragon** [comment]
Does [this version(http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.41) fix this bug?
