### ISSUE TITLE
game crashes while loading

### ISSUE THREAD

**Issue by LocoMinerDad** [mcenderdragon/Futurepack-API#187]
Hi There, 

I entered a stack of dirt into a rftools storage and my game crashes and now it crashes on startup. RFtools says its a LogisticStorage mod issue. I think you use that. Please see link below.

thank you

https://github.com/McJty/RFTools/issues/1198#issuecomment-303277862

**Comment by Wugand** [comment]
I currently asked back to the other mod devoloper. Because i can'T understand why he pass null

**Comment by mcenderdragon** [comment]
But we will try to prevent your game from crashing.

**Comment by LocoMinerDad** [comment]
Ok so which of you is going to fix this?

**Comment by mcenderdragon** [comment]
I dont know how good this works but [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.41) should fix most issues.

**Comment by LocoMinerDad** [comment]
Everything appears to be working thank you
