### ISSUE TITLE
[1.10] Cables acting odd

### ISSUE THREAD

**Issue by Zygus42** [mcenderdragon/Futurepack-API#189]
When you lay redstone cables and then put down a normal cable so that it attaches to the redstone cables, the redstone cables turn into something called super cables.  You can then pick them up and have super cables.

**Comment by Zygus42** [comment]
1.10.2  Futurepack (v.24.2.144)

**Comment by mcenderdragon** [comment]
This is fixed in 1.11, and are you breaking/minig them or use the pickup function from creative ?

**Comment by Zygus42** [comment]
Mining with a pick.

**Comment by Zygus42** [comment]
But when you look at them with Hwyla before mining them, it already calls them Super Cables, although they still look like Redstone Cables.

**Comment by Zygus42** [comment]
On further testing, you don't even need to mine them - place a block of Redstone on the ground, place a Redstone cable next to it and it's still a Redstone cable, but if you then attach another Redstone cable to that first Redstone cable, both Redstone cables become Super Cables, although visually they still look like Redstone cables.

**Comment by mcenderdragon** [comment]
Hwyla is in theory mining them to get the name information. and in 1.10 there was a meta shift wich causes aktive cables to drop the wrong meta.

**Comment by mcenderdragon** [comment]
as this is solved in later version I will close this.
