### ISSUE TITLE
[1.11.2] Research for Energy Tools

### ISSUE THREAD

**Issue by Tetosan** [mcenderdragon/Futurepack-API#190]
Hello,
I'm playing on a server which runs FuturePack 25.2.39 for 1.11.2.
I'm at the point where i should be able to unlock the Energy Tools research but when i try to do it the 3rd field shows up as red.

I've looked at the research.json and found that it should also require a Normal Battery.
However it seems the entry for that somehow broke so the Item is not found and doesn't appear on neither the Blueprint or as a prompt in the Window, but the researcher will still require the faulty Item.

In this case i think the problem is that the research.json asks for a 'fp:NormalBatery' when it should probably ask for 'fp:NormalBatTery'
Just thought i'd let you know about this so it may be fixed in future versions.

**Comment by Wugand** [comment]
Fixed:
https://minecraft.curseforge.com/projects/futurepack/files/2427232
