### ISSUE TITLE
[1.11.2] Missing language files

### ISSUE THREAD

**Issue by logiid** [mcenderdragon/Futurepack-API#192]
> 'tools.escanner' not found, report this to the mod autor.
> 'tools.sword.neon' not found, report this to the mod autor.

On the other hand, I am translating the language files of FuturePack into Spanish (esES) and I was wondering if you would like to be sent to introduce them in the mod.

Greetings

**Comment by mcenderdragon** [comment]
It would be grate if you translate the futurepack into spanish here is our lang repo: https://github.com/Wugand/FuturePack-Language

**Comment by mcenderdragon** [comment]
#179

**Comment by mcenderdragon** [comment]
all sword researches are done. And escanner.
