### ISSUE TITLE
Wardrobes behaving a bit oddly in 1.10.2

### ISSUE THREAD

**Issue by Zygus42** [mcenderdragon/Futurepack-API#193]
Futurepack-1.10.2-24.2.144
When you pick a Wardrobe to pick it up, it keeps it's contents, which is a great feature, but certain items drop to the ground from inside the wardrobe when you do.  These include:  Opti Bench, Laser Turret & Machine Board.  There may well be others, but those are the ones that it happened with for me, and it is a repeatable problem.

**Comment by kleshchevand** [comment]
There is another oddity:
Similar wardrobes picked from dungeon (the large one in my case) do not stack once emptied, but they do stack if you place them in same location/coordinates, empty by hopper (haven't tried the same manually) and break... (place one, break, place next, break...)
Same goes for some other blocks at 1.10.2-24.2.144 like block breakers. Yet crafting station and some other types of wardrobes (probably ones with four rows of inventory) stack without issues if emptied.

**Comment by mcenderdragon** [comment]
This is not an issue it is intendet. THe items droped have an nbtag already story data. This feature prevents world corruption by stacking to many inventorys in each other.

**Comment by mcenderdragon** [comment]
In the 1.11 we wil change this to actually check the NBT size, so also other mods backbakcs will drop, but smaller items with NBT will still remain.
