### ISSUE TITLE
fp research drop

### ISSUE THREAD

**Issue by Chromogen** [mcenderdragon/Futurepack-API#194]
after a crash and not proper shutdown the whole research data was droped for some reason
can not properly reproduce but might have issue, but i did not want to leave this unmentioned

also if you unlock all researches per command and delete it again, all 'not read' notifications will still show up

in any case: can you please tell me the format in which the file is written?
or is there an option like in HQM to give researches?

**Comment by mcenderdragon** [comment]
the /fp command has option to give you single researches, and have you still the crash ?

**Comment by Chromogen** [comment]
i really cant say what crashed the game. perhaps another mod. it crashed that hard that even crashreport and console didnt log what happened ^^; 
i think it was while saving the level?

did not happen again though. unfortunately not very helpful :-/
but still, regaining all research is a pain since alot of typing and unknown researches and stuff...maybe possible to add states of research beside none and all to help out serverowners later on?

**Comment by mcenderdragon** [comment]
well the complet progress is saved into these files and having a research is yes or no and if the file is gone then its is basicaly as if you create a new world. the file is just a gzip-ed json.

**Comment by mcenderdragon** [comment]
Also how did it get dropped, or is the file just corrupted ?

**Comment by Chromogen** [comment]
well this chapter is part of the grand book of unreproducable things of noone will ever find out :/

it just...reset after logging out an back in in sp. no crash no big error, just nothing :/

edit: would rather close

**Comment by mcenderdragon** [comment]
I will try to make somekind of backup logic, so not everything is lost.
