### ISSUE TITLE
suggestion: foodtube

### ISSUE THREAD

**Issue by Chromogen** [mcenderdragon/Futurepack-API#195]
hey there, i just noticed that food tubes recipe is just an aluminum ingot in a crafting grid.
i would suggest changing that since alot of mods register ingot -> nugget recipes which will give nasty conflicts

thx alot :)

**Comment by ghost** [comment]
Also 'iron rod' receipt (one ingot above another) conflicts with Immersive engineering receipt. They probably should be ore-dictionaried (hopefully Immersive engineering is also oredictionaried)

**Comment by thebloxxer11** [comment]
Right now, even though I am not a developer, install stimmedcow - NoMoreRecipeConflicts. It should help.

**Comment by Wugand** [comment]
Food tube recipe is changed (added IronStick). 
Ironstick is OreDict registered as "stickIron"
