### ISSUE TITLE
Tyros icon in Tech Tree stays disabled

### ISSUE THREAD

**Issue by kleshchevand** [mcenderdragon/Futurepack-API#196]
"Tyros" icon in Tech Tree does not enable after reaching Tyros, instead it starts flashing...

![bug](https://cloud.githubusercontent.com/assets/12720541/26723224/21b8514e-479c-11e7-8761-4409004c7e6e.png)
Minecraft 1.10.2 Futurepack 24.2.144 (and tryed 24.2.162 to see if it fixes issue)

P.S. Energy Cells are displayed as enchantable in JEI, I doubt they are supposed to be

**Comment by mcenderdragon** [comment]
well it displays needs tyros, so thie iks enabled after you get the achivement Tyros.

**Comment by mcenderdragon** [comment]
the cell problem I can not confirme this, wish version of the Futurepack are you using ?

**Comment by kleshchevand** [comment]
>enabled after you get the achivement Tyros.
There is no such achievement and I did visit planet. Before visit icon was completely black.
Version 24.2.144

**Comment by kleshchevand** [comment]
> enabled after you get the achivement Tyros.

I have it aparently. Before visit tech tree icon was completely black.
![tyros](https://cloud.githubusercontent.com/assets/12720541/26743154/7e94ff46-47e9-11e7-946f-bd1a948905c3.png)

**Comment by mcenderdragon** [comment]
This is issue is fixed in the 1.11, because it was a breaking change and would corrupt your world (most likely) We had to migrate from meta based to nbt based and thus alot of metas were not used anymore, wish can result in massive item shifts.

**Comment by mcenderdragon** [comment]
I will close this, the last researches are a bit borket, but as far as I know after Tyros is nothing.
