### ISSUE TITLE
charging research table

### ISSUE THREAD

**Issue by Chromogen** [mcenderdragon/Futurepack-API#197]
hey there, not sure if this is intentional but the charging of a researcher is in a really slow rate

tried out too put more energy modules on a researcher and powered them all. result was, the research took all the needed energy into its block so no more energy supply was needed, but it still took like 15min to actually fill the research bar until the real progress on the timer kicked in. 

so... i m not sure if time is just ment to be a resource on the time bar or maybe on energy bar too but it definetly feels wrong! and if intentional, maybe leave a note somewhrere? i didnt find one on energy charge time :/

thx alot

**Comment by mcenderdragon** [comment]
the calculation modules are to decrese the time needed to fill up the neon bar.

**Comment by Chromogen** [comment]
tutoriatext just mentions it will speed up the process...so i expected the calculation block to help with the normal (white) time bar. would be nice if you could mention the neon bar in this tutorial text :)

anyway: closed!
