### ISSUE TITLE
[1.10.2]"Your spaceship is open" message when it is not open

### ISSUE THREAD

**Issue by MechWarrior99** [mcenderdragon/Futurepack-API#2]
I keep getting this message when right clicking board computer. To make sure there were no open places I made it a 5x5x5 cube. I tried several different blocks (some from FP some not), but none worked.

**Comment by mcenderdragon** [comment]
Can you make screenshots ? And what matierial are the Blcoks/what Blocks espacial do you use?

**Comment by MechWarrior99** [comment]
I am using the "White Colored Metal" from FP. It looks the same on all sides. And the inside picture was taken with night version
http://imgur.com/9Du33Zl
http://imgur.com/6qSNSPO

**Comment by mcenderdragon** [comment]
in the 1st picture whats behind you?

**Comment by MechWarrior99** [comment]
A wall http://imgur.com/QH3BRBB

**Comment by mcenderdragon** [comment]
Interesting, you used only metal blocks but its seem not to work.

**Comment by mcenderdragon** [comment]
Are the wires somehow building a hole through a wall or the bottom?

**Comment by MechWarrior99** [comment]
Nope, all 4 walls, the roof, and the floor are all solid white colored metal blocks

**Comment by mcenderdragon** [comment]
OK, I am able to reproduce it. I will look into this. :)

**Comment by MechWarrior99** [comment]
Okay, good to hear. Thanks :)

**Comment by mcenderdragon** [comment]
Can you confirm this bug is fixed in this version: http://redsnake-games.de/Downloads/fp/fp.php?version=24.1.2 ?

**Comment by MechWarrior99** [comment]
Yes, I can confirm that it is fix in that version.
