### ISSUE TITLE
[1.11.2] Huge dungeons not generated in latest version

### ISSUE THREAD

**Issue by donqixot** [mcenderdragon/Futurepack-API#200]
I am using latest version of Futurepack 1.11.2-25.2.76, forge version 1.11.2-13.20.0.2313, java version 1.8.0_131, the only other mod I have is JEI version 1.11.2-4.3.5.277. I am using MultiMC for launcher.

When I create new world in these settings, small dungeons are generated, but huge ones are not. I checked config between 1.10.2 and 1.11.2 and frequency is be the same. Yet even with 32 chunks in video settings (which is about 1000x1000 world map) and even after some travel, I find no huge dungeons. I am using Minutor to view underground map.

Also tried previous version of Futurepack 1.11.2-25.2.39, same results.

**Comment by Wugand** [comment]
In current version the big dungeons are removed, we currently workon an new and better Version (including better loot and bosses) .
We try to bring them back as soon as possible

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/159

**Comment by donqixot** [comment]
Thanks! One more question, in 1.10.2, when you find huge dungeon, sometimes it is "locked" so you cannot place torches or take wardrobes, while other huge dungeons are not locked. Why is that?

**Comment by mcenderdragon** [comment]
in thorie all should be locked, but that did not worked, so we removed them

**Comment by donqixot** [comment]
All locked until certain achievements are complete? Or forever? I can proceed as intended if I knew what the purpose was.

**Comment by mcenderdragon** [comment]
Locket unil the dungeon is clered and the protection is deactivated in the main frame.

**Comment by donqixot** [comment]
Thanks, interesting. So I need to get all the loot and then I can take all blocks? Cool. You can close this issue since it's duplicate or close the #159.

Thank you very much for the mod! It is very original and interesting! I think it will take off soon in popularity. Good luck!
