### ISSUE TITLE
[1.11.2] World Tick CME

### ISSUE THREAD

**Issue by Shadows-of-Fire** [mcenderdragon/Futurepack-API#201]
Forge 13.20.0.2315
Futurepack 25.2.76

I wish I had more than a crash report here, but this happened when I was logged off.  It may be worth noting I have done nothing involving Futurepack aside from raiding structures yet on this world.  This was just a couple seconds after I had logged off, and the game crashed with a CME traced down to your WorldTickEvent handler `FPMain.java:530`.  
Full crash report: https://gist.github.com/Shadows-of-Fire/8796ad46a1dba93cc257f78b9b05e77f

Since this occured during saving, it also caused this crash report on next startup, but this was a one-time occurrence.  
Full crash report: https://gist.github.com/Shadows-of-Fire/1e6c508b6f6fc8dff4d76a1160a2b880  

Finally, the entire fml-server log of the first report.
https://gist.github.com/Shadows-of-Fire/c8e70d18d73020a86c35ff38cb540a56  
Be warned, that is a 250k line log file.

**Comment by mcenderdragon** [comment]
This is interesting, because i am just calling a normal minecraft method to get some entittys...

**Comment by mcenderdragon** [comment]
Has this only happened once or more often ?

**Comment by mcenderdragon** [comment]
The bad thing is, this is cause by someone modifieng the entity list while saving most likely from another thread, but the crash is cause by my mod.

**Comment by mcenderdragon** [comment]
You  can try [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.91) It should not crash again, but this crash was very odd, and seemd very random.

**Comment by Shadows-of-Fire** [comment]
I have yet to see it again.  Will reopen if I csn reproduce.
