### ISSUE TITLE
[1.10][24.2.144] Crash

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#202]
https://pastebin.com/yBBBJncM

Original: https://minecraft.curseforge.com/projects/futurepack?gameCategorySlug=mc-mods&projectID=237333#c234

**Comment by Wugand** [comment]
not happens on 1.12
1.10 is no longer supported

**Comment by mcenderdragon** [comment]
there was a reason I added this to a milestone...
