### ISSUE TITLE
[1.11.2]some minor bugs

### ISSUE THREAD

**Issue by Chromogen** [mcenderdragon/Futurepack-API#203]
found that the 2 core machineboard for the calculation module is item.machineboard.youdidsomethingwrong
there is some more but not sure if those are actualy implemented

and the smelting of alutine gives all kind of aluminum, cycling through all registered oredict ingots....which is somewhat annoying if you need a stackable amound for research!

thx alot and keep up the good work!

**Comment by mcenderdragon** [comment]
What machine did you use for smelting? EFurnace or other furnaces?

>found that the 2 core machineboard for the calculation module is item.machineboard.youdidsomethingwrong
>there is some more but not sure if those are actualy implemented

And what do you mean by that?

**Comment by mcenderdragon** [comment]
> found that the 2 core machineboard for the calculation module is item.machineboard.youdidsomethingwrong
> there is some more but not sure if those are actualy implemented

And what do you mean by that?

**Comment by Chromogen** [comment]
1. its both furni. they process 3 alu crystals in one go and give 3x1 different ingot bar (embers, immersive engineering and futurepack)

2. the machineboard with 2 processors for the calculation module...you messed with the item display name...the displayname ingame is:
item.double_machineboard.name

same for:
item.pearlegger.name
item.pearlegger_empty.name
item.shredder.name
item.analyzer.name
item.lasercutter.name
item.timemanipulator.name
item.module_shield.name

**Comment by mcenderdragon** [comment]
Wich Minecraft Version, Forge version and Futurepack version do you use?

Do you mean by both furni Industrial Furnace and Neon Industrail furnace, because the vanilla Furnace and the EFurnace can only progress one item (and I am confused)

**Comment by Chromogen** [comment]
minecraft 1.11.2
forge-13.20.0.2314
Futurepack-1.11.2-25.2.76

Industrial Furnace and Neon Industrail furnace. they both do this
they eat up 3 alu crystals (and a coal in normal version) and you get get one immersive engineering ingot, one from embers and one from futurepack in just one opperation

for now i cant say if it is modinteraction but even if it was... its pretty much just FP which does this :/

i m sorry that i cant provide more info but i dont have much time and loading time on my potatoe-pc is does no good for me too :-/

modlist:
https://pastebin.com/cYAJhtp6

->noticing while uploading: unidict (mod)

**Comment by mcenderdragon** [comment]
ahh yeah.. this bug, it seems like iot gets more worse the more mods are installed. Yeah I think we had this behaivier already and i though we fixed it...

**Comment by mcenderdragon** [comment]
the aluminum thing is done

**Comment by mcenderdragon** [comment]
namings should also work now.
