### ISSUE TITLE
[1.12][1.11.2?] Missing research blocking

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#204]
Only tested in 1.12

Always craftable:
- Techtable
- [x] Sword handle (from Neon swords)
- [x] Dual Machine Board
- [x] Tank
- [x] Metal Fence Gate
- [ ] Most of the Food
- [x] advanced boardcomputer (only gray one, meta:6)

**Comment by Wugand** [comment]
- Techtable                                                                       -- make no sense
- Sword handle (from Neon swords)                                 -- Fixed
- Dual Machine Board                                                      -- Fixed
- Tank                                                                              -- Fixed
- Metal Fence Gate                                                          -- Fixed
- Most of the Food                                                          -- No research - TODO?
- advanced boardcomputer (only gray one, meta:6)         -- Fixed

**Comment by mcenderdragon** [comment]
I thnk food can stay as it is.
