### ISSUE TITLE
[1.12] Cannot open techtable

### ISSUE THREAD

**Issue by donqixot** [mcenderdragon/Futurepack-API#207]
Thank you for migrating to 1.12 so quickly!

I tried today to craft techtable, it works, but I cannot open it. There is no message saying I don't have access. I followed normal research process, scanning all items, including erse and then crafted techtable. To investigate, I tried command "fpdebug techtabel", no info. I then tried command "fp research @me unlock all" and then tried to open techtable, no luck. I even followed minecraft achivements tree to make sure I have everything, even got sushi block, still no luck.

I am on forge 14.21.1.2387, fp version 1.12-26.1.1, the only other mod is JEI 1.12-4.7.0.68,

**Comment by mcenderdragon** [comment]
Thanks for the report, I am digging into it!

**Comment by mcenderdragon** [comment]
You can try [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=26.1.2) it should fix the bug.

**Comment by elucent** [comment]
Any chance you could release 26.1.2 on Curse? Several of my users in my modpack are running into this bug and they're very eager to play through Futurepack!

**Comment by mcenderdragon** [comment]
No one has confimed if the 26.1.2 fix the bug yet :/

**Comment by BlackWingReg** [comment]
So I just downloaded the 26.1.2 version into the modpack @elucent is using, and I can confirm that it fixes the Tech Table issue. Doesn't seem to have caused any other issues with the pack that I can identify. Just wanted to confirm the fix seems to work!

**Comment by mcenderdragon** [comment]
https://minecraft.curseforge.com/projects/futurepack/files/2452701

**Comment by elucent** [comment]
Thank you ever so much! :D
