### ISSUE TITLE
[1.11.2] Recycler Research, unable to complete

### ISSUE THREAD

**Issue by FlyingScotsman1** [mcenderdragon/Futurepack-API#212]
Hi small issue where after completing the research for the analyzer, I place the recycler back into the scanner to get the last blueprint but when I click on each of the side buttons all I get for every single one is a yellow cross, and this is even when selecting them one at a time, thus blocking me from continueing with any further research.

**Comment by FlyingScotsman1** [comment]
I apologize for my hasty report of a non-existant issue, I figured it out and feel like a complete idiot, so please tag this as solved or whatever and keep up an amazing mod.

**Comment by mcenderdragon** [comment]
better to much issues, then not enough :)
