### ISSUE TITLE
[1.12] FP-TyrosTreeGen Crash?

### ISSUE THREAD

**Issue by Dhenier** [mcenderdragon/Futurepack-API#213]
My 1.12 Beyond the New Frontier modded server just crashed and I am trying to track down the issue. 

https://pastebin.com/qxB3jkQH

**Comment by mcenderdragon** [comment]
Is this reproduceable ? It seems like this is caused by one of the coremods, try to remove foamfix first, the do heavy stuff with ASM.

**Comment by Dhenier** [comment]
I updated to the latest BTNF v 2.2. And I swapped out the foamfix.anarchy for the foamfix.lawful - as recommended by that mod author. I still got a crash that reports the same error from FP-TyrosTreeGen. There are a lot of other errors, but FP is the only identifiable mod in the list of errors. And crash only happens during chunk gen as I fly around the world. So it is happening during chunk generation.

I will try to remove foamfix completely and see if that helps. The sad things is it takes awhile to find this crash bc it happens during a new chunk gen and it is random if things will generate in any given chunk.

Here is the latest crash report:
https://pastebin.com/riQqeEHm

Thank you

**Comment by mcenderdragon** [comment]
Well this crash has nothing to do with the Futurepack. java.lang.Error is also VERY rare, and I think some of the coremods fucked up the ASM, so only Futurepack will most likely work.
And then add mob by mod and see when it starts crashing.
A
I am very sorry I cant help more then this.

**Comment by mcenderdragon** [comment]
You can strart with the coremods, one of them is most likely causing this.
