### ISSUE TITLE
[MC 1.11.2] Electromagnet recipe incorrect

### ISSUE THREAD

**Issue by FlyingScotsman1** [mcenderdragon/Futurepack-API#214]
Hey just found a little mismatch in the Electromagnet, the scanner shows the recipe as 2 copper coils, 2 composite metal, 2 neon ingots, 1 magnetite block, 1 colored metal block and a machine board, however as this never worked I checked it with JEI and the recipe there is 4 copper coils, 2 composite metal, 1 Iron block, 1 colored metal block and the machine board. I tested both recipes and sure enough the one shown on JEI works and the recipe on the scanner does not.

otherwise having a lot of fun with the mod 👍 
imgur pics to show the differences: http://imgur.com/a/6wZ96

**Comment by mcenderdragon** [comment]
[This version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.135) should fix it
