### ISSUE TITLE
[1.11]Some content is missing

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#217]
Fluid Pump
- [ ] Research
- [x] Crafting

Fluid Tank
- [ ] Research
- [x] Crafting

Fluid Tube
- [ ] Research
- [x] Crafting

**Comment by mcenderdragon** [comment]
@Wugand  any updates on this?

**Comment by Wugand** [comment]
+TODO Fluid Intake
Work in progress

*Closed because duplicate to asana
