### ISSUE TITLE
[1.12] Advancement names are not properly localized.

### ISSUE THREAD

**Issue by elucent** [mcenderdragon/Futurepack-API#218]
A fairly minor bug, but it should still be reported!

EDIT: Originally linked the wrong image. The actual images of the bug are linked below.

**Comment by mcenderdragon** [comment]
That image are thermal items, what do they have to do with the issue ?

**Comment by elucent** [comment]
...whoops, I linked the wrong image. Let me grab the right one.

Here's one screenshot one of my users reported: https://cdn.discordapp.com/attachments/335186981640339456/335983716050403350/unknown.png

And an additional screenshot from the same user: https://cdn.discordapp.com/attachments/335918323524960257/336190068660109314/unknown.png

While I'm here, let me just say, Futurepack is really cool! I'm glad I took the time to take an in-depth look at it, it's really underrated!

**Comment by mcenderdragon** [comment]
Thanks :D, yeah the localisation is mssing, alias, in the files are still achievements, but the system is different now, will will fix that........

**Comment by mcenderdragon** [comment]
great in dev they work, but outside they dont...

**Comment by mcenderdragon** [comment]
fixed in 26.1.4
