### ISSUE TITLE
[1.12] Substantial lag when rendering the player data page of the E-Scanner.

### ISSUE THREAD

**Issue by elucent** [mcenderdragon/Futurepack-API#219]
In a large pack where the player has a ton of data, the first page of the E-Scanner that displays the player's data appears to lag significantly and FPS decreases a lot. If you haven't already, you could probably add optimizations to only render the lines that are currently in-view.

**Comment by mcenderdragon** [comment]
I am alredy rendering part only if they are vissible, but texts are a whole component. I think I will just split them if they are too big.

**Comment by elucent** [comment]
Thank you for the prompt response!

**Comment by mcenderdragon** [comment]
Can you try [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.124) (for 1.11)

**Comment by elucent** [comment]
Sure, but since my pack is on 1.12 any testing I do will be no better than the testing you do yourself most likely. :P

**Comment by elucent** [comment]
I am not seeing the same issues in the new version though! Seems like whatever you did fixed it. :)

**Comment by mcenderdragon** [comment]
Cool. This means i will make an 1.12 build soon to test if it is done.

**Comment by mcenderdragon** [comment]
[This version](https://www.mediafire.com/file/o2ozx13aq7owcit/Futurepack-1.12-26.1.3.jar) should fix this for 1.12.
