### ISSUE TITLE
Sorter stops if first slot not processable

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#22]
If the first slot in the sorter is filled with Item, that can't actually be emited all other slots are blocked and don't get processed.

**Comment by mcenderdragon** [comment]
Solved with: 42f07c4fc2d4985762ca272dda962952d9c5a651

**Comment by Wugand** [comment]
Not really

**Comment by mcenderdragon** [comment]
completly solved. (21335c339c9467b661c51a61d45e98c5ff942695)
