### ISSUE TITLE
[1.11/1.12] Partially Implemented Content

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#222]
Major:
- [x] Dungeons

Normal:
- [ ] Force Field (Generator)
- [x] Menelaus Mushrooms
- [x] Ion Collector
- [x] Super Cable
- [ ] Absorbtion Turret
- [x] Regerneration Turret
- [x] Quantum Core
- [x] Fluid Tube
- [x] Fluid Tank
- [x] Fluid Pump
- [ ] NON Generation
- [x] Dungeon (Artifact) Generation
- [x] Torus (Artifact 2) Generation
- [ ] Check Overdrive Text
- [x] AstroFood
- [ ] White Lens
- [ ] Purple Lens
- [x] Mendelflower
- [ ] Second Chemical
- [ ] Crystal Cell
- [ ] PlayerEgger
- [x] Neon Sword ' s
- [x] Modular Armor
- [x] Energy Modul
- [x] Shield Modul
- [x] Time Manipulator
- [ ] Music Discs
- [ ] Crystal Cell
- [x] Magnet Armor
- [ ] Use Astronomy1
- [x] Text Recycling
- [ ] Text Tryros
- [x] Zentrifuge color extraction
- [x] Zentrifuge ore extraction
- [x] QBitFlash Drive
- [x] Text E-Scanner

1.12:
- [ ] Filter System
- [x] Oneway rail

**Comment by mcenderdragon** [comment]
You mentioned Absorbtion Turret 3 times...

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/217

**Comment by mcenderdragon** [comment]
We need to make a research to say the ability of the mendel berry to make any  crystal sand to neon sand.

**Comment by mcenderdragon** [comment]
- [x] FP-Schalter
- [x] Texte für die DUngeon Keys

**Comment by mcenderdragon** [comment]
@Wugand can you update this ? I think some stuff has researches now.

**Comment by Wugand** [comment]
All copy of #272 or noted in asana
