### ISSUE TITLE
[1.12] Recycler Text and Recipe Missing In E-Scanner Tech Tree

### ISSUE THREAD

**Issue by BlackWingReg** [mcenderdragon/Futurepack-API#223]
JEI still has the recipe, and it unlocks correctly, showing as buildable in JEI instead of having the warning marker for unresearched items.

The text for Recycling on the Basics Group reads: 'recycling' not found, report this to the mod author.

On the production page, the text for the recycler reads: 'production.recycler' not found, report this to the mod author.

The text for the shredder reads: 'production.recycler.shredder' not found, report this to the mod author.

I'm using build Futurepack-1.12-26.1.2.jar - I presume this is 26.1.2.

**Comment by BlackWingReg** [comment]
Additional Information: The same issue happens for the Analyzer. I haven't unlocked all the research, but it might be that the entire Recycler and the grinder/insertable components for the Recycler are all missing their text.

The specific message is: 'production.recycler.analyzer' not found, report this to the mod author.

**Comment by mcenderdragon** [comment]
ok, only the timemmanipulator is still missing its text.

**Comment by mcenderdragon** [comment]
done
