### ISSUE TITLE
[1.12] Monorail Guide Text not Localized for English

### ISSUE THREAD

**Issue by BlackWingReg** [mcenderdragon/Futurepack-API#224]
The text for the monorail unlocks in Futurepack 26.1.2 is in German (I think). I'm playing with the English. The images are there, and the text appears complete. This seems to be the case for the monorail and it's sub-researches.

**Comment by mcenderdragon** [comment]
This is a bug, because i think there are english ones available. I am digging into it.

**Comment by BlackWingReg** [comment]
The actual monorail research for the basic rail is in English. The monocart and the waypoint are documented in German. I haven't unlocked the rest of the monorail research yet.
