### ISSUE TITLE
[1.12] Crash when disconnecting a Thermal Expansion machine from a Neon Engine

### ISSUE THREAD

**Issue by elucent** [mcenderdragon/Futurepack-API#225]
https://gist.github.com/elucent/a5b3ec664fe1dcc3ef399c7eff038b2f

I'm guessing you might just be missing a nullcheck on something?

EDIT: Using Futurepack 26.1.2

**Comment by mcenderdragon** [comment]
Sorry I was on vacation, I will look into it.

**Comment by mcenderdragon** [comment]
[This version](https://www.mediafire.com/file/o2ozx13aq7owcit/Futurepack-1.12-26.1.3.jar) should fix this.
