### ISSUE TITLE
[1.12] Crash when Morpheus installed

### ISSUE THREAD

**Issue by drewbit** [mcenderdragon/Futurepack-API#229]
I believe it's the same problem as https://github.com/mcenderdragon/Futurepack-API/issues/209

Futurepack version: Futurepack-1.12-26.1.2
Morpheus Version: Morpheus-1.12-3.3.2
Log: https://pastebin.com/Bxq0aAbz

Problem goes away when Futurepack is removed.

**Comment by mcenderdragon** [comment]
I have fixed it but I am currently unable to uplade th fixed version.

**Comment by Poisonsting** [comment]
Any update on when the fixed version will be uploaded?

**Comment by mcenderdragon** [comment]
[Version 26.1.3](https://www.mediafire.com/file/o2ozx13aq7owcit/Futurepack-1.12-26.1.3.jar)

**Comment by Quetzi** [comment]
Easiest way to solve these issues is to stop shipping my api.

**Comment by mcenderdragon** [comment]
@Quetzi, I have already done this but I have independ branches for the different version, so I hadn't merged the fix yet.
