### ISSUE TITLE
[1.12] Two uncolored metal slabs result in client crash

### ISSUE THREAD

**Issue by davqvist** [mcenderdragon/Futurepack-API#232]
MC 1.12
Forge 2443
Futurepack 26.1.2

A user of my server placed 2 uncolored metal slabs on top of each other which seems to result in a weird state that The One Probe doesn't like and kicked him from the server and couldn't come back. We had to delete the block. It doesn't look like a TOP issue, if yes, I will report there. 

https://gist.github.com/SjetCraft/6424aa72e42ea86cabf663067a21a915

**Comment by mcenderdragon** [comment]
Well it is a combination of the one probe and futurepack, normaly a slab item with meat 8  would not exists but TOP created one and tried to get the name of it wich resulted in a crash. I will try top fix this on my end.
