### ISSUE TITLE
[1.12] Iron sticks do not have Ore Dictionary registration.

### ISSUE THREAD

**Issue by elucent** [mcenderdragon/Futurepack-API#233]
Iron rods should have the `stickIron` ore dictionary entry. This should help avoid recipe conflicts with rods from other mods such as Immersive Engineering.

No rush, but it'd be helpful!

**Comment by mcenderdragon** [comment]
do you know if they are also crafted like this ?

**Comment by elucent** [comment]
They are also crafted in this way, though the recipe only produces 4 sticks instead of 8. A pretty minor difference IMO, they'd still be good to be oredicted together.
