### ISSUE TITLE
[1.12] Missing Textures

### ISSUE THREAD

**Issue by Boolyman** [mcenderdragon/Futurepack-API#234]
The sand Menalaus and Trees on Tyros have missing textures.  I have included a screenshot of the trees.
![s-l225](https://user-images.githubusercontent.com/24765883/29249703-80beb338-7fe9-11e7-996e-2dc0bf189aa6.jpg)

**Comment by mcenderdragon** [comment]
Wich version of Futurepack, Forge and Minecraft are you using?
