### ISSUE TITLE
Question: skyblock possible?

### ISSUE THREAD

**Issue by wizard1399** [mcenderdragon/Futurepack-API#236]
Hello,

I am creating a skyblock style mod pack and would like to include your mod. I have noticed that some of the content is dependent on exploration. 

Is there a way to turn off the world generation via configs? What game play would this break? For example, if I added a crafting recipe for the e scanner instead of finding it down one of the pipes, would that work. I would probably also have to change the beginning recipes that rely on the colored blocks from the dungeon by using craft tweaker.

**Comment by mcenderdragon** [comment]
I think it is possible, the EScanner alredy has a recipe but you probably cant gain the required resources. Besides the metl blocks, you would also need atleast one neon sand, and one alutin sand to grow the crystals. You also have to keep in mind at the beginning you need to scan some blocks/entitys to get the 12 aspects.

**Comment by wizard1399** [comment]
Thanks for the reply. Is there any config options I should know about? 

P.S. I think you should consider changing the name of the e scanner. There are several mods that have books that level up and change based on doing certain things. Most of these have similar names: thauminomicon, necronomicon, etc. Maybe you could call your book the technomicon. Just a thought for you to consider.

**Comment by wizard1399** [comment]
After looking at the recipe for the e scanner, I have come to the conclysion that there is a flaw in your logic. The reason for adding a recipe for an item needed to start the mod

**Comment by wizard1399** [comment]
is so that if a player can not find the item through exploration, then they can craft the item. The current recipe for the escanner requires items that can only be obtained much later in the mod. Thus to start the mod , a player would need items from something that he has not researched yet. You may want to reconsider the crafting recipe for the escanner.

**Comment by wizard1399** [comment]
Question: could you possible provide a cheat sheet for what to scan for pack makers so we can guide players in the right direction?

**Comment by mcenderdragon** [comment]
ther escanner crafting is for mutliplayer, if not enough eScanner are available, so the players who already started researching, can help each other. 
https://gist.github.com/mcenderdragon/28735f173859b4aa19d11bc3beba4af1
