### ISSUE TITLE
[1.12.1] Futurepack ores not working with NotEnoughWands swapping wand

### ISSUE THREAD

**Issue by donqixot** [mcenderdragon/Futurepack-API#237]
Thank you again for this mod! Amazing!
NotEnoughWands mod (https://minecraft.curseforge.com/projects/not-enough-wands) has swapping wand which can swap blocks. For instance, I can swap copper ore with cobblestone, effectively mining this ore in large area. By testing this wand on various ores (vanilla, Thermal Expansion, Forestry, Actually Additions etc.) I found that the only ore this wand has issues with is Futurepack. For any ore fp:erze:* it gives you fp:erze:0, which is Tin. I opened issue with NotEnoughMod, but author suspects it is not his mod issue https://github.com/romelo333/notenoughwands/issues/60. He says he is using block.getItem(). Can you possibly look into this?

**Comment by mcenderdragon** [comment]
What does the swapping wand with vanilla coal ore and vanilla quartz ore ?

**Comment by donqixot** [comment]
You get coal_ore or quartz_ore (not coal or quartz) in your inventory in exchange for cobblestone (or other material of your choice). It acts like silk touch pick.

**Comment by mcenderdragon** [comment]
this seems like NotENoughWands is doing strange things.

**Comment by donqixot** [comment]
That's what I thought too, but strange thing is the only ore it has problems with is Futurepack.

**Comment by mcenderdragon** [comment]
If it is as MCJty said, then its totatly the fault of notENoughWands four using outdated code. But because most likely they wont fix it, I add support so this bug no longer occures. In the next 1.12.1 build it will available.

**Comment by donqixot** [comment]
Thank you sooo much!!! It will be really helpful!

**Comment by donqixot** [comment]
I just tried new version Futurepack-1.12.1-26.2.6, it's working!! Thank you very much! I am closing this issue.
