### ISSUE TITLE
[1.12] Way to Disable Underwater Air Domes?

### ISSUE THREAD

**Issue by Boolyman** [mcenderdragon/Futurepack-API#238]
There are quite a few Underwater Futurepack Air Domes that really seem to serve no real purpose.  The broken water flowing is creating unnecessary lag and I want to greatly reduce or turn off the generation of these domes.  I did not see this option in the configs... am I missing something?

**Comment by mcenderdragon** [comment]
can you make a screenshot? because I dont know what you mean.

**Comment by mcenderdragon** [comment]
And on wich Minecraft version are you playing ?

**Comment by craft90** [comment]
Ran into this too. It appears the world gen appears to attempt to generate the crystal domes in ocean biomes, creating large air pockets of flowing water and crystal. The water is in a "frozen" state, however an block update floods the "dome".

**Comment by mcenderdragon** [comment]
Are the completly inside the ocean or only the upper part ?

**Comment by craft90** [comment]
In my experience they spawned on top of the ocean floor. However the big crystal expand upwards and so does the air "dome".

**Comment by mcenderdragon** [comment]
Ahh yeah, detected this is harded then it sounds, because checking to much blocks can cause generation of new blocks, but iw will try to avoid this.

**Comment by mcenderdragon** [comment]
This will be fixed in the next 1.12 version.
