### ISSUE TITLE
[MC 1.12x] Recycling not found

### ISSUE THREAD

**Issue by craft90** [mcenderdragon/Futurepack-API#240]
It told me to report to the mod maker so I did.  It's the recycle tab on teach tree in Scanner tech tree which gave me this error.

**Comment by mcenderdragon** [comment]
recycling in the first tab (at the top) ?

**Comment by craft90** [comment]
Yes the first tab. The Recycler itself is available.

**Comment by mcenderdragon** [comment]
@Wugand - please tell me what you have planned for this research.

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/244
