### ISSUE TITLE
Question: which id is used for dimensions Menelaus/Tyros?

### ISSUE THREAD

**Issue by donqixot** [mcenderdragon/Futurepack-API#241]
I believe it used to be 100 and 101, but in 1.12.1 I can't find them. Nothing in config either. Thanks again for this mod!

**Comment by donqixot** [comment]
Found it in the old logs - 73 and 74.

**Comment by mcenderdragon** [comment]
They use dynamic IDs. if 73 or 74 is not available, forge gives me another one.
