### ISSUE TITLE
[MC 1.12.1] Futurepack causes texture Errors

### ISSUE THREAD

**Issue by mcfilmmakers** [mcenderdragon/Futurepack-API#242]
Running in forge 2463, removing Futurepack means I don't see the following errors:

[https://pastebin.com/Hm3JYd3q](https://pastebin.com/Hm3JYd3q)

**Comment by mcenderdragon** [comment]
As long as everythings works they can be ignored. Somestuff is niot fully implementd yet (filter + filter assembler )
