### ISSUE TITLE
[MC 1.1X] No Neon Energy API or ForgeE interface

### ISSUE THREAD

**Issue by JustJinxed** [mcenderdragon/Futurepack-API#243]
This is a bit problematic for us mod pack developers. Could you maybe move towards a flavored ForgeEnergy name, or provide an RF API interface to the batteries? Having 8 different forms of energy with no possible conversions makes this a difficult integration.

**Comment by mcenderdragon** [comment]
I can understand your point, but RF or ForgeE (that is basicly RF too), has no real value anymore (look at this marathon who produces more RF per tick).
We have the neon engine to convert NE to RF, and we are alredy working on a conversation of RF to NE. Does this help or not realy ?

**Comment by mcenderdragon** [comment]
It seems like CoFH dont supports ForgeE with its fluxducts, you have to first use a energy cell.
