### ISSUE TITLE
[1.12.1] Missing entries from scanner

### ISSUE THREAD

**Issue by b0bst3r** [mcenderdragon/Futurepack-API#244]
This scanners knowledge WAS opened using the cheat (I'm a pack maker so needed to look at the tech tree).

Scanner - Production tab - Ore Extraction 

Result below 

![oxtcnf4](https://user-images.githubusercontent.com/2760085/30029808-a1fe1cc8-9182-11e7-80f7-af74ffbe602f.png)

Futurepack-1.12.1-26.1.5.jar

**Comment by b0bst3r** [comment]
Color Production also missing (2 to the right of ore extraction.

https://i.imgur.com/MzkK0Oo.png

**Comment by b0bst3r** [comment]
Basics
- Astronomy 1 (astronomie1 not found)
- Ion Tech (ionentechnik not found)
- Laser Tech 2 (lasertechnik2 not found)
- Tyros (tyros not found)
- Recycling (recycling not found)

Production
- Ore Extraction (production.zent.extraction2 not found)
- Color Production (production.zent.color not found)
- Purple focus Lens (production.nind.linse.l not found)
- Green Focus Lens (prodution.nind.linse.g not found)

Logistics 
- Crystalline Energy Cell (log.battery.crystal not found)

Energy generation
- Ion Collector (energy.ionen not found)

Circuits 
- Non Memory (ram.non not found)
- Dungeon RAM (ram.dungeon nopt found)
- Torus RAM (ram.univers not found)
- NoN Core (core.non not found)
- Dungeon Core (core.dungeon not found)
- Torus Core (core.univers not found)

Space Travel
- Regeneration Laser (space.turret.heal not hound)
- Absorption Laser (space.turret.absorb not found)

Tools
- Neon Sword (tools.sword.neon not found)
- Glowtite Sword (tools.sword.glowtite not found)
- Retium Sword (tools.sword.retium not found)
- Bioterium Sword (tools.sword.bioterium not found)

**Comment by mcenderdragon** [comment]
does this also happen without the texture pack, and can you give me the game log? I think something is wrong with the path were the scanner is searching for the texts

**Comment by b0bst3r** [comment]
Removed Resourcepack and reloaded MC and the entries are still missing.

Yeah there's an entry for each of the above (and some I missed) in the FP-Latest.log http://pastebin.ubuntu.com/25465672/ (edit: it seems the log gets re-written on every MC launch so the entries for all the above are not present)

[15:34:40][Netty Local Client IO #0] Get Research Data from Server
[15:34:43][Client thread] java.io.FileNotFoundException: .\mods\futurepack\lang\en_us\ram.univers.json (The system cannot find the path specified)
[15:34:43][Client thread] java.io.FileNotFoundException: .\mods\futurepack\lang\en_us\ram.univers.json (The system cannot find the path specified)
[15:34:43][Client thread] java.io.FileNotFoundException: .\mods\futurepack\lang\de_de\ram.univers.json (The system cannot find the path specified)
[15:34:44][Client thread] java.io.FileNotFoundException: .\mods\futurepack\lang\ram.univers.json (The system cannot find the path specified)
[15:34:46][Client thread] Send Research Request to Server

**Comment by b0bst3r** [comment]
Ahh looking inside the mod that path should be assets\fp\lang\en-us\ along with all the other files but the missing entries above don't appear to have files in that location.  For example assets\fp\lang\en-us\ram.univers.json does not exist

**Comment by mcenderdragon** [comment]
what futurepack version do yoiu use ? And were have you downloaded it?

**Comment by b0bst3r** [comment]
Says in original post Futurepack-1.12.1-26.1.5.jar and from Curse

**Comment by mcenderdragon** [comment]
hmm..., as I dont know why it is not searching inside the jar, can you test this again with the default vanilla launcher (i guess from the folder you are using multiMC) And can ypo prove the client-latest.log

**Comment by b0bst3r** [comment]
The files don't exist in the mod (where the other files are) no amount of changing anything will make them appear, the files don't exist https://github.com/mcenderdragon/FuturePack-Language/tree/master/en_us here either.  Are you saying that they are in the mod somewhere else?

**Comment by mcenderdragon** [comment]
Yeah, these files have not been written yet. I am sorry, i derped :D
