### ISSUE TITLE
[1.12.1] Can't load a world

### ISSUE THREAD

**Issue by Blatts12** [mcenderdragon/Futurepack-API#247]
https://pastebin.com/x6FRDwd7

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/245. basicly this can be closed.

**Comment by Blatts12** [comment]
BTW. I can create a new world but I can't load it. It's occurs every time.

**Comment by mcenderdragon** [comment]
Everytime is strange, this happens sometimes, but not very often.

**Comment by Blatts12** [comment]
I'm trying without optifine now

**Comment by Blatts12** [comment]
Okay it's optifine's fault

**Comment by mcenderdragon** [comment]
this is interesting... can you open an issue in optifines issue tracker and link it here ?

**Comment by Blatts12** [comment]
https://github.com/sp614x/optifine/issues/893
