### ISSUE TITLE
[Suggestion] Allow Research Machine Restrictions to be Toggled

### ISSUE THREAD

**Issue by Boolyman** [mcenderdragon/Futurepack-API#248]
Hello.  I was very excited to try your mod, and hopefully incorporate it into my upcoming modpack release.  However, in trying to configure the mod in a way that fit the theme and pace of my pack, I realize that you have really locked down the flexibility of the mod.  You don't allow any workaround for the countless hours of research grinding.  Every machine gives you an error if you try to use it without first completing the research.  This is a very strict unflexible way to incorporate the progression.

Even Thaumcraft, who had a very similar research system, allowed "knowledge books" to be shared between players.  In Thaumcraft you could even turn off research, and allow the users to pay experience to activate research nodes.  Now, obviously this is YOUR mod, and you can set it to be as strict or unflexible as you would like.  

A great mod like this is a labor of love, I'm sure.  And I'm sure you have a very specific idea in mind for how you want players to interact with your mod.   But I really feel like you should allow the modpack devs to also contribute to the incorporation of your mod in their packs.  Allow modpack devs to adjust the need for research, or whether machines are locked without research, through the config files.  This will make make your mod a great addition to any style of modpack... not just heavy tech-grind packs.

I saw one of your reddit threads, where you acknowledged that the scanning of research was a common dislike from players.  But I'm not sure if you actually planned on allowing it to be adjusted.

**Comment by mcenderdragon** [comment]
I am not sure, but I think the knowledge books were a addon for Thaumcraft, and any one can make somethin like this for the futurepack too. Your idea to add this to the confics is not bad, but do you need something to disable the research lock in general, or just the machine lock (some recipes are locked too). Or do you want to enable only some machines, if so you would need to know the research name and I could add something like a disabled list to the confics.

**Comment by Boolyman** [comment]
In my opinion, the best approach would be to just have a config option that toggled whether or not all machines were locked to users that had not completed the research yet.  If you wanted to do a whitelist or blacklist type of thing, that would work too, but it seems like it would be more work for you and the modpack dev.

**Comment by mcenderdragon** [comment]
will be in 26.2.10

**Comment by Boolyman** [comment]
That is awesome... way to listen to the community dude... right on.

**Comment by mcenderdragon** [comment]
:D

**Comment by Boolyman** [comment]
I might be reading the versions wrong, but it looks like it went right from 26.2.6 to 26.2.13.  I couldn't find a 26.2.10 and I didnt see anything in the changelog about this option being added.

**Comment by mcenderdragon** [comment]
"+ added config to disable machine lock" from 26.2.13

**Comment by Boolyman** [comment]
My bad, thanks!

**Comment by Boolyman** [comment]
Now that the machines are unlocked, I'm realizing that doesn't really accomplish anything, since the recipes  for all the machines are still locked to research.  I guess there is no way around it, you have pretty much locked down every aspect lol.

**Comment by mcenderdragon** [comment]
:D  yeah we tried to close every shortcut. Do you want more config options ?

**Comment by Boolyman** [comment]
You have been so obliging already, I hate to ask for more config options... I think it would make the mod more flexible, but it's up to you.

**Comment by Boolyman** [comment]
What about just allowing Blueprints to be researched without being locked to the scanner process.  So the only shortcut would be if the modpack creator gave the player the blueprint for an item.

**Comment by mcenderdragon** [comment]
this should be already possible.

**Comment by Boolyman** [comment]
Nope, the blueprint goes in the machine and nothing happens.  No icons show up telling you what items are needing to be input to complete the process.

**Comment by mcenderdragon** [comment]
ok added another config for that.

**Comment by Boolyman** [comment]
Awesome!  I can't wait.  Your mod is going to be a huge part of my upcoming pack, and after you release this build I can finally dive into putting it together.  I'll be watching for the file upload!  Thanks!

**Comment by Boolyman** [comment]
I don't want to rush you, as I know you have a lot on your plate, but do you have an estimate of when this update will be available for download?

**Comment by mcenderdragon** [comment]
Well the next update planed for Sunday

**Comment by Boolyman** [comment]
Damn.  Ok.  Thanks!

**Comment by Boolyman** [comment]
I'm super excited about today's update.  Just wanted to say that lol.

**Comment by mcenderdragon** [comment]
ok, at first the 1.11: https://minecraft.curseforge.com/projects/futurepack/files/2486401
