### ISSUE TITLE
[1.12.1] Host disconnect on LAN player join

### ISSUE THREAD

**Issue by MokahTGS** [mcenderdragon/Futurepack-API#249]
I'm getting a weird disconnect to the main menu when another player joins on a LAN.  Not sure what is causing it as there isn't a crash log.

**Comment by mcenderdragon** [comment]
can you lock in the game log if there is any crash (in your minecraft folder, latest.log ,fml-client-latest.log, and  fp-latest.log)

**Comment by MokahTGS** [comment]
This seems to have been fixed with an update to another mod.
