### ISSUE TITLE
Hologramm don't work for Cables

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#25]
Setting a hologramm for an calbe does no effect. Pipes work correctly.

**Comment by mcenderdragon** [comment]
no

**Comment by mcenderdragon** [comment]
Duplicate of this: https://github.com/mcenderdragon/Futurepack-API/issues/19

**Comment by mcenderdragon** [comment]
Also tested in single or in mutliplayer?
