### ISSUE TITLE
Crash On opening controls - Clientside

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mcenderdragon/Futurepack-API#252]
I like this mod but not enough to prioritize it. Hope this helps future users.

https://gist.github.com/P3rf3ctXZer0/9fe92c79885d324835427dc84a639d11

Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1557715832 bytes (1485 MB) / 8385986560 bytes (7997 MB) up to 8385986560 bytes (7997 MB)
	JVM Flags: 9 total; -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=40 -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSScavengeBeforeRemark -XX:+AggressiveOpts -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms128m -Xmx8064m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
FML: MCP 9.41 Powered by Forge 14.22.1.2485 Optifine OptiFine_1.12.1_HD_U_C5 124 mods loaded, 124 mods active

**Comment by mcenderdragon** [comment]
Hmm, sorry if I ask, but why do you thing futurepack caused this? Did removing the futurepack fixed this? Also I currently wonder why forge is not accepting  out signature...

**Comment by P3rf3ctXZer0** [comment]
yes, removing this mod prevented crash.

**Comment by mcenderdragon** [comment]
Does this also happen with only futurepack installed ?

**Comment by P3rf3ctXZer0** [comment]
Not sure ... I will test it later I just know that it breaks my modpack. I am sure its a mod interaction.

**Comment by mcenderdragon** [comment]
I think this was most likely caused by a coremod. Vanilla code can hardly crash there.

**Comment by P3rf3ctXZer0** [comment]
Whether a core mod or not it seems its only triggered when futurepack is enabled. I have about 217 mods playing nicely together.

**Comment by mcenderdragon** [comment]
did you try the new version ?

**Comment by P3rf3ctXZer0** [comment]
Still loading.

I promise to report the results.
If it helps the modder of Twilight forest had a similar issue back in 1.7.10 days.

**Comment by P3rf3ctXZer0** [comment]
Its fixed.
