### ISSUE TITLE
 a question and a request

### ISSUE THREAD

**Issue by shyguy79** [mcenderdragon/Futurepack-API#253]
hi, 

i love using your mod on my server but i was wondering in the 1.10.2 version is there a way to disable the Hugh dungeons,

many thanks

**Comment by mcenderdragon** [comment]
I am not sure if the config there was alreaqdy implemented, can you send me a copy of the fp.cfg file in your configs folder?

**Comment by shyguy79** [comment]
here is my fp.cfg in a zip file format thank you for the help 


[fp.zip](https://github.com/mcenderdragon/Futurepack-API/files/1318699/fp.zip)

**Comment by mcenderdragon** [comment]
You can try to change hugeDungeon_spawnrate to 0.

`S:hugeDungeon_spawnrate=0.0`
