### ISSUE TITLE
How to automate erse harvesting and accelerate crystal growth?

### ISSUE THREAD

**Issue by donqixot** [mcenderdragon/Futurepack-API#254]
Thank you again for this mod! I have 2 questions.

I tried to use mining drone to harvest erze, no luck. Right click harvest mod "SimpleHarvest" doesn't work either. Is there any way to automate erze harvesting without going to other large tech mods?

Also, how to accelerate alutin and neon crystal growth?

**Comment by mcenderdragon** [comment]
there is no way to accelerate crystakl growth, simply use larger neon sand fileds. Also what happens if you use the mining drone to harvest ores ? does nothing drop or is the minig drone not minign the block ?

**Comment by donqixot** [comment]
Sorry for my german, I meant erse (plant), not erze (ores). I noticed when you hit grown plant once, it gets you fruit and revert back to age 4 of the plant, I was hoping to use mining drone to harvest them, but it removes them completely.

**Comment by mcenderdragon** [comment]
the block breaker can be used to automate farmes (not only erse but also other crops like weath or potatoes)
