### ISSUE TITLE
[1.12.1] RedstoneCables store sygnal forever

### ISSUE THREAD

**Issue by Ardagan** [mcenderdragon/Futurepack-API#256]
forge 1.12.1-14.22.1.2485
Futurepack-1.12.1-26.2.13.jar 
a) cables keeps sygnal on forever
b) cable doesn't hook up to redstone.

a) put 2 vertical redstone cables, attach redstone to cables, give sygnal, remove sygnal. Redstone syngnal will remain on. (just noted, you can break bottom cable after it. cable will lose sygnal, redstone block will remain powered)
b) put redstone on surface, put cable nearby, hook something to cable, give power to redstone. Redstone will be powered, cable will not transmit signal.

![redstonecable](https://user-images.githubusercontent.com/12602502/30837500-3087c1b8-a21a-11e7-8653-5460046e0274.PNG)

**Comment by mcenderdragon** [comment]
the bottom one is powered and powers the upper cable, the upper cable poweres the redstone and the redstone powers the block and the lower cable. you have build a perfect loop.  
fixing this withoput making the redstone cable realy annoing will be difficult.

**Comment by mcenderdragon** [comment]
Does this problem still exists ?

**Comment by mcenderdragon** [comment]
this should be fixed by now.
