### ISSUE TITLE
[1.10.2] No Crystal caves in different dimensions using normal worldgen

### ISSUE THREAD

**Issue by DeadSix27** [mcenderdragon/Futurepack-API#259]
I use Just enough Dimensions to create a overworld dimension but I can not seem to find any crystal cave, I highered the config percentage "hole_neon" assuming its the neon crystal cave percentage to 100 to check if that helps, but no luck so far.. 

Can you offer any help on this?

**Comment by mcenderdragon** [comment]
I am checking for dimension Id 0 (overworld) to generate only there neon and alutin, in menealus only retium and glowtite. the dimensions created by JED have most likely other IDs

**Comment by mcenderdragon** [comment]
Also you can join our teamspeak if you are still online.

**Comment by DeadSix27** [comment]
@mcenderdragon Yes, logically they have another ID, any chance you can make it a list option e.g "Dimension ID's to generate crystal caves in:" 

About TS, sadly it's too late here right now, but I can come another day.

~~If making it a config option is too much work on 1.10, I can also work with a easy change to the code and just run a self-compiled version, you'll have to point me to the line where it checks for dimension ID tho.~~ 
Nvm I thought the whole code is open source, but just the API is..

**Comment by mcenderdragon** [comment]
Has it to be 1.10 ? Because due to a git fault I lost my 1.10 env, but 1.11 and 1.12 are fine.
Edit: we live in the same country :P

**Comment by DeadSix27** [comment]
@mcenderdragon 

> Has it to be 1.10 ?

Yes, gotta be 1.10,2 _unless you want to update EnderIO to 1.12 today :/_

> Edit: we live in the same country :P

Interesting

**Comment by Boolyman** [comment]
For the record, I'm ok with you not updating the 1.10 version until after your next 1.12 release is uploaded.  1.10 is old news :P  Some people can be so demanding... Now you are charged with updating EnderIO LOL

**Comment by DeadSix27** [comment]
@Boolyman You wanna do it? :p

**Comment by Boolyman** [comment]
@DeadSix27  Nope, noone is obligated but the EnderIO dev.  McEnderDragon is extremely kind to even entertain the idea of redoing his whole 1.10 fork after losing the env.  Especially since its not to fix a bug, but to add a new feature for you.  Most devs would just drop support for a  MC version that is already two major patches behind.  This Futurepack team seems extremely dedicated to the community, and we should be thankful for their support.
