### ISSUE TITLE
[1.10.2] Logistic Editor not working on server

### ISSUE THREAD

**Issue by pzlingo** [mcenderdragon/Futurepack-API#260]
Cannot recharge Batteries in Battery-Box neither change state of other items.
Sometimes after clicking 3 times state seemes to change, but not regurarly. There is some error.

**Comment by mcenderdragon** [comment]
can you provide the fml-server-latest.log anf FP-latest.log from your server ?

**Comment by pzlingo** [comment]
Some more information. Using the Logistic Editor there are no visible help to see the current configuration like in other MC versions, not only on Battery-Box, also on Energy-Modules and all others. On 1.11.2 this issue does not exist, but on 1.10.2.


These are the requested file. 

https://pastebin.com/KT8HbiQj

https://pastebin.com/hjZDhVQE
https://pastebin.com/qUPjAgE8

**Comment by mcenderdragon** [comment]
Does this also happen with only futurepack installed, and is this only an isse happening on servers ?

**Comment by pzlingo** [comment]
I tried setting up a server 1.10.2 with just futurepack. Enabled full fp research, and tested Editor on BatteryBox. Same issue. Does not show configuration.

**Comment by pzlingo** [comment]
Experimented same issue on client world only.
Using forge 1.10.2-12.18.3.2477

**Comment by mcenderdragon** [comment]
Ok I think this was an sync issue, does rejoining help/ change the state ? And are you testing wiht neon/energy mode or wich mode are you testing ?

**Comment by pzlingo** [comment]
Actually not. I am testing with Energy mode, but issue is present on all modes. If I click 3 times on a BatteryBox, I may sometimes change its mode from descarging to charging. But no visible indication like I saw on 1.11.2 for example (green/red). I only see the white/blue indicator how much of the BatteryBox is charged. But I cannot see which sides are input and which are output.
Thank you.

**Comment by pzlingo** [comment]
[out.zip](https://github.com/mcenderdragon/Futurepack-API/files/1346293/out.zip)

**Comment by mcenderdragon** [comment]
That outline is rendered very strange, but you say in 1.11 it works ? How does the outline looks there ?

**Comment by pzlingo** [comment]
Yes, I tested it first on 1.11.2. There the outline (green/red) and the different working modes of Logistic Editor worked very well. It was rendered with arrows (incoming/outgoing). I just switched back to 1.10.2 because of some other mods, not because of Futurepack.

**Comment by ToxikPotato** [comment]
Hey, This issue is still here :/ Playing on MC 1.16.5. Trying to build stuff but when i pull out my logistics editor i see the UI for 30 seconds max. Then it dissapears and can no longer see the outline on my battery boxes. If i keep holding it in my hand soon it crashes my game completely, any ideas?

**Comment by mcenderdragon** [comment]
@ToxikPotato I can to repdorduce this, for me it works fine on a server. 
1) What other mods have you installed ?
2) please send the crash report if it crashes
3) please press F3 and make a screenshot and send it
4) please open a new isue with all this.

thanks for reporting this.
