### ISSUE TITLE
Rendering Crash with Futurepack

### ISSUE THREAD

**Issue by Vahara91** [mcenderdragon/Futurepack-API#261]
Hi, 

I got a crash everytime i try to lock at Futurepack maschines. We are playing the "Beyond the Minecraft" Modpack in Version 1.7.2. I can log in, walk around and as soon as I look at a Futurepack maschine the game crashes. I got the crashreport below. I hope you can help me with this. Please tell me if you need more/specific Information. 

Thanks a lot! 

[https://pastebin.com/cQBfe0rm](url)

**Comment by mcenderdragon** [comment]
Its a coremod... can you try to remove FoamFix first and if that does not help all other coremods, one of them is editing miencraft classes so futurepack cant finds a render method.

**Comment by mcenderdragon** [comment]
Does [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.144) fix the bug in 1.11 ? I will do a 1.12 version later this day
