### ISSUE TITLE
Researcher contains wrong Blueprint after update

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#263]
Blueprint inside a Researcher (working) and Scanner changed from "Boardcomuter" to "Plantmarker" (allways researched), after updating from "Futurepack-1.12.1-26.2.14" to "Futurepack-1.12.1-26.2.17".
NBT of researcher get bugged after reemoving the wrong research (high, negative ssupport value)

**Comment by mcenderdragon** [comment]
we save the research id (int) and after inserting new researches this always causes an ID shift

**Comment by mcenderdragon** [comment]
as far as I know negative values can be correct
