### ISSUE TITLE
[1.12] Crash when shift-clicking item

### ISSUE THREAD

**Issue by DaedalusGame** [mcenderdragon/Futurepack-API#264]
This happens regardless of inventory.
Two seperate occasions:
[https://pastebin.com/TqDP8gHX](https://pastebin.com/TqDP8gHX)
[https://pastebin.com/RHG4dk1w](https://pastebin.com/RHG4dk1w)

**Comment by Scrogs63** [comment]
We also have players with this issue

**Comment by mcenderdragon** [comment]
what Item was underneath ? This crash is caused by the Item tooltip.

**Comment by DaedalusGame** [comment]
Supposedly it happened when the guy shiftclicked one of the machines into a chest. It may have been the researcher.

**Comment by mcenderdragon** [comment]
Does [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=26.2.19) fixes this bug ?

**Comment by trogarus** [comment]
Downloading the fix there, will test in a few hours as I am in the middle of some other stuff presently. Will post back the results. I will also be sure to use the same embers aluminum to see if I can reproduce the problem. Sorry for the delay. Past few days have been a bit hectic for me =)

**Comment by trogarus** [comment]
Posted the results at my original crash post, but if you see this first, I shift clicked into and out of the scanner, and used the original Embers aluminum that created my original crash. No crash. Seems the files did the job. Thanks again for your hard work, and keeping your mod crash free =)

https://github.com/mcenderdragon/Futurepack-API/issues/280
