### ISSUE TITLE
1.12.2 - Worldgen is spewing out Teleporter Blocks constantly

### ISSUE THREAD

**Issue by KAfable** [mcenderdragon/Futurepack-API#265]
Forge **14.23.0.2493**
FuturePack: **26.2.17**

Created a flat creative world for testing in my modpack - came across a tall, but slim vertical structure that was FP worldgen. Had Neon Crystals Block at the top and bottom was made out of Purple Metal Blocks. The structure had a teleporter with a red dot on the bottom, and it was dropping Teleporter item entities on the ground (stack per minute). Even in creative it seemed to auto regenerate itself and couldn't destroy any blocks.

https://imgur.com/a/PKVPc

**Comment by donqixot** [comment]
Hi, I am curious to reproduce this issue. Could you provide details like what type of flat world, seed and coordinates of the structure? Thanks.

**Comment by Vyraal1** [comment]
Seed is -2666598245928731485
It was a regular presets for a flat world, Cheats On and Gamemode creative. Structure coords are in the screenshot.

**Comment by donqixot** [comment]
Indeed, this is an interesting case. I noticed that spewing of teleporter blocks stops after a while - I believe it only happens while huge dungeon is being generated around. You can't even see dungeon until you step away and then come back and then the whole dungeon is in the air and spewing stops. I am not a developer of this mod, so I cannot comment on design, but my personal opinion is I like it the way it is. It's kind of cool to see these dungeons in the air. The alternative of not generating anything at all seems too boring. May be there is an option of stopping the spewing.

**Comment by mcenderdragon** [comment]
It is very strange it not only produces this amount of items, but also the wrong items...
