### ISSUE TITLE
[1.12.2] Tech Dungeons Generate Through Bedrock

### ISSUE THREAD

**Issue by MokahTGS** [mcenderdragon/Futurepack-API#267]
v26.2.17

I'm finding tech dungeons generating through the bedrock layer making for some seriously dangerous ladders. :)

**Comment by MokahTGS** [comment]
Here's some screen shots of world gen:

Odd water domes in the ocean:  https://www.dropbox.com/s/4uh3f2u5bvsc9vg/2017-10-06_09.46.38.png?dl=0

https://www.dropbox.com/s/1ecpdty651gmzoz/2017-10-06_09.46.59.png?dl=0

Dungeon through bedrock:  https://www.dropbox.com/s/rxwhooohj5n90cm/2017-10-06_10.05.45.png?dl=0

Also, is it normal for some of the blocks in the dungeon to have block protection?  Is that a feature to keep players from cheesing the dungeons?

**Comment by b0bst3r** [comment]
https://i.imgur.com/AkgRL8n.jpg picture from underneath Y0

**Comment by mcenderdragon** [comment]
[This version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.153) should fix the problem.
