### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by 0Navis0** [mcenderdragon/Futurepack-API#269]
I suggest to add liquid Bioterium, Glowtite, Retium, Quantium, Wakurium since liquid Neon exist. I suggest too to add a compatibily with Tinkers Construct for the liquid metals.

I suggest too to add Wakurium and Quantium crystal block and sand to the Tyros generation for making it more interesting and unique.

**Comment by 0Navis0** [comment]
Is there any news about it ?

**Comment by mcenderdragon** [comment]
We renamed wakurium and Quantanium so they have all the same name. Because of what liquid neon is Tinkers construct support would be logical wise wrong (it is basicaly the silicon version from ethanol and the cristals can dissolve into it)

**Comment by mcenderdragon** [comment]
But yeah liquids of all the other 4 are in our ideas list, we have alot of ideas with liquids.

**Comment by 0Navis0** [comment]
And for Wakurium and Quantanium which would generate naturally in Tyros ?

**Comment by mcenderdragon** [comment]
They are synthetic crystals ingots so basicaly something like n/p-doped silicon, so it would make less sense. And yeah we are aware of the boring terrain, but we will improve it (Menelaus has not yet completeted completly yet)

**Comment by 0Navis0** [comment]
Oh yeah it would be awesome. ^w^
