### ISSUE TITLE
[1.12.2] Techtable recipes shown wrong in JEI

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#270]
The Techtable Recipes should not be shown as "Vanilla Crafting" in JEI (they need a seperated techtable catergory). 
This is confusing!

**Comment by mcenderdragon** [comment]
1.) this is a bug from the 1.12 update from JEI
2.) I have spoken with mezz, he cant do anything as this comes m ore or less from the new crafting system from 1.12
3.) we have to options: making vanilla table work or reimplement crafting logic
4.) the vanilla table can now craft researchable recipes.
