### ISSUE TITLE
Calculation module uneven acceleration in various phases

### ISSUE THREAD

**Issue by donqixot** [mcenderdragon/Futurepack-API#271]
I have 3 calculation modules attached to researcher, they all have 2 torus cores (16 cores in total) and 6 torus ram (48 rams in total), efficiency is at 238.6%. I take weaponry research (waffentechnik) as an example. It requires 48,000 NE plus 6,000 in time.

Without calculation module it takes 48,000 ticks (40 minutes) in phase 2 (energy phase) and 6,000 ticks (5 minutes) in phase 1 (time phase).

With just one calculation module, it takes 5 minutes in phase 2 (8 times acceleration) and 5 minutes on phase 1 (no acceleration at all).

With three calculations modules, it takes 2 minutes in phase 2 (20 times acceleration!) and 5 minutes in phase 1 (no acceleration at all). 

It appears acceleration only applies to energy phase. It would be nice to see acceleration in time phase as well.

I am using Futurepack-1.12.1-26.2.17, forge 14.23.0.2512.

**Comment by donqixot** [comment]
One particularly bad example is weaponry (waffentechnik), it need 48,000 NE and takes about 40 minutes. Blueprint says time required is 6000, if this means 6000 seconds, then it is 100 minutes unaccelerated. If accelerated time is 40 minutes, that's a factor of 2.5. With efficiency of 238.6% in ram, I was expecting at least 4 times faster, possibly 8.

**Comment by mcenderdragon** [comment]
yeah as the research from teh calculation modul srtates, only the neon bar gets a speed up, this is intended. Time manipulation is possible after you have researched quantum sience. Then you can make the external core, w ith can speedup anything (as long as it has a tile entity)

**Comment by donqixot** [comment]
Cool, thanks, good to know. I am closing this.

**Comment by donqixot** [comment]
Do you mean you can make Quantum Core? It is currently locked (no recipe or research), right?
