### ISSUE TITLE
Story "story.dungeon_1" not found

### ISSUE THREAD

**Issue by donqixot** [mcenderdragon/Futurepack-API#272]
I tried to explore new huge tech dungeons in latest version in 1.12.2 and found research named "story.dungeon_1" in wardrobe next to lasers. It was easy to run it in researcher and when it finished, I found 2 icons in page "Story" - Cryptography and Dungeon Key 1, but when I click on them, it says story not found. I am very curious to read these stories!

I am using Futurepack-1.12.1-26.2.17, forge 14.23.0.2512.

**Comment by donqixot** [comment]
Story "space.advanced" when played in English is actually in German.

Also missing stories:
~~story.dungeon_2~~
~~story.dungeon_3~~
story.dungeon_4
~~zent.color~~
~~zent.extraction2~~
~~recycling~~
production.nind.linse.l (purple lense)
~~production.nind.linse.g (green lense)~~
space.turret.heal
space.turret.absorb
~~ionentechnik~~
~~energy.ionen~~
tyros
log.battery.crystal
core.non
ram.non
~~core.dungeon~~
~~ram.dungeon~~
~~core.univers~~
~~ram.univers~~
lasertechnik2
~~astronomie1~~

**Comment by trogarus** [comment]
Also have the same issue with dungeon stories. Have found 2 but don't remember the names exactly. I think it was dungeon 1 and 3,

**Comment by b0bst3r** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/244

**Comment by kingofrunes** [comment]
Btw, the dungeon keys aren't craftable. Will they be craftable in the future so we can actually complete the new futurepack dungeons?

**Comment by mcenderdragon** [comment]
yes, @Wugand is working on it.

**Comment by Wugand** [comment]
Ok, an summary (Development state, maybe diffrent from latest release).
- Thanks for all reports -

Done:
story.dungeon_2  --  done
story.dungeon_3  --  done
space.turret.heal  --  done
core.dungeon -- done
ram.dungeon -- done
core.univers -- done
ram.univers -- done
tools.sword.*  --  done
"nanostructure manipulation"  -- done
"advanced board computer"  --  done
log.supercable  --  done
production.nind.linse.g (green lense)  --  done
zent.color             --  done
zent.extraction2 (Ore Extraction)   -- done
recycling -- done
log.flash.6 -- done
ionentechnik & energy.ionen   -- done
chips.externalcore  --  done
chip.combination -- done
production.nind.linse.l (purple lense)  --  done
space.turret.absorb  --  done
lasertechnik2 -- done
core.non -- done
ram.non -- done
astronomie1 -- done
tyros  --  done

Placeholders (marked as not implemented):
story.dungeon_4  --  not needed atm
log.battery.crystal -- not needed atm
core.entronium -- not needed atm
ram.entronium -- not needed atm

Last changed: 12.11.2018

**Comment by mcenderdragon** [comment]
so updated whats alredy done @Wugand any changes to this ?

**Comment by mcenderdragon** [comment]
- [x] tools.modul.dynamo
- [x] tools.modul.oxygenmask
- [x] tools.modul.magnet
- [x] tools.modul.paraglider
- [x] bergbau2
