### ISSUE TITLE
Suggestion: Configs to whitelist/blacklist Worldgen

### ISSUE THREAD

**Issue by KAfable** [mcenderdragon/Futurepack-API#273]
Would it be possible to add configs (for modpack makers mostly) to set where Tecdungeons and Crystal holes/caverns would be? I'm planning a multidimensional modpack and was actually hoping to have some of your crystals and their structures spawn in the twilight forest if that were possible.

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/298
