### ISSUE TITLE
Menelaus gravel not found on Menelaus

### ISSUE THREAD

**Issue by donqixot** [mcenderdragon/Futurepack-API#274]
Menelaus gravel is very useful material to produce Rare Earth, yet I do not find any on Menelaus. I used world-edit mod in my testing, selected very large area - 512x512, from level 0 to level 127, not a single block is Menelaus gravel. Of course I can get by with Menelaus dirt, but it would be nice to have Menelaus gravel as well.

**Comment by mcenderdragon** [comment]
yep very rare. But it would be to easy if I just say where to find it (and maybe i played to much secret world legens ...). So here is a hint:  menelus gracel will be there, where in reality also would be very large amounts of gravel.

**Comment by donqixot** [comment]
Thanks! Will be looking...
