### ISSUE TITLE
Quantum Tech dependencies

### ISSUE THREAD

**Issue by donqixot** [mcenderdragon/Futurepack-API#275]
I am testing version Futurepack-1.12.1-26.2.17, Forge 14.23.0.2512.

On page "Basics" there are 3 research items which are directly dependent on Quantum Tech (quantentechnik) -  Ion Tech (ionentechnik), Laser Tech2 (lasertechnik2), Astronomy1 (astronomie1). I tried to scan quantanium ingot, but it cannot be researched. Which item can be scanned in place for  quantentechnik? It looks like Astronomy1 and Laser Tech2 are Work in Progress and are currently locked, but what about Ion Tech? Or is this the type of blueprint we suppose to find in dungeons?

Another item is Laser bow, in the past versions we could find this blueprint in dungeons, what do we do now?

**Comment by mcenderdragon** [comment]
the laserbow blueprint is still findable in the dungeons.

**Comment by donqixot** [comment]
Ok, thanks, I take it the rest is Work in Progress.
