### ISSUE TITLE
modified creepers dont scan for chemistry (isDerived instead of isType)

### ISSUE THREAD

**Issue by ghoulsblade** [mcenderdragon/Futurepack-API#276]
afaik scanning a creeper should unlock the chemistry aspect, it doesnt work in BobsTechMarvel (AT), i suspect its due to creeper mobs being modified by another mod, probably using a derived class,
so i'd suggest using a check if the mob is derived a derived class of the vanilla creeper as well as literally the same if that is possible.
Futurepack-1.12.1-26.2.19.jar
and i think the mod that causes it is this one:
BetterWithMods-1.12-2.0.14.jar 
Workaround for Players: scan a witch, they're a lot harder to come by sadly.

**Comment by donqixot** [comment]
Could you scan TNT instead?

**Comment by mcenderdragon** [comment]
a Witch should also work. And brewingstands. If it dont work the the mod is not using the EntityCreeper base class.

**Comment by ghoulsblade** [comment]
yeah, can you check if it is a derived class of the EntityCreeper intead of exactly that class maybe ?

**Comment by mcenderdragon** [comment]
I check for "isAssignableFrom" , this is true if this class or any parent is the Creeper class. (So there is nothing a can do, codewise it is an entirely different entity)

**Comment by ghoulsblade** [comment]
ah ok, thats cool then, thanks :)
