### ISSUE TITLE
[1.12] Heating Mechanics Are Very Confusing

### ISSUE THREAD

**Issue by MaxAstro** [mcenderdragon/Futurepack-API#277]
Currently trying to tweak a water turbine for optimal output, and I am very confused.  Trying different combinations of chips and I really can't work out what works best.  I think things stop working if they overheat, and that reduces your output...  But some of the numbers change as I swap chips and some of them don't change unless I close and reopen the GUI.  And every time I open the GUI the numbers are different.  And the heat does this thing where when I open the GUI it's really high, but then it suddenly drops to nothing... until I close and reopen the GUI again...  I have an external cooler attached, if that makes a difference.

Not sure how much of this is working as intended or if any of it is a bug, but it's very confusing and counter-intuitive.

**Comment by mcenderdragon** [comment]
the heat drop is caused because the machine stops ticking while you open them,  but the enviorement still cools it down. Probably alot of the weird numbers and reopen issues are caused by this.

**Comment by MaxAstro** [comment]
Okay, well, with respect...  That's *really* confusing and not very helpful as far as being able to tell what heat your machines are actually actively running at.  :)

**Comment by mcenderdragon** [comment]
well stopping them was an idea so they dont instandly break if you put new parts in but well, it didnt got that well... A restart button would help right ?

**Comment by MaxAstro** [comment]
Maybe instead of displaying the current temp the machine could display the temp it was running at before you opened it?

Just anything to make it more possible for the player to see what temp their machine is actually running at peak.

**Comment by mcenderdragon** [comment]
I found alot of sync isses so the client heater was never syncronised with the servrer, and also a start button. overc locking is now a lot more fun .
