### ISSUE TITLE
Tech Dungeon looses protection

### ISSUE THREAD

**Issue by kingofrunes** [mcenderdragon/Futurepack-API#279]
So I was exploring a tech dungeon at first it worked fine and all but then after seeing that I couldn't progress any further I left and went away. Chunk hadn't been loaded in a few days, and a few server restarts happened from there. Did a bunch of research (none of the dungeon researches) and came back and the spawn protection of the dungeon was gone. No signs of any other player having visited. Looking around it seems you are storing the protection state it in a dat file and you have a couple other issues related to this that you are trying to fix so maybe this is already fixed. Making this just in case though.

Unless me being the OPS on the server is what's causing me to be able to bypass it?

**Comment by mcenderdragon** [comment]
well it is realy strange at some servers the dat file gets extremly huge (2MB+), normaly everything should get saved in the chunk itself so no extra files, but it seems sometimes the evnts dont trigger correctly.

**Comment by mcenderdragon** [comment]
can you provide the log from this session ?

**Comment by kingofrunes** [comment]
I was checking through the log and I didn't see anything that would be related. My server only seems to have a log file for sunday. Possible the corruption happened before then. My client was receiving a lot of lag on Saturday that was making the game unplayable. I ended up rebooting the server then. Wonder if that's the day it got corrupted.

What I do have though is lots of backups. Let me compare my earliest backup I have with what my current dat file is like see if that helps. Scratch that, seems the only good backups I have is from yesterday. I'll just send you the FPDungeons.dat file for now so there's at least something :/

**Comment by kingofrunes** [comment]
[FPDungeons.zip](https://github.com/mcenderdragon/Futurepack-API/files/1410046/FPDungeons.zip)

**Comment by mcenderdragon** [comment]
I absolutly dont know why this file is so fucking huge...

**Comment by mcenderdragon** [comment]
lossing protection should be fixed with [26.2.42](http://redsnake-games.de/Downloads/fp/fp.php?version=26.2.42)
