### ISSUE TITLE
[1.12.2] Crash mousing over items.

### ISSUE THREAD

**Issue by MokahTGS** [mcenderdragon/Futurepack-API#282]
https://pastebin.com/NM9Scptg

Get this crash with FB v26.2.17

**Comment by MokahTGS** [comment]
So this is happening consistently when mousing over the industrial furnace from FP.  I tried to shift click it into the FTB trash can and it crashed.

https://pastebin.com/yabvBE4j

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/280

**Comment by mcenderdragon** [comment]
THis is  caused by one of the core mods. We dont know yet wich one is causing it.
