### ISSUE TITLE
Dungoen Protection and Entry Platforms (suggestions)

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#283]
Although it seems like once a dungeon is cleared, that you can then harvest the blocks, which I am fine with but unsure if that's the desired functionality. HOWEVER, with this said, you cannot remove the entry platform even in creative. This is an issue as it can mess up a build if one wants to clear one of these areas, especially if they are close to spawn.

If it is intended that these structures are not to be cleared (permanently protected to prevent harvesting blocks etc) then maybe consider an implementation like Actually Additions came up with where the blocks break into nothingness. Just some thoughts and a request to fix the protection system so that we can somehow remove the blocks for builds, especially those near spawn.

**Comment by trogarus** [comment]
Also of note, have found NO way of removing the force field blocks short of being lucky enough to clear the dungeon and then go creative to remove them.

**Comment by mcenderdragon** [comment]
well the force fields are there to not get destroyed, after all tehy should protect stuff. But yeah when building stuff this can be tiresome

**Comment by trogarus** [comment]
I get protecting, but, at some point in time, in theory, you should be able to remove them to get to what is on the other side right? Else, what is the point of what lies beyond the field other than to take up space in the world? If we can't get past it, then it's just hogging up space with no real purpose. If we can't get past it, then what's the point of your work in generating the stuff beyond it that we'll never see?

**Comment by mcenderdragon** [comment]
no it cant be destroeyed, but it can let you pass through it, if you meet the requirements ;)

**Comment by trogarus** [comment]
Ahhh, whelp, no idea what those are. Haven't figured that out yet. But playing through so far, everything is functioning up through the menalous stuff. Of course, I'm at the point where I can't progress further without building the ship and making the jump. Trying to figure that out at this point. Watching JavaVampire's play through to see how that works presently. So as of last release plus the present file fix, all is working so far except the missing dungeon stuff, and the story tab with the research.story.kryptogrophie stuff. Rather enjoying the mod, save some of the research takes a bit long for my tastes given I am an adult gamer with limited time =)

**Comment by ghost** [comment]
Ooooh, well, I guess I've kinda broken the progression. I didn't understand what the hell I should do with the Forcefields, and, considering the dungeons have no protection, I made a tunnel by its side to get to the other side. Welp.
Now I'm sad.

**Comment by mcenderdragon** [comment]
they should have protection...

**Comment by kraft2004** [comment]
Strange, something is wrong in my world then. 

FP 26.2.17

**Comment by trogarus** [comment]
As of Futurepack-1.12.1-26.2.39, after clearing a dungeon, the protection thing and removing the top platforms for entry seems to no longer be an issue. Just figured I'd report that back here, as I just cleared 2 dungeons side by side and was now able to remove both top platforms. So at least that part of it doesn't seem to be a problem, but they're still losing protection before clear (I was able to cheat past the walls by the lasers again)

**Comment by mcenderdragon** [comment]
I forget to add the data... expect a 41 wich should fix just everything :P

**Comment by trogarus** [comment]
OK, I haven't restarted game yet, so I'll just wait for the 41 then before I do the restart later =) Thanks again =)

**Comment by mcenderdragon** [comment]
ok wait, you alredy got the 41, the next whould be 42.

Thsi link will works as soon as the version is uploaded: [26.2.42](http://redsnake-games.de/Downloads/fp/fp.php?version=26.2.42)

**Comment by trogarus** [comment]
Derp on my part, yes, 42, checking for it now.

**Comment by trogarus** [comment]
Still waiting on the water and fluids to be cleared before I run the builder to crater that area I typically do. The pump part normally takes the better part of a day afk =) So by tomorrow, I should be  back to report about the rift stuff, and maybe the results of another dungeon run =) Still haven't figured out how to bypass the force field though. No idea what item is required =)

**Comment by mcenderdragon** [comment]
in the wrd robe should be a research.... *hint Hint*
