### ISSUE TITLE
[1.12.1-26.2.17] Messages in Chat and Titles use Unlocalised Names

### ISSUE THREAD

**Issue by ThomasRules2000** [mcenderdragon/Futurepack-API#287]
Messages in chat are the delocalised names (such as laser.attack.warn.time) instead of the message in English.

**Comment by mcenderdragon** [comment]
anything else besides laser.attack .... ?

**Comment by ThomasRules2000** [comment]
The ones that do the titles on the screen also do it, but I can’t remember off the top of my head what they say.

**Comment by mcenderdragon** [comment]
yeah it seems like I forgot to write the mapping into the lang files :>

**Comment by mcenderdragon** [comment]
ok laser and the dungeon messages are fixed.
