### ISSUE TITLE
Industrial Neon Furnace Not Working?

### ISSUE THREAD

**Issue by MaxAstro** [mcenderdragon/Futurepack-API#289]
Finally, after much work, I got the INF.  However...  The instant I placed it down, it sparked and said "your machine is burned".  When I opened it, the chips I used to build it were gone.  Okay...  I added new chips, and now it isn't giving an error.

However, it's refusing to accept Neon energy.  I have a water turbine connected to it with cables, and it's energy sits at 0.  I know the turbine is working because if I connect it to a battery, the battery ticks up.

Help?

**Comment by trogarus** [comment]
Have you used the tool to be sure energy is being extracted from the turbine and that the machine is set to input, or checked to be sure it's default set and didn't change for some reason?

**Comment by MaxAstro** [comment]
Yeah.  I don't know what happened - I ended up destroying the furnace and replacing it with a new one and it worked fine.  Haven't had any problems since then.

**Comment by trogarus** [comment]
There is also an update on curse for the mod. Might want to grab it =) Has some other bug fixes in it =)

**Comment by mcenderdragon** [comment]
This was propably linked to #426.

**Comment by thePalindrome** [comment]
Reporting this issue on 26.3.210

The components exist, but it is not accepting power (I have verified that NE is available)

**Comment by mcenderdragon** [comment]
@thePalindrome this is a bug due to cashing, it is possibel to have a power outage for roughly about 30 seconds and then energy is properly transmitted again. The fix is already in progress (currently testing if it always works).

**Comment by thePalindrome** [comment]
All other machines are working, and Ive spent 30 minutes here scratching my head at why theres no power in this one machine. Any workarounds? (Im rather new to FP)

**Comment by thePalindrome** [comment]
Creative spawning one works, even after replacimg the components

**Comment by mcenderdragon** [comment]
please check with the logistics editor if the sites of your machine are correct configured, maybe they were wrong.

**Comment by Tronif** [comment]
Hi guys.
I play Minecraft 1.12.2, FuturePack MOD 26.3.210.
Industrial Neon Furnace works in Creative world, but don't work in Survival. It seems that NE is not supplied to INF.
I'm stuck with this problem,  so please give me hints and advice.
