### ISSUE TITLE
Research Not Found Futurepack-1.12.1-26.2.19 MC 1.12.2

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#291]
Ore Extraction
'production.zent.extractions2' no found, report this to the mod autors

Color Production
'production.zent.color' not found, report this to the mod autors

**Comment by trogarus** [comment]
This is still missing in Futurepack-1.12.1-26.2.27 as well. Just a heads up. You did catch some of them, as I saw posted in some other localization issues posted in past days, but this is still missing. The dungeon ones are still missing as well.

**Comment by donqixot** [comment]
#272 all missing stories listed in 272 in comments.

**Comment by b0bst3r** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/244
