### ISSUE TITLE
Crash with Terraqueous

### ISSUE THREAD

**Issue by davqvist** [mcenderdragon/Futurepack-API#292]
Forge 2515
MC 1.12.2
Futurepack 26.2.27

I was flying around in creative on Menelaus and when I reached the Sea Biome it crashed. Log hints at interaction with Terraqueous, not sure which mod's fault. Let me know if I should report to Terraqueous dev.

https://pastebin.com/tN1Li59c

**Comment by mcenderdragon** [comment]
I think this is an issue from Terraqueous, as it is passing the wrong state to Block.canSustainPlant

**Comment by davqvist** [comment]
Reported
