### ISSUE TITLE
[1.12] Improve Hologram Rendering

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#294]
- [x] Holograms should use fast TESR
- [ ] Improve pipe rendering
- [x] Improve wire rendering

**Comment by trogarus** [comment]
So this is the reason my FPB drops so badly and my memory spikes after adding hologram blocks and little else? =)

**Comment by mcenderdragon** [comment]
fps drops yeah , memory spikes normaly no.

**Comment by trogarus** [comment]
Seems cyclops core has/had a netty leak, which is probably the root of the memory increase. I've already posted there concerning what they thought was a fix, which doesn't seem to be a fix as the creep is still happening even with updating to their present cyclops core version. =)
