### ISSUE TITLE
Feature request: travel to another mods dimensions using Futurepack's ships.

### ISSUE THREAD

**Issue by donqixot** [mcenderdragon/Futurepack-API#297]
There are many mods with new dimensions. Advanced Rocketry by default adds some 63 planets (many more can be manually created). Futurepack small dungeons are already generated in all of these planets. It would be way cool to be able to travel to these using Futurepack's ships! Even getting to The End using ship would be really cool!

**Comment by mcenderdragon** [comment]
This is all possible and we provide an API for other mods to register as planet.

**Comment by donqixot** [comment]
So in case of The End, how to use these?

**Comment by Wugand** [comment]
In the moment, the only way is to build your ship inside the End. 
If you don't destroy the boardcomputer you can allways get back to The End, using the home button.

**Comment by donqixot** [comment]
ok, thanks.
