### ISSUE TITLE
Tec Dungeons still spawning every after configs set to 0, also Worldgen Dim Black/Whitelist?

### ISSUE THREAD

**Issue by KAfable** [mcenderdragon/Futurepack-API#298]
Chance of a normal Tecdungeon to spawn in a chunk [range: 0.0 ~ 0.2, default: 0.006666667]
S:tecDungeon_spawnrate=0.0

Chance of a huge Tecdungeon to spawn in a chunk [range: 0.0 ~ 0.2, default: 0.0035]
S:hugeDungeon_spawnrate=0.0

https://cdn.discordapp.com/attachments/362334528720601088/375807311584952320/2017-11-02_20.43.31.png

This still resulted in Tec Dungeons appearing in Dim 0, which I designed specifically to be a skyblock. Would it also be possible to get a Dimensional Blacklist/Whitelist for the worldgen? Including the dungeons and the crystal caves?

**Comment by DJJBanx** [comment]
Also dungeons seem to be able to go below Y-level 0, allowing for holes into the void in some worlds.

**Comment by mcenderdragon** [comment]
@DJJBanx does this also happen in 26.2.27 ? (And if you have created a world wich an older version maybe it got generated there but you only have found it now)

@Vyraal1 this is odd and not intended...
Also Blacklists/WHitelist is something I thought abou alot. What is more likely for a User to know the DImension ID or the registered DImensional name ?

**Comment by davqvist** [comment]
My 2 cents; It is common practice to use dimension ids

**Comment by mcenderdragon** [comment]
@davqvist I was just asking because The futurepack uses dynamic ID hopping if 73 and 74 are not available.

**Comment by davqvist** [comment]
Sure but often you care about dimension from other mods which you want to blacklist, right? So I think using "/forge tps" to get the dim id or any other easy method should be much easier. Also let's say I have Advanced Rocketry, I have no idea how all the planets are named internally, but I can get the ids very easily.

**Comment by mcenderdragon** [comment]
I hope this blacklist/whitelist design is ok.

```
# A whitelist for enabling alutin crystal caves in other dimensions. [default:[0]]
    I:wl_alutincave <
        0
     >

    # A whitelist for enabling bioterium crystal caves in other dimensions. [default:[0]]
    I:wl_bioterium_cave <
        74
     >

    # A whitelist for enabling glowtite crystal caves in other dimensions. [default:[0]]
    I:wl_glowtite_cave <
        73
     >

    # A whitelist for enabling huge dungeon spawn in other dimensions. [default:[0]]
    I:wl_huge_dungeons <
        0
     >

    # A whitelist for enabling neon crystal caves in other dimensions. [default:null]
    I:wl_neon_cave <
        0
     >

    # A whitelist for enabling retium crystal caves in other dimensions. [default:[0]]
    I:wl_retium_cave <
        73
     >

    # A blacklist to stop tec dungeon spawn in dimensions. [default:[0]]
    I:bl_tec_dungeons <
     >
```

**Comment by Vyraal1** [comment]
Agreed with Qvist on Dimensional Id over registered names, mostly cause it's easier to find across most mods and troubleshooting methods. 

Also thank you so much for separating each feature gen to have it's own config list, thats much more useful than a blanket list for everything.
