### ISSUE TITLE
Tech Dungeon Can't find Story 1 Research

### ISSUE THREAD

**Issue by kingofrunes** [mcenderdragon/Futurepack-API#299]
I think you may need to tweak how often the Story 1 Research for the dungeons come up. I've visited 3 or 4 so far and all of them haven't had story 1 before I hit the first barrier. Lots of Story 2 though.

**Comment by mcenderdragon** [comment]
seems like the gods of random dont like you much...

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/272
