### ISSUE TITLE
[1.10] internal server error when jumping planets

### ISSUE THREAD

**Issue by MechWarrior99** [mcenderdragon/Futurepack-API#3]
Why trying to jump to another planet the would will shut down with an internal server error, but the game will not crash.
Once you rejoin the world you will be in your ship close to/at the top of the world. 
after trying to jump again the same thing will happen but when you rejoin the world your ship will be gone but you will still be in the overworld.
Using FP 1.10.2-24.1.2

**Comment by mcenderdragon** [comment]
;( meh.You tried to jump to Menelaos or to Tyros?

**Comment by mcenderdragon** [comment]
I cant repdroduce the bug but is not working, so i will look into this.

**Comment by MechWarrior99** [comment]
I tried to jump to the one with the yellow icon. Sorry I'm not sure which that is.

**Comment by mcenderdragon** [comment]
yes thats menelaos. http://redsnake-games.de/Downloads/fp/fp.php?mc=1.10.2. In a few minuits there should be a 24.1.3 available. There thi should be fixed :)

**Comment by psychofad** [comment]
Is that related to this crash: 

[http://pastebin.com/fAyuNHg0](http://pastebin.com/fAyuNHg0)

or do i need to open another issue?

TP'd to dimension 73 as OP and this crashed my server.

**Comment by mcenderdragon** [comment]
@psychofad this is another issue. Please open a new one.
