### ISSUE TITLE
Tyros leaves are undestroyable

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#30]
Tyros Leaves are undestroyable in Survival and Creative

**Comment by mcenderdragon** [comment]
cant reproduce :/, but saw it on the server

**Comment by mcenderdragon** [comment]
maybe this is caused by the forestzry farm?

**Comment by Wugand** [comment]
Also at real Tyros Tree ... maybe a effect of color change?

**Comment by mcenderdragon** [comment]
nope not connected with color.

**Comment by Wugand** [comment]
It happens!

**Comment by mcenderdragon** [comment]
Does this also happen on a only fp server?

**Comment by Wugand** [comment]
A main problem of tyrosleaves is the use of "getCombinedLight", which is not existing on the server.

Report:
http://pastebin.com/7043GAg4

**Comment by Wugand** [comment]
without this crash it is destroyalbe ... but it needed for color

**Comment by mcenderdragon** [comment]
should now be fixed
