### ISSUE TITLE
Stuck on post Tyros Research

### ISSUE THREAD

**Issue by kingofrunes** [mcenderdragon/Futurepack-API#300]
I can't seem to progress in research to get access to:

Ion Collector
External Processing Unit
Regeneration Laser
Nanostructure Repair Unit

I get ? when attempting to scan the Solar Generator, Recycler, and Laser Turret.

I've tried scanning every thing I can and not making any headway. Like the Advanced Boardcomputer, Researcher - Experience Module, Quantium ingot, the coordinates, the telescope. None of them are yielding anything and the cores/ram lead to a dead end as well.

**Comment by kingofrunes** [comment]
These are the researches I"m guessing those things are locked behind but I can't seem to get the research for these:
![ss 2017-11-04 at 12 06 23](https://user-images.githubusercontent.com/1063298/32407029-ac0d0b10-c158-11e7-9f63-ff99e1d1e962.png)

**Comment by mcenderdragon** [comment]
You alredy were on tyros and got some bioterium crystals ?

**Comment by kingofrunes** [comment]
Yes. I did that prior to the last release you did. When I got back from Tyros and did research it didn't auto give me the Tyros research despite me having gone there and had to manually give it

**Comment by mcenderdragon** [comment]
Have you already the timemanipulator (production) and the dronestation (space) ?

**Comment by kingofrunes** [comment]
The time manipulator is one of the things I can't seem to get. Recycler I'm assuming is supposed to give that but it's giving a big yellow ? when I research it and got Drone Station but it's saying I've gotten everything from it.

**Comment by mcenderdragon** [comment]
Ahh ok, it is not possible. For anything else you need one of the 3 researches after quantum technologie, but you cant get them, because quantum technonolgie doesnt enables any items so you have nothing to continue researching.

**Comment by mcenderdragon** [comment]
Thanks for pointing this out.
