### ISSUE TITLE
Problem with Kryptographie

### ISSUE THREAD

**Issue by Vsgroundnet** [mcenderdragon/Futurepack-API#304]
There seems to be a problem regarding the Kryptographie on the Story Tab.
It says: 'story.kryptographie' not found, report this to the mod author.
I dont know if this issue was already posted before, but if it was, it's just another heads up.

![imagem](https://user-images.githubusercontent.com/33607555/32703421-bd46f792-c7ed-11e7-8e0e-44057209f4f1.png)

![imagem](https://user-images.githubusercontent.com/33607555/32703423-cabbae90-c7ed-11e7-8ee1-ff9cebbb6978.png)

**Comment by donqixot** [comment]
see also #272

**Comment by mcenderdragon** [comment]
this is alredy fixed but not realesed yet...
