### ISSUE TITLE
Which event type of decoration is "fp:erse"?

### ISSUE THREAD

**Issue by donqixot** [mcenderdragon/Futurepack-API#306]
I am trying to use BiomeTweaker with Futurepack. I need to disable fp:erse generation on some worlds (like Mars). According to forge https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/event/terraingen/DecorateBiomeEvent.java#L112

there are following type of decoration events:
public static enum EventType { BIG_SHROOM, CACTUS, CLAY, DEAD_BUSH, DESERT_WELL, LILYPAD, FLOWERS, FOSSIL, GRASS, ICE, LAKE_WATER, LAKE_LAVA, PUMPKIN, REED, ROCK, SAND, SAND_PASS2, SHROOM, TREE, CUSTOM }

Which one is fp:erse decoration? I tried FLOWERS, GRASS, SHROOM, CUSTOM, DEAD_BUSH, nothing works. Before I submit issue to BiomeTweaker, I need to know which event is it.

**Comment by mcenderdragon** [comment]
none of them, I use ore generation to replace tall grass (single blocks, not the double blocks). because the decorstion event is for biomes, and I have no control over vanilla biomes. 
SO if you block normal grass also erse will get blocked.

**Comment by donqixot** [comment]
Thanks!
