### ISSUE TITLE
Question - Resetting Tyros and Menelaus for Server Admins

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#307]
I am guessing that to do this, like some admins reset the end from time to time, you just go into the saves and delete the tyros or menelaus folders. I am correct in this assumption, or is there more that needs to be done to reset worlds, or is it not possible to do so? Thanks, still rather enjoying the play through on the mod.

Reason I want to reset is I accidentally went to tyros in creative mode (I was fixing some stuff in the world and forgot to revert to survival before going).

**Comment by mcenderdragon** [comment]
yeah just deleting the DIM filders should be enough :)

**Comment by trogarus** [comment]
Another clarification, as I've seen a world folder in other mods and a dim folder. So to be fully clear, deleting either tyros or menelaus folder is all that is created by your mod and there is no 1DIM or -1DIM (1 used as an example only for any number that might be given)? Sorry, just trying to be fully clear on the process, so that should i see others wondering how to do so I can properly tell them how =)

**Comment by mcenderdragon** [comment]
deleting the menelus/tyros folder will reset the dimension, this does not affect any content from the overworld or other dimensions (this is al in the regions folder or in extra files)

**Comment by trogarus** [comment]
Many thanks again, not only for the very prompt responses to things I've posted here, but for the mod and your work on it.
