### ISSUE TITLE
Items using builtin/generated model

### ISSUE THREAD

**Issue by Shadows-of-Fire** [mcenderdragon/Futurepack-API#308]
Some of your items (it's inconsistent, but there are a few) are using the horrible looking model known as `builtin/generated` which was commonly used in 1.8.9, but doesn't look like normal items, and it makes items using it feel out of place.  
This toasted core is using said model (item: `fp:spaceship`)
![Item with builtin/generated](https://i.imgur.com/odnc2NC.png)
However, the E-Scanner is using the proper model (`item/generated` or `builtin/generated` with the transform `forge:default-item`)
![E-scanner with proper model](https://i.imgur.com/0bnY95x.png)
You can see the difference being one is being held like a shield, while the scanner is held as a normal item.

**Comment by mcenderdragon** [comment]
ok mI have fixed in int toasted ram, toasted chip, and toasted core, have you found it anywhere else ?

**Comment by Shadows-of-Fire** [comment]
I think those were the only ones, but I haven't progressed very far in the mod.
