### ISSUE TITLE
Rendering Pipes and wires

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#309]
https://puu.sh/ynYyF/19b70f040b.png

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/294

**Comment by mcenderdragon** [comment]
Swtich Pipe + Wire to JSON
(https://github.com/TheGreyGhost/MinecraftByExample/tree/master/src/main/java/minecraftbyexample/mbe05_block_dynamic_block_model2)

**Comment by mcenderdragon** [comment]
wires are now JSONS.
So only Pipes left.

**Comment by mcenderdragon** [comment]
as cables have a lot of bugs regarding uüdates and pipe need to render items, they will keep the model for now, but maybe use a Fast TESR for the rendering

**Comment by SkyProgs** [comment]
@mcenderdragon @Wugand wie beschlossen bitte schließen
