### ISSUE TITLE
Block Breaker dupe bug

### ISSUE THREAD

**Issue by braingkk** [mcenderdragon/Futurepack-API#31]
When using the block breaker, many magnets and other auto collectors seem to grab the broken block as well.

this results on the block being the storage chest behind the breaker as well as the player inventory or other collector.

**Comment by mcenderdragon** [comment]
In wich version dioes this ocure and wich Mod add these collectors? Does this also happens with the Vanilla Hopper?

**Comment by braingkk** [comment]
after further testing, it does seem to only work reliably with the "Quantum Flux" Item Magnet.

version of the mod is 24.1.4 pre, using 1.0.1 api.

version of quantum flux being used is 1.9.4-2.0.7

**Comment by braingkk** [comment]
on further investigation, it may be a quantum flux issue, https://github.com/joekaiser/QuantumFlux/issues/102
sorry for raising flags in the wrong place

**Comment by mcenderdragon** [comment]
No its okay, better to much than not enough.
