### ISSUE TITLE
Crash due to sided AABB constructor

### ISSUE THREAD

**Issue by Shadows-of-Fire** [mcenderdragon/Futurepack-API#310]
https://gist.github.com/Shadows-of-Fire/918bfc490750e30151219b70ce0b007f
Futurepack: `26.2.27`
Forge: `14.23.0.2538`
You're using the client-only AABB constructor `AxisAlignedBB(Vec3d min, Vec3d max)` in a dedicated server environment.  Surprised forge hasn't de-sided that constructor yet.

**Comment by mcenderdragon** [comment]
Fixed in 26.2.33

**Comment by mcenderdragon** [comment]
[Version 26.2.39](http://redsnake-games.de/Downloads/fp/fp.php?version=26.2.39) (so also other bug fixes)
