### ISSUE TITLE
Bedrock rift not honoring COFH flat bedrock oregen Futurepack-1.12.1-26.2.39 forge 2544 MC 1-12-2

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#312]
Results in a bunch of floating rifts in flat bedrock world gen. Are there supposed to be so many?

**Comment by mcenderdragon** [comment]
I have not understood a signle world. what is a cofh flat world ? (why is this needed, can't you just use the vanilla custom layers?) and what is a bedrock rift ?

**Comment by trogarus** [comment]
It is generating and labeled as futurepack block. COFH is behind the thermal mods, like Thermal Dynamics etc. They also include the ability to generate flat bedrock, which I prefer over the swiss cheese bedrock gen created with vanilla mechanics. All it does is makes the bedrock layer flat, and however many layers you want it to be. I typically only use 1 so that the overworld has 1 layer at the bottom and the nether has one layer at the top.

A lot of people use the thermal mods for automation, machinery, and in absence of ender IO, it is the goto pack, most times, for ducts to transfer fluids, items, and redstone. Let me attempt a screen shot so you can see what I'm talking about. *scratches head trying to remember how to do that in minecraft*

**Comment by mcenderdragon** [comment]
Ahh I rember and finally know about what you are talkin, sorry I am stressed Uni is sucking up time :/. 
Yeah, bedrock rifts should be this many, and well they are becoming a very important Futurepack feature and well they are bedrock. I am locking into it to improve it so they are less floating. meaybe just generating berrock around them so it locks like a little hill.

**Comment by trogarus** [comment]
No worries, I understand stress, did uni myself, also did military. Many just like the ability to have flat bedrock so it doesn't mess with them trying to build or automate things (you know, the frustration of trying to work around bedrock that you can't move when you're trying to build or automate something). So not sure how that mound thing would work. Maybe just ensure they only generate at y 1 as an alternative? Then they wouldn't float at all =) Or y level of top of nether dimension?

**Comment by trogarus** [comment]
Oh, and side note, updating to the later forge and some of the mod updates did some world corruption;. So rather than roll back, I'm just starting a new world, so will be able to report if there are any issues from a fresh run of futurepack in my modpack. I'll keep posting as I have been, files and such as well.

**Comment by trogarus** [comment]
So basically, I'm not a coder, but wouldn't it be easy enough to check for dimension and then have the generation restricted to the y level that corresponds to the typical dimension bedrock gen? Then having it only generate on either the bottom most y level (for dimensions like overworld where y1 is bedrock) or topmost y level like the nether?

**Comment by mcenderdragon** [comment]
I have not written the rifts myself so I will look into it, it is probaply only something minor.

**Comment by mcenderdragon** [comment]
Ahh okay it is complicated, we first generate the rifts, and then flat bedrock removes the bedrock around it so it locks like floting, and we cant fix it because if we just add more bedrock it will get removed :S, but I have an idea.

**Comment by mcenderdragon** [comment]
Fixed: [Version 26.2.41](http://redsnake-games.de/Downloads/fp/fp.php?version=26.2.41)

**Comment by trogarus** [comment]
Already grabbed the file, as stated in the other thread, I'll slot it for next game restart and let you know how it is working. Do these also generate in the other dimensions like nether, rf dimensions, and the mining dimension? =)

**Comment by mcenderdragon** [comment]
yes they should.

**Comment by trogarus** [comment]
Good, then I won't have to crater another spot in my overworld =) I try to keep that to a minimum of 1 per dimension when I play. I clear out a big ole 501 by 501 cylinder so I have plenty of resources and then play it a bit like a skyblock. Not as much overhead for my laptop potatoe as then mobs only spawn where I allow them to =) Nice and safe game play that way too. When I want to deal with mobs and such, I just leave the crater and go investigating =)

**Comment by mcenderdragon** [comment]
Interesting gameplay...

**Comment by trogarus** [comment]
OK, results seem to be rifts generating at y2 encased in obsidian. This works, in my humble opinion, although I might prefer they were at y1 so there weren't "bumps" in the bedrock layer (other OCD people might feel the same, although I'm not OCD, just know how that can be for some). It's a good middle ground for what was going on and I appreciate your looking into this.

Side note, you sure you want to gate the rifts behind the ability to mine obsidian (diamond pick)? Just thinking about those that run only slightly modified packs where diamonds might still be an issue. Of course, if this is meant to be later game content, then the obsidian gating makes sense. Just wondering.

Once again, still enjoying the mod and appreciate your work on it.

Will be off in a bit to check the changes to the dungeons and will report in that other thread my findings on that.

**Comment by mcenderdragon** [comment]
Well you can use the block breaker or the composite tools to brek obsidian (so it will take some minuits to find a small tec dungeon with block brakers),

It seems like thermal just replaces everyblock at y=1 with stone regardles if it was diamond ore bedrock or something else....

**Comment by trogarus** [comment]
Not sure on the exact mechanics concerning the ore replacement for flat bedrock they use, and not a coder who can look into that. In either event, what you've done is a nice work around. It still keeps things at y1 and y2 (that can't usually  be moved/removed) so that it doesn't interfere so much with builds or automation. Once again, thanks for the work on this mod, and sorting stuff like this out. You do it quickly as well, which is always nice.

I still haven't gone dungeon hunting yet, but I will report back on that in the other thread once I do. Again, many thanks for your work. Mods that add additional dimensions, and interesting mechanics, help spice up minecraft that gets a little stale after a while.

**Comment by mcenderdragon** [comment]
(Sorry if you have to generate mcuh worls) here is a build were atleast the rift will not disappear if seomthing is generated over them. [26.2.49](http://redsnake-games.de/Downloads/fp/fp.php?version=26.2.49)

**Comment by trogarus** [comment]
No worries, will either just do an rf tools dimension, or maybe see how this functions in the deep dark =) Will slot this one for next game start. Just grabbed all the updated mods from curse (now have 211 of them in the pack I created) =)

**Comment by trogarus** [comment]
Oh, and btw, the report above on the rifts were in Aroma's mining dimension world =)

**Comment by mcenderdragon** [comment]
perfect :)

**Comment by trogarus** [comment]
Update on present file test for rifts. The liquid clearing in the deep dark is a bit over half done. Will then set the 501 x 501 cylinder for quarry and report back. No, haven't forgotten, but tomorrow is a holiday here so play time is a bit limited.

**Comment by trogarus** [comment]
Test in latest files I have, Futurepack-1.12.1-26.2.49, deep dark rift generation similar to the others reported above. Rifts at y2 enclosed in obsidian. So far so good. Looks like the change a few files back fixed the floating rift issues. Thanks again for your work on the mod.

**Comment by trogarus** [comment]
Still haven't managed to test the dungeon update stuff. Time has been a bit more limited with the holiday. Will report in that thread once I manage the time to investigate.

**Comment by mcenderdragon** [comment]
ok I will close this since its fixed

**Comment by trogarus** [comment]
@mcenderdragon one problem. Just got to the end and found a bunch of rifts floating in the end. Might want to disable end rifts at this point? Otherwise, just looks weird and since it's a void world, they kind of don't belong there. =)
