### ISSUE TITLE
Major Incompatability issue

### ISSUE THREAD

**Issue by Moobien** [mcenderdragon/Futurepack-API#313]
hey guys, I have been having an issue with the Mekanism Digital Miner and after testing several of their Dev buiilds I removed FP and made a new world and the Digital Miner started working.  The Mek devs believe that the problem lies in  chunk protection.  My guess is whatever you guys use to make your new dungeons unbreakable is stopping machines from other mods working.

Here is the issue I raised with the mek guys.

https://github.com/aidancbrady/Mekanism/issues/4820

**Comment by mcenderdragon** [comment]
i guess this is solved from mecanism side.

**Comment by Moobien** [comment]
Not solved, but explained :)

**Comment by Moobien** [comment]
@mcenderdragon out of curiosity, does FP have anything that persists in the save files after the mod is removed? I ask this because the mek dminer works fine in a new world created after removal of FP but doesnt in existing worlds after FP is removed.

**Comment by mcenderdragon** [comment]
some stuff will still be there like the NBT valus and some sutff, but nothing wich can somehow influence your game (everything wich executes code is in the jar)

**Comment by Moobien** [comment]
Cool. Might as well close this issue. I was completely wrong about what was protecting chunks from the dminer. Sorry for the inconvenience
