### ISSUE TITLE
Crashes when I open E-scanner

### ISSUE THREAD

**Issue by chuhanuman** [mcenderdragon/Futurepack-API#317]
I use this mod called akaskic tome which allows me to have multiple items that do actions on right click like books. I combined an e-scanner with that and acquired another e-scanner. Now, whenever I open either e-scanner, my game crashes. I tried deleting one and I tried resetting my research but it still crashes. I have attached two crashes, one with an e-scanner deleted and one with research reset and an e-scanner deleted.

[crash-2017-11-24_18.52.59-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/1502721/crash-2017-11-24_18.52.59-client.txt)
[crash-2017-11-24_19.54.11-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/1502722/crash-2017-11-24_19.54.11-client.txt)

**Comment by mcenderdragon** [comment]
ohh yeah bad written minecraft code... lets see what I can do...

**Comment by mcenderdragon** [comment]
This should be fixed: [26.3.8](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.8)

**Comment by chuhanuman** [comment]
Thanks so much!

**Comment by mcenderdragon** [comment]
[I will reopen this until I make a public realese]

**Comment by chuhanuman** [comment]
It always takes a moment to load, which it didn't do before but thats probably because I have a bad computer.

**Comment by mcenderdragon** [comment]
No this propably means it crashes internaly, you can look if somewhere in the E-Scanner in something like [StackOverflow] wich is an Error I print to indicate there was something wrong while opening the E-Scanner.
