### ISSUE TITLE
Why are there no config options for 1.7.10?

### ISSUE THREAD

**Issue by brandyyn** [mcenderdragon/Futurepack-API#319]
Hey so since there is barely any documentation for 1.7.10 idk how different it is from newer versions but whenever I launch my game I get a crash because of conflicting ID's, and I cant change the ID's from the futurepacks config due to it having nothing in the config folder

**Comment by mcenderdragon** [comment]
there is no fp.cfg file ? And the 1.7.10 is very different from the current version (the complete research system was not implemented back then). Also do you have still this crash ?

**Comment by brandyyn** [comment]
here is the cfg folder it generated http://prntscr.com/hgyjsb
but it has nothing inside of it ? http://prntscr.com/hgyjww
here is the crash: https://pastebin.com/MqjDjUQU

**Comment by mcenderdragon** [comment]
Futurepack automaticly uses other ID if the IDs are alredy used, it seems like Futurepack gets laoded before gedomancy and thus they crash, you can try to rename their j so it is starting with an a so it will get loaded before the FUturepack, this should prevent this crash.

**Comment by brandyyn** [comment]
would you mind backporting future pack to 1.7? like its really really awesome mod and im sad that allot of options arent in 1.7 and it would be really cool to have in my pack im gonna launch soon :)

**Comment by brandyyn** [comment]
also still crash

**Comment by mcenderdragon** [comment]
backporting is nerly im possible due to the JSON models and alot of forge changes wich made some features possible (this whould be alot of stuff just gone)

**Comment by brandyyn** [comment]
hmm thats very interesting i didnt know that :(

**Comment by brandyyn** [comment]
is there any possibility of you adding the cfg options tho so i can play atleast the 1.7 version lol :D
