### ISSUE TITLE
[1.9.4-capabilities] Pipes don't "update" when edited with Scrench

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#32]
Pipe system don't update their routes, if the pipes get edited with an scrench.
This cause stuid paths. To Example: items fly throw air or ignore inventories
Routs get corected if an block in pipe system is placed/removed.

![wrong_rout](https://cloud.githubusercontent.com/assets/11357199/19371914/77d9ef42-91b7-11e6-963f-5b65ee9e59cf.png)

**Comment by mcenderdragon** [comment]
If i edit this, it may cause huge performance issues, but wie will see...
