### ISSUE TITLE
Large Dungeon generate higher than surface

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#321]
https://prnt.sc/hio6hs

Maybe we should limit the heigth of the dungeons...

**Comment by mcenderdragon** [comment]
@TheRealM18 does the dungeon reach the button (y=1) or is there alot of space ?

**Comment by Wugand** [comment]
lowest block is at y=3

**Comment by mcenderdragon** [comment]
then there was hardly anyother way then going bejond the surface, at wich high is the the sand there ?

**Comment by Wugand** [comment]
63 - 78

**Comment by mcenderdragon** [comment]
maybe we should stop them if they are too huge, or make them more beatiful outside the ground

**Comment by mcenderdragon** [comment]
[26.3.144](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.144)

**Comment by mcenderdragon** [comment]
now the get covered.

**Comment by mcenderdragon** [comment]
![2018-03-02_20 47 43](https://user-images.githubusercontent.com/6342933/36918704-039230ae-1e5b-11e8-821f-bf99e764780f.png)

**Comment by mcenderdragon** [comment]
![2018-03-02_21 15 52](https://user-images.githubusercontent.com/6342933/36919822-e90d8f54-1e5e-11e8-93b6-937c001ad35f.png)

**Comment by mcenderdragon** [comment]
Now the blocks no longer gnerate on the inside of the dungeon.

![2018-03-02_21 36 33](https://user-images.githubusercontent.com/6342933/36920687-d5ffa674-1e61-11e8-9ea8-f62f1e72834e.png)

**Comment by mcenderdragon** [comment]
![2018-03-02_22 15 11](https://user-images.githubusercontent.com/6342933/36922135-3136d72e-1e67-11e8-98cf-2098a4d65876.png)
