### ISSUE TITLE
MC 1-12-2 Rift Issues as of Futurepack-1.12.2-26.3.7 and Forge 2555

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#323]
1 - Rifts generating all over the end in a void world. I'd suggest there be none there as it looks odd and ridiculous given that it's supposed to be a void world.

2 - Mobs spawning all over rifts because although they look like bedrock, they are not recognized as non spawning blocks. As such, this completely defeats the idea of quarrying out an area for mob farms to defeat spawn and force mobs to spawn where we want them to, a typical game mechanic many use for mobfarms in moded until they are able to obtain spawners.

Other than that, as of this release and my new playthrough, research up through menelaus seems to still be in tact and functioning fine, along with machine mechanics working as one would expect. Previous issues in past versions where different machines were not keeping inventory seems to be fixed as well.

Once again, thanks for your hard work on the mod. I'm still mostly enjoying the playthrough, although with the number of times I've restarted the research that part is getting a bit tedious. Yes, I know, I can cheat command all research, but then I wouldn't be able to test that portion of the mod, and I've still yet to get to the point where I've done all the research. Thanks again.

**Comment by mcenderdragon** [comment]
1) yes this looks very funny, but its alrey fixed (indev)
2) consider it as fixed as soon as I'll push to git.

**Comment by trogarus** [comment]
Great, wasn't sure if you saw my comment on the other solved rift issue I posted or not. I do appreciate your attention to detail and keeping the mod in working order, as I've said before. I definitely appreciate that you, and your team, are active in this mod's development as it is a nice mod and enjoyable to play. It's in the same vein as advanced rocketry and galactic craft, and I've always appreciated mods that extend the vanilla dimensions beyond the base three minecraft offers. Thanks again for the quick replies and your attention to detail. I look forward to how this mod pregresses and any other potential planets you and the tam might develop and add to the mod.

**Comment by trogarus** [comment]
Now that I have Futurepack-1.12.2-26.3.24, I'll reset the end and get rid of the rifts =) Thanks again for the attention to detail in the mod and the fixes.
