### ISSUE TITLE
About distribute the mod

### ISSUE THREAD

**Issue by sxjeru** [mcenderdragon/Futurepack-API#324]
( Sorry, my English is poor )
Hi! I think this mod is very interesting. And I usually play the mod. 
I also want to share your mod to my country Minecraft's players. But I think you know, in China, Minecraft's players hard to visit the Curse.
( If you don't know, you can use Google search "GFW". )
So I please you can give me the permission. Then I can distribute the mod to [mcmod.cn](http://www.mcmod.cn/)
( mcmod.cn ( mc百科 ) is a Minecraft's mod wiki from China. It is all Chinese, You can visit it by Google translate. )
Thx and Thx again!

**Comment by mcenderdragon** [comment]
If I understand this site correctly it can provide download links to curse, right? I think as long as there are always up to dat links it is fine :)

**Comment by sxjeru** [comment]
You're right. But I want to distribute the mod binary files, not links. 
Why? Please look this image. 
![image](https://user-images.githubusercontent.com/20513115/33801464-a0fd5996-dd96-11e7-990e-1f840898d699.png)
That's TOO SLOW! So that almost no one will wait.

BTW, you may want to look Futurepack in mcmod.cn. [Link](http://www.mcmod.cn/class/512.html)

**Comment by mcenderdragon** [comment]
well I  think this is an issue from curseforge and you should talk to them and point out there are soem loading issues.

**Comment by sxjeru** [comment]
It's not curseforge wrong. It's our governmental restrictions, and I can't change their order. 
If you do not want to give me authorization, never mind. I will not bother you anymore. 
Because I believe have more people will talk to you about this, from China.

**Comment by mcenderdragon** [comment]
As the site is already there with the downloads kepp it. IF your government is doing this then this is strange but ok, it makes sense there is so much for china if the government is slowing down other servers. And of course everyone should be able to get my mod (we are an open community :D )

**Comment by sxjeru** [comment]
Thank you for your understanding and support. Have a good day! 
^ ^
