### ISSUE TITLE
Crash NullPointerException Rendering screen with MC 1-12-2 CCL 1.12-3.1.4.316-universal Forge 2555 and Futurepack-1.12.2-26.3.7

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#325]
Not sure if this is you or them, but here is the crash log mentioning both mods.

Cross posted this with them as well https://github.com/TheCBProject/CodeChickenLib/issues/122

Crash Log
[crash-2017-12-09_15.13.11-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/1545075/crash-2017-12-09_15.13.11-client.txt)

Client Latest
[fml-client-latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1545076/fml-client-latest.log)

FP Latest
I'd post it if it wasn't so large and don't have pastebin accounts etc.

**Comment by trogarus** [comment]
From covers1624, one of the devs for ccl.

"Futurepack seems to be attempting to render a null ItemStack, Ill leave this open for now, but its a Futurepack issue."

**Comment by mcenderdragon** [comment]
ANd I would say its an issue in their renderer... lets see were this leads...

**Comment by trogarus** [comment]
More details

Got the external processor research from the scanner. Tried to put that into the researcher with all modules attached (energy, support, XP) connected to 8 calculation modules connected by network cable, and this is what caused the crash.

Booting the world back up and trying to go into the researcher with the research still in it prompted another world crash

[crash-2017-12-09_16.37.50-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/1545149/crash-2017-12-09_16.37.50-client.txt)

The only way to bypass this issue was to break the unit, replace it with a new one, and discard the one with the blueprint still in it. World is still playable now without the crash, but still crashed last loadup after trying to open the research module with the research blueprint in it.

**Comment by trogarus** [comment]
Just to be clear, the copy and paste quote above was keeping you in the loop about what's going on with this crash, nothing more, nothing less. It wasn't posted to be taken as it's "your fault please fix it", it was to suggest that they think you have a null item stack so you could see if you really do or not. If you don't, then it goes back to them because you don't have a null item stack issue.

CCL is a big mod that's used in a lot of mods many in the community use. I'm just trying to help get something sorted so that things play nice together so the community isn't forced to drop one mod or the other.

**Comment by mcenderdragon** [comment]
Does this also happen without CCL? I am asking because there is somethign wrong with the Item, somehow it cant get an Item for an needed ingedient for the research.

**Comment by trogarus** [comment]
Let me do a backup then remove ccl and see what happens. Going to mess up my present world because of endertanks and such to transfer items, which requires ccl, as does thermal expansion and such now as well. It doesn't help that I have a craptop potatoe to do this on either.

**Comment by mcenderdragon** [comment]
Maybe you dotn have to: Try [this version](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.23) it should fix the bug, but please be carefull as it is possible it will not display items needed for the research :/

**Comment by trogarus** [comment]
But will that version tell you if it's your render or something with theirs? I'll just do the backup and such, and restart first. Then we'll know.

**Comment by mcenderdragon** [comment]
it was something with my renderer but I am more concerned there _existed_ an null itemstack, this means something has gone wrong near startup time (and most likely still is wrong)

**Comment by trogarus** [comment]
Well, maybe this might be the issue then. Let's approach this from a logical standpoint. Firstly, can I reproduce the crash. Yes I can, game is presently crashing from same process as already mentioned. OK, so does it maybe have something to do with the research blueprint and what items it's calling. It looks weird because all other research requires more than one item at this point, and this research blueprint requires one item only. So, while I'm doing the backup and removing things to see if it still does this without CCL, lets look at what game tells me this research requires while we wait.

Research Blueprint 7629/0
External Processing Unit
Needed Resources
Nanostructure repair unit
time 3200
ne 307200
xp 600

Also of note, as soon as I put this in the researcher and hit the button to load it, game crashed at that point. I'm guessing it's not telling me everything that is needed for this research, and that's what might be causing the item stack null issue. Just logicing things. I might be wrong.

**Comment by trogarus** [comment]
Also, if I can help get things to where your mod and all these others place nice together, all the more reason for people to use your mod as well. Just so you know what's all in this pack that I created, here ya go.

http://modlister.com/user/trogarus

**Comment by mcenderdragon** [comment]
I think I have found the bug and it is extramly stupid. In our research definit was a comma ( , ) to much so there was nothing and it tried to prase it, this pseudo null resulted in this crash.

Version [26.3.24](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.24) should fix this ^^'

**Comment by trogarus** [comment]
Not a coder, but I figured it had to do with what the blueprint was calling, just logic to figure that bit out. No worries. Again, love the mod, just want to make sure I can keep using it without bugs =) Thanks again for the quick replies and fixes. I'll load up the new file and see if I can get into the researcher after last crash and report back.

**Comment by trogarus** [comment]
OK, reloaded, got into researcher, but only 1 nanobot repair thing for this research considering everything else at this level requires a bunch more?

**Comment by mcenderdragon** [comment]
THis is @Wugand part, he writes what is needed. He is most likely not done wiht it yet and just made it possible to research it so you can continue researching.

**Comment by trogarus** [comment]
OK, during the research, it says that part press research completed. I did that DAYS ago lol. Not sure why that triggered there, but I already had it, and it triggered before the research is even complete.
