### ISSUE TITLE
Things still missing/issues in Futurepack-1.12.2-26.3.7

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#326]
- [x] iontechnik not found
- [x] energy.ionen not found
- [ ] production.nind.1.inse.1 not found

- [x] nanostructure manipulation - still in german
- [x] green focus lens - still in german
- [x] advanced board computer - still in german

dungeon ram uncraftable via jei or game noted recipe

Also of note, I have traveled all the way to tyros and have most of the research unlocked but I can still not seem to complete the dungeon key researches (1 through 4). When I try to put them in the researcher, it refuses to take the research blueprint so I can put the items in. I have all the modules hooked up to the researcher now as well and still no ability to complete the research.

**Comment by trogarus** [comment]
These are still issues as of Futurepack-1.12.2-26.3.24, just a heads up.

**Comment by trogarus** [comment]
space.externalcore not found

**Comment by trogarus** [comment]
chat nessage for supercable research "Your research (research.log.supercable) finished"

Log Icon research.log.supercable

Log Entry log.supercable not found

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/272

**Comment by mcenderdragon** [comment]
@Wugand is the crafting fixed by now ?

**Comment by Wugand** [comment]
Crafting is fixed, texts are added or listed at #272
