### ISSUE TITLE
1.7.10 1558 Thermos Crash

### ISSUE THREAD

**Issue by voidswrath** [mcenderdragon/Futurepack-API#328]
As title says. IF you need more info just let me know

---- Minecraft Crash Report ----
// Why did you do that?

Time: 12/12/17 11:16 AM
Description: Exception in server tick loop

java.lang.RuntimeException: java.io.FileNotFoundException: ./world/DIM1/DIM1/FPChunks.dat (No such file or directory)
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:146)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.unloadWorld(CraftServer.java:1034)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:501)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1020)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: ./world/DIM1/DIM1/FPChunks.dat (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at futurepack.common.FPChunckManager.onWorldUnload(FPChunckManager.java:118)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_379_FPChunckManager_onWorldUnload_Unload.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: cyberdynecc:Thermos:1.7.10-1614.58
	Plugins: WorldEdit, Essentials, VoxelSniper, EssentialsSpawn, WorldGuard
	Disabled Plugins: 
	Operating System: Linux (amd64) version 2.6.32-431.el6.x86_64
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2491942544 bytes (2376 MB) / 7629438976 bytes (7276 MB) up to 7629438976 bytes (7276 MB)
	JVM Flags: 2 total; -Xmx7500M -Xms7500M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 102
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 104 mods loaded, 104 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (Thermos.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (Thermos.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	AdvancedRocketryCore{1} [Advanced Rocketry] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{IvToolkit} [1.2] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	modJ_StarMinerCore{0.9.9} [StarMinerCore] (minecraft.jar) 
	UCHIJAAAA	WarpDriveCore{1.7.10-1.3.34.-} [WarpDriveCore] (minecraft.jar) 
	UCHIJAAAA	securitycraft{v1.8.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.1.jar) 
	UCHIJAAAA	fp{18.7 pre} [Futurepack] ([1.7.10]Futurepack 18.7.jar) 
	UCHIJAAAA	lightsabers{1.1.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-1.1.1.jar) 
	UCHIJAAAA	libVulpes{0.2.5.} [libVulpes] (LibVulpes-1.7.10-0.2.5-universal.jar) 
	UCHIJAAAA	advancedRocketry{1.2.5} [Advanced Rocketry] (AdvancedRocketry-1.7.10-1.2.5.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHIJAAAA	MovingWorld{1.7.10-1.8.1} [Moving World] (movingworld-1.7.10-1.8.1 (1).jar) 
	UCHIJAAAA	ArchimedesShipsPlus{1.7.10-1.8.1} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.8.1 (1).jar) 
	UCHIJAAAA	neighbormod{0.6.5} [Atlantis Neighbor Mod] (AtlantisNeighborMod-0.6.5.jar) 
	UCHIJAAAA	skinswitch{0.1.6} [Atlantis Skin Switch] (AtlantisSkinSwitch-0.1.6.jar) 
	UCHIJAAAA	starwars{1.0} [Atlantis Starwars] (AtlantisStarwars-0.5.0.jar) 
	UCHIJAAAA	AtlantisWater{1.0} [Atlantian Water] (AtlantisWater-1.9.1.jar) 
	UCHIJAAAA	tennox_bacteria{2.3.2} [Bacteria Mod] (BacteriaMod-1.7.10-2.3.2.jar) 
	UCHIJAAAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1 (1).jar) 
	UCHIJAAAA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHIJAAAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	chisel{2.9.0.3} [Chisel] (Chisel-2.9.0.3.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10 (1).jar) 
	UCHIJAAAA	cookingbook{1.0.140} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.140.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d_AC.jar) 
	UCHIJAAAA	darkcore{0.3} [Dark Core] (darkcore-0.3-86.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJAAAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1 (1).zip) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAAAA	enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12 (1).jar) 
	UCHIJAAAA	fantastic{1.0.0} [Fantastic Fish] (fantastic-1.4 (1).jar) 
	UCHIJAAAA	flansmod{@VERSION@} [Flan's Mod] (Flan's Mod Plus 1.0.4.3.jar) 
	UCHIJAAAA	HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.6 (1).jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental (1).jar) 
	UCHIJAAAA	Forestry{4.2.0.47} [Forestry for Minecraft] (forestry_1.7.10-4.2.0.47.jar) 
	UCHIJAAAA	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar) 
	UCHIJAAAA	fossil{7.3.2} [Fossils and Archeology Revival] (fossilsarcheology-7.3.2 (1).jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.502 (1).jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.502 (1).jar) 
	UCHIJAAAA	GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta (1).jar) 
	UCHIJAAAA	kcweaponmod{0.1.5} [KC's Weapon Mod v0.1.5] (KCs Weapon Mod v0.1.5 (MC 1.7.10) (Weap v1.3).jar) 
	UCHIJAAAA	halocraft{0.7.6} [Halocraft v0.7.6] (Halocraft v0.7.6 (MC 1.7.10) (KCWM Weap v1.3).jar) 
	UCHIJAAAA	killerchief_halocraft{0.7.0} [HalocraftOldIDUpdater] (Halocraft v0.7.6 (MC 1.7.10) (KCWM Weap v1.3).jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (Bromine-Mercury-X01)} [Hbm's Nuclear Tech] (hbm1.0.27_BETAX01.jar) 
	UCHIJAAAA	hidenames{1.1.7} [Hide Names] (Hide Names-1.7.10-1.1.8.jar) 
	UCHIJAAAA	lasermod{v1.2.0a} [Laser Mod] (LaserMod-1.7.10-v1.2.0a-universal.jar) 
	UCHIJAAAA	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10] (1).jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.13.1} [MalisisCore] (malisiscore-1.7.10-0.13.1.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.12.2} [Malisis' Doors] (malisisdoors-1.7.10-1.12.2.jar) 
	UCHIJAAAA	mcheli{0.10.6} [MC Helicopter] (MC Helicopter.zip) 
	UCHIJAAAA	Mekanism{9.1.1} [Mekanism] (Mekanism-1.7.10-9.1.1.1031 (1).jar) 
	UCHIJAAAA	MekanismGenerators{9.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.1.1031 (1).jar) 
	UCHIJAAAA	MekanismTools{9.1.1} [MekanismTools] (MekanismTools-1.7.10-9.1.1.1031 (1).jar) 
	UCHIJAAAA	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3 (3).jar) 
	UCHIJAAAA	MorePlanet{1.4.3} [More Planets] (More-Planets-1.7.10-1.4.3-GC502.jar) 
	UCHIJAAAA	moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels_1.7.10b_Cody (3).jar) 
	UCHIJAAAA	Morph{0.9.3} [Morph] (Morph-Beta-0.9.3.jar) 
	UCHIJAAAA	cfm{3.4.8} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCHIJAAAA	notenoughIDs{1.4.3.4} [NotEnoughIDs] (NotEnoughIDs-1.4.3.4.jar) 
	UCHIJAAAA	openmodularturrets{2.2.11-238} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.2.11-238.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10La (1).jar) 
	UCHIJAAAA	starwarsmod{1.3.3} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.3.3.jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJAAAA	rftools{4.23} [RFTools] (rftools-4.23.jar) 
	UCHIJAAAA	rivalrebels{1.7.10Y} [Rival Rebels] (rivalrebels-1.7.10Y.jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) 
	UCHIJAAAA	modJ_StarMiner{0.9.9} [Starminer Mod] (Starminer1710-0.9.9.jar) 
	UCHIJAAAA	TardisMod{0.994} [Tardis Mod] (tardismod-1.7.10-0.994-124-DS.jar) 
	UCHIJAAAA	Techguns{0.1.2_alphatest4.1} [Techguns] (Techguns.beta.1.2_alphatest4.1.jar) 
	UCHIJAAAA	torchLevers{1.4.2} [Torch Levers] (TorchLevers-V1.4.2-MC1.7.10.jar) 
	UCHIJAAAA	WarpDrive{1.7.10-1.3.34.-} [WarpDrive] (WarpDrive-1.7.10-1.3.34.-.jar) 
	UCHIJAAAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	EnderIO: Found the following problem(s) with your installation:
                 An unsupported base software is installed: 'thermos, cauldron, craftbukkit, mcpc, kcauldron'. This is NOT supported.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 

Bukkit, Cauldron, or other Bukkit replacement

These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by mcenderdragon** [comment]
I am sorry but 1.7.10. is very old and also you use bukkit. Can you try to reproduce this without bukkit ?

**Comment by voidswrath** [comment]
Yeah crazy but we still find 1.7.10 to be the better platform for modpacks and such. I will give it a test later and get back to you with a report or confirmation on it being the compatibility with bukkit
