### ISSUE TITLE
[1.12.2] recycling not found

### ISSUE THREAD

**Issue by lag42** [mcenderdragon/Futurepack-API#329]
![2017-12-15_11 54 05](https://user-images.githubusercontent.com/22325011/34054089-fff8e75c-e18e-11e7-9996-68aced948edd.png)

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/272

**Comment by mcenderdragon** [comment]
Thanks for reporting, we are on it!
