### ISSUE TITLE
[1.9.4-capabilities] Pipes don't connect to some Inventories

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#33]
Pipes don't connect (opticaly) to the Block.
Functionality is ok; Item get insert.

Seen at:
Water Cooler
Wardrobe
Pusher
(Drone Station)
T0-Generator

**Comment by mcenderdragon** [comment]
So the rendering again.

**Comment by mcenderdragon** [comment]
@Wugand test plz.
