### ISSUE TITLE
More Detail on Restructuring?

### ISSUE THREAD

**Issue by Boolyman** [mcenderdragon/Futurepack-API#331]
Is there anywhere I can find more information on what your change log means by "research restructuring"?  I am deep into setting up an in-depth quest line using Futurepack, and if the whole research path was rewritten this is going to throw a LOT of things off.  Should I not bother ever updating the mod past the version I have now?

**Comment by mcenderdragon** [comment]
The Research order and dependencies are the same, we only moved the researches in the main overviewaround, and removed some unneeded dependencies, it should not interfere with an alredy existing world.
