### ISSUE TITLE
Am I Doing Something Wrong?

### ISSUE THREAD

**Issue by Boolyman** [mcenderdragon/Futurepack-API#332]
I apologize in advance for whatever it is that I obviously missed with this process, but I can not pinpoint what I am missing here.  According to the wiki, the beginning of progression starts with making a Tech Table, Part Press, and Industrial Furnace... then you need to make a Scanner and Researcher.  

Well, the scanner and researcher require you to be able to make Metal Blocks... which you can't make without Composite Metal... which you can't make without researching Composite Metal... which you can't research without having the Researcher you are trying to make. So, how do I get Composite Metal to make the Metal Blocks to make the Researcher to learn how to make Composite Metal?

Dude, I love your mod, so don't take this the wrong way... but this Thaumcraftian research system is killin it for me and a few others lol.

**Comment by mcenderdragon** [comment]
:D Do you remember what blocks were used when you found your EScanner ?, didnt the walls had black metal blocks ?

**Comment by mcenderdragon** [comment]
I think this is solved
