### ISSUE TITLE
Render glitches 

### ISSUE THREAD

**Issue by Flashwar** [mcenderdragon/Futurepack-API#333]
When using Blur with Futurepack and want to look up in JEI some recipe, the background is flickering, also the Blur in the inventory doesn´t work. 

MC Version: 1.12.2
Forge:14.23.1.2555
JEI: 4.8.5.138
Blur:1.0.4-14
FP:26.3.48

https://www.youtube.com/watch?v=P9SqxNRLHkI&feature=youtu.be

**Comment by mcenderdragon** [comment]
I am not sure if I can do something about this, since the gui renderer is from JEI and Blur is from someone else, have you looked if this issue is allready known to Blur ?

**Comment by Flashwar** [comment]
Yes, the issue is not known. But this issue comes only when FP is installed

**Comment by mcenderdragon** [comment]
Ok strange, pinging @mezz (JEI) and @tterrag1098 since I am completly lost with this issue. 
I think what is most interresting: also Guis from only JEI flicker: the Recipes for Brewing.
Also It seems like the blur slowly gets stronger.

**Comment by mcenderdragon** [comment]
@Flashwar you did not even look at Blurs issue tracker :<
https://github.com/tterrag1098/Blur/issues/13

**Comment by Flashwar** [comment]
I did, but missed that Issue xD Sry

**Comment by Flashwar** [comment]
Update: with FuturePack 1.12.1- 26.2.17 blur is working correctly
