### ISSUE TITLE
mcmods.info

### ISSUE THREAD

**Issue by Frinn38** [mcenderdragon/Futurepack-API#335]
Not really an issue and that's nor really important but there is severals speaking mistakes in your mcmods.info.
I don't wan't to be an english teacher but I repport them to you anyway =)
![image](https://user-images.githubusercontent.com/32675710/34457713-0986fdcc-edba-11e7-97ab-22e9d8502f63.png)

**Comment by mcenderdragon** [comment]
consider this as fixed, and thanks fopr pointing this out (It is long ago sicne I last touched this file ^^)

**Comment by Frinn38** [comment]
No problem, I know it's the file that you edit 1 time when you create the mod and never open it again ^^
