### ISSUE TITLE
All info with the E-scanner missing

### ISSUE THREAD

**Issue by Dutchborg** [mcenderdragon/Futurepack-API#338]
When I open the E-scanner and want to read more info about the new discovering I got the message : 

"Production.industrieofen" not found, report this to the mod author.

This is an example for the Industrial Furnace, but looks like all info i want to use with the e-scanner is missing.

I downloaded this verdion from curse 26.3.48

**Comment by mcenderdragon** [comment]
And this happens for all entrys? What language have you selected and can you please link the FP-latest.log, latest.log and the fml-client-latest.log

**Comment by Dente222** [comment]
Just updated the mod in my modpack and got same problem Im using original English lang

**Comment by mcenderdragon** [comment]
Om yeah we found the bug

**Comment by mcenderdragon** [comment]
You propaply have installed the colorisation addon, it is exidantly overriding all researches and thus all researche files are searched under the fpa namespace but not found, I will realese a version were it gives a log output if you try to overwrite alredy existing researches, and I alredy talked to RealM so he is on it.
