### ISSUE TITLE
Menelaus is not escapable/ survival-ready

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#34]
This are considerations for an full survival-able Menelaus! (Plaese mark as Feature)

- [x] get Fuel*
-- [x] get BlazeRod*
- [x] get Quartz
- [x] get NeonCrystal / Neon Ingots*
- [x] get Clay*
- [x] get Paper (Researcher)*
- [x] get Food
- [ ] make Menelaus Resources usefull
- [ ] * are all Machines craftable?

- [ ] test it!

**Comment by Wugand** [comment]
Mushroom-Food would be usefull

**Comment by Wugand** [comment]
Some solutions:
+Neon crystals: change recepies to "all Crystals"
+Clay: use Centrifuge (recheck this to the recepies)
+Paper: from Biopolymer

**Comment by mcenderdragon** [comment]
fireflies are imoplemented

**Comment by mcenderdragon** [comment]
Resource from Menalaus are mostly useless
* Sand
* Cobble
* Sandstone (is this even reachable)

**Comment by mcenderdragon** [comment]
Sugar Cane is now generating.

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/116

**Comment by mcenderdragon** [comment]
The mendelberry flowers are useless

**Comment by mcenderdragon** [comment]
Red Menelaus stone is not breakable with wood pickaxe

**Comment by kleshchevand** [comment]
Blaze Rod is 'supported' by many mods with crushers/macerators/e.t.c and this makes it extremely easy to duplicate. Like Blaze rod->crusher->blaze powder-> NeonIndustrialFurnace -> multiple blaze rods. And all it costs is a tiny bit of gold.
As result fuel becomes 'cheap' or at least cheaper then it should have been.

Possible solutions:
- either fuel receipt should use alternative to blaze rod, or blaze rod receipt should use different(new) type of powder/drop (Shiny dust, Menelaus 'wisp' dust or something like that)
- There can be alternate, less efficient fuel types (ender pearl based for example, but user will have to have twice as many thrusters for same mass)
- Alternate Thrusters, like single use 'chemical' thrusters or some kind of 'reactant' thruster that is far harder to fuel/manage.

**Comment by mcenderdragon** [comment]
@kleshchevand do you know the highest mod blazepowder output from a blaze rod ? If so we could use this value in our rezipe or an even higher version. Menelaus has unlimited blaze powder so even if we use 10 powder for 1 rod it would be possible. And wont create dooping machines in combination with other mods.

**Comment by kleshchevand** [comment]
Ic2 macerator - 5 blaze powder. 


Note: a number of mods also allows exchange of something into blaze powder. For example Thermionic expansion exchanges one glowstone+liquid redstone into blaze powder.
Smart-storage mods (AE, Logistick pipes, RS) 'dislike' cycling receipts,

**Comment by mcenderdragon** [comment]
Iam not sure but  I think thermal had 6 blaze powder in a recipe...

**Comment by mcenderdragon** [comment]
and you also need gold so it is expensive.

**Comment by kleshchevand** [comment]
1 gold ingot (which is barely used in this mod, sons some batteries) into 9 much rarer blaze rods isn't expensive.
Thermal crafts 4+sulfur.

**Comment by mcenderdragon** [comment]
I think gold is much rarer then the blze rods (you need to kill blazes wich is imo easy and you can completly negate their damage with potions) and I also changed the recipe to use 4 powders instead of 2, so now you need cheaty machines from other mods with over 200% output. But also you are loosing material constantly.

**Comment by kleshchevand** [comment]
Well, before manelanos I had around 2-3 stacks of gold, and barely any blaze rods (I'm not a good combatant and I had no spawners yet, and I always forgetting about potions in combat). Even what blaze rods I got, I did in a bit cheaty way - soul viled encountered blazes and then killed those with 'lucky' sword while staying in water. Now I have dozens stacks of gold and still little blaze rods (and those I cheat through industrial neon furnace)
Gold is abundant in overworld, especially if you know how to mine effectively, for blaze rods you have to go to nether, search for blazes or/and their spawners.

**Comment by mcenderdragon** [comment]
well once you found a nether bridge it is very easy to get them and when they spawn there is a cooldown before they first shoot in this time it is possible to kill all of them.

**Comment by Wugand** [comment]
OK, to say the problem in Numbers: 1 Gold Ore -> 2-4 Gold Ingot -> 16 - 32 Blaze Rods (in "doubling machine"). Yes it's quite to much ...

We currently discuss the following solutions (inspired by you suggestions):
1 - Fireflys give "Special Dust" which can crafted to Blaze Rods and Blaze powder, but it is itself only avialable as drop.
2 - Put the catalyst (maybe the unorganic chemicals) in the fuel tank together with the rods (crafted without blaze rods)

**Comment by mcenderdragon** [comment]
It seems good so far.

**Comment by Wugand** [comment]
Yes, you can basically survive and build spaceship
