### ISSUE TITLE
Ticking Block Crash (Flash Server) MC 1-12-2 Futurepack-1.12.2-26.3.48  and forge 2560

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#341]
Not sure what's going on. New world (again) and just running RFTool builder to pump out an area and Refined Storage to store the fluids at this point. Wasn't even interacting with the block nor in the dungeon at all.

Crash
[crash-2018-01-06_10.10.02-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/1608932/crash-2018-01-06_10.10.02-client.txt)

FP Latest
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1608934/FP-Latest.log)

FML Client Latest
[fml-client-latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1608935/fml-client-latest.log)

**Comment by mcenderdragon** [comment]
I think I c ant to anything here, it crashed inside the world class when I checked for a TileEntity, because either something added a null TileEntity or a TileEntity with a null BlockPos. Sore probaply something else is the root of this issue.

**Comment by mcenderdragon** [comment]
Does this always happen or only someuimes?

**Comment by trogarus** [comment]
So far, only has happened that one time, but was different and weird as it's not something I've experienced before during any of my, now 3 times, play throughs of the mod. Still enjoying it btw, just wanted to let you know about things that happen at times so you can keep any potential bugs squashed out of the mod =)

**Comment by mcenderdragon** [comment]
It is possible this was a random not realy reproduceable bug, if not please tell me. Also thanks for reporting :)

**Comment by trogarus** [comment]
Yeah, still haven't seen it again and I've been playing quite a bit past days, and you are much welcome. Thanks again for the mod. I might be doing up an actual pack in a few months after I can get a memory upgrade into this thing.  Might upload it to the launchers, which will include the list here and a few more I'd like to have but can't because of present memory.

[http://modlister.com/user/trogarus](url)

**Comment by ProsperCraft** [comment]
Could this issue be related to mine? I came to report that flash servers in dungeons are ticking high in the server, can they be inactive and not tick at all until they are in actual use? 

Should I make a new issue?

![flashservers](https://user-images.githubusercontent.com/4427684/35390220-d8806a46-0197-11e8-959d-251d11bcfd40.png)

https://i.gyazo.com/c191f9c71bac9bb548058082b4b141eb.png

**Comment by mcenderdragon** [comment]
@ProsperCraft nope not realy related please open a new issue (and I think it is something important because they dont do much, or any at all, there is no reason why they should take this long)
