### ISSUE TITLE
[1.12.2-26.3.48] Grappling slime bug when logged out/disconnected.

### ISSUE THREAD

**Issue by piromanwwr** [mcenderdragon/Futurepack-API#342]
This issue occurred when I got kicked from server for flying (used grappling slime to travel, and flying was disabled at that time on the server). When I logged in I got pulled to the place where slime ball was (it was still in the world), and I couldn't move away from it. All I could do was to use grappling slime again to travel  for some distance, but after canceling it, I was pulled back to the same place where i was before. Fortunately I tried to use the grappling slime and logout several times and i got free after 8-10 tries. Additionally all range weapons like bow, rifle had distorted trajectory ( the projectile was launched towards a point between the target and the slime ball). As I know this problem occurred only in the nearest chunks.

Edit: Current issue still occurs. Logging out and in doesn't fix it. Playing on "b0bst3rs Technological Marvel 3.5.0".

![2018-01-18_18 27 18](https://user-images.githubusercontent.com/1630264/35116868-1bd0bab8-fc8d-11e7-90c0-12fde02a0bd9.png)
![2018-01-18_18 28 02](https://user-images.githubusercontent.com/1630264/35116902-2d00eca4-fc8d-11e7-9d84-8feff9c87fc4.png)

**Comment by mcenderdragon** [comment]
Ok this is interesting, as I through I fixed the flying kick. I'll dig into it, and this is kidnof funny :)

**Comment by WPaul15** [comment]
I also have encountered this bug if I die while the Grappling Slime is active (i.e. attached to something). If I return to that spot to retrieve my stuff, I become connected to the old slime line and can't move away from it without teleporting.

**Comment by mcenderdragon** [comment]
The hook now disappers if the player discconects from the server. [26.3.177](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.177)
