### ISSUE TITLE
[dafuq?!] Cannot get property PropertyInteger

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#344]
I just saw this stacktrace in console on my server.  Not sure what triggered it.

Futurepack-1.12.2-26.3.48.jar
forge-1.12.2-14.23.1.2598-universal.jar

Modpack - 
https://minecraft.curseforge.com/projects/towncraft

**Comment by mcenderdragon** [comment]
A full log or at least the full stacktrace would be realy helpfull.

**Comment by ProsperCraft** [comment]
So sorry, I somehow neglected that.

https://gist.github.com/ProsperCraft/bb13c9e606c15f1606ae5cb0116d304d

**Comment by mcenderdragon** [comment]
Wow, this exception is the "what the hall this can even happening"-kind. First I check if the block is a wire/calbe and then I wont to get the state from it, but it crashs because its air. Either a core mod is doing strange things or 2 or more threads are modifing the world at the same time.
