### ISSUE TITLE
[MC 1.12.2, FP v26.3.48, Forge 14.23.1.2555] Ultimate Chipset not producing XP

### ISSUE THREAD

**Issue by WPaul15** [mcenderdragon/Futurepack-API#345]
I recently researched the Ultimate Chipset and installed one in a Crusher and another in a Neon Oven. However, when removing the items from the machines, I have only actually gotten XP two times out of several attempts. Is this a bug, or a feature?

**Comment by mcenderdragon** [comment]
Sadly this system higly depends on weather XP is registred for the vanilla furnace or not, and if not also my machine can not produce them properly.

**Comment by mcenderdragon** [comment]
ok this is a bug it should drop XP if a ultimate chip is installed, what chip power does the ultimate chip have ?

**Comment by WPaul15** [comment]
Both are `Chippower: 2.8000002`. The fact that it's `2.8000002` and not `2.8` may potentially be a bug on it's own, I'm not sure, That happens with other chips as well.

**Comment by mcenderdragon** [comment]
yeah thats because how floats and doubles works internaly, (bits and precsission)

So each machine has a 2.8 ultimate chip ? how big was the stacksize you took out ?

**Comment by WPaul15** [comment]
I've tried it with varying stack sizes, but mostly a full stack (64).

**Comment by mcenderdragon** [comment]
[This version](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.71 ) increases the XP output

**Comment by WPaul15** [comment]
I am still unable to get XP from my machines. Here are the stats of the machines:
Crusher:
- Ultimate Chipset (Chippower: 2.8000002)
- Master-Mind Processor (Core: 9)
- Master RAM (RAM: 9.0, Corepower: 5)
- Master RAM (RAM: 6.0, Corepower: 2)

Neon Oven:
- Ultimate Chipset (Chippower: 2.8000002)
- TCT Processor (Core: 8)
- TCT RAM (RAM: 7.0, Corepower: 4)
- Master RAM (RAM: 6.0, Corepower: 2)

Both machines also have Isotope Flashdrives in them.

I've tried with a full stack of Iron, Gold, Copper, Tin, and Zinc Ingots, and a stack of Aluminum Plates, and haven't received any XP.

Should I run any specific tests to check if it has to do with the machines?

**Comment by mcenderdragon** [comment]
if smelt it in a vanilla furnace do you get XP ?

**Comment by WPaul15** [comment]
Smelting various dusts (Iron, Copper, Tin, etc.) in a vanilla Furnace does give me XP. Smelting those dusts in a Neon Oven does not. However, since a furnace doesn't crush things, I can't test the reverse process in anything but the Crusher, which doesn't give me XP.

**Comment by mcenderdragon** [comment]
Hmm this is strange in theorie I use the same code as the furnace, I will test this more anf if it works for me but not for you it could be a coremod issue, but I need more testing to be sure.

**Comment by mcenderdragon** [comment]
I am clsoing this as someone recently said the Ultimate chip is producing to much XP ^^
