### ISSUE TITLE
[MC 1.12.2, FP 26.3.48, Forge 14.23.1.2555] Metal Fence connecting with Iron Ladder

### ISSUE THREAD

**Issue by WPaul15** [mcenderdragon/Futurepack-API#346]
Metal Fences connect with Iron Ladders, which I don't think is what they should be doing.
![2018-01-21_11 10 59](https://user-images.githubusercontent.com/16868897/35192991-39d281c0-fe9c-11e7-96d8-8996dfb4c6a4.png)

**Comment by SkyProgs** [comment]
Unfortunately, we can no longer support the 1.12.2. In 1.16 it is fixed.
