### ISSUE TITLE
[MC 1.12.2, FP 26.3.48, Forge 14.23.1.2555] Torus Processors/RAM not stacking

### ISSUE THREAD

**Issue by WPaul15** [mcenderdragon/Futurepack-API#347]
Torus Processors with the same Cores value don't stack like other processors. The same goes for Torus RAM with the same RAM and Corepower values.

**Comment by mcenderdragon** [comment]
Are you shure, can you provide a video ? I am asking because I cant reproduce this behauvier.

**Comment by mcenderdragon** [comment]
Also a mod list could maybe help.

**Comment by WPaul15** [comment]
Here's a video of me trying to stack the items:
![minecraft 1 12 2 23 01 2018 15_54_00_gif_004](https://user-images.githubusercontent.com/16868897/35282893-1025bb46-0057-11e8-9321-f85fd8f7099c.gif)

Mod List:
[**AppleCore** (AppleCore-mc1.12.2-3.1.0)](https://minecraft.curseforge.com/projects/applecore)
[**AppleSkin** (AppleSkin-mc1.12-1.0.9)](https://minecraft.curseforge.com/projects/appleskin)
**FuturePack** (FuturePack (v26.3.48))
[**SimpleHarvest** (Harvest-1.12-1.2.6-18)](https://minecraft.curseforge.com/projects/simpleharvest)
[**Inventory Tweaks** (Inventory Tweaks 1.63)](https://minecraft.curseforge.com/projects/inventory-tweaks)
[**Just Enough Items** (jei_1.12.2-4.8.5.132)](https://minecraft.curseforge.com/projects/jei)
[**JourneyMap** (journeymap-1.12.2-5.5.2)](https://minecraft.curseforge.com/projects/journeymap)
[**MouseTweaks 2.8** ([1.12.1] Mouse Tweaks 2.8)](https://minecraft.curseforge.com/projects/mouse-tweaks)
[**OptiFine** (OptiFine 1.12.2HD U C6)](https://optifine.net/downloads)
[**VeinMiner** (VeinMiner 0.38.1 [MC1.12, rev 639])](https://minecraft.curseforge.com/projects/veinminer)

**Comment by mcenderdragon** [comment]
Well it is unusual they have 3 nbt tags, can you scan the wardrobe with the EScanner and make a video of you slowli scrolling thriu the text ? (or copy the completle Escanner text out of the game log)

**Comment by WPaul15** [comment]
Here's the text from the scan of the wardrobe containing the Processors: [E-Scanner Log.txt](https://github.com/mcenderdragon/Futurepack-API/files/1663770/E-Scanner.Log.txt)
It looks like the Torus Processors have the NBT tags: `core`, `rambase`, and `corebase`, whereas the TCT and Master-Mind Processors only have a `core` tag. It looks like two Torus Processors with the same `core` values aren't stacking because they have different `corebase` values. The Dungeonheart Processors don't have any tags, which may be because I took them from the laser turrets in a Tech Dungeon; I didn't make them in the Assembly Table.

For reference, here's an image of the contents of the wardrobe:
![2018-01-25_12 36 40](https://user-images.githubusercontent.com/16868897/35386462-72c9b1aa-01cc-11e8-8f13-d427da1c1505.png)

**Update:** This is essentially the same issue for the RAM as well; the Torus RAM have the tags: `rambase`, `corebase`, and `ram`.

**Comment by mcenderdragon** [comment]
Yeah the rambase/corebase values, they exists mainly for recycling to get better parts out of them depending from what they where crafted.
