### ISSUE TITLE
Freature Request - Decrease the two tunnel dungeons with 4 wardrobes.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#348]
It seems like you can't go a few hundred blocks without running in to one of these dungeons, is there a config option to decrease the frequency?

**Comment by mcenderdragon** [comment]
yes

**Comment by mcenderdragon** [comment]
In worldgeneration:  S:tecDungeon_spawnrate=0.00667

**Comment by ProsperCraft** [comment]
Thank you.
