### ISSUE TITLE
Can't respawn on other Planets, if Spaceship is gone

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#35]
If someone fly away without you and you need to respawn, it ends in endless, deadly fall.
Spawnpoint need to be changed in this case!

**Comment by Wugand** [comment]
Sleeping should work on other Menelaus. (i know there are Problems, but please)

**Comment by Wugand** [comment]
We have notes for an inteligent respawn/escape system ...

**Comment by mcenderdragon** [comment]
Its fine if we have notes but I cant do anything about that. It should already working.
