### ISSUE TITLE
Futurepack-1.12.2-26.3.48 not working with CraftTweaker furnace recipes

### ISSUE THREAD

**Issue by b0bst3r** [mcenderdragon/Futurepack-API#351]
You did something as this was working prior to 26.3.48, from the changelog
-fixed crafttweaker support

I have 2 simple lines in CT to change the magnetite furnace recipe as my pack has Better with Mods hardcore turned on (which smelts all ores to nuggets).

``` // Remove magnetite ore to 4 iron ingots smelting recipe
furnace.remove(<fp:erze:4>);
furnace.addRecipe(<immersiveengineering:metal:29> * 4, <fp:erze:4>);
```
```immersiveengineering:metal:29``` is iron nuggets from Immersive Engineering

From CT log
```
[POSTINITIALIZATION][CLIENT][INFO] Removing furnace recipes for: <fp:erze:4>
[POSTINITIALIZATION][CLIENT][INFO] 0 recipes removed for: <fp:erze:4>
[POSTINITIALIZATION][CLIENT][INFO] Adding furnace recipe for <fp:erze:4>
```
Magnetite still smelts to 4 iron ingots.

**Comment by mcenderdragon** [comment]
prior to 26.3.48, craft tweaker support did not work at all (at least in 1.12)

**Comment by b0bst3r** [comment]
It did I had that recipe working maybe not on the immediate version before 26.3.48 but certainly on older ones.

**Comment by mcenderdragon** [comment]
Also "furnace" refercs to the vanilla furnace and that is completly handled by craftweaker/minetweaker. I dont think I can to something here :S ( or at least I dont know what)

**Comment by b0bst3r** [comment]
Yeah it's the vanilla furnace the script isn't working on.

**Comment by mcenderdragon** [comment]
does furnace.remove searches for output of for input ?

**Comment by b0bst3r** [comment]
Removal

There are 2 ways to remove Furnace recipes, being:

```furnace.remove(output)```

And

```furnace.remove(output, input);```

**Comment by b0bst3r** [comment]
Output but that remove line I added in after the furnace recipe change didn't work

**Comment by mcenderdragon** [comment]
it is locking for somehting with fp:erze but cant find something. In game the recipe is still present and working ?

**Comment by mcenderdragon** [comment]
I dont add a recipe wich outputs magnetide, I only add a recipe to add smelt magnetide to 4 iron, and if remove is searching for output I think chaning the search pattern to iron should remove my recipe (propaply also others)

**Comment by b0bst3r** [comment]
In game fp:erze:4 (magnetite ore) is still smelting to 4 iron ingots which is default for FP.

The script is supposed to change that to 4 iron nuggets.

The script does nothing and magnetite remains smelting to 4 iron ingots.

I can't find any errors in any log pertaining to the script entry, it simply is ignored and does nothing.

Please ignore ```furnace.remove(<fp:erze:4>);``` I added that afterwards which is wrong I know, the 2nd line is supposed to change the furnace recipe.

**Comment by mcenderdragon** [comment]
I dont know much about Minetweaker, have you already asked someone who is familiar with the scipts  ?

**Comment by b0bst3r** [comment]
Ok sorry for wasting your time, the behaviour of CT has obviously changed between versions.

Remove magnetite ore to 4 iron ingots smelting recipe
```furnace.remove(<ore:ingotIron>, <fp:erze:4>);```
```furnace.addRecipe(<immersiveengineering:metal:29> * 4, <fp:erze:4>);```

Works fine before I didn't need to remove the old recipe, the previous script was 

Remove magnetite ore to 4 iron ingots smelting recipe
```furnace.addRecipe(<immersiveengineering:metal:29> * 4, <fp:erze:4>);```

Obv something changed between CT versions and removing is now necessary.

Again sorry for wasting your time.
