### ISSUE TITLE
Request regarding Erse flowers/food

### ISSUE THREAD

**Issue by b0bst3r** [mcenderdragon/Futurepack-API#352]
Would it be possible to add config options to allow pack makers to balance this food with packs.

Atm it breaks into multiple and gives 3 food and is plantable.

Can you consider giving us options please.

Erseplantable = true/false
Erseworldgenned = true/false
Erserarity = make a scale having only once in 20 chunks as the rarist would suit my needs
Ersefood = 1 (how much food restoration it gives)

Having Erse drop something non-edible which is later craftable by FP machines is another probably less brutal approach?

I'd be quite happy if you changed the default food to restoring half a food bar (instead of 3) such is the commonality of the food.

**Comment by mcenderdragon** [comment]
Wow, I never imagined you would need a config fot this :D

**Comment by b0bst3r** [comment]
It's just too OP you don't need any other food ever, from any other mod ever.

**Comment by mcenderdragon** [comment]
OK removing the plantability dynamicly is hard without breaking other mods, but the generation and foot options should be possible

**Comment by mcenderdragon** [comment]
[test this](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.69)

**Comment by b0bst3r** [comment]
testing

**Comment by b0bst3r** [comment]
Tested SSP and SMP seems to work fine thanks.
