### ISSUE TITLE
Dungeon flash servers causing server TPS issues.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#353]
I came to report that flash servers in dungeons are ticking high in the server, can they be inactive and not tick at all until they are in actual use?

![futurepack-flashserver](https://user-images.githubusercontent.com/4427684/35451602-02a13d16-0281-11e8-93cf-23db4d068c54.png)

https://i.gyazo.com/c191f9c71bac9bb548058082b4b141eb.png

**Comment by mcenderdragon** [comment]
They dont do aynthing at all, I am very confused why they need so much time per tick.

**Comment by mcenderdragon** [comment]
Can you check if this version fixes this bug: ?[26.3.68](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.68)

**Comment by ProsperCraft** [comment]
Are you going to push that version to curse so I can push it to my pack and test it live on the server with the players?

**Comment by mcenderdragon** [comment]
Well I would like to know if it works first, to avoid version spamming. Is curse the only way for you to test this ?

**Comment by ProsperCraft** [comment]
Tested Without the update in single player - got a baseline, then updated to your .68 and it totally fixed it.

I then tested on the server with only me logged in and it seems to have totally fixed it.

**Comment by mcenderdragon** [comment]
\o/ cool

**Comment by mcenderdragon** [comment]
Then I will push an updtae out today :D
