### ISSUE TITLE
Lava pools under block breakers can replace bedrock.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#355]
![2018-01-28_20 22 25](https://user-images.githubusercontent.com/4427684/35492254-0eff424e-0469-11e8-8ddf-f468bae12d6b.png)

**Comment by mcenderdragon** [comment]
[this version should fix it](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.73)
