### ISSUE TITLE
Composite Chests rendering problem

### ISSUE THREAD

**Issue by 1skandar** [mcenderdragon/Futurepack-API#356]
There is a wee bit of a problem with the way Composite Chests render, or at least composite double chests.

Now you see it:
![2018-01-29_03 05 19](https://user-images.githubusercontent.com/4127779/35499694-77edd3be-04a1-11e8-9572-344310ab1255.png)

However, turn ever so slightly to the right and...
![2018-01-29_03 05 22](https://user-images.githubusercontent.com/4127779/35499709-902c6f76-04a1-11e8-970e-2acb7eca4e75.png)

Now you don't.

**Comment by 1skandar** [comment]
A little more experimentation shows it is only on double chests and only on the right side of those double chests. Left side renders as expected.

**Comment by mcenderdragon** [comment]
Already fixed in a side branch, this will hopefully soon get merged into the main one :)
