### ISSUE TITLE
Research for "Research Module (AI)" not accepting correct resources in version 1.12.2-26.3.71

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#358]
In version 1.12.2-26.3.71 the research for "Research Module (AI)" does not accept the ingredient "Research Module - Energy".  

It worked correctly when I downgraded to version 1.12.2-26.3.48, so I am pretty sure that it was not just me doing something wrong.

**Comment by mcenderdragon** [comment]
wow I am so dump, expect a new version fxing this soon 🤦‍♂️

**Comment by mcenderdragon** [comment]
[26.3.74](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.74)

**Comment by qrss** [comment]
Wow, that was a very quick response and fix. Good Job!
