### ISSUE TITLE
[1.9.4-capabilities] Compilation error at T-Module

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#36]
"undefined Method" in:
Modul T1:
Zeile 58-61: "new SlotUses"

Modul T2:
Zeile 112:  "isUseableByPlayer"
Zeile 59-62: "new SlotUses"

**Comment by mcenderdragon** [comment]
This error didnt show up at mine.

**Comment by mcenderdragon** [comment]
Wait, capabilitrs are hat 1.9.4, and jei is in 1.10.2. what did you do?

**Comment by Wugand** [comment]
eventually used the wrong forge version .... i check this

**Comment by Wugand** [comment]
Ok, i'am to stupid to read an version number ... but it doesn't fix the problem
