### ISSUE TITLE
[Suggestion] Space ship

### ISSUE THREAD

**Issue by litjohn50** [mcenderdragon/Futurepack-API#362]
With the board controller is there anyway to add a typing command to the X Y Z cords? 

I was spinning my mouse in circles for awhile just to go a few 1k blocks

**Comment by mcenderdragon** [comment]
shift/control is supported for faster increases, of the position.
also it is balanced because it takes afford :P /irony

**Comment by litjohn50** [comment]
Ok that changes things! I like the control feature really does speed it up. But, I the e-scanner never talked about it that's why I never knew.

But, if that's in then there is no need for typing option.

**Comment by mcenderdragon** [comment]
well in theorie this feature does not exist, it was an experiment ^^
