### ISSUE TITLE
Huge Dungeon / Tec Dungeon not spawning in Custom Dimension

### ISSUE THREAD

**Issue by KAfable** [mcenderdragon/Futurepack-API#363]
Hi,

So my modpack partner made this [mod](https://minecraft.curseforge.com/projects/interaction-dimensions-mod) for my pack. It adds custom underground cave dimensions, which I wanted to fill with your worldgen. However after adjusting configs, I could only get the caves (retium. glowtite, etc.) to spawn. I couldn't get any of the Tec-Dungeons or the Huge Dungeons to spawn. 

Do those dungeons depend on some sort of specific biome or specific World provider to spawn in?

Thanks again! Love the mod, and I'm really glad you implemented the dimension whitelist for your world generation.

**Comment by mcenderdragon** [comment]
the small tec dungeons should spawn everywhere (thatswhy the black list), and the huge ones spawn (story wise) only the the default dimension
