### ISSUE TITLE
Cable - SuperCable  energy flow bug

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#367]
![bug](https://user-images.githubusercontent.com/11357199/35772304-c815af3a-093b-11e8-829d-ef8c91cef6e9.png)

**Comment by mcenderdragon** [comment]
- Neues System kann jetzt getsstet werden
- Logistic System wird noch vollständig ignoriert

**Comment by mcenderdragon** [comment]
- new wire system should fully work now

**Comment by mcenderdragon** [comment]
ALso batbox weirdnesss is fixed.
