### ISSUE TITLE
Incorrect recipes shown in the Tech Tree

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#368]
The Penton RAM and Core are shown to need 3 neonparts/gold parts, but in practice only need 1.

The Teleport Block recipe shown in the Tech Tree does not work. For debugging purposes I installed JEI, which showed a different recipe with a button in the top middle slot instead of Aluminum Plates, which does work.

**Comment by Wugand** [comment]
Both should be fixed in: [26.3.127](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.127)

**Comment by qrss** [comment]
Both do seem to be fixed.

I've progressed further in the mod since I made this issue and noticed a few more inconsistencies with the Assembly Table recipes:

TCT Core: 
Tech Tree says: 4 goldparts
Actual recipe: 2 goldparts

Note that TCT Memory takes 4 neonparts vs the 2 goldparts of the TCT Core. I'm not sure whether they are intended to take the same number of parts.


Ultimate Chipset:
Tech Tree says: 2 silicon
Actual recipe: 2 quantanium

**Comment by Wugand** [comment]
Thank you for report, fixed again: [26.3.218](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.128)

**Comment by qrss** [comment]
This indeed fixes it. Thank you for your effort.

A question:
If I notice some typos or want to improve the wording of the English text a bit, I should make a pull request to this repository
https://github.com/Wugand/FuturePack-Language
right?

**Comment by mcenderdragon** [comment]
Yes :)
