### ISSUE TITLE
[v.26.3.76] Researcher  / Blueprints Fail for Pipes - unable to progress

### ISSUE THREAD

**Issue by wideblaze** [mcenderdragon/Futurepack-API#369]
I'm unable to progress research tree due to apparent bugs with researcher and pipes

1) Research Blueprint Neon Pipe - Needed Resources Normal Pipe
Placed in researcher asks for 8 Normal Pipe
Added 8 normal pipe - input shows redbox / does not process

2) Research Blueprint Redstone Pipe - Needed Resources Redstone, **tile.pipe_32767.name**
Placed in researcher asks for 8 redstone dust, 2 tile.pipe_32767 (also shows no-render checkerboard tile)
No such item tile.pipe_32767

**Comment by phrostt** [comment]
Same problem here, for pipes and energy module that takes 8 wires to research. using the version Futurepack-1.12.2-26.3.78 that was linked in a similar issue thread, still same problem.

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/360

**Comment by mcenderdragon** [comment]
Does the version I posted in the other issue helped?

**Comment by phrostt** [comment]
No, the version .78 you posted in #360 does not help.

**Comment by mcenderdragon** [comment]
interesting, what other mods are installed ?

**Comment by mcenderdragon** [comment]
@phrostt in single or in multiplayer ?

**Comment by mcenderdragon** [comment]
Can you try this version: [26.3.88](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.88)

**Comment by phrostt** [comment]
Single player, will try the version and let you know.

**Comment by phrostt** [comment]
Still does not work. I added futurepack to all the mods 3, so there is a lot of mods present. It shows a red box around even when I put in the correct item.

**Comment by mcenderdragon** [comment]
for the support pipe research ? Or another one ?

**Comment by mcenderdragon** [comment]
New version: [26.3.93](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.93)

**Comment by PricklyPorcupine** [comment]
Had the same problem with research for Renewable Energy not accepting 16 Cable in .76 and .88. Just updated to 26.3.93 and the research completed, except it only consumed 1 Cable and 1 Normal Pipe (out of 4).

Research for Water Cooler and Upgraded AI-Memory correctly consumed all items (assuming they are meant to consume the Water Bucket without returning an empty Bucket).

**Comment by phrostt** [comment]
Just tried .93 looks to be working

**Comment by phrostt** [comment]
Same as PricklyPorcupine said about consuming only 1.

**Comment by mcenderdragon** [comment]
Also the stacksize bug should be fixed: [26.3.97](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.97)
