### ISSUE TITLE
[1.12] Hint to Airbrush recepies

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#37]
It would be nice to show the coloring / uncoloring of blocks in JEI as "airbrush recepies"

**Comment by mcenderdragon** [comment]
AS there are no recipe in the runtime this is almost impossible.

**Comment by Wugand** [comment]
Test for coloring methodes?

**Comment by mcenderdragon** [comment]
yeah but JEI search for items itself so I have no control over it...

**Comment by mcenderdragon** [comment]
Are implemnted since 25.2.3

**Comment by Wugand** [comment]
Background Texture looks extremly strange.

**Comment by mcenderdragon** [comment]
mAntes has still not given me a better one :/
