### ISSUE TITLE
Player kicked from the server when pressing research on a scanner.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#370]
Console stacktrace- 

https://gist.github.com/ProsperCraft/0fbf7be8698c9e2768c057ec5ea4d3f5

The pack we are testing with is the town building and tech pack - 
https://minecraft.curseforge.com/projects/towncraft

**Comment by mcenderdragon** [comment]
Does tjis always happen or only sometimes ?

**Comment by ProsperCraft** [comment]
He has not been able to reproduce it.

**Comment by mcenderdragon** [comment]
Ok this is god, because it logical then ^^

**Comment by mcenderdragon** [comment]
[26.3.85](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.85), this version should fix this.

**Comment by Lithorn** [comment]
All I can say is, clicking around in the researcher seemed to kick me to the home screen. I'd have to scour my forge logs to see where it happens if it hasn't already been overwritten.

**Comment by mcenderdragon** [comment]
I can tell from the error it is extremly rare, it can only occur when you have a large amount of tile entities and in the exact same moment as someone opens the escanner somwhere has to be a tileentity placed or destroyed.
