### ISSUE TITLE
Bouncing ingots

### ISSUE THREAD

**Issue by 1skandar** [mcenderdragon/Futurepack-API#374]
I, um, am not sure what to make of this. Hold any Futurepack ingot in your hand. Right click your mouse. And then duck as the ingot goes bouncing all over the room. Oh, and it changes into a wakurian ingot in the process. Tried it with copper, zinc and neon ingots. All went flying, all got transformed. 

This is the latest version of Futurepack on Curse, 23.7.36

**Comment by mcenderdragon** [comment]
It should be fixed in this version:[26.3.98](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.98)

**Comment by 1skandar** [comment]
It is fixed. Well, to the point that only wakurian ingots are flingable, and I have to imagine that has an actual purpose?

**Comment by mcenderdragon** [comment]
it is in fact somehow lore relevant ^^
