### ISSUE TITLE
Player kicked from server when trying user a scanner for the first time. CME

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#375]
https://gist.github.com/ProsperCraft/6ff277dc43ca72f17eedfe86af72c8cf

Futurepack-1.12.2-26.3.76

forge-1.12.2-14.23.2.2613-universal

**Comment by ProsperCraft** [comment]
It did it again when he scanned stone.

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/370

**Comment by ProsperCraft** [comment]
I should mention this was the portable scanner.

**Comment by mcenderdragon** [comment]
it was an E-Scanner right ? yeah it the same bug as in 370
