### ISSUE TITLE
Can't complete Research

### ISSUE THREAD

**Issue by davqvist** [mcenderdragon/Futurepack-API#376]
I want to complete Research Module - Energy  which needs 8 Cables but I can't complete it.
See the following Screenshot: https://i.imgur.com/TKVF0iW.png

What am I doing wrong?

MC 1.12.2
Forge 2599
Futurepack 26.3.76

**Comment by mcenderdragon** [comment]
#360, #369 - can you please try this version: [26.3.97](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.97), it should be fixed there.

**Comment by davqvist** [comment]
Fixed, thanks

**Comment by DigitalSketch** [comment]
FYI, with this version, it appears the colored tanks aren't craftable.
