### ISSUE TITLE
Decoration tab?

### ISSUE THREAD

**Issue by davqvist** [mcenderdragon/Futurepack-API#378]
Futurepack 26.3.97
MC 1.12.2
Forge 2615

Sorry if this is a dumb question or if I am blind, but I am still trying to learn the mod in creative.
I just now learned Optics and it says it has stuff added to the Decoration tab. But I don't have a Decoration section. My tabs are in order: Basics, Story, Production, Logistics, Circuits, Space Travel, Tools
I just can't find what I unlocked.

**Comment by mcenderdragon** [comment]
@Wugand we need to rewritte the references to the tabs.

**Comment by Wugand** [comment]
We merged Decoration into Space travel and Energygeneration into Production some time ago. The discriptions will be updated in next version.
