### ISSUE TITLE
Industrial furnace poor performance on the server when idle.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#379]
Futurepack-1.12.2-26.3.76

![2018-02-15_23 29 06](https://user-images.githubusercontent.com/4427684/36295987-12840236-12a8-11e8-857c-eb7e277f9507.png)

![2018-02-15_22 48 11](https://user-images.githubusercontent.com/4427684/36295999-25f93dea-12a8-11e8-81ad-eb81b8c7bb17.png)
![2018-02-15_22 43 50](https://user-images.githubusercontent.com/4427684/36296001-2b48dbca-12a8-11e8-926a-579b35e8224f.png)

As you can see the furnace is taking an amazing amount of server ticks just from being idle with some lava in it.

Without lava, it doesn't tick at all.

![2018-02-15_23 33 53](https://user-images.githubusercontent.com/4427684/36296091-bb09d96c-12a8-11e8-896d-833e9d3645b3.png)
The one on the left is empty, the one on the right has some lava in it.

Once we removed the offending furnace that was taking 17% of the entire server ticks, it no longer showed up on the report.

Now to troubleshoot the Industrial Neon Furnace, which I noticed was reported before.

![2018-02-15_23 42 56](https://user-images.githubusercontent.com/4427684/36296311-f6b2ac04-12a9-11e8-854f-d4c317e72124.png)
![2018-02-15_23 43 51](https://user-images.githubusercontent.com/4427684/36296356-1aa8af96-12aa-11e8-8255-1496e981eaa5.png)
https://github.com/mcenderdragon/Futurepack-API/issues/371

**Comment by mcenderdragon** [comment]
yeah most likly the same problem as the industrial neon furnace also applies for the normal one, I will check this out.

**Comment by mcenderdragon** [comment]
this versipn should fix it. : [26.3.102](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.102)

**Comment by ProsperCraft** [comment]
**before update...**
![2018-02-16_09 59 34](https://user-images.githubusercontent.com/4427684/36321064-bb003f76-1305-11e8-8521-0dc90a952ef5.png)
![2018-02-16_09 59 45](https://user-images.githubusercontent.com/4427684/36321070-bfd86d8e-1305-11e8-87b5-a3f66c58447c.png)

**After update.**
![2018-02-16_10 38 57](https://user-images.githubusercontent.com/4427684/36321077-c7837e2a-1305-11e8-8dbb-41c776d62a80.png)
![2018-02-16_10 39 08](https://user-images.githubusercontent.com/4427684/36321078-c90b568c-1305-11e8-88ca-b20044bc474a.png)

I would say its MUCH better, but not solved.
The industrial furnace with lava in it is(on the right) taking 45x more server ticks then the one without lava in it.

as a comparison
![2018-02-16_10 52 18](https://user-images.githubusercontent.com/4427684/36321600-8f64225e-1307-11e8-93a2-ad39172be546.png)
, on top of that industrial furnace on the right, is a thermal expansion igneous extruder actively extruding cobble from lava and water.

As you can see the idle furnace with lava in it is taking more then double the amount of ticks then an actively producing machine.

The idle extruder and idle industrial furnace without lava match.

**Comment by mcenderdragon** [comment]
only lava is in it but no items ?

**Comment by ProsperCraft** [comment]
No items at all, only a bucket of lava.  Its not doing anything just sitting idle.

**Comment by ProsperCraft** [comment]
Hold the press, the right block is a Neon furnace...more testing inbound.  I swear it was an industrial furnace.

**Comment by ProsperCraft** [comment]
![2018-02-16_11 06 18](https://user-images.githubusercontent.com/4427684/36322121-6e04e95c-1309-11e8-80b7-2d720ceb626e.png)

Industrial furance with and without lava competely solved... next up...neon furnace and industrial neon furnace.

**Comment by mcenderdragon** [comment]
I will reopen this until the fix is availab el on curse (for me so the changeslog is easier )
