### ISSUE TITLE
JEI don't show main-board Recepies [important]

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#38]
JEI don't show any crafting recepies for machines.
Example: Centrifuge, NeonFurnace, SuperCrusher, ....

Only working: Entity Eater, E-Magnet

maybe caused by meta.

Important: Fix this before Release

**Comment by mcenderdragon** [comment]
If you have researched them, are they then visible?

**Comment by Wugand** [comment]
Yes, if they researched they are visible.
