### ISSUE TITLE
[Issue (I think)] Research Blueprint for Energy using cables

### ISSUE THREAD

**Issue by DigitalSketch** [mcenderdragon/Futurepack-API#380]
I got a blueprint to research and it asked for cables.  I put cables into the slot, but it doesn't seem to take them.  The white bar shows full, but nothing happens.  I think it's a bug, but I'm new to the mod and I may have missed something somewhere that I have to do.  Just can't seem to progress.

**Comment by mcenderdragon** [comment]
Is it possible the same issue as in #376 ? Can you try the version posted there ?

**Comment by DigitalSketch** [comment]
Looks like that fixed it.  Thanks!

**Comment by DigitalSketch** [comment]
FYI, with this version, it appears the colored tanks aren't craftable.

**Comment by mcenderdragon** [comment]
the colored tanks for the air brush ?

**Comment by DigitalSketch** [comment]
Yup, tried to make a black one but the output didn't show.  I tried multiple orientations of the recipe, although it shows it as shapeless.

**Comment by mcenderdragon** [comment]
did you use  the tec htable a nd have you already researched the recipes ?

**Comment by DigitalSketch** [comment]
Yup I learned it, and tried it both in the tech table and regular crafting table.

**Comment by HordeCommander** [comment]
I can confirm the Tanks not being able to be built.

**Comment by litjohn50** [comment]
yes the colored dyed tanks can't be made in either tech-table or normal table had to use crafttweaker to add a different recipe. even if you have the research finished for it.

**Comment by mcenderdragon** [comment]
Ok it seems like this is caused by forge, after I updated to thelatest version they implemented "isSimple" t Shapeless recipe and using a different comparsen mathed (wich failes) I have disabled it for now but I dont know whats causing it.

**Comment by mcenderdragon** [comment]
Tanks should be crftable again: [26.3.115](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.115)

**Comment by DigitalSketch** [comment]
Confirmed, it works in that update, thanks!
