### ISSUE TITLE
Gravestone mods are incompatible with huge dungeon

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#381]
https://www.reddit.com/r/feedthebeast/comments/7v1hzd/died_inside_a_futurepack_dungeon_ship_that_you/

**Comment by mcenderdragon** [comment]
MAybe we can use inter mod communication for this + a whitelist of always breakable blocks.

**Comment by mcenderdragon** [comment]
FIx: [26.3.105](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.105)

**Comment by ProsperCraft** [comment]
Gravestone mods that require block breaking are inferior to Tomb Many Graves, where you simply sneak across your grave, all modpacks should switch :)  This is what we are using.
