### ISSUE TITLE
[Question] I'm stuck

### ISSUE THREAD

**Issue by DigitalSketch** [mcenderdragon/Futurepack-API#382]
I'm not sure where to ask this, so I apologize if this isn't the right place (if not, could I get a FAQ or forum where I can ask?)

I'm stuck.  I can't seem to advance, but have done all that I think I can.  Everything in my E-Scanner is locked and has a little line with a dot above all the un-researched things.  I've researched all I can think of and the things that aren't full, have the yellow question mark.  Looking at the achievements, it looks like the next thing I have to do is craft a bow, and/or travel to Menelaus.  

What is next?  I've gotten the Dungeon key 1, but haven't found any other blueprints other than the dungeon key 2 and 3.

**Comment by mcenderdragon** [comment]
can you send screenshots from each tab inside the EScanner ?

**Comment by DigitalSketch** [comment]
OK here ya go: [https://imgur.com/a/oh0zW](https://imgur.com/a/oh0zW) and thanks!

**Comment by mcenderdragon** [comment]
In the first picture the very right research, after the roboto arm with the 2, this is the research you need to aquire.

**Comment by DigitalSketch** [comment]
Hmm I'm trying everything I can think of, can I have a hint?

**Comment by mcenderdragon** [comment]
I think you can still research the Optibench

**Comment by DigitalSketch** [comment]
I could have sworn I did that, but yea it showed another one.  Not sure how I missed it, especially since it says "Optibench" in the Production 2 section.

**Comment by mcenderdragon** [comment]
I think this is fixed now
