### ISSUE TITLE
World crashes when placing monocart on station

### ISSUE THREAD

**Issue by HordeCommander** [mcenderdragon/Futurepack-API#383]
Greetings. I've just started working with monorails. I was trying to open my monorail Station with a scrench in my hand. Now the world refuses to load (stops on "Building Terrain), and when it finally fails, it leaves me with no crash report... (I know, not helpful). 

I cannot reproduce the result myself... as I would have to play through the whole mod to get to that point. (I likely will be doing it, it just will take me a lot of time to get there again)

**Comment by litjohn50** [comment]
You can try to reproduce it in creative by doing "/fp research unlock name single" . Spaces in names are counted as . periods  so like "/fp research unlock neon.pipe single"

**Comment by mcenderdragon** [comment]
can you please give the logs in you lougs folder (after loading the wolrd till it crash intern) fml-client-latest-fml-early-junk, fp-latest, latest.log

**Comment by HordeCommander** [comment]
I will try to go get the logs for you. And I will try using the command thanks guys.

**Comment by HordeCommander** [comment]
Found the file, do you want me to put the whole log in here, or id you have a place you wanted me to put the file?

**Comment by HordeCommander** [comment]
[fml-client-latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1735259/fml-client-latest.log)
[Uploading fml-junk-earlystartup.log…]()
[Uploading FP-Latest.log…]()
[Uploading latest.log…]()

**Comment by mcenderdragon** [comment]
this should fix it: [26.3.117](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.117)
