### ISSUE TITLE
[1.12.2] Crash when entering Menelaus with Terraqueous

### ISSUE THREAD

**Issue by orbwoi** [mcenderdragon/Futurepack-API#384]
When I try to enter the planet Menelaus with Terraqueous installed, the game crashes.
It appears to be an issue with the sand blocks and terraqueous worldgen.

The log is attached.

Futurepack version: 1.12.2-26.3.76
Terraqueous verison: 1.12.0-1.4.8

[crash-2018-02-16_22.02.01-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/1734384/crash-2018-02-16_22.02.01-server.txt)

**Comment by mcenderdragon** [comment]
@ShetiPhian GenPlants.generate has a bug. you pass the sate from the plant to the soil, but you have to pass the state of the soil itself. Yes I know this is quite strange but it is also at all other methods so. I have also evidence: BlockCactus#canBlockStay line 134 (the return) 

```
 IBlockState state = worldIn.getBlockState(pos.down());
return state.getBlock().canSustainPlant(state, worldIn, pos.down(), EnumFacing.UP, this) //this is the BlockCactus
```

**Comment by mcenderdragon** [comment]
I have created an issue at his mod: https://github.com/ShetiPhian/Localizations-and-Issues/issues/149

**Comment by mcenderdragon** [comment]
in the other issue was a fix posted, you can try that version and report here (and to him) if its fixed.

**Comment by mcenderdragon** [comment]
Terraqueous pushlied a new build were this is fixed.
