### ISSUE TITLE
[Issue] Holograms after the new update

### ISSUE THREAD

**Issue by DigitalSketch** [mcenderdragon/Futurepack-API#385]
Updating to 26.3.115 to fix the dye tanks caused the holograms to go away.  It looks like it's only happening with redstone cables.

Forge version I have loaded is 14.23.2.2617

**Comment by mcenderdragon** [comment]
does simply readding them helps ?

**Comment by DigitalSketch** [comment]
no, the holograms seem to be an issue, just tried it on a normal cable too and it crashed the game as well.

Here is the crash report if it helps: [https://pastebin.com/BpsEHUhC](https://pastebin.com/BpsEHUhC)

**Comment by mcenderdragon** [comment]
your forge is outdated try to update forge.

**Comment by DigitalSketch** [comment]
ok let me give that a shot

**Comment by DigitalSketch** [comment]
Updated to 2618 and it crashed again.

**Comment by mcenderdragon** [comment]
can you give that crash report ?

**Comment by mcenderdragon** [comment]
ok Interesting the last version you had should nto crash, can you try to run with only futurepack?, SOmeof the coremods is maybe breaking it.

**Comment by DigitalSketch** [comment]
Using just the Futurepack mod, it seems to work, not sure what other mod is conflicting with it.

**Comment by mcenderdragon** [comment]
puBulkData, is quite new and was added thorugh a PR from me, maybe a coremode is renaming it or patching it out.

**Comment by DigitalSketch** [comment]
No idea what that is :) but hope I'm helping!  I like the new cable textures by the way.

**Comment by mcenderdragon** [comment]
Is it still crashing with 26.3.123 ?

**Comment by DigitalSketch** [comment]
It works!  I did get a message saying I should upgrade to Forge .2616 but I'm running .2618.

Thanks and well done!

**Comment by mcenderdragon** [comment]
yeah this message is printed when the method is not found, so its kind of a pseudo bug but atleast it is playble again :)
