### ISSUE TITLE
[Issue] Can't get the industrial furnace to trigger Production 3 research

### ISSUE THREAD

**Issue by DigitalSketch** [mcenderdragon/Futurepack-API#387]
Rolled back to the latest release of FP (3.76) and I can't get the industrial furnace to be recognized to start research for production 3.

[https://imgur.com/a/Z1SFY](https://imgur.com/a/Z1SFY)

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/360

**Comment by mcenderdragon** [comment]
The Bug should be also caused by this one
