### ISSUE TITLE
Composite Doors duplicating when the upper part is broken

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#388]
A composite door drops two composite doors when the upper part is broken.

When the lower part is broken, only one composite door drops, as intended.

**Comment by Wugand** [comment]
It only happens when using rigth tool (>= iron pickaxe) in survival. 
(It's reproducible)

**Comment by mcenderdragon** [comment]
This should fix it: [26.3.143](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.143)

**Comment by qrss** [comment]
Can confirm that this is no longer an issue.
