### ISSUE TITLE
JEI never update Recepies [important]

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#39]
JEI recepies keep locked if the research is finished; also try to renew researches with E-Scanner don't work.

The Researches definitly ARE get updated:
[15:08:21] [Client thread/INFO] [Futurepack]: Send Research Request to Server
[15:08:21] [Netty Local Client IO #0/INFO] [Futurepack]: Get Research Data from Server

Sould be fixed befor release!

**Comment by mcenderdragon** [comment]
Are you shure you tested with the right researches?

**Comment by Wugand** [comment]
I test it with the first few researches and command ... nothing works
