### ISSUE TITLE
Pulverizer- Tin= Alutine?!

### ISSUE THREAD

**Issue by CTH999** [mcenderdragon/Futurepack-API#390]
If you have Future pack and Thermal Expansion, and you pulverize Thermal expansions Aluminum, you get Alutine Crystals. This would be fine, but even though you get Alinting, it's in-usable in Thermal Expansion recipes. I think what's happening is that Alutine is the same in many ways (Just not Ore-Dict) To Aluminum, and for some reason it's just assuming it's Alutine. Just figured I'd put that there. An item-id change should, theoretically, work.

Just so you know!

**Comment by mcenderdragon** [comment]
can you provide screenshots ? Because I dont fully get what you are saying.

**Comment by CTH999** [comment]
Ok, in a few!

**Comment by CTH999** [comment]
Config Values- Default

Screenshots- Why bother, It's now working. My guess would be that you changed something. And, that something was somehow connected to this issue. Therefore, you accidently fixed it. If it happens again, I'll reopen this with screenshots. Thanks!

**Comment by mcenderdragon** [comment]
Öhh ok, ... great ^^

**Comment by CTH999** [comment]
Yup!
