### ISSUE TITLE
Server crash on worldgen - ClassCastException BlockWire

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#391]
https://paste.fedoraproject.org/paste/i5tNMFLa2xp0kFeDJYsVPw

![2018-02-18_21 01 05](https://user-images.githubusercontent.com/4427684/36362138-1dd9eada-14ef-11e8-8732-0032907385e2.png)

**Comment by ProsperCraft** [comment]
![2018-02-18_21 05 16](https://user-images.githubusercontent.com/4427684/36362178-744edb6e-14ef-11e8-8eb3-ce66e09959bb.png)

Perhaps because its adjacent to this flash server?

**Comment by ProsperCraft** [comment]
Here is another Cast exception from a new location-
https://paste.fedoraproject.org/paste/i5tNMFLa2xp0kFeDJYsVPw
![2018-02-18_22 42 19](https://user-images.githubusercontent.com/4427684/36363802-499f61be-14fd-11e8-95ef-2f89036131e6.png)
![2018-02-18_22 42 32](https://user-images.githubusercontent.com/4427684/36363804-4b795dc8-14fd-11e8-89c2-b306247629ec.png)
![2018-02-18_22 42 36](https://user-images.githubusercontent.com/4427684/36363805-4cc8f922-14fd-11e8-8f77-4a66ac1252de.png)

**Comment by mcenderdragon** [comment]
two dungeons generated in each other, is this correct?, are at the surface 2 entrances pretty close to each other ?

**Comment by mcenderdragon** [comment]
This should fix this issues,a dn the other worlgen issues [26.3.118](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.118)

**Comment by mcenderdragon** [comment]
I pushed the 118 to curse :)
