### ISSUE TITLE
Server crash - NegativeArraySizeException DungeonProtection.loadQueed

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#392]
https://paste.fedoraproject.org/paste/EVX3LPF2BZFtXbOexOJjSA

**Comment by mcenderdragon** [comment]
This should fix this issues,a dn the other worlgen issues [26.3.118](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.118)

**Comment by mcenderdragon** [comment]
I pushed the 118 to curse :)
