### ISSUE TITLE
The Advancement "It contains metals" not triggering when picking up Menelaus Dirt

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#393]
The Advancement description says "Get Menelaus Gravel od Dirt". (this typo should also be fixed "od -> or")

It triggers when you pick up Menelaus Gravel, but not when you pick up Menelaus Dirt.

**Comment by Wugand** [comment]
Fixed in [26.3.124](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.124)

**Comment by qrss** [comment]
Can confirm that it is working correctly now.
