### ISSUE TITLE
Inventory interaction issues in the GUI of Research Module - Experience

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#394]
Note that for me the specific behavior depends on the GUI size. The monitor resolution is 1920 x 1080.

If the GUI size is set to AUTO, I pick up the item in the third hotbar slot when clicking on the PLUS button in the GUI of Research Module - Experience. When clicking on specific areas of the GUI, not necessarily on any buttons, sometimes an item in some specific slot is picked up.

When the GUI size is small enough, then this does not happen.

An item that is picked up can be placed in an inventory slot, but the items can not be picked up by actually clicking on them in the inventory.

**Comment by mcenderdragon** [comment]
Does this only happe in the gui of the t3 modul ?

**Comment by qrss** [comment]
Yes.

**Comment by mcenderdragon** [comment]
[26.3.122](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.122)

**Comment by qrss** [comment]
This fixed all the problems I noted.

I noticed an unrelated issue with Research Module - Experience.
When you use the Ultimate Chipset + Network Chipset + Transport Chipset combo to pipe experience into the Experience Module, the amount of stored experience can go past the maximum 1500.

I'm not sure whether I should make a new issue for this, I don't want to spam the issue tracker with posts, so I'll just make a note of it here.

**Comment by mcenderdragon** [comment]
Spamming is ok,  and yes you should make a new issue for that :)
