### ISSUE TITLE
Complaint - latest build requires forge 2616

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#396]
What is it with you developers that push latest not even forge recommended builds? Present recommended build is 2611, forge does that for a reason because it is the most recent stable in the development cycle. Why developers want to keep building beyond such recommended builds is not only aggravating (given the non recommended typically have more bugs still needing worked out than the recommended) but frustrating that you seemingly want to force your community to deal with even potentially more buggy builds than need be,

Guess I'll be rolling back the futurepack update at present as I don't care to deal with the instability of non recommended builds. WHY do developers do this?

**Comment by mcenderdragon** [comment]
in 2616 a PR from me got accepted wish result in stable 60FPS for falling trees even if they have the size of the huge natura trees :) And well the few things they did are stable, also please dont roll back, that build was far more instable (futurepack wise), I did this to prevent "method not found excpetions" because I use this new feature.

**Comment by mcenderdragon** [comment]
But it is interesting how users thing about this :)

**Comment by trogarus** [comment]
Look, as I have stated before numerous times, I do enjoy this mod, but when a developer pushes to the latest instead of the recommended, it creates potential issues in a few ways. Firstly, many of the popular pack developers only upgrade to the recommended because of the potential stability issues beyond recommended builds. As such, when another developer pushes to a version beyond present recommended, it winds up breaking packs because that one developer is beyond where many other developers presently sit, and that breaks their mod in the process because their development cycle is based upon forge recommended.

Hopefully this makes more sense to you. Every time I have to upgrade to a version beyond recommended forge version, MOST TIMES, it breaks my present pack because of changes made in the newer forge versions that the other mod developers have NOT made changes for because it is not yet part of the recommended forge build. This is frustrating for not only people like me who make our own custom packs to play, but also for pack developers.

**Comment by mcenderdragon** [comment]
I under stand your point but be sure you are save:

```
Changelog:
Build 2618:
	bs2609: Don't cull generated item models with non-default transforms (#4749)

Build 1.12.2-14.23.2.2617:
	bs2609: Maintain deterministic order in deserialised Forge blockstates (#4748)

Build 1.12.2-14.23.2.2616:
	goto.minecraft: Add function to BufferBuilder to directly insert byte data. Closes #4722

Build 1.12.2-14.23.2.2615:
	bs2609: Clean up some GUI code and change magic numbers to GL constants (#4734)

Build 1.12.2-14.23.2.2614:
	mezz: Minor cleanup for TestAnnotationParser

Build 1.12.2-14.23.2.2613:
	LexManos:
		Remove Mercurius from release JSON, Sadly it's dead we may address it at
		a later date.
	LexManos:
		Initial implementation of JSON based annotation scanning. Disabled by
		default for now, until proven to be fully function. Enable using
		-Dfml.enableJsonAnnotations=true

Build 1.12.2-14.23.2.2612:
	mezz: Update Github Stale bot message to better explain how to un-stale issues

Build 1.12.2-14.23.2.2611:
	LexManos: Bump version for RB.
```

2611: just new version means 2610 is also stable (becuase code wise the same)
2612:stable bot is a txt file so this is github repo only
2613: lex manos commits are save
2614: test are only active in the github
2615: this clean up dont effects the end user, only dvelopers (code wise the same)
2616: I added a mthod thorugh a PR, so it cant break except my mod if I had done something wrong (no one uses this method yet)

**Comment by mcenderdragon** [comment]
But it is very interesting, the forst time I force a forge version this happens ^^, I wonder why nothing happen when I implemnetd the CriticalHitEvent wish was at this time also quite new.

**Comment by mcenderdragon** [comment]
Ohh also to the concern about breaking other mods: I sed a VERY old forge version before ^^ and it still wroked, LexManos realy tries to mathc binary compatiblity and all breaking changes only happen between MC versions.

**Comment by mcenderdragon** [comment]
For the future and the next FP version: is it better to use the old version if the never is not avilable and not force poeple to use the new forge version ?

**Comment by 1skandar** [comment]
Another mod pack dev chiming in. I'd say if you've got a good reason to build against a non-recommended version of Forge then there isn't really a big problem. It happens more than you'd likely expect. 

Also, I'm not sure what he is on about, Forge is almost always perfectly backwards compatible unless not being so is strictly necessary. I almost always run non-recommended versions of Forge in my mod pack updates and rarely have I seen an issue. And in most cases those issues are caused by a mod that hasn't updated in like 6 months or so and are lagging a good two or three Forge recommended versions behind anyway.

**Comment by trogarus** [comment]
I have had issues, even recently, with popular mods like extrautils and even actually additions at times, and those are relatively quickly updated. So we're not talking about obscure mods that the developer falls months behind in updating concerning my issues with this. Forestry is another one that has had this issue at times in past year as well, and that one is presently in active development for 1.12 as well. Just because you haven't run into it doesn't mean it doesn't exist. If we were talking about obscure mods where development is lagging, as you mentioned, then that's a different story. That isn't the case in this situation.

Sometimes it's just the huge size of a mod and it taking the developer considerable time to update to forge changes. And although it's not supposed to break backwards compatibility (forge), it does indeed do so at times because the developers are human.

Just saying, I tend to stick with recommended because it USUALLY causes less issues. Many mod developers seem to do the same, either because it causes less issues, or they have so much to update between forge changes that they only update to recommended, potentially because of time constraints etc.

**Comment by mcenderdragon** [comment]
the new curse version no longer requires forge.

**Comment by trogarus** [comment]
To be COMPLETELY clear. Even after all the playthroughs I have done, recently, I still very much enjoy the mod. Of course, I haven't done so again with latest updates, but my only issue previously was with the bedrock fissures (already fixed and thank you), and the time it seems taking for some of the research (which is quite considerable at the higher levels, a bit more than I expected), but I'm OK with that. So once again, as stated many other times, thank you for the work you put into this, and for the attention you provide to ensure it remains stable, healthy, and fun.
