### ISSUE TITLE
[Issue] Game crashes when going to Menelaus

### ISSUE THREAD

**Issue by DigitalSketch** [mcenderdragon/Futurepack-API#397]
Finally got a ship built, and went to Menelaus, but the game crashes every time.  I used a mod to preload the world, and tried it again, but it still crashed.

Here is the crash report:  [https://pastebin.com/HaasQQFR](https://pastebin.com/HaasQQFR)

**Comment by DigitalSketch** [comment]
Update: Saw the Terraqueous mod also throw an error, so removed that mod and it loaded.

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/384

**Comment by mcenderdragon** [comment]
https://github.com/ShetiPhian/Localizations-and-Issues/issues/149

**Comment by mcenderdragon** [comment]
So it should alredy be fixed.

**Comment by DigitalSketch** [comment]
I'm running the latest download.

**Comment by mcenderdragon** [comment]
the version were this is fixed is  terraqueous-1.12.0-1.4.9.jar, but you are running terraqueous-1.12.0-1.4.8.jar (according to your crash report)

**Comment by DigitalSketch** [comment]
Ahh gotcha, yea it was updated after I removed it :)

**Comment by mcenderdragon** [comment]
ok good this isse is fixed.
