### ISSUE TITLE
Odd night sky in Menelaus

### ISSUE THREAD

**Issue by DigitalSketch** [mcenderdragon/Futurepack-API#398]
I have Optifine installed, not sure if that's doing something with it, but the sky has these odd white shapes pointing at my "cross hair":

[https://imgur.com/a/iv7dg](https://imgur.com/a/iv7dg)

**Comment by mcenderdragon** [comment]
ok looks interesting, does this also happen without optifine ?

**Comment by DigitalSketch** [comment]
Yea gave it a shot and still did it.. really weird.  Does do it during the day, but not as much.

**Comment by mcenderdragon** [comment]
This is most likely caused by optifine.

![](https://cdn.discordapp.com/attachments/501723564840321025/517753325274267648/2018-11-26_20.png)

**Comment by mcenderdragon** [comment]
@DigitalSketch 

> Has it worked with any older OptiFie version?
> You can try to disable Fast Render, Shaders, AA and AF.
