### ISSUE TITLE
Drones not putting items in the Drone Station's inventory

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#400]
The Forestmaster drone does not put any materials from cut down trees into the Drone Station's inventory and the Mining Drone does not put any mined blocks into the Drone Station's inventory.

Also, no items are left on the ground, so the blocks/items just disappear.

**Comment by qrss** [comment]
As an additional note, this is only the case in the latest version.

**Comment by mcenderdragon** [comment]
yeah I changed the item transfer system, I knew it would break but in all my test cases it wokred, guess you found the faulty ones ^^

**Comment by mcenderdragon** [comment]
[26.3.120](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.120)

**Comment by qrss** [comment]
Thanks! That fixed it.

I have to say that I am happy that this mod is developed so actively that we get such rapid responses and fixes.

A+ customer service.

**Comment by mcenderdragon** [comment]
this was the 400th issue :tada:
