### ISSUE TITLE
Transport Chipset recipe not working

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#401]
The Transport Chipset recipe (Silicon + Quartzparts + Bow) is not working. The old one with the Pusher does not work either.

The Forge version I am using is 14.23.2.2618.

**Comment by mcenderdragon** [comment]
This should fix this: [26.3.121](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.121)

**Comment by qrss** [comment]
Yup, fixed.

Thanks again.
