### ISSUE TITLE
Can't advance

### ISSUE THREAD

**Issue by DigitalSketch** [mcenderdragon/Futurepack-API#402]
I've been to tyros and gotten the meloglo achievement, and the bio crystals, but can't advance anymore.  I'm not able to scan anything, it all has a question mark on it when I try to scan.

**Comment by mcenderdragon** [comment]
Also the optibench and the neon industrial furnace  ?

**Comment by DigitalSketch** [comment]
Yea I finally figured it out, I researched all that was available, and got stuck, so just commanded in the rest, and they weren't finished yet :)
