### ISSUE TITLE
Duplicating stackable and chargeable items with Research Module - Energy

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#403]
If you charge a stackable item in Research Module - Energy, it duplicates when you sneak+click to get it out after charging.

It does not go into your inventory, but stays in the Research Module, so you can keep sneak clicking until you have a whole stack of that item.

It works with items like Laser Rifles and energy swords and does not work with non-stackable items like Grenade Launchers, Grappling Slimes and batteries.

Note that the Laser Rifle can be put into the charging slot even when it has full charge, while the energy swords can not.

**Comment by mcenderdragon** [comment]
THis should fix it: [26.3.122](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.122)

**Comment by qrss** [comment]
That does seem to fix it.

Thank you for your effort.
