### ISSUE TITLE
Research Module - Crashes Game very Strange

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#404]
When using the Ultimate Chipset + Network Chipset + Transport Chipset combo to pipe experience into the Experience Module, the amount of stored experience can go past the maximum 1500.

**Comment by mcenderdragon** [comment]
404: Issue not found exception

**Comment by qrss** [comment]
You mean you can't replicate it?

Here is an example setup:
![2018-02-24_22 13 06](https://user-images.githubusercontent.com/32312262/36634625-0c965900-19b0-11e8-8458-b7a719320d07.png)
A Neon Furnace piping XP to the right and items to the left.

If needed, I can also make and upload a small example world. What command do I use to give myself all of the research?

**Comment by mcenderdragon** [comment]
No it was a joke 404, is the http error for not found, and this issues is issue #404 :D

**Comment by mcenderdragon** [comment]
Should be fixed: [26.3.126](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.126)

**Comment by qrss** [comment]
Research Module - Experience will no longer store more than the maximum amount of experience, but the game crashed while I was testing this and now keeps crashing with the same error whenever I load the world.

Not sure whether the crash is related to the fix.

Crash log:
[crash-2018-02-24_22.55.03-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/1755231/crash-2018-02-24_22.55.03-server.txt)

**Comment by mcenderdragon** [comment]
Ok this is strange I dont think I am related to this issue but I will check what caused this.

**Comment by mcenderdragon** [comment]
Nope I dont know how this could even happen.

**Comment by qrss** [comment]
I did some more testing and the crash does seem to be connected to the fix somehow.

The crash happens semi-consistently when I'm messing around with the setup I posted before under the following conditions:

1) The Neon Furnace is smelting 
2) The Research Module is full of experience
3) The player is standing nearby and picking up the experience that is spilling out

Under these conditions the game sometimes crashes, but not always. I had a period of almost 5 minutes where I could not reproduce that crash, but sometimes it crashes soon after I put a stack of items into the Neon Furnace to smelt.

When I am not touching that setup, then there are no crashes.

Since it is a ConcurrentModificationException, then one of the affecting factors might be lag (my game performance is not the best). That might make reproducing it more difficult.


I would like to do some additional testing on a clean world, but that is complicated by the fact that research does not carry over. What command should I use to give myself all of the research?

[EDIT] Nevermind, I figured out the commands.

**Comment by qrss** [comment]
Try opening this save and putting a stack of Gold Ore into the Neon Furnace.
[ExperienceCrash.zip](https://github.com/mcenderdragon/Futurepack-API/files/1755483/ExperienceCrash.zip)

For me that crashes the game a lot of the time.

I have also tried spamming Bottles of Enchanting at the Experience Module, but that does not seem to crash the game.

**Comment by mcenderdragon** [comment]
I have to check from wish thread I spawn the XP orbs

**Comment by mcenderdragon** [comment]
I moved the XP spawn to ensure it is the main thread, this version should fix it: [26.3.141](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.141)

**Comment by qrss** [comment]
I tested it and have not had a crash yet, so the issue is potentially solved.

**Comment by mcenderdragon** [comment]
That's great news :)
