### ISSUE TITLE
Client crash java.lang.NoClassDefFoundError: net/minecraft/world/World$2

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#405]
https://gist.github.com/ProsperCraft/d7ec71cd0e1ed87449476b05afeb2a96

Futurepack-1.12.2-26.3.123

**Comment by mcenderdragon** [comment]
As I am only calling func_175698_g (sewtBLockToAir) this issue can not be mine, it is a mssing CLass Excpetion in a Vanilla class, so you should check if you updated your coremods.

> CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
>   FarseekCoreMod (Farseek-1.12-2.2.3.jar)
>   Techguns Core (techguns-1.12.2-2.0.1.1.jar)
>   Plugin (NotEnoughIDs-1.5.4.2.jar)
>   Wizardry Plugin (wizardry-0.7.2.jar)
>   LoadingPlugin (noRecipeBook_v1.1.0formc1.12.2.jar)
>   OpenEyePlugin (OpenEye-1.12.1-0.8.jar)
>   RandomPatches (randompatches-1.12.2-1.0.1.0.jar)
>   ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
>   IELoadingPlugin (ImmersiveEngineering-0.12-77-core.jar)
>   Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
>   ForgelinPlugin (Forgelin-1.6.0.jar)
>   LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
>   TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
>   Born in a Barn (Born In A Barn V1.8-1.12-1.0.jar)
>   LibrarianLib Plugin (librarianlib-1.12.2-4.7.jar)
>   LoadingPlugin (NoNausea-MC1.12-1.0.jar)
>   CoreModLoader (applied-llamagistics-1.12.1-rv5-beta-10.jar)
> BCModPlugin (backpacks 1.12.2 - 3.4.3.jar)
