### ISSUE TITLE
Super Cables also transport Support and Network signals

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#406]
Even though Super Cables do not visibly connect to Support devices or say that they transport Support, they can still transport Support points.

They can also transfer Experience over the Network. I have not tested whether it works for connecting research devices.

They do not transfer redstone signals.

**Comment by mcenderdragon** [comment]
Should be solved: [26.3.142](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.142)

**Comment by qrss** [comment]
It indeed seems fixed.

Thanks for the hard work!  👍
