### ISSUE TITLE
FP calling things off the main thread causing issues?

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#407]
https://github.com/SpongePowered/SpongeForge/issues/2024

**Comment by mcenderdragon** [comment]
Why does sponge always break?!

**Comment by ProsperCraft** [comment]
It broke before with generic CME messages but bit we had no idea where to report them until  Sponge our a label in them.

**Comment by mcenderdragon** [comment]
It broke with CME if you tried to jump with your Chip ?

**Comment by ProsperCraft** [comment]
I am not 100% I can make that association, which is why I may not have reported it, here are the crashes without sponge.

https://gist.github.com/ProsperCraft/3a4b827aea48c835514afb4fb18ce488
https://gist.github.com/ProsperCraft/2906869164d7d4df79cb21382b2b4a5b
https://gist.github.com/ProsperCraft/0239cfb63aee6f92449fd19f8bde9d8d
https://gist.github.com/ProsperCraft/f9d5b0a37daad040e41fc580ba3fd085
https://gist.github.com/ProsperCraft/463fe3f7059614020690f0a76f8a486c
https://gist.github.com/ProsperCraft/1085ca7ba96bc50b56eec8c252d08b03
https://gist.github.com/ProsperCraft/11f106c4f414043370e53a416c647a23
https://gist.github.com/ProsperCraft/a5c4a6a49e95301afa45fcc6c597707b
https://gist.github.com/ProsperCraft/ab81c8fcd70c2820725a0ff1d20dc970
https://gist.github.com/ProsperCraft/f3610beb482f7fff1c93c45c39b6dff6
https://gist.github.com/ProsperCraft/b2ca7b2cbb4c9cb73ebf0004f3553f03

**Comment by mcenderdragon** [comment]
the CME with the Entity Tracker: #404 
the CME with the PlayerChunkMap, hmm maybe...

**Comment by mcenderdragon** [comment]
Ok the sponge crash when teleporting the ship should be fixed: [36.3.140](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.140)

**Comment by ProsperCraft** [comment]
Fix confirmed, push :)

Teleported 5 times.

**Comment by mcenderdragon** [comment]
\o/
