### ISSUE TITLE
Can't Repair Composit armour

### ISSUE THREAD

**Issue by litjohn50** [mcenderdragon/Futurepack-API#408]
You get the armor drops from the emperor

https://gyazo.com/6608bcfdbc5273b96a591ea133b3a32f

but won't repair even with nanostructure repair unit.

**Comment by mcenderdragon** [comment]
As this is unimplemented/WIP content, this can take a while... But thanks for reporting

**Comment by mcenderdragon** [comment]
This is fixed by 26.3.203.

https://minecraft.curseforge.com/projects/futurepack/files/2552517
