### ISSUE TITLE
Feature Request - Please add a config to disable spawner chest

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#409]
I don't want spawners moved on my server, so I have blocks that move them disabled, would you please add a config option to disable the spawner chest, or its ability to move spawners?

**Comment by mcenderdragon** [comment]
Ok I added the config, but a test build will take time, because we currently rewrite alot of our researches to prevent the "EScanner recipes differenrs from aktual recipe" issue.

**Comment by mcenderdragon** [comment]
In the mean time you can try to use crafttweaker to remove the assembly recipe (if that is possible)

**Comment by ProsperCraft** [comment]
We tried but it wouldn't cooperate, I think Rev said it had something to do with the fact that it wasn't a crafting table recipe or something.

**Comment by mcenderdragon** [comment]
well we have crafttwekaer support so it should be possible.

**Comment by Reveter** [comment]
I tried to remove the spawner chest with crafttweaker, but with this script it is still craftable.

```
import crafttweaker.item.IItemStack;

val array1 = [<minecraft:chest>] as IItemStack[];

mods.futurepack.assembly.remove(array1);
```

I also tried the other two items as the "input item", and it still didn't work.

**Comment by mcenderdragon** [comment]
try "minecraft:slime_ball", minecraft:chest and fp:chip, meta 0. The order is important.

**Comment by Reveter** [comment]
I changed it, but it still doesn't work.
```
import crafttweaker.item.IItemStack;

val array1 = [<minecraft:slime_ball>, <minecraft:chest>, <fp:chip:0>] as IItemStack[];

mods.futurepack.assembly.remove(array1);
```

**Comment by mcenderdragon** [comment]
does the log print something ? because if the recipe exist in will get deleted, how to you check if it does work ?

**Comment by Reveter** [comment]
I don't see anything in the logs and crafttweaker doesn't report any syntax errors. I've been testing by just logging into a single player world and trying the recipe again.

**Comment by mcenderdragon** [comment]
hmm maybe try to add to the slime_ball and chest a :0, I dont know what the default meta from crafttweaker is.

**Comment by Reveter** [comment]
I believe the default meta from crafttweaker is 0, but even changing all the items to have :0 didn't make a difference.

**Comment by mcenderdragon** [comment]
Hmm

**Comment by mcenderdragon** [comment]
Ok it is now stable enough for you to test (the research rewrite) [26.3.137](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.137)
