### ISSUE TITLE
[Waiting for Forge PR] FP Event Subscriber causing lag - 

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#410]
![futurepackeventsubscriber](https://user-images.githubusercontent.com/4427684/36692583-c1458772-1af5-11e8-9b81-3d2621487338.png)

Ticking at 25k

**Comment by mcenderdragon** [comment]
Is there a way to display wish methods ?

**Comment by LeonPhilips** [comment]
No, it currently only tracks the event subscribed, in this case: `net.minecraftforge.fml.common.gameevent.TickEvent.WorldTickEvent`.

Look for a class that has:
```
@SubscribeEvent
public void something(net.minecraftforge.fml.common.gameevent.TickEvent.WorldTickEvent event){
    //Your code here
}
```

**Comment by ProsperCraft** [comment]
^Laggoggles mod author

**Comment by mcenderdragon** [comment]
@TerminatorNL well I have anout 4 of them thats why I asked ^^

**Comment by mcenderdragon** [comment]
@ProsperCraft are you using lasers/rocket launcher with Transport chips?

**Comment by mcenderdragon** [comment]
Or have you many living Entitys ?

**Comment by mcenderdragon** [comment]
I think I know source of this lag, I have to check every tick if the PotionEffects from entities have changed so with alot of entities this will take alot of time, as I am iterating over the complete EntityList. This will get fixed as soon as https://github.com/MinecraftForge/MinecraftForge/pull/4614 gets merged.

**Comment by LeonPhilips** [comment]
I'm glad you found it! :+1: :+1:

**Comment by mcenderdragon** [comment]
@ProsperCraft out of curiosity, what does the current timings show (I optimised since February alot)

**Comment by mcenderdragon** [comment]
It got merged, this means I can finally fix this.
