### ISSUE TITLE
Worldgen issue- tunnels with ladders going to above bedrock in aqua cavern

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#411]
The aqua cavern from Caverns 2 mod has bedrock below and above it like the nether, a player found the bottom of the 2 ladder dungeon and followed it from Y 10 to Y 256 above bedrock.

![2018-02-27_00 50 36](https://user-images.githubusercontent.com/4427684/36716979-7fab0cb0-1b59-11e8-81ed-4bf16c81b481.png)
![2018-02-27_00 50 38](https://user-images.githubusercontent.com/4427684/36716982-8197fbb4-1b59-11e8-859c-788e31d1748a.png)
![2018-02-27_00 48 20](https://user-images.githubusercontent.com/4427684/36716986-835c6e12-1b59-11e8-82a7-d5ffcea924d8.png)

**Comment by mcenderdragon** [comment]
Hmm, that should not happen ^^, I wonder why this has not happend in the nether yet...

**Comment by ProsperCraft** [comment]
Is it because this dim is full of water?

**Comment by mcenderdragon** [comment]
could be yes, as I am searching for air to end the tubes.

**Comment by ProsperCraft** [comment]
If bedrock..then end currentpos-10?

**Comment by mcenderdragon** [comment]
yep the current solution looks pretty much like that xD

**Comment by mcenderdragon** [comment]
This should fix it: [26.3.137](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.137)
