### ISSUE TITLE
External Processing Unit recipe incorrectly requires dual machine board

### ISSUE THREAD

**Issue by Reveter** [mcenderdragon/Futurepack-API#415]
The crafting recipe for the external processing unit requires a dual machine board, even though the machine has a single core. Additionally the components used to craft the dual machine board do NOT appear in the machine once crafted. Instead it always has the same core, ram, and chipset.

**Comment by mcenderdragon** [comment]
This version should fix it: [26.3.164](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.164)
