### ISSUE TITLE
Industrial furnace poor performance in Futurepack-1.12.2-26.3.123

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#418]
A single furnace was ticking at 6656

![2018-03-06_07 01 49](https://user-images.githubusercontent.com/4427684/37036492-149292c2-210d-11e8-9099-26036e62a4ad.png)
![2018-03-06_07 05 20](https://user-images.githubusercontent.com/4427684/37036512-249d515c-210d-11e8-8b1a-9bd6fbdc555e.png)
![2018-03-06_07 05 08](https://user-images.githubusercontent.com/4427684/37036520-26e45456-210d-11e8-8ca1-3c5f9dde9c4a.png)
![2018-03-06_07 05 10](https://user-images.githubusercontent.com/4427684/37036524-2863a1c4-210d-11e8-85f5-032dd51766fd.png)
![2018-03-06_07 05 12](https://user-images.githubusercontent.com/4427684/37036526-2a15c1d2-210d-11e8-9012-64815fb0a529.png)
![2018-03-06_07 08 36](https://user-images.githubusercontent.com/4427684/37036556-42736bc6-210d-11e8-8c9c-9e8a5c3a8ea4.png)
![2018-03-06_07 08 42](https://user-images.githubusercontent.com/4427684/37036558-443968ca-210d-11e8-9ebe-ae85fb28ed2b.png)
![2018-03-06_07 08 48](https://user-images.githubusercontent.com/4427684/37036560-467735cc-210d-11e8-9fd8-2d83fb9a48ca.png)

Here is a timings report.
https://timings.aikar.co/?id=8508745ac9ac43468fe96fb1cb68a1d2

Another laggoggles profile - 

![2018-03-06_07 11 10](https://user-images.githubusercontent.com/4427684/37036692-a8f68ffe-210d-11e8-8110-05857706cd39.png)

Here is a sampler report to open in VisualVM
[furnace.zip](https://github.com/mcenderdragon/Futurepack-API/files/1785305/furnace.zip)

Here is a warmroast report-
[Warmroast.zip](https://github.com/mcenderdragon/Futurepack-API/files/1785319/Warmroast.zip)

**Comment by mcenderdragon** [comment]
I am not sure if I can do much about this, as this furnace has a lot of recipes and needs to check for them.

**Comment by ProsperCraft** [comment]
What if you check less frequently?  That one furnace is ticking at 7066 right now, and it's not being used.

**Comment by ProsperCraft** [comment]
Can you do something like - is there work? no...idle 15 seconds.

**Comment by mcenderdragon** [comment]
well you decide through the RAM speed, and if there are items inside it will check if a recipe is working. I have tested some stuff but I dont know if they had a large impact.

**Comment by mcenderdragon** [comment]
I made a few improves, please test if they had a large impact for your setup: [26.3.155](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.155)

**Comment by mcenderdragon** [comment]
Could you check if the industrial furnace has also this problem ?

**Comment by ProsperCraft** [comment]
You totally fixed it!

I cloned the server, logged in, verified it was still acting badly, then upgraded to this new version, and this is the result.
![2018-03-06_11 34 12](https://user-images.githubusercontent.com/4427684/37051078-c8693e70-2132-11e8-91e9-119ee2959ac1.png)
![2018-03-06_11 34 18](https://user-images.githubusercontent.com/4427684/37051082-c9ed6460-2132-11e8-8d66-1444ce3839d6.png)

**Comment by ProsperCraft** [comment]
Please push so we can enjoy it :)

**Comment by mcenderdragon** [comment]
well a better term would be hidden, I let them wait a second if no recipes were found, and I improved the recipe searching, (I used some bad vanilla methods)
