### ISSUE TITLE
[1.10.2] Futurepack server crash - powerThisPipe

### ISSUE THREAD

**Issue by r3volut1on** [mcenderdragon/Futurepack-API#419]
Dedicated server crashes after starting Chunk pregenerator after adding RealisticTerrainGeneration and BiomeTweaker.

Crash report: https://pastebin.com/nfX7VdaT

**Comment by mcenderdragon** [comment]
This crash can not happen with the code I have written, so propaply one of the coremods is doing this. (A line above I make a !=null check...)
