### ISSUE TITLE
Combination Research no longer completed

### ISSUE THREAD

**Issue by ghost** [mcenderdragon/Futurepack-API#420]
Just upgraded the server from .118 to .159 this afternoon...  On the chipset page, the combination research used to be completed and readable.  I thought it was a new research item... but after looking at it a bit, it was where it used to tell me to add an ultimate, transport, and network chipset to get XP moved to the researcher.

**Comment by ghost** [comment]
After completing the research for the flux transformer, I got this research came back... so it seems like it might only be an issue when upgrading from one version to another...

**Comment by mcenderdragon** [comment]
Yeah, I renamed this research so once you somehow update the researches it will auto activate again.
