### ISSUE TITLE
FP possess the players body and makes them say things in chat.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#423]
We are running forge-1.12.2-14.23.2.2625-universal

![2018-03-13_16 15 42](https://user-images.githubusercontent.com/4427684/37372859-ec14e836-26d9-11e8-9749-9f2891b069fd.png)
![2018-03-13_12 09 10](https://user-images.githubusercontent.com/4427684/37372867-f503fb80-26d9-11e8-8db0-bc01ed9339a0.png)

**Comment by mcenderdragon** [comment]
It seems like the mod wish adds the tags adds them even when just sending you a messeg only client side. see #385

**Comment by mcenderdragon** [comment]
wow they changed the mcp mappings, sendTextMessage() let the player send a chat message to the server but sendMessage() sends a message to you the player and only you will see that -.-

**Comment by mcenderdragon** [comment]
This should send in to you and not to the server... [26.3.165](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.165)

**Comment by ProsperCraft** [comment]
![2018-03-17_22 37 00](https://user-images.githubusercontent.com/4427684/37562667-cb0aeb56-2a33-11e8-9b5a-1b42ca19b088.png)

We have java 8 it should not be warning about it.

**Comment by mcenderdragon** [comment]
I think I am not the only modder who is having problems with this ^^ but no,  as far as I know this is not me ^^
