### ISSUE TITLE
Screnching a monocart deletes everything the monocart was carrying

### ISSUE THREAD

**Issue by 1skandar** [mcenderdragon/Futurepack-API#424]
Was playing around with the monorail system last night (which is wicked awesome, btw). Didn't have a monorail charger yet, so was using batteries to charge the monocart. Used to scrench to pick up the monocart and the 'cart popped off the monorail but the batteries vanished. Later on was playing around with cargo. Screnched a 'cart carrying cobble, 'cart popped off but the cobble and batteries vanished.

(latest Curse version, 26.3.159)

**Comment by mcenderdragon** [comment]
This should fix it: [26.3.174](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.174)

**Comment by 1skandar** [comment]
Yup, that fixed it. A minor bug, however, in its place.
![2018-03-18_12 46 17](https://user-images.githubusercontent.com/4127779/37568362-93f7cc20-2aaa-11e8-8443-f80f59ba7537.png)

![2018-03-18_12 46 24](https://user-images.githubusercontent.com/4127779/37568372-a75da046-2aaa-11e8-88f0-9b5c83fb55a8.png)

When screnched and the cart ends up in your inventory it is temporarily invisible. Opening and closing your inventory makes it reappear or clicking on where it is supposed to be. As I said, it is a minor bug, visual only, so if it is to big a deal to fix leaving it shouldn't be a priority

**Comment by mcenderdragon** [comment]
I spawn the item in the world, so I am not sure if this is caused by another mod.

**Comment by 1skandar** [comment]
Yeah, it really is a minor thing. Not worth hunting down if it isn't immediately visible why.
