### ISSUE TITLE
[1.10.2] Researches don't need NE and Support

### ISSUE THREAD

**Issue by EngineerXL** [mcenderdragon/Futurepack-API#425]
Reseacher drains NE from air, Same with Support
![Research](https://user-images.githubusercontent.com/37447286/37526619-e99121a6-2940-11e8-937d-972cf0f9c758.png)
![Researcher doesn't have any NE sources](https://user-images.githubusercontent.com/37447286/37526661-03e2e954-2941-11e8-90fc-0b7c74bacb6b.png)
![???](https://user-images.githubusercontent.com/37447286/37526712-2a97319a-2941-11e8-8288-48112f12a818.png)
![Full NE](https://user-images.githubusercontent.com/37447286/37526730-36b0d918-2941-11e8-93b9-d0ce3b24fd98.png)

**Comment by mcenderdragon** [comment]
Can you provide all logs ?

**Comment by EngineerXL** [comment]
Server logs?

**Comment by mcenderdragon** [comment]
fml-client-latest.log, fml-junk-earlystartup.log, fml-server-latest.log, FP-latest.log, latest.log. And if possible press F3 + C for more then 10 seconds to make a crash report.

**Comment by EngineerXL** [comment]
If i'm playing on server, should I post fml-server-latest.log?

**Comment by mcenderdragon** [comment]
post everything whats available in the logs subfolder. If you are playingon the server then I need the logs from the server and the client.

**Comment by EngineerXL** [comment]
Server logs
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1819658/FP-Latest.log)
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1819659/latest.log)
[fml-junk-earlystartup.log](https://github.com/mcenderdragon/Futurepack-API/files/1819660/fml-junk-earlystartup.log)
[fml-server-latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1819661/fml-server-latest.log)

**Comment by EngineerXL** [comment]
Client logs
[fml-junk-earlystartup.log](https://github.com/mcenderdragon/Futurepack-API/files/1819667/fml-junk-earlystartup.log)
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1819668/FP-Latest.log)
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1819669/latest.log)
[fml-client-latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1819670/fml-client-latest.log)

**Comment by mcenderdragon** [comment]
Does this alway happen or only if all side are air? Was to researcher at any time connected to a T1 modul ? Does this also happen with only Futurepack installed.

**Comment by EngineerXL** [comment]
It happens also if I connect empty Neon Generator, also if I simply place researcher. I haven't crafted T1 module yet. I haven't checked it with only FuturePack installed

**Comment by EngineerXL** [comment]
Should I check this bug with only FP installed?

**Comment by mcenderdragon** [comment]
yes please check this.

**Comment by EngineerXL** [comment]
Yep. I got this issue with mods: JEI, FuturePack, FoamFix

**Comment by EngineerXL** [comment]
The same without JEI and FoamFix. Mods folder have ONLY FuturePack

**Comment by mcenderdragon** [comment]
can you scan the scanner with the EScanner while sneeking and send then the client log again ?

**Comment by EngineerXL** [comment]
Client logs.
I scanned Researcher two times. First I scanned idle machine. Second I scanned researcher draining NE from air.
[fml-junk-earlystartup.log](https://github.com/mcenderdragon/Futurepack-API/files/1820610/fml-junk-earlystartup.log)
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1820612/latest.log)
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1820653/FP-Latest.log)
[fml-client-latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1820659/fml-client-latest.log)

**Comment by mcenderdragon** [comment]
Can you scan a new placed researcher and send me the FP-latest.log ? Currently somehow a huge amount of neon is already stored in the researcher...

**Comment by EngineerXL** [comment]
Done. First scan - idle. Second and third - while researching
[fml-junk-earlystartup.log](https://github.com/mcenderdragon/Futurepack-API/files/1821700/fml-junk-earlystartup.log)
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1821701/FP-Latest.log)
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1821702/latest.log)
[fml-client-latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1821703/fml-client-latest.log)

**Comment by mcenderdragon** [comment]
Have you pressed the red X ?

**Comment by EngineerXL** [comment]
I placed Researcher, put all items -> Scan 1 -> Start Research scan 2 and 3

**Comment by EngineerXL** [comment]
Will it be fixed soon?

**Comment by mcenderdragon** [comment]
As I have no idea what is causing this, this will propably take a while...

**Comment by EngineerXL** [comment]
I'm not 100% sure, that i hadn't clicked red X. Should i scan researcher again?
