### ISSUE TITLE
Forestmaster  magnet duration not long enough to pull in all items.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#427]
![2018-03-18_19 27 53](https://user-images.githubusercontent.com/4427684/37573961-ac16898a-2ae2-11e8-93e8-f2c7e3524545.png)

He leaves a lot of items on the ground, if the magnet duration was doubled, I think he would get them all.

**Comment by mcenderdragon** [comment]
The problem is, I create a list of all items when the tree is felled. So if an item is droped after the felling the drone does not know about it. The complete magnet behauvier was to improve the yield ^^. I will think about something to improve this.

**Comment by mcenderdragon** [comment]
Other Problem: forstmaster inserts saplings into already full sapling holders. THis results in droping the item into the world.
