### ISSUE TITLE
Dungeon Keys

### ISSUE THREAD

**Issue by phrostt** [mcenderdragon/Futurepack-API#430]
This is not as much an issue as a question. I finally advanced far enough to craft dungeon key 1. It was my understanding that using it I can get past the first force field, but I cant seem to do that. What is the dungeon key 1 for and how do I use it?

**Comment by mcenderdragon** [comment]
You need the first key in your hand and then you can go thourgh the force field. (THis is only possible if the force field needs key 1 and not key 2 or any other upper key). A blueprint to the key you need is usualy in the wardrobes nearby.

**Comment by phrostt** [comment]
Thank you for clarifying that, I will try to find forcefield 1 and go through it with m key, see if it works.

**Comment by mcenderdragon** [comment]
Not every dungeon has forcefield lvl 1, some start with lvl 2 or higher.

**Comment by phrostt** [comment]
You know adding that explanation to the e-scanner could be really helpful. There is so little information available about this amazing mod on the web, e-scanner seems to be the best source of information and sometimes its not very descriptive.

Perhaps add a few lines explaining how the keys work.a

**Comment by mcenderdragon** [comment]
Yeah we should do that ^^. It is hard for us to know if we said about something enough since we created it. Thats why your feedback is very important.

**Comment by phrostt** [comment]
Also another quest. I am completely stuck. All my research items require glowtite and I have no way of getting it. Cant unlock any new research, scanned everything I could, and cant get glowtite, what do I do? I read that you get glowtite on menelaus, but how do I get to menelaus?

**Comment by mcenderdragon** [comment]
have you already researched the board computer ?

**Comment by thePalindrome** [comment]
The drop rate seems to be a bit off (I searched six dungeons, got 2 level 3 blueprints, and 4 level 2 blueprints)

Considering the descriptions for the keys, maybe allow higher tier keys to open lower tier forcefields?

UPDATE: The seventh dungeon had a level one key. At this point, I had already made the level two key, so it feels a bit silly that I have to make the lower one

**Comment by mcenderdragon** [comment]
Well thats random, it gets more equal for a large amount of iterations. But we can look into it.

**Comment by mcenderdragon** [comment]
the dungeons are now alot larger and always start with ther first lvl.
