### ISSUE TITLE
Is this a problem?[FP-ChunkScanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at futurepack.common.FPChunkScanner.progressAll(FPChunkScanner.java:210)

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#431]
https://gist.github.com/ProsperCraft/df0a991a6021c18fafa710479a758352

I am getting a lot of these while pregenning our new world.

**Comment by mcenderdragon** [comment]
yes, yes it is..

**Comment by mcenderdragon** [comment]
Somehow the LinkedList completly broke, or somemod is ASM my classes. I do a check in the line above so there is in theorie not way the list is not em pty but the first element is null...

**Comment by mcenderdragon** [comment]
Could yu check the log if it still is sending error messages: [26.3.183](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.183)

SOmething like `"ChunkScanner: Lost 4 chunks due to broken LinkedList"`

**Comment by ProsperCraft** [comment]
I wiped my pregenning world, put this version in, and starting pregen over, will inform.

**Comment by ProsperCraft** [comment]
It looks cleaner, I did happen to look when it said this though.

https://gist.github.com/ProsperCraft/1240e0489a466cbcab58885135d46ebf

**Comment by ProsperCraft** [comment]
We did have one of those you were looking for 
https://gist.github.com/ProsperCraft/77134392e3e05ddbbd8c7a0a67ab8caa

**Comment by ProsperCraft** [comment]
Also this - 
https://gist.github.com/ProsperCraft/8644390f9f3367d30458d57002afd333

**Comment by mcenderdragon** [comment]
[26.3.184](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.184)

**Comment by mcenderdragon** [comment]
[26.3.185](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.185 )

**Comment by mcenderdragon** [comment]
Please test if it still works: [26.3.186](redsnake-games.de/Downloads/fp/fp.php?version=26.3.186)
