### ISSUE TITLE
 java.lang.NoSuchMethodError: futurepack.common.research.ResearchLoader.getLocalisated

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#432]
https://gist.github.com/ProsperCraft/aa2b1f20f8f436d403742e4fdf6c010b

Seeing this on sever boot on my pregen server with Futurepack-1.12.2-26.3.183.jar

**Comment by mcenderdragon** [comment]
[26.3.184](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.184)
