### ISSUE TITLE
Being able to define "Home" Dimension?

### ISSUE THREAD

**Issue by davqvist** [mcenderdragon/Futurepack-API#433]
Hi, I am working on a modpack since several months with Futurepack being used in the end game. I am close to the finish but now have a huge game breaker that I just noticed. The Board Computer always links per default to the overworld (Dim 0) as default "Home Dimension". The issue is that the player isn't supposed to reach dimension 0 as the whole modpack plays in different dimensions. I wonder if you could add in the configs being able to define the dimension id for the home dimension. This would be so awesome and appreciated.

MC 1.12.2

**Comment by mcenderdragon** [comment]
Therefore the Home Button is there. The home button is set to the dimensions were thia spaceship was first build.

**Comment by davqvist** [comment]
I am confused the Home Button leads me to overworld (Dim 0) every time.

**Comment by mcenderdragon** [comment]
were did you build your spaceship and did you break the boardcomputer once ? Or has your ship more then one boarcomputer ?

**Comment by davqvist** [comment]
It is Dim 70 and not that I remember.

**Comment by davqvist** [comment]
So I created a new world, tp'd to Dim 70 where you build the Rocket, unlocked all research per command, built a rocket, selected the first of the 3 buttons in the Board Computer and it teleported me to the overworld (dim 0). This is a big gamebreaker unfortunately for me. Are you willing to add a config to define a Home Dimension?

**Comment by mcenderdragon** [comment]
As we are not talking about the same thing let me explain some its...
![boardcomputer](https://user-images.githubusercontent.com/6342933/38353548-0a4cb66e-38b7-11e8-8c8f-9ce22d23b4eb.JPG)
The red cycrle is always dim 0 as its the vanilla world. This can hardly change since you are supposed to always come back to earth.
the black cycle is your current dimension
the green one is the dimension from the coordinate slot
and the blue cycrle is the back to home dimension button.

**Comment by mcenderdragon** [comment]
You however need the first button to not be set to dim 0 but to a custom one correct ?

**Comment by davqvist** [comment]
Sorry for being ambiguous. Yes, I want the red circled button to not point to dim 0 as the player is not supposed to go there. Is there a possibility to add a config to disable that button or anything? I just need the player not reach dim 0.

**Comment by mcenderdragon** [comment]
Just out of curiosity how is the nether portal handeled ? And yes a confic for the overworld should be possible.

**Comment by davqvist** [comment]
The Nether is disabled. And I would love to have such a config option. Thanks in advance.

**Comment by mcenderdragon** [comment]
This should fix it: [26.3.191](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.191)

**Comment by davqvist** [comment]
The link doesn't work. I wait for the release.

**Comment by mcenderdragon** [comment]
Sorry wrong link: [26.3.192](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.192)

**Comment by davqvist** [comment]
Tried with 192, set I:overworld_dimension=70 and did the same thing again I wrote above. Meaning:

I created a new world, tp'd to Dim 70 where you build the Rocket, unlocked all research per command, built a rocket, selected the first of the 3 buttons in the Board Computer and it teleported me to the overworld (dim 0).

Am I missing something?

**Comment by mcenderdragon** [comment]
check the logs if something like "Overworld dimension 70 was not found" occured.

**Comment by davqvist** [comment]
Indeed. 

> [15:48:3][Client thread] Overworld dimension 70 was not found, setting overworldDimension back 0

How to prevent that?

**Comment by mcenderdragon** [comment]
dimension 70 is not defined. I am checking it with DimensionManager.isDimensionRegistered

**Comment by davqvist** [comment]
Might that be a load order issue? Can you check at a later state? It is a custom dimension with the mod JED. Should I ask the JED dev why that might be the case?

**Comment by mcenderdragon** [comment]
yeah please ask him.

EDIT: I search for them in the FMLInit, as in FMLPreINit dimensions should get registered.

**Comment by davqvist** [comment]
I just realized it is not JED, I use Advanced Rocketry to generate that dimension. I will ask that dev.

**Comment by davqvist** [comment]
I have not got confirmation by the dev, but I looked at the code and it seems AdvRocketry registers dimensions on server start / world load and not on Minecraft / Pack Load which would explain why the dimension is not registered when you check the configs. How can we deal with that?

**Comment by davqvist** [comment]
Can you maybe check if the Dimension is registered on accessing the GUI or even pressing the button instead of doing it on load?

**Comment by mcenderdragon** [comment]
If I do this it will mostlikely crash if the dimension is not available. I can change it so it will print the warning on startup if the dimension was not there so it is up to the player if it crashes or not.

**Comment by davqvist** [comment]
I meant
`onButtonClick(){
  if( DimensionManager.isDimensionRegistered( configDimId ) ){
   teleportTo( configDimId );
  }
} `

in pseudocode which would not crash, but yeah I would appreciate just printing out a warning. If someone changes this config they hopefully know what they are doing anyway.

**Comment by mcenderdragon** [comment]
so here it should work : [26.3.199](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.199)

**Comment by davqvist** [comment]
Thanks very much, working now
