### ISSUE TITLE
Console is getting spammed with millions of these lines after update, is it FP?

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#435]
https://gist.github.com/ProsperCraft/a5a293d67ae1b89eb94f4e1b8990bf10

**Comment by mcenderdragon** [comment]
As far as I know no. Is this always happening or only if certain players are in an area ?

**Comment by ProsperCraft** [comment]
Constant stream, I will experiment to see who it is

**Comment by ProsperCraft** [comment]
Not Futurepack, got it to happen without it, I am on the hunt!
