### ISSUE TITLE
[Help Wanted] Client Crash - Updating Screen Events Code Issues - 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mcenderdragon/Futurepack-API#437]
https://gist.github.com/P3rf3ctXZer0/36da9a8fe1346a7aeec49c2ba8f94e60

Thank Lexmanos for helping track down the code issues.

**Comment by P3rf3ctXZer0** [comment]
This crash only occurs when future-pack is present so it is caused by the mod. Please look at screen update code for crash fix.

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/252

**Comment by mcenderdragon** [comment]
I am absoltily clueless why this happens because with only Futurepack installed this does not occur, thus I am not able to repdroduce this. I am also using the same code JEI is using for their controls so I have no idea how to fix this.

**Comment by mcenderdragon** [comment]
YOu can try this version fi it changes anything... [26.3.189](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.189)

**Comment by P3rf3ctXZer0** [comment]
Oh **** sorry @mcenderdragon  http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.189 did fix it. I thought I responded my bad I have been moving for about 2 months and stress started hitting me hard.

**Comment by mcenderdragon** [comment]
No worries, I am glad if it worked :) Also happy moving. (Hopefully the stress settles down soon)
