### ISSUE TITLE
Absorption Laser has no description in entry

### ISSUE THREAD

**Issue by davqvist** [mcenderdragon/Futurepack-API#439]
'space.turret.absorb' not found, report this to the mod author

FP 26.3.199
Forge 2654
MC 1.12.2

**Comment by davqvist** [comment]
Astronomy 1 as well I just noticed.

**Comment by davqvist** [comment]
Annd... bergbau2 is affected as well

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/272
