### ISSUE TITLE
[Sponge] Deep core Miner chunkloading - Feature request - config option.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#441]
When lagbusting our server I found that a massive base is loaded and the player has been offline for two days.

Sampler gave me this information- 

![2018-04-22_13 26 16](https://user-images.githubusercontent.com/4427684/39099118-fb31aa3a-4631-11e8-936c-c6232ac8cc37.png)

In asking in the Teamspeak channel I was told it would be the deep core miner.

Would you please add a config option to disable chunkloading entirely from FP?  from the deep core miner?

We have our own chunkloading.  On a large multiplayer sever having everyone's base loaded when they are not online kills the server.

**Comment by mcenderdragon** [comment]
The DeepCore has not the ability to load chunks, so there is something else.

**Comment by mcenderdragon** [comment]
And forge has a config for this matter.

**Comment by ProsperCraft** [comment]
What block is loading chunks?

**Comment by mcenderdragon** [comment]
Claimes and a working Miner does.

**Comment by ProsperCraft** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2119

server crash on setting to 0 in forge config.

**Comment by mcenderdragon** [comment]
At this point I would suggest you to not use sponge as it is not worth it... (in my opinion)

**Comment by ProsperCraft** [comment]
The fact that we can't disable chunkloading because it breaks your mod is not sponge's fault.

Please add a config to stop chunkloading from your mod blocks like the Claim and Miner.

**Comment by mcenderdragon** [comment]
the CocurentModificationException is was caused by sponge, the spaceships not fully working is something else, as this is done to prevent some other bugs from vanilla (cant hotload dimension exception)

**Comment by mcenderdragon** [comment]
I added a config to disable chunk loading for claimes and miners: [26.3.211](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.211)
