### ISSUE TITLE
Researching issue's

### ISSUE THREAD

**Issue by Shruikahn** [mcenderdragon/Futurepack-API#442]
Okay so Early on I researched things that just required one item of researching items. when I finally branched into two items needed for researching, on two separate items I was researching.
The first one I had another player bring their table over and had me place it down and it worked fine and was able to get passed the research where it required 8 redstone and 2 pipe's. 

The second one was after he took his item back and I made a new research table and still the same issue where it wanted 8 redstone and 2 cable's.

before the server reboot, it wasn't working. and now the server has restarted now mine works fine..

still might want to look into this and see if you can reproduce the issue

**Comment by mcenderdragon** [comment]
what version did youbuse ? (If pre 26.3.203, then it should be fixed)

**Comment by MrTubzy456** [comment]
Currently having this issue on 26.3.210. I've had it happen on two different items that I've tried researching.

Forge version 14.23.4.2707
Modpack: Exoria

**Comment by mcenderdragon** [comment]
@MrTubzy456  are you in single player or on a server ?

**Comment by MrTubzy456** [comment]
@mcenderdragon on a server. I'm an admin so I tried spawning in another research table to try on another table and still had the same issue. I tried with all three research tables and had the same issue.

**Comment by mcenderdragon** [comment]
do you use sponge or a forge server?

**Comment by MrTubzy456** [comment]
It's a forge server.

**Comment by mcenderdragon** [comment]
Can you send a screenshot of the researcher?

**Comment by MrTubzy456** [comment]
I think I've figured it out. I needed the "Researcher - Energy" to complete the research. See, I didn't know that because I had jumped over that part somehow. My friend gave me an extra one of his and I completed it that way.
