### ISSUE TITLE
[feature request]  1.12 add config option to blacklist dimensions for ore spawn

### ISSUE THREAD

**Issue by Zygus42** [mcenderdragon/Futurepack-API#443]
You already have a dimension blacklist for the tech dungeons - would love to also see a dimension blacklist for the ore spawn.  I can turn it all off and have some other mod spawn it in where I want, but would be a lot neater if it was already built in.

**Comment by mcenderdragon** [comment]
Is it a possibility to not have minecraft:stone in the dimension ?

**Comment by Zygus42** [comment]
Think that would cause other issues.  

The  modpack I'm building has 
1) a fantasy/magic dimension (Twilight Forest), which will have ores appropriate up to just short of iron, 
2) the Overworld which will be medieval/renaissance with a bit of magic, and the ores there will stop short of the ores needed for the higher end tech mods (uranium, osmium, magnetite, etc), 
3) a modern/high tech dimension (Lost Worlds mod), which will have all the higher tech ores, and
4) a laid back, pretty tropical world (Tropicraft) - just because it was so pretty, I couldn't resist adding it 😄 

It could be argued that Magnetite is just iron, and I could have it in the overworld and Lost worlds dimension, but really want to keep it out of Twilight Forest.  

I'm probably going to be using OreSpawn to control those few ores that I can't manage any other way, as it allows setting multiple instances of the same ore with different ore spawns and dimension settings, but I've just found in the past that it's better if a mod that adds spawn manages it's own spawn rather than another mod messing with it as it causes less issues in the long term.

But, if it's too hard, that's no problem.  I have a workaround in OreSpawn and Futurepack is a fantastic mod any which way - you've provided many hours of amusement for many people.

**Comment by mcenderdragon** [comment]
I added a black list for the ores: [26.3.209](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.209)

**Comment by Zygus42** [comment]
Wow, awesome and quick too.

Tested and works like a charm.
