### ISSUE TITLE
1.12 config dimension blacklist not working

### ISSUE THREAD

**Issue by Zygus42** [mcenderdragon/Futurepack-API#444]
Either the blacklist to stop tech dungeons spawning is not working or I can't figure out the syntax.  I've tried
# A blacklist to stop tec dungeon spawn in dimensions. [default:[0]]
    I:bl_tec_dungeons <
	0,1,-1,7
     >

and 

# A blacklist to stop tec dungeon spawn in dimensions. [default:[0]]
    I:bl_tec_dungeons <
	[0,1,-1,7]
     >

and

# A blacklist to stop tec dungeon spawn in dimensions. [default:[0]]
    I:bl_tec_dungeons <
	[0,
          1,
        -1,
        7]
     >

and the dungeons keep spawning in dimension 7 (Twilight Forest):
![2018-04-26_14 13 12](https://user-images.githubusercontent.com/20757445/39288895-770cbe10-495c-11e8-8381-fd69fe62df73.png)

**Comment by mcenderdragon** [comment]
The syntax is:
```
I:bl_tec_dungeons <
    0
    1
    -1
    7
 >
```

(Its a forge feature dont ask me why the formatting is so weird.)

**Comment by Zygus42** [comment]
Worked like a charm.  Suggest adding 2 dimensions to the example in the config for other people.
