### ISSUE TITLE
[1.12.2] Server crash - java.lang.StackOverflowError: Ticking block entity .... block.BlockHologram.func

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#446]
https://gist.github.com/ProsperCraft/927caa663c7453a513e29965e7a4ada8

**Comment by mcenderdragon** [comment]
Does this still occur with this version: [26.3.209](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.209)

**Comment by ProsperCraft** [comment]
I don't know how I could reproduce it, it was a very rare event, best to just push it, and we will test it live on the server and let you know if it happens again.

**Comment by mcenderdragon** [comment]
It is caused if you cover a wire with a wire. (Hologram editor)

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/e07c42c17564e6f1345ae2a970fecf13

A bunch of players can't log in because every time they do it throws a stacktrace in console and kicks them.

Can you push an updated build to curse?

**Comment by ProsperCraft** [comment]
I can confirm this fixes the issue.

**Comment by mcenderdragon** [comment]
great, here is the curse link (curently it is still under rewiev so you might not see it): https://minecraft.curseforge.com/projects/futurepack/files/2557541
