### ISSUE TITLE
Spaceship Jumps are blocked if chunkloading is disabled

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#448]

**Comment by ProsperCraft** [comment]
We just verified this on my server, when I changed the forgechunkloading config from 


fp {
    I:maximumChunksPerTicket=1
    I:maximumTicketCount=1
}

to 


fp {
    I:maximumChunksPerTicket=100000
    I:maximumTicketCount=200
}


Players were able to fly their ships to planets again.

**Comment by mcenderdragon** [comment]
The bad thing about claimes and miner is: it will most likely crash if only the miner is loaded but not the claim... but yeah the chunk loadign thing should be better configureable.

**Comment by mcenderdragon** [comment]
It now creates a warning in the log if it could not create a ticket to load the needed chunks. Also the chunks are only loaded for generation and then unforced again, so they will not stay loaded.

**Comment by mcenderdragon** [comment]
All drones now use player tickets, so as long as normal chunk loading is enabled it will work.
