### ISSUE TITLE
Recycler and wierd repair results

### ISSUE THREAD

**Issue by TheRealM18** [mcenderdragon/Futurepack-API#449]
On version 26.3.210 we were noticing that bows, fishing rods, shears, flint and steel, and hoes from vanilla could not be repaired.  That being said some stuff like peridot armor JEI is says you can, but you are not able to do it in the recycler.  I am more wondering if some of this is disabled or is some of it not able to register correctly.  The list could get bigger as we are cleaning up the Applied Energistic 2 system and were wanting to keep some of that stuff for crafting later.

**Comment by rbandboy** [comment]
Of note: The Chisels and Bits chisels and the Chisel chisels all work for repairs in the same instance.

**Comment by rbandboy** [comment]
Also of note:

IC2 does NOT repair(although several items have a recycler recipe)
Caverns 2 gear DOES, mostly
Forestry does NOT
Chisel DOES (but has no recipe)
Chinjufu does NOT (but has a recipe)
Mekanism does NOT (but has a recipe)

**Comment by mcenderdragon** [comment]
Hmm interesting, it does not seem to follow any patterns...
I will look into it.

**Comment by Wugand** [comment]
should work much better now. Recipe generation is controlable by config.
