### ISSUE TITLE
Crash 1.12.2 - TileEntityExternCooler

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#451]
Reported by RealM:
https://pastebin.com/caLh7ujT

net.minecraft.world.World.func_175625_s   is   getTileEntity(BlockPos pos)
net.minecraft.world.World.func_189508_F   is   getPendingTileEntityAt(BlockPos pos)

**Comment by mcenderdragon** [comment]
@TheRealM18 1) did you running around whne this happened? 2) was a extern cooler around you when this happend? 3) did this happen when joining the world ?

**Comment by Wugand** [comment]
As I remember he said that he entered a dungeon

**Comment by mcenderdragon** [comment]
then it is hopefully a chunkloading problem (the other block was on the edge of a chunk)
