### ISSUE TITLE
Neon Sand Creation

### ISSUE THREAD

**Issue by rbandboy** [mcenderdragon/Futurepack-API#452]
Without going into any specifics, a neon sand extruding method has been found.  TheRealM18 can confirm on this, but only just what he knows - further testing has found only Neon Sand, rather than any of its varieties, can be created.

**Comment by rbandboy** [comment]
(also confirmed to not be a sponge issue - was found on Futurepack Lives v. 1.0.4.)

**Comment by mcenderdragon** [comment]
yeah we have a method to creat neon sand. If it involves liquids then it is intended and not a bug.
