### ISSUE TITLE
[OptiFine] E-Scanner GUI Missing (1.12.2)

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [mcenderdragon/Futurepack-API#459]
I have created a modpack in Minecraft 1.12.2 that includes Futurepack, and the E-Scanner will not pop up its GUI when right-clicked. I still get notified in chat when I research something new, but the GUI does not show whatsoever. There is no error code in the server console when this happens. My Forge version is 14.23.4.2705. The modpack runs on a server.

**Comment by mcenderdragon** [comment]
As this is the first time someone is reporting this, it is mostlikely another mod who is breaking something. Is Optifine installed and what coremods are installed?

**Comment by AwesomeAnimationGamer** [comment]
Optifine is installed, yes. I built the modpack using Twitch launcher and exported it for my friends to install to get on the server. I'll upload it here, as it will likely be the easiest way for you to take a look.
[MagiTech [1.12.2]-1.1.zip](https://github.com/mcenderdragon/Futurepack-API/files/2153543/MagiTech.1.12.2.-1.1.zip)

**Comment by mcenderdragon** [comment]
as optifine is often responsibible for visible bugs, please try to remove it and test again if the Gui is still missing.

**Comment by AwesomeAnimationGamer** [comment]
Yeah, just tested, turns out it was Optifine the whole time... thanks for the help
