### ISSUE TITLE
[1.12.2] Industrial Neon Furnace don't work at survival mode

### ISSUE THREAD

**Issue by Tronif** [mcenderdragon/Futurepack-API#460]
Hi guys.
I play Minecraft 1.12.2, FuturePack MOD 26.3.210.
Industrial Neon Furnace works in Creative world, but don't work in Survival. It seems that NE is not supplied to INF.
I'm stuck with this problem, so please give me hints and advice.

**Comment by mcenderdragon** [comment]
please check if the sides are correctly defined as inputs with the logistics editor.

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/289

**Comment by Tronif** [comment]
Yes, I confirm that the connection surface is an input. And already read #289. I think that it is completed except research requiring INF, but I do not know which one is missing.
I used cheat command, "/fp research <player> unlock all" in Creative world, so there is a possibility that research is insufficient.

**Comment by mcenderdragon** [comment]
if you have not unloced the research then it is not blocking the machine from filling up with Ne (normaly). PLease make a backup of your world and try this version [26.3.275](https://redsnake-games.de/Downloads/fp/fp.php?t=eQwp7cme2z343KKCQXPQGg--). I recently fixed some edge cases where NE did not got transfered correctly.

**Comment by Tronif** [comment]
I tried 26.3.275, but it did not change. And there was no change in the research that was added, even though we tried what we were able to do now.

**Comment by Tronif** [comment]
Oh, INF worked. (turned to version 26.3.210)
I understood the colors that logistics editor shows light blue is NE, yellow is SP, green is XP.
I am sorry to have trouble.

**Comment by Tronif** [comment]
Logistics editor's color :
Light blue : NE
Yellow : Support point
Pink (purple?) : 
Green : Network (item?)
Blue : Fluid

Is this correct?

**Comment by mcenderdragon** [comment]
The Name of the logisitcs editor change and displays wha state is currently selected, Green is Item/Inventory IO.

**Comment by Tronif** [comment]
Thank you for your advice. I will go next step.
