### ISSUE TITLE
OptiBench air recipe

### ISSUE THREAD

**Issue by Danilkat** [mcenderdragon/Futurepack-API#462]
when i crafted air recipe in optibench and tried to autocraft it, my game crashed
crash log:
[crash-2018-07-10_19.10.17-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/2180445/crash-2018-07-10_19.10.17-server.txt)
https://paste.dimdev.org/edeludageb.mccrash
playing on TownCraft modpack
crash everytime i try to load world

**Comment by mcenderdragon** [comment]
well that was kind of expectable... ^^

**Comment by mcenderdragon** [comment]
PLease check if this version fixes your problem: [26.3.277](https://redsnake-games.de/Downloads/fp/fp.php?t=FJUi2b8d62NDdiaMNIJXSQ--)

**Comment by Danilkat** [comment]
yep, that's fixed it. loaded world with no problem

**Comment by Danilkat** [comment]
thank you
