### ISSUE TITLE
SUGGESTION/REQUEST: Type Destination Coordinates

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [mcenderdragon/Futurepack-API#463]
I love this mod, truly I do. I have managed to make a fully-functioning "TARDIS" using it (a possibly-a-bit-too-big blue metal box with a Mekanism portal at the back) but my wrist is aching after spinning my mouse in circles for 2 minutes just to set my destination for translocation. Would it be possible in future versions to allow typing the destination coordinates instead of spinning the wheels?

**Comment by mcenderdragon** [comment]
Shift and Ctrl are supported for "faster" rotation. (By every Gui of this mod)
