### ISSUE TITLE
[1.12.2/Question] I'm stuck! What to do next ?

### ISSUE THREAD

**Issue by Tronif** [mcenderdragon/Futurepack-API#464]
FuturePack : 26.3.210.

Most of Tech Tree has been researched and the next research will not open. The blueprint found in the dungeon is only the dungeon key, it can not create the necessary TCT core for the dungeon key 2 and can not proceed further to the back of the dungeon. How can I proceed from here?
By the way, I was fortunate enough to obtain Growtite, Retium, Bioterim crystal, but there is no way to research the Laser bow. In this case, do I need to get a blueprint drawing somewhere?

**Comment by mcenderdragon** [comment]
please define next research. Also the TecTree is doable without the help of the big dungeons. Have you already researched the board computer. ALso please provide screenshot from your main tab.

**Comment by Tronif** [comment]
![2018-07-12_01 30 03_2](https://user-images.githubusercontent.com/40921102/42586496-393539f2-8573-11e8-9ab6-a53fd81f2e52.png)

**Comment by mcenderdragon** [comment]
Good, have you already been to menelaus ?

**Comment by Tronif** [comment]
No, Do you still need a spaceship?

**Comment by Tronif** [comment]
No, I suppose firstly I should make a spaceship. This seems to be tough.

**Comment by mcenderdragon** [comment]
it is doable with a minimum of 5 blocks.

**Comment by mcenderdragon** [comment]
Since this issue os solved I will close this, if yu have any questions feel free to ask.
