### ISSUE TITLE
[1.12.2] Remained invisible grid block after destroying airlock.

### ISSUE THREAD

**Issue by Tronif** [mcenderdragon/Futurepack-API#465]
If I destroy after rotating the expanding airlock, the grid block which is immortal and invisible remains.
I removed these blocks using mcedit.
![2018-07-12_16 05 37](https://user-images.githubusercontent.com/40921102/42618136-0acf862c-85ef-11e8-8cbf-68b03f3fac5d.png)

**Comment by mcenderdragon** [comment]
how do you rotate the airlock ?

**Comment by Tronif** [comment]
right click with using scrench.

**Comment by mcenderdragon** [comment]
This will be hard to fix as the airlock does not know its previes rotation and the hitbox block is only for not getting through a closed airlock.

**Comment by mcenderdragon** [comment]
Fixed in 1.14

**Comment by SkyProgs** [comment]
Unfortunately, we can no longer support the 1.12.2, so I'm closing this, as it is fixed in newer versions.
