### ISSUE TITLE
e-scanner entries missing

### ISSUE THREAD

**Issue by Danilkat** [mcenderdragon/Futurepack-API#468]
![image](https://user-images.githubusercontent.com/41061608/42692580-5fb42566-86d6-11e8-9aa5-d1842b74a92e.png)
![image](https://user-images.githubusercontent.com/41061608/42692935-98f890e0-86d7-11e8-87f5-71cc7c6797b3.png)

**Comment by mcenderdragon** [comment]
wish version of Futurepack?

**Comment by Danilkat** [comment]
latest you sent me in my previous issue page 26.3.277

**Comment by mcenderdragon** [comment]
Ahh ok, yeah thats why this version is not released, we still need to write the texts :^)

**Comment by Tronif** [comment]
It is the same with a purple focus lens at version 26.3.210. Please write this texts, too.

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/272
