### ISSUE TITLE
[1.12.2/Question] About transportation method of support point.

### ISSUE THREAD

**Issue by Tronif** [mcenderdragon/Futurepack-API#470]
FuturePack Version: 26.3.210

I have a question about how to transfer support points from Neon Furnace to Flash Server. I output the support point of Neon Furnace using the support cable, and set the Flash Server as I / O, but the support point will not be transferred. But Support points from Flash Server to Centrifuge seem to be forwarded. What is going on with this?

**Comment by mcenderdragon** [comment]
Is a support chip installed in the Neon Furnace ?

**Comment by Tronif** [comment]
Changed the logic chip to the support chip, then transferred the support point.
Thank you.
