### ISSUE TITLE
[1.12.2] crash when using the laser pen of refraction

### ISSUE THREAD

**Issue by lampyr** [mcenderdragon/Futurepack-API#472]
When i use the laser pen with futurepack installed i crash.
log: https://gist.github.com/lampyr/bab0134d73c86b15e6c6188c564f3aeb
crash log: https://gist.github.com/lampyr/6b8adb662da2b252a54d6236dae26daa

futurepack: 26.3.210

link to the issue in github of refraction: https://github.com/TeamWizardry/TMT-Refraction/issues/56

If you want other stuff ask me.

**Comment by mcenderdragon** [comment]
please test if it is already fixed [26.3.280](https://redsnake-games.de/Downloads/fp/fp.php?t=je5qDf33ANDqCaHhyF8nEg--)

**Comment by lampyr** [comment]
Sorry i crash again : https://gist.github.com/lampyr/8486875a5d639f0db246fda8fa0f2d2a

**Comment by mcenderdragon** [comment]
Someone has created an Entity wish return null as ItemStack in the Armor slots, but this is not allowed as of 1.11/1.12 where ItemStacks have to return ItemStack.EMPTY.

**Comment by mcenderdragon** [comment]
please try this version [26.3.281](https://redsnake-games.de/Downloads/fp/fp.php?t=SOqKnVqHPCQ85fT5hjJyYg--) It should produce a log output stating where the errors is.

**Comment by lampyr** [comment]
thank you i didn't crash and your FP-Latest.log: https://gist.github.com/lampyr/3d9b21ec128490d299e18153967eb04e

i think it is the laser pointer.

**Comment by Rikshy** [comment]
sorry für die unannehmlichkeit mit dem NPE und danke :)

sorry for the inconvenience with the NPE and thanks for letting me know :)

**Comment by lampyr** [comment]
thank you very much it is fixed.
