### ISSUE TITLE
Crash Whilst Updating Screen Events (1.12.2)

### ISSUE THREAD

**Issue by djddanman** [mcenderdragon/Futurepack-API#474]
I'm playing a custom modpack with a friend who wanted to build one around Futurepack, but we occasionally get game crashes citing updating screen events, with the block fp:triebwerk as the issue. I had this crash twice in a row when clicking on EnderIO's Enhanced Wireless Charger in JEI. EDIT: This happens when I right click any EnderIO Enhanced machine in JEI to see uses as well as pressing U. The error message that pops up is:

https://pastebin.com/TFZyQBj0

The full crash report is:

https://pastebin.com/bmtd6Rw1

**Comment by mcenderdragon** [comment]
enderIO is calling the thursters with an invalid meta and it crashes. You should open an issue at their issue tracker and link to this one. (it gets called from crazypants.enderio.base.paint.PaintUtil)

**Comment by djddanman** [comment]
There is an open issue for this with other mods on the EnderIO issue tracker.

https://github.com/SleepyTrousers/EnderIO/issues/4755

**Comment by tyler489** [comment]
In short: This fails: ((ItemBlock) itemStack.getItem()).getBlock().getStateFromMeta(itemStack.getItem().getMetadata(itemStack.getMetadata())); It looks very convoluted, but this is how vanilla's ItemBlock+Block work together to convert an item damage to a blockstate.

**Comment by SkyProgs** [comment]
Unfortunately, we can no longer support version < 1.16. If this happens in a newer version please open a new issue.
