### ISSUE TITLE
Suggestion: add a config option to turn off machine noises

### ISSUE THREAD

**Issue by McFrugal** [mcenderdragon/Futurepack-API#475]
The machines in this mod make extremely annoying sounds and I want to turn them off.

**Comment by mcenderdragon** [comment]
YOu can turn on and off the sound witht eh vanilla silders.

**Comment by McFrugal** [comment]
I don't see a Futurepack sound slider.  If you're referring to the "Blocks" slider, no, I'm not turning that to 0 just to silence your machines.

**Comment by mcenderdragon** [comment]
![2018-08-04_13 47 11](https://user-images.githubusercontent.com/6342933/43676207-ecd95408-97ec-11e8-8320-d9a427ed1a39.png)

**Comment by mcenderdragon** [comment]
[26.3.287](https://redsnake-games.de/Downloads/fp/fp.php?t=.x6rePhvSvACjl7HKBfgiA--)
