### ISSUE TITLE
Request: Config setting for disable_research

### ISSUE THREAD

**Issue by Nonsanity** [mcenderdragon/Futurepack-API#476]
I'm of mixed feelings when it comes to the research portion of the mod. I like the idea, but in practice, far too much time ends up spent in the Scanner clicking, clicking, clicking. FuturePack is a big focus of the pack I'm working on but the unanimous response from playtesting is that the research is getting in the way of actually using the mod—and getting in the way of having fun with it.

I think the research can definitely be made appealing to more people—and I'd be happy to offer my professional game development experience for that—but until that time, a config option to basically do the same thing as the "/fp research <player> unlock all" command, but automatically for all players upon joining a server would be nice, instead of needing an op to log in and run the command every time. It could also be done with a command block, but with the command already in existence, it seems a config setting would be simple enough to add. At least, simple enough to request. :D

**Comment by mcenderdragon** [comment]
These to configs should do what you requested.
B:disable_machine_lock=true
B:disable_research_check=true

**Comment by Nonsanity** [comment]
That leaves the tech tree in the E-Scanner still locked—you can't look up information on any of the blocks. The recipes in the machines don't seem to work either, since none of them are researched.

**Comment by mcenderdragon** [comment]
Yes so the players need to research it if they want the information but they dont have to do it as they can craft it without this information.

**Comment by Nonsanity** [comment]
But I couldn’t craft anything either. Is this the same as unlocking all research with the command? What this feature request is all about is duplicating the command’s effects (unlocking all research) automatically when someone logs in for the first time because of a config setting.

**Comment by mcenderdragon** [comment]
[26.3.288](https://redsnake-games.de/Downloads/fp/fp.php?t=0PmUJxR3ThULwnEpFPCggw--)
