### ISSUE TITLE
Crash due to conflict with RedstonePlusPlus

### ISSUE THREAD

**Issue by Flybuild** [mcenderdragon/Futurepack-API#477]
Forge version: 1.12.2-14.23.4.2707
Futurepack version: 1.12.2-26.3.159
Mod conflicted with: RedstonePlusPlus 1.2d

Singleplayer.

Description: I go to create a new world, However it crashes when it says 0% right after Loading world/Building Terrain. If Vanillafix is present, the crash does not occure, but when Vanillafix AND Bionisation3 (along with red+ and fp) is present, the crash will occure again, and Vanillafix will blame Futurepack and Bionisation 3 before putting you back to the main menu

I have a crash report, And heres a link to the pastebin: https://pastebin.com/qvtNeSBj (This is with only Futurepack and Redstone+++, No other mods present at all)

Note: I have already contacted the Redstone++ creator, they said they cant do anything without the source code of Futurepack.

**Comment by mcenderdragon** [comment]
This is caused because I bake the the research items with the FMLServerStartedEvent, I can't do this earlier because the ID mapping is different for each world. And as the crafting recipe are linked to the researches they to to access them via the not yet baked items and thus it crashes.

**Comment by mcenderdragon** [comment]
Has Redstone++ an issue tracker ?

**Comment by mcenderdragon** [comment]
This version should fix it: [26.3.284](https://redsnake-games.de/Downloads/fp/fp.php?t=CqkubOuPyA2oE60PzjhWiA--)

**Comment by Flybuild** [comment]
Thank you very much, Your mod is amazing.
