### ISSUE TITLE
More granular configuration options for blocks to conserve IDs/RAM

### ISSUE THREAD

**Issue by asiekierka** [mcenderdragon/Futurepack-API#479]
Since we have Chisels & Bits already, I'd like to avoid redundancy on an already heavy pack.

In particular, I'm thinking of the stair, slab and wall variants of Futurepack blocks. However, any options useful for us at BTM are more than welcome.

**Comment by mcenderdragon** [comment]
The slabs are not remove able since we would remove the base block aswell (the full blocks are the same as a dobble slab) But we could preserve 48 ids trough fence gates and stairs. Is this it wourth?

**Comment by asiekierka** [comment]
That's fair. It's more thinking forward about other users too, really - fewer blocks = fewer models = less RAM

**Comment by mcenderdragon** [comment]
well you know lex stance about configs changing the id map...

**Comment by asiekierka** [comment]
LexManos has enough RAM to get away with it. Most players might, but BTM has to work well for everyone.

**Comment by mcenderdragon** [comment]
I have to test out how our research system and the recipes reacte to this but I am working on it.

**Comment by asiekierka** [comment]
I mean, you don't *have* to add it if you don't want to. We can do without it for now, and we most likely won't reach 4096.

**Comment by mcenderdragon** [comment]
I am surprised it works without crashing. I will post a version here soon.

**Comment by mcenderdragon** [comment]
[26.3.299](https://redsnake-games.de/Downloads/fp/fp.php?t=p0TnVshhj9QywRct3X4uOQ--) It will create alot of crafting recipe errors on startup, but everything else works. the config option is BTM in categorie server.
