### ISSUE TITLE
"Hold Shift for Details" shown to often

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#48]
At some Blocks the "Hold Shift for Details" (under Block name, when Hover) is shown, but their are no further informations.

Seen at:
TechTable
IndustrialFurnace

**Comment by mcenderdragon** [comment]
this is also at many other mods so...no?! OR maybe... dunno if I can check it with little changes

**Comment by mcenderdragon** [comment]
thius is fixed as shift iks working now.
