### ISSUE TITLE
Displayed energy level of machines doesn't always sync properly to the client

### ISSUE THREAD

**Issue by Maxwell-lt** [mcenderdragon/Futurepack-API#486]
In some cases, the energy bar of a machine will fail to fully sync to the client, appearing to drain from full to 1 NE each time the interface is opened. The machine is recieving plenty of power, and the bar starts at full whenever the player opens the machine's interface. Checking with an E-Scanner shows the power at 1000.0 NE consistently.

Here's a video demonstrating the bug: [https://streamable.com/v0mr8](https://streamable.com/v0mr8)

The machine here is using a Torus Core and two Torus RAM, all made in an SP boosted Assembly Table (so roughly 23 for the Core and 20 for the RAM). It is powered by an array of 9 Turbine Generators producing 30 NE/t each. To see this bug, the machine must be operating at maximum speed, in this test I had to clear the output buffer and fill the input manually since the hoppers I was using were unable to keep up.

Mod List:

- Futurepack-1.12.2-26.3.210.jar
- jeiintegration_1.12.2-1.5.1.36.jar
- Hwyla-1.8.26-B41_1.12.2.jar
- JustEnoughResources-1.12.2-0.8.10.50.jar
- jei_1.12.2-4.12.0.216.jar
- LagGoggles-FORGE-1.12.2-4.1.jar

Using latest Forge: v14.23.4.2760

**Comment by mcenderdragon** [comment]
Yeah I am aware of this bug and its quite hard to fix, this only happens if you produce alot more power then you need, it should be already fixed in dev: [26.3.380](https://redsnake-games.de/Downloads/fp/fp.php?t=t6f3LFqYw06q7LIfTbN7yw--)

**Comment by Maxwell-lt** [comment]
In my testing, the dev version fixes the issue.
