### ISSUE TITLE
RedstoneWire Performance issue + Stackoverflow possible

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#488]
The issue is seen Server Side (Client side is unkown). 

Setup:
    Multiple Redstone wires triggered by RsTimer

Result:
   Very high server load (47,7% at 70ms Tick time)
   Very Very large Stack, with more Wires a Stackoverflow is not impossible

![rswire1](https://user-images.githubusercontent.com/11357199/45769151-08b76b80-bc3f-11e8-94b0-b77e0f1b6345.png)

![rswire2](https://user-images.githubusercontent.com/11357199/45769264-69df3f00-bc3f-11e8-8c0a-384c1492ffab.png)

**Comment by Wugand** [comment]
Ticking at 1s:
![rswire3](https://user-images.githubusercontent.com/11357199/45769668-99427b80-bc40-11e8-9714-db7930c32109.png)

**Comment by Wugand** [comment]
Another Problem case, with very high load:
(Ticking at 1s)

![rswire4](https://user-images.githubusercontent.com/11357199/45769970-7795c400-bc41-11e8-879b-4ba2ff1ab2ca.png)

![rswire5](https://user-images.githubusercontent.com/11357199/45769979-795f8780-bc41-11e8-9a50-a22844b55037.png)

*Inside the selected Line, the same long recursive chain

**Comment by mcenderdragon** [comment]
about the stacktrace: this is how redstone work, I can not edit how things are done. Also about the second priflling: I only see vanillas inefficient redstone wires, needing way too much time.
