### ISSUE TITLE
Is this chicken that spawns when you right click on a dungeon teleporter from Futurepack?

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#493]
![2018-10-04_21 17 42](https://user-images.githubusercontent.com/4427684/46514565-d51e3900-c81b-11e8-8dd3-8411bba5c857.png)

Seems someone is playing a prank, but it isn't that funny because you are unable to enter the dungeon.

**Comment by ProsperCraft** [comment]
Console says this - https://gist.github.com/ProsperCraft/9020475b93531067417d6c3dabd4b1c0

**Comment by mcenderdragon** [comment]
"Soul" indicate at this position it was unable to generate a dungon as there is already one or it would not fit, into the terrain (size-wise). From your screenshot it seems like this was an older dungeon, generatet befor 26.3.210, therefor this teleporter does not work anymore.

**Comment by ProsperCraft** [comment]
This is fun and silly, but here is my take on it...

1. The deaths of Soul spam the chat...people spam click the teleporter because people are how they are and it makes tons of chickens and when they suffocate they spam chat.

2. It tells the player nothing about why the teleporter isn't working, and leaves them befuddled as to why  it isn't working and why there is a chicken spawning.

A simple message in chat saying this outdated portal seems to be broken would be far more desirable.

**Comment by mcenderdragon** [comment]
The teleporter gets replaced by an colored iron block, (because this teleporter will not work anyway) if this is not happening something (other mod, sponge, permission systems) is interfering and blocking the block replacement. Also there are mayn reasons why this could happen and the user can do nothing about it. So the information the user gets is 'broken' and thats all them need to know (IMO).

**Comment by mcenderdragon** [comment]
I changed the spawn behaviour to only trigger if the block replacement succeeds: [26.3.420](https://redsnake-games.de/Downloads/fp/fp.php?t=ES64mi1JzStJ_AyZBWWaUw--)
