### ISSUE TITLE
[1.12.2]How to craft any ingotPrismid?

### ISSUE THREAD

**Issue by Tronif** [mcenderdragon/Futurepack-API#494]
FuturePack : 26.3.417

ingotPrismid seems no recipe.
I want to research Laser Tech2, but ingotPrismid cannot craft now.

**Comment by mcenderdragon** [comment]
Prisimid can be found on Tyros.

**Comment by Wugand** [comment]
i think i done an typing mistake: it should be gem not ingot

**Comment by lastwish23** [comment]
Having the same problem. Tried using prismid vein and prismid but nothing is working.

**Comment by mcenderdragon** [comment]
Please try if this fixes the isue: [26.3.458](https://redsnake-games.de/Downloads/fp/fp.php?t=8o31m36Tx82H1NmEEPKqSA--)

**Comment by lastwish23** [comment]
Will this work if I'm playing on someone else server or do I need the server owner to download it to the mudpack?
    On ‎Tuesday‎, ‎November‎ ‎6‎, ‎2018‎ ‎01‎:‎20‎:‎52‎ ‎PM‎ ‎EST, mcenderdragon <notifications@github.com> wrote:  
 
 
Please try if this fixes the isue: 26.3.458

**Comment by mcenderdragon** [comment]
yes this is needed on the server.

**Comment by lastwish23** [comment]
Thank you, I will ask the owner to add the file and get back to you. Again, thank you.     On ‎Tuesday‎, ‎November‎ ‎6‎, ‎2018‎ ‎01‎:‎28‎:‎40‎ ‎PM‎ ‎EST, mcenderdragon <notifications@github.com> wrote:  
 
 
yes this is needed on the server.
