### ISSUE TITLE
[1.12.2] Is able to run calculation modules in parallel processing?

### ISSUE THREAD

**Issue by Tronif** [mcenderdragon/Futurepack-API#495]
FuturePack : 26.3.417

There are 10 calculation modules on one network and 2 Researchers on the same network.
When running two Researchers in this state, it seems that the calculation module on the network is not functioning.
How do you think that it is correct to assign calculation modules in parallel processing?

**Comment by mcenderdragon** [comment]
If everything is connected via network cables the researches should display the amount of active calculation modules (when hovering the bar with the mouse)

**Comment by Tronif** [comment]
Both reseachers displayed active calculation modules that is 0 or 1, and displayed huge time completion.
Case of reseaching fising lod, reseacher displayed 10. So I presented this issue.
