### ISSUE TITLE
[1.12.2] Flash server texture display is wrong.

### ISSUE THREAD

**Issue by Tronif** [mcenderdragon/Futurepack-API#497]
FuturePack : 26.3.417

The texture display of the flash server is incorrect with scrench.
![2018-10-08_03 07 21](https://user-images.githubusercontent.com/40921102/46585129-a87e5180-caa7-11e8-904a-f66d0aafb6f7.png)
![2018-10-08_03 07 18](https://user-images.githubusercontent.com/40921102/46585130-ab794200-caa7-11e8-9ea6-f05447081f6d.png)

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/366

**Comment by mcenderdragon** [comment]
Does this only happen when a scrench is held, or also with other items ?

**Comment by Tronif** [comment]
When I have scrench after changing the version of MOD to 26.3.417. and  the rendering of flash server in the dungeon which was captured is strange, too.
The rendering  of the flash server from time to time to the previous version is somewhat odd, so once destroyed and reinstalled it was repaired.

**Comment by mcenderdragon** [comment]
Rendering issues should be fixed: [26.3.420](https://redsnake-games.de/Downloads/fp/fp.php?t=ES64mi1JzStJ_AyZBWWaUw--)

**Comment by Tronif** [comment]
I confirmed that it seemed good. Thank you for your response.
