### ISSUE TITLE
[1.12.2] You have not reseached this yet!

### ISSUE THREAD

**Issue by Tronif** [mcenderdragon/Futurepack-API#499]
FuturePack : 26.3.417

For example, Quantanium ingot.
If I check the recipe with JEI immediately after starting the game,
"You have not researched this yet!" Is displayed.
After that, open the E-Scanner once and check the recipe again with JEI the error icon disappears.

**Comment by mcenderdragon** [comment]
The researches have not yet been send to the client. This issue is minor & the e-scanner is for the recipes anyway.
