### ISSUE TITLE
Some help please

### ISSUE THREAD

**Issue by tayler2000** [mcenderdragon/Futurepack-API#5]
I have some issues with the mod, in the 1.10.2 version, if anyone can respond please

**Comment by mcenderdragon** [comment]
Please specifi you problems

**Comment by tayler2000** [comment]
Im having some problems with some items recipes, red focus lens appears as a missing object, some items are completely in german and I cant seem to figure out how to use them, even tho some recipes ask for magnet ingots it never gave the recipe, been using the ones I found in chest and stuff, 
Items "research.production.miner.claime/drone/station appears also as a missing object,
Also cant make networks, all the explanation is in german

**Comment by mcenderdragon** [comment]
The researches are not finished jet, and we are translating them. The recipes with magnets are intended to be like this. (So yes you have no recipes you have to use the magnets you find)

**Comment by tayler2000** [comment]
Well then, thanks, hope you update this soon, I like the mod so far

**Comment by mcenderdragon** [comment]
Well you can whatch the update progress at the translation repo: https://github.com/Wugand/FuturePack-Language
