### ISSUE TITLE
[1.12.2] Cannot complete Crystalline Energy cell research.

### ISSUE THREAD

**Issue by Tronif** [mcenderdragon/Futurepack-API#500]
FuturePack : 26.3.417

Although Crystalline Energy cell research is completed, but advancement  are not canceled yet.

**Comment by mcenderdragon** [comment]
why should the advancvement be canceled ? ALso as far as I know the crystaline energy cell does not hoave a reaserch, you can only obtain it from the dungeon.

**Comment by Tronif** [comment]
Please see log file.
In log file, already completed log.battery.crystal.
If you are right, should you remove log.battery.crystal ?
I think no need research about log.battery.crystal.


[21:10:37][Client thread] Completed Reserach log.battery.crystal(167) { x:7, y:0, Icon:futurepack.common.gui.RenderableItem@431f7f7a, Parents:[log.battery.compact, surveyscan.tyros], Grandparent:null, Needed:[Lfuturepack.api.ItemPredicates;@4b0c0215, Enabled:[1xitem.CrystalEnergyCell_full@0] }

[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/2464589/FP-Latest.log)

**Comment by mcenderdragon** [comment]
thats the loading line, it has nothing to do with ingame mechanics. @Wugand

**Comment by Wugand** [comment]
Crystalline Energy cell research is not implemented at the moment. It's not reasearchable in normal way.

This behavior is correct for the moment and will be changed in some later update.
