### ISSUE TITLE
[1.12.2/Question] What is the difference between a block that can be destroyed in a controlled dungeon and a block that can not be broken?

### ISSUE THREAD

**Issue by Tronif** [mcenderdragon/Futurepack-API#501]
FuturePack : 26.3.417

If i want to enter at already Controlled dungeon, a gate changed to soul, and vanished gate.
It was interpreted as specification change. It's Ok.

Then, digging the ground and going to the controlled dungeon, breaking the block of the wall, there is a dungeon that can invade and a dungeon that can not invade.

**Comment by Tronif** [comment]
sorry, FuturePack : 26.3.420.

**Comment by mcenderdragon** [comment]
All the larger dungeons have been moved to another dimension (because of issue with other world generation from mods) This has as a sideeffect all older dungeons will no longer work.

**Comment by Tronif** [comment]
Ok. I understand this question.
Thank you for your quick reply.
