### ISSUE TITLE
Crash will removing wire. 1.12.2

### ISSUE THREAD

**Issue by TheRealM18** [mcenderdragon/Futurepack-API#505]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 20.10.18 00:52
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at futurepack.common.block.FPBlocks.spreadPower(FPBlocks.java:1718)
	at futurepack.common.block.FPBlocks.powerLowestBlock(FPBlocks.java:1351)
	at futurepack.common.block.TileEntityWire.func_73660_a(TileEntityWire.java:110)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at futurepack.common.block.FPBlocks.spreadPower(FPBlocks.java:1718)
	at futurepack.common.block.FPBlocks.powerLowestBlock(FPBlocks.java:1351)
	at futurepack.common.block.TileEntityWire.func_73660_a(TileEntityWire.java:110)

-- Block entity being ticked --
Details:
	Name: minecraft:fp-wire // futurepack.common.block.TileEntityWire
	Block type: ID #329 (tile.wire // futurepack.common.block.BlockWire // fp:wire)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-98,71,-7), Chunk: (at 14,4,9 in -7,-1; contains blocks -112,0,-16 to -97,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #329 (tile.wire // futurepack.common.block.BlockWire // fp:wire)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 4 total; [EntityPlayerMP['Mantes'/254, l='world', x=-79,79, y=63,66, z=22,70], EntityPlayerMP['CrimsonCobra817'/306, l='world', x=129,58, y=95,12, z=1008,00], EntityPlayerMP['wugand'/5912, l='world', x=-65,18, y=65,77, z=14,62], EntityPlayerMP['TheRealM18'/92363, l='world', x=-87,35, y=63,00, z=11,13]]
	Chunk stats: ServerChunkCache: 978 Drop: 0
	Level seed: 8554790206322494199
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8746375 game time, 6139 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_172, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1571103200 bytes (1498 MB) / 2639265792 bytes (2517 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 1 total; -Xmx8192M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID        | Version      | Source                                  | Signature                                |
	|:--------- |:--------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft | 1.12.2       | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp       | 9.42         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2768-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge     | 14.23.5.2768 | forge-1.12.2-14.23.5.2768-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | fp        | 26.3.417     | Futurepack-1.12.2-26.3.417.jar          | 3ad693059337b95c41b649ec9f29c4a6e8282586 |
	| UCHIJAAAA | fp.api    | 1.1.0        | Futurepack-1.12.2-26.3.417.jar          | None                                     |
	| UCHIJAAAA | worldedit | 6.1.8        | worldedit-forge-mc1.12-6.1.8-dist.jar   | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 4 / 100; [EntityPlayerMP['Mantes'/254, l='world', x=-79,79, y=63,66, z=22,70], EntityPlayerMP['CrimsonCobra817'/306, l='world', x=129,58, y=95,12, z=1008,00], EntityPlayerMP['wugand'/5912, l='world', x=-65,18, y=65,77, z=14,62], EntityPlayerMP['TheRealM18'/92363, l='world', x=-87,35, y=63,00, z=11,13]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by mcenderdragon** [comment]
fixed in 26.3.447
