### ISSUE TITLE
Industrial Neon Furnace causing crash on block place

### ISSUE THREAD

**Issue by RedLila** [mcenderdragon/Futurepack-API#510]
Playing on a custom modback server with futurepack included, however I'm running everything purely on futurepack. Placing Idustrial Neon Furnace on any block causes a client crash. Upon reloading the block is placed but the furnace doesn't function even with Power supplied and on 0 SP recipes. Its UI indicates it recognizes the items by the burners lighting up but no progress ever begins. The orignal in inventory furnace is also still present and has charcoal in it for some reason. This is being placed within 4 blocks of a regular neon furnace that produces Charcoal for Infusion generators if that makes any difference.

**Comment by mcenderdragon** [comment]
Please include the crash report.

**Comment by RedLila** [comment]
I believe I identified the root cause on this as being caused by a non-empty industrial furnace being used in initial crafting. Subsequent creation of a Neon Industrial Furnace in creative mode but placement in survival worked without crash. I'll find and upload the crash report when I get home though.



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by mcenderdragon** [comment]
is the crash comming ?

**Comment by Wugand** [comment]
https://hastebin.com/imetivotig.rb

The Tag contains more Items, then the Neon Industrial Furnace have slots

**Comment by mcenderdragon** [comment]
should be fixed: [26.3.460](https://redsnake-games.de/Downloads/fp/fp.php?t=39u0988iRgXuk1EVW8afgw--)
