### ISSUE TITLE
mining drone Crash

### ISSUE THREAD

**Issue by Offliner78** [mcenderdragon/Futurepack-API#511]
client crashes when miningdrone is aktive... it seems reason ist something by "how big is the Claim" ...
[crash-2018-11-06_10.03.49-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/2552353/crash-2018-11-06_10.03.49-server.txt)

**Comment by mcenderdragon** [comment]
similar issue as in #509

**Comment by mcenderdragon** [comment]
shoulb be fixed in 26.3.458 but needs testing

**Comment by Offliner78** [comment]
btw. Forestmaster works fine now...                      2 Bedingungen scheinen den Crash auszulösen: 1.) Oberkante vom Claim ist unter einem Block (nicht AIR) 2.) Größe des Claims > 4x4x4

**Comment by mcenderdragon** [comment]
chunk grenzen, es passiert wenn über eine chunk grenze hinweg items eingesammtelt werden

**Comment by mcenderdragon** [comment]
Please try if this fixes the crash: [26.3.458](https://redsnake-games.de/Downloads/fp/fp.php?t=8o31m36Tx82H1NmEEPKqSA--)

**Comment by Offliner78** [comment]
erste Tests erfolgreich -> Absichtlich chunkgrenzen überschritten und auch komplett unterirdisch kein Crash mehr ; auch größere Claims in 3 Chunks gleichzeitig
first tests successful -> deliberately exceeded chunk limits and also completely underground, no more crashes; also larger claims in 3 chunks at the same time
I think the problem is solved
