### ISSUE TITLE
Ability to fly to other dimensions

### ISSUE THREAD

**Issue by Tortyash** [mcenderdragon/Futurepack-API#514]
If it's possible, I would like to add coordinates of GC planets or other dimensions for using by board computer (or alternative board computer for this needs)

**Comment by mcenderdragon** [comment]
Write a mod and add a [IPlanet](https://github.com/mcenderdragon/Futurepack-API/blob/1.12/futurepack/api/interfaces/IPlanet.java) and then you have to register in inside the [FPApiMain#registerPlanet](https://github.com/mcenderdragon/Futurepack-API/blob/1.12/futurepack/api/FPApiMain.java#L43)

**Comment by mcenderdragon** [comment]
feel free to reopen this if you have any more questions/problems.
