### ISSUE TITLE
FPChunkScanner create constant load and log

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#515]
An idle server (0 players online) writes every second to log:
_[00:00:00] [FP-ChunkScanner/INFO] [STDOUT]: [futurepack.common.FPChunkScanner:progressAll:226]: Buffered: 585_

This also creates constant CPU load (much higher than ServerThread, in case of no palyers). Gernerally i don't think the chunk scanner shouldn't have any work in this situation.

![vvm](https://user-images.githubusercontent.com/11357199/49424785-ed6aef80-f79b-11e8-81b3-d4c96ea46e9f.png)

**Comment by mcenderdragon** [comment]
from the profiling the chunk scanner is constant asleep, also it states it is buffering the chunks hence something is blocking the thread from evaluating the chunk.

**Comment by mcenderdragon** [comment]
is the Buffered number constant or decreasing ?

**Comment by Wugand** [comment]
Everytime constant 585 (over at least 1 day)

**Comment by mcenderdragon** [comment]
then this log is exactly that what it meant todo: notifing something with the filesystem went wrong so it cant write the scanned chunks to disk.

**Comment by mcenderdragon** [comment]
there are no exceptions in the log?

**Comment by mcenderdragon** [comment]
(most likely befor the spam started)

**Comment by Wugand** [comment]
yes:

https://pastebin.com/raw/yVZpinMW

after that (maybe no regard to this problem) 46 times the following within 1 sec:

https://pastebin.com/raw/Rief0fzS

Some minutes later the "Buffered" value raises up to 585 while new chunks are generated.

**Comment by mcenderdragon** [comment]
Basicly only a restart can fix this problem, as the filesystems in java itself crashed and are still in memory (crashed) we now have to check if we can merge the .tmp and the .dat files to not loose this data.

**Comment by mcenderdragon** [comment]
solved in 26.3.471
