### ISSUE TITLE
Compact Energy Cell with max energy of 0

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#516]
Compact Energy Cellc from dungeons tent to have max Energy of 0.

**Comment by qrss** [comment]
Okay, I did some testing and the dungeon is unrelated to this issue.

The problem seems to be with shift-clicking batteries into the minus slot of the Battery Box.

It does not happen always and and I'm having trouble figuring out the nescessary conditions to have that happen.

Will report back when I have done more testing.

**Comment by mcenderdragon** [comment]
could be related: https://github.com/mcenderdragon/Futurepack-API/issues/512

**Comment by qrss** [comment]
Aha, that seems to be it.

So I guess the way to reproduce it might be shift-clicking empty looted batteries into the minus slot.

That would explain why I had trouble reproducing it. Need to go loot some batteries to test this.

**Comment by mcenderdragon** [comment]
Also a modlist of your would be nice, as this might be a mod interaction problem.

**Comment by qrss** [comment]
The modlist is whatever your server is running (CaptCarrot here).

**Comment by mcenderdragon** [comment]
Ahh okay, so just Futurepack. (plus morpheus & fast leave decay but the dont do such things)

**Comment by qrss** [comment]
Okay, I did some testing and the problem indeed seems to be incorrect NBT data of dungeon batteries, combined with buggy handling of such batteries by the Battery Box.

Batteries found in the T1 research modules in dungeons (that are not in the + slot) have the following NBT data:

neon: {
 maxNE: (some value)
}

compared to a normal empty battery, which has NBT data:

neon: {
 maxNE: (some value)
 ne: 0
}


Putting a battery with NBT data

neon: {
 maxNE: (some value)
}

into a MINUS slot of a Battery box turns the NBT data into

neon: {
 ne: 0
}

Note that "maxNE: (some value)" is now missing, which causes the max charge of the battery to show up as 0.

**Comment by mcenderdragon** [comment]
This is the most detailed report of a Bug I (knowlingly received) and it saves me tons of digging around, thank you very much. (Also my sanity is gone as I have been doing stuff for my uni which must be finsihed tomorrow for the last ~5h)

**Comment by qrss** [comment]
Glad I could be helpful.

Hope you don't burn yourself out trying to do uni and modding at the same time.

**Comment by mcenderdragon** [comment]
I fixed the problem with the maxNE showing as 0 (it nopw correctly uses the default value). But I do not understand why the value "maxNE" got removed...
