### ISSUE TITLE
ultimate + transport + network: does not work on our server

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#517]
The XP orb get produced but not put into the T3 modul connected via network cable.

Happened to CaptCarrot.

**Comment by mcenderdragon** [comment]
fixed in 26.3.467

**Comment by mcenderdragon** [comment]
The problem is: if more then one cable is connected it tries to use the first one it finds as a network cable, if this is not given the XP is not send and thus dropped.

**Comment by qrss** [comment]
Thanks.
