### ISSUE TITLE
Using Scrench (Block Rotate Mode) on Network Cable, makes it look like a regular Cable

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#519]
Version: 26.3.461

Right clicking a Network Cable with a Scrench in Block Rotate Mode makes it look like an ordinary Cable. The effect is only visual, but remains after relog. The block still acts like a network cable and drops a network cable when broken.

**Comment by mcenderdragon** [comment]
Even after e restart of the client ?

**Comment by qrss** [comment]
Yes, even after restart (tested in Single Player).

Looking at the cable with the F3 info open shows that the right click changes Mode from "network" to "l1". A normal cable has Mode: normal

**Comment by mcenderdragon** [comment]
This means the state is also on the server side wrong, interresting.

**Comment by mcenderdragon** [comment]
Fixed: https://minecraft.curseforge.com/projects/futurepack/files/2668303
