### ISSUE TITLE
Industrial Neon Furnace's initial logistics configuration broken

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#520]
Version: 26.3.461 (server)

A newly crafted Industrial Neon Furnace has incorrect logistics settings:

The Energy and Support settings are on None, meaning it gets no power by default.

The Items setting is on Input/Output, which is a setting that should not be possible, since you can not set them into that mode with a Logistics Editor

**Comment by mcenderdragon** [comment]
do you recall your crafting ingredients, as the nbt data from there is passed on.

**Comment by qrss** [comment]
Well, one of the ingredients is an Industrial Furnace, which can not send or recieve power and has item logistics set to Input/Output by default.

Perhaps that is indeed the reason.

**Comment by mcenderdragon** [comment]
This is very lickely the cause.
