### ISSUE TITLE
Magnet Ingot recipe conflict/weirdness

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#523]
Version: 26.3.461

When an Industrial Neon Furnace has enough SP and is supplied with enough (for example a stack of) Magnetite Dust, Iron ingots and Neodymium ingots, it does not use the correct recipe 
Magnetite Dust + Iron Ingot + Neodymium Ingot -> 4 x Magnet Ingot

It instead combines it with the early game recipe
2 x Magnetite Dust + Iron Ingot -> Magnet Ingot 

In other words, the recipe it uses is the sum of the two Magnet Ingot recipes, meaning that it effectively uses the recipe
3 x Magnetite Dust + 2 x Iron Ingot + 1 x Neodymium Ingot -> 5 x Magnet Ingot

**Comment by mcenderdragon** [comment]
basicly if more recipes are available all get executed, it seems like this is not always intended / good.

**Comment by qrss** [comment]
An easy fix would be to change one of the recipes to use Iron Dust.
