### ISSUE TITLE
Part of a dungeon not under block protection

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#524]
Version: 26.3.461

Part of a dungeon was not protected (Dungeon Core not yet triggered).

For example, on the server at X Y Z 600 183 217 in the dungeon dimension.

**Comment by mcenderdragon** [comment]
I guess its just one chunk which (somehow) lost protection.

**Comment by qrss** [comment]
Do you know the server's seed, so that I can test whether the same thing would happen in a fresh world?

**Comment by mcenderdragon** [comment]
not unfortunetly not but I guess I can joind and execute the command for it

**Comment by mcenderdragon** [comment]
Also good idea to test if is seed depended.
Seed is: -6440190905258192644

**Comment by mcenderdragon** [comment]
I have rewritten the system to use chunk capabilities from now on, maybe this solves the problem for the future.
