### ISSUE TITLE
The dungeon teleporter teleports you slightly too high

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#525]
Version: 26.3.461

If there is only 2 blocks of free space above a dungeon teleporter, you take a bit of damage when teleporting back to that teleporter.

For example at X Y Z 659 70 302 on the server.

**Comment by mcenderdragon** [comment]
Bad thing is: if I dont do that there is a propability of falling strough the bottom (Old mojang bug, as they sync the heigh as byte and not as float)

**Comment by qrss** [comment]
It is fine then, it is not that big of a deal. 

I guess you can mark this as wontfix.

**Comment by mcenderdragon** [comment]
After digging around this glitching through bottom bug is the same as when entitys glitch though fences.

**Comment by qrss** [comment]
Perhaps this is the bug?
https://bugs.mojang.com/browse/MC-2025

Seems like it was fixed in 1.13.

**Comment by mcenderdragon** [comment]
yeah, basicly when the hitboxes already intersect then you will glitch though, thats why I am teleporting the player to high, I reduced the offset from 0.5 to 0.2 so the player should nolonger be inside the top block.
