### ISSUE TITLE
Silk touching Menelaus Wood drops Tyros Wood

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#528]
Version: 26.3.461

Breaking Menelaus Wood with a Silk Touch tool drops Tyros Wood.

Probably related to #473, as breaking the leaves of a Menelaus mushroom tree also drops untextured items of several different types, corresponding to the different configurations of the mushroom blocks.

**Comment by mcenderdragon** [comment]
I dont like silk touch ^^
