### ISSUE TITLE
[1.9.4-capabilities] Industrial Furnace don't work wiht multi Item Recepies

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#53]
The Industrialk Furnace stops/don't work, if it gets an speacial recepie (like composite metal)

**Comment by Wugand** [comment]
Also at Neon Industrial Furnace

**Comment by mcenderdragon** [comment]
cant reproduce...

**Comment by Wugand** [comment]
OK, the machines has the wrong owner (without researches)

Bug is invalid!
