### ISSUE TITLE
Opti bench duplication bug

### ISSUE THREAD

**Issue by Alexandregd** [mcenderdragon/Futurepack-API#535]
The bug can be replicated using 2 opti benches (The ones you can get in creative) and connecting then using thermal expansion itemducts with the worst servo. You need to in one of the opti benches place a recipe to make something into a block and in the other to make the block into the something. I belive the opti bench of the something must be nearly full for it to work and that it's somehow related on how itemducts with the worst servo move 8 items at a time.

**Comment by mcenderdragon** [comment]
see https://github.com/mcenderdragon/Futurepack-API/issues/111 :P

**Comment by mcenderdragon** [comment]
We will see if anyone discovers the full thing.

**Comment by Crocolode** [comment]
So... It's not a bug, it's a feature?

**Comment by mcenderdragon** [comment]
right. This was the whole purpose of the optibench. looping the output and input was never ment to be used this much though.
