### ISSUE TITLE
Spawning on Menelaus 

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#54]
The weather and weather-timer schould be reseted when you sleep on menelaus.

Sleeping at day sould be blocked "you can only sleep at night".

Spawnpoint sould be set at the side of bed, not inside the bed.

Spawnpoint for spaceship sould set to the position in front of boardcomputer, and not inside it.
Teleport set the player ~3 Blocks to high.

**Comment by Wugand** [comment]
At respawn in bed:  The client set the position correctly, after a few seconds you will be teleportet into the upper block of bed.

**Comment by Wugand** [comment]
_"Sleeping at day sould be blocked "you can only sleep at night"."_

It works on multiplayer Server correctly

**Comment by mcenderdragon** [comment]
rain/thunder is all like the main world

**Comment by mcenderdragon** [comment]
and sleeping is blocked while daytime

**Comment by mcenderdragon** [comment]
The IN-bed-respawn is because ic hange the player position to the exactly point were you should respawn (else you can spawn outside your shipe)

**Comment by Wugand** [comment]
rain/thunder is ok how it is; no need to fix

**Comment by mcenderdragon** [comment]
is it now working ? (24.2.5 or higher)

**Comment by Wugand** [comment]
it looks like, but i like to test it some more
