### ISSUE TITLE
Crash when shift over Block Breaker in inventory

### ISSUE THREAD

**Issue by TheRealM18** [mcenderdragon/Futurepack-API#541]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ZarakLIBCore (ZarakLIB.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  AstralCore (astralsorcery-1.12.2-1.10.10.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  LoadingPlugin (Reskillable-1.12.2-1.11.0.jar)
  DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
  Wizardry Plugin (wizardry-0.9.9.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 2/1/19 1:14 PM
Description: Rendering screen

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at futurepack.common.block.TileEntityBlockBreaker.getInputSide(TileEntityBlockBreaker.java:271)
	at futurepack.common.block.TileEntityBlockBreaker.getOutputSide(TileEntityBlockBreaker.java:265)
	at futurepack.common.block.TileEntityBlockBreaker.hasCapability(TileEntityBlockBreaker.java:309)
	at futurepack.depend.api.helper.HelperInventory.getHandler(HelperInventory.java:191)
	at futurepack.common.item.ItemMetaMultiTex.displayStoredItems(ItemMetaMultiTex.java:206)
	at futurepack.common.item.ItemMetaMultiTex.func_77624_a(ItemMetaMultiTex.java:190)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.gui.GuiScreen.func_191927_a(GuiScreen.java:143)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at net.minecraft.client.gui.inventory.GuiChest.func_73863_a(SourceFile:33)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at futurepack.common.block.TileEntityBlockBreaker.getInputSide(TileEntityBlockBreaker.java:271)
	at futurepack.common.block.TileEntityBlockBreaker.getOutputSide(TileEntityBlockBreaker.java:265)
	at futurepack.common.block.TileEntityBlockBreaker.hasCapability(TileEntityBlockBreaker.java:309)
	at futurepack.depend.api.helper.HelperInventory.getHandler(HelperInventory.java:191)
	at futurepack.common.item.ItemMetaMultiTex.displayStoredItems(ItemMetaMultiTex.java:206)
	at futurepack.common.item.ItemMetaMultiTex.func_77624_a(ItemMetaMultiTex.java:190)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.gui.GuiScreen.func_191927_a(GuiScreen.java:143)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at net.minecraft.client.gui.inventory.GuiChest.func_73863_a(SourceFile:33)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiChest
	Mouse location: Scaled: (336, 165). Absolute: (1010, 521)
	Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheRealM18'/457815, l='MpServer', x=-48.25, y=75.88, z=-48.05]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-72,64,-35), Chunk: (at 8,4,13 in -5,-3; contains blocks -80,0,-48 to -65,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 4535787 game time, 4636412 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 63 total; [EntityItem['item.item.rottenFlesh'/530957, l='MpServer', x=8.31, y=68.00, z=-23.72], EntityBat['Bat'/534542, l='MpServer', x=-127.99, y=29.10, z=-32.68], EntityItem['item.item.rottenFlesh'/530692, l='MpServer', x=-92.05, y=74.00, z=-39.29], EntitySkeleton['Skeleton'/537883, l='MpServer', x=-126.50, y=27.00, z=-52.50], EntityBat['Bat'/536855, l='MpServer', x=-121.84, y=34.57, z=-44.94], EntitySkeleton['Skeleton'/537129, l='MpServer', x=-23.50, y=44.00, z=-115.50], EntitySquid['Squid'/537135, l='MpServer', x=9.54, y=59.73, z=-103.48], EntitySkeleton['Skeleton'/529441, l='MpServer', x=-47.50, y=70.00, z=-24.51], EntityZombie['Zombie'/536895, l='MpServer', x=17.50, y=59.00, z=-62.50], EntityItem['item.item.rottenFlesh'/530995, l='MpServer', x=-27.12, y=71.00, z=8.71], EntityArmorStand['Armor Stand'/171068, l='MpServer', x=-37.50, y=73.00, z=-53.50], EntityZombie['Zombie'/537418, l='MpServer', x=22.50, y=18.00, z=-4.50], EntityZombie['Zombie'/537419, l='MpServer', x=22.50, y=18.00, z=-2.50], EntityZombie['Zombie'/537420, l='MpServer', x=21.50, y=18.00, z=-3.50], EntityWolf['Wolf'/72, l='MpServer', x=-71.50, y=75.00, z=-79.44], EntityPlayerSP['TheRealM18'/457815, l='MpServer', x=-48.25, y=75.88, z=-48.05], EntityRabbit['Rabbit'/84, l='MpServer', x=-110.93, y=62.00, z=-4.52], EntityBat['Bat'/538716, l='MpServer', x=13.89, y=16.34, z=-98.29], EntityEvilWizard['Wizard'/536671, l='MpServer', x=-26.50, y=31.00, z=-143.50], EntityZombie['Zombie'/534100, l='MpServer', x=-83.50, y=25.00, z=-110.50], EntityItem['item.item.string'/531298, l='MpServer', x=-18.49, y=16.00, z=12.53], EntityZombie['Zombie'/536163, l='MpServer', x=-3.50, y=45.00, z=-116.50], EntityZombie['Zombie'/538726, l='MpServer', x=10.50, y=22.00, z=-105.50], EntityBat['Bat'/536700, l='MpServer', x=-28.25, y=41.10, z=-109.07], EntityBat['Bat'/536688, l='MpServer', x=-98.54, y=22.29, z=-46.25], EntityItem['item.item.rottenFlesh'/530569, l='MpServer', x=-98.47, y=64.00, z=-13.32], EntityBat['Bat'/538765, l='MpServer', x=12.66, y=30.26, z=-109.77], EntityItem['item.item.rottenFlesh'/530575, l='MpServer', x=-76.13, y=66.00, z=4.25], EntityZombie['Zombie'/537987, l='MpServer', x=-35.50, y=31.00, z=-126.50], EntityBat['Bat'/538499, l='MpServer', x=-22.34, y=13.08, z=-127.65], EntityItem['item.item.arrow'/531076, l='MpServer', x=-55.17, y=71.00, z=-0.62], EntityCreeper['Creeper'/537733, l='MpServer', x=-121.50, y=18.00, z=-88.50], EntityCreeper['Creeper'/537734, l='MpServer', x=-123.50, y=18.00, z=-88.50], EntityOtherPlayerMP['DrVox'/420692, l='MpServer', x=-47.82, y=75.88, z=-48.32], EntityZombie['Zombie'/537479, l='MpServer', x=-121.50, y=25.00, z=-90.50], EntitySkeleton['Skeleton'/537735, l='MpServer', x=-123.50, y=18.00, z=-86.50], EntitySquid['Squid'/536475, l='MpServer', x=-3.40, y=58.26, z=-100.68], EntityItem['item.item.rottenFlesh'/530579, l='MpServer', x=-98.88, y=65.00, z=2.65], EntityItem['item.item.arrow'/533164, l='MpServer', x=8.13, y=18.00, z=-107.00], EntityItem['item.item.bone'/533165, l='MpServer', x=8.14, y=18.00, z=-106.74], EntityZombie['Zombie'/537506, l='MpServer', x=-118.50, y=33.00, z=-46.50], EntitySkeleton['Skeleton'/538791, l='MpServer', x=-18.50, y=39.00, z=-114.50], EntityZombie['Zombie'/534968, l='MpServer', x=-31.50, y=45.00, z=-123.50], EntityPig['Pig'/181, l='MpServer', x=2.77, y=71.00, z=-61.29], EntityZombie['Zombie'/537277, l='MpServer', x=-102.20, y=25.00, z=-40.51], EntityBat['Bat'/537270, l='MpServer', x=18.55, y=22.07, z=30.70], EntityPolarBear['Polar Bear'/191, l='MpServer', x=26.05, y=64.00, z=-7.06], EntityPolarBear['Polar Bear'/192, l='MpServer', x=25.50, y=64.00, z=5.49], EntityZombie['Zombie'/538830, l='MpServer', x=20.50, y=24.00, z=-38.50], EntityCreeper['Creeper'/536007, l='MpServer', x=-31.50, y=14.00, z=-124.50], EntityCreeper['Creeper'/538584, l='MpServer', x=-118.50, y=25.00, z=-88.50], EntityZombie['Zombie'/538585, l='MpServer', x=31.50, y=45.00, z=31.50], EntityItem['item.item.bone'/538588, l='MpServer', x=-51.39, y=70.00, z=-23.77], EntityItem['item.item.bone'/534225, l='MpServer', x=-46.85, y=70.00, z=-22.82], EntitySpider['Spider'/538579, l='MpServer', x=-127.50, y=27.00, z=-52.50], EntitySkeleton['Skeleton'/537302, l='MpServer', x=18.79, y=56.00, z=-60.49], EntitySquid['Squid'/538593, l='MpServer', x=-8.25, y=58.31, z=-106.85], EntitySquid['Squid'/538595, l='MpServer', x=-13.60, y=60.00, z=-110.99], EntityZombie['Zombie'/537573, l='MpServer', x=-103.50, y=24.00, z=-53.50], EntityCreeper['Creeper'/538087, l='MpServer', x=-24.50, y=45.00, z=-112.50], EntityEnderman['Enderman'/532199, l='MpServer', x=-10.50, y=46.00, z=-116.50], EntityItem['item.item.rottenFlesh'/530936, l='MpServer', x=-96.70, y=71.00, z=-43.70], EntityBat['Bat'/538352, l='MpServer', x=-101.91, y=25.09, z=-102.11]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 788371208 bytes (751 MB) / 2228748288 bytes (2125 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -Xmx8192m -Xms256m -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2808 Optifine OptiFine_1.12.2_HD_U_E3 84 mods loaded, 84 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                  | Source                                            | Signature                                |
	|:------ |:------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                 | 9.42                     | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2808.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2808             | forge-1.12.2-14.23.5.2808.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | foamfixcore         | 7.7.4                    | minecraft.jar                                     | None                                     |
	| LCHIJA | opencomputers|core  | 1.7.3.146                | minecraft.jar                                     | None                                     |
	| LCHIJA | ctm                 | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                         | None                                     |
	| LCHIJA | appliedenergistics2 | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | bdlib               | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                      | None                                     |
	| LCHIJA | ae2stuff            | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                     | None                                     |
	| LCHIJA | baubles             | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCHIJA | p455w0rdslib        | 2.0.36                   | p455w0rdslib-1.12.2-2.0.36.jar                    | None                                     |
	| LCHIJA | ae2wtlib            | 1.0.6                    | AE2WTLib-1.12.2-1.0.6.jar                         | None                                     |
	| LCHIJA | forgelin            | 1.8.2                    | Forgelin-1.8.2.jar                                | None                                     |
	| LCHIJA | thaumcraft          | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                  | None                                     |
	| LCHIJA | thaumic_arcana      | 1.2.0                    | Thaumic Arcana-1.2.0.jar                          | None                                     |
	| LCHIJA | jei                 | 4.14.4.264               | jei_1.12.2-4.14.4.264.jar                         | None                                     |
	| LCHIJA | appleskin           | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| LCHIJA | astralsorcery       | 1.10.10                  | astralsorcery-1.12.2-1.10.10.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | betteradvancements  | 0.0.16.71                | BetterAdvancements-1.12.2-0.0.16.71.jar           | None                                     |
	| LCHIJA | biomesoplenty       | 7.0.1.2425               | BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar     | None                                     |
	| LCHIJA | guideapi            | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                       | None                                     |
	| LCHIJA | bloodmagic          | 1.12.2-2.3.3-101         | BloodMagic-1.12.2-2.3.3-101.jar                   | None                                     |
	| LCHIJA | bloodarsenal        | 1.12.2-2.1.0-25          | BloodArsenal-1.12.2-2.1.0-26.jar                  | None                                     |
	| LCHIJA | botania             | r1.10-358                | Botania r1.10-358.jar                             | None                                     |
	| LCHIJA | chisel              | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| LCHIJA | reskillable         | 1.12.2-GRADLE:BUILD      | Reskillable-1.12.2-1.11.0.jar                     | None                                     |
	| LCHIJA | theoneprobe         | 1.4.27                   | theoneprobe-1.12-1.4.27.jar                       | None                                     |
	| LCHIJA | compatskills        | 1.12.2-1.13.2            | CompatSkills-1.12.2-1.13.2.jar                    | None                                     |
	| LCHIJA | dummycore           | 2.4.112.5.               | DummyCoreUnofficial-2.4.112.5.jar                 | None                                     |
	| LCHIJA | ebwizardry          | 4.1.4                    | Electroblob's Wizardry - 4.1.4 - MC 1.12.2.jar    | None                                     |
	| LCHIJA | ic2                 | 2.8.109-ex112            | industrialcraft-2-2.8.109-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | emt                 | B_EMT3.4                 | EMT-R_EMT10.5.jar                                 | None                                     |
	| LCHIJA | ea                  | 1.0.1                    | ExpandedArcanum-1.0.1.jar                         | None                                     |
	| LCHIJA | extrabotany         | 51                       | ExtraBotany-r1.1-51.jar                           | None                                     |
	| LCHIJA | extracells          | 2.6.2                    | ExtraCells-1.12.2-2.6.2a.jar                      | None                                     |
	| LCHIJA | extraskills         | 1.0.2                    | extraskills-1.12.2-1.0.2.jar                      | None                                     |
	| LCHIJA | familiarfauna       | 1.0.11                   | FamiliarFauna-1.12.2-1.0.11.jar                   | None                                     |
	| LCHIJA | fancylamps          | 1.0.4                    | fancylamps-1.0.4.jar                              | None                                     |
	| LCHIJA | foamfix             | 0.10.3-1.12.2            | foamfix-0.10.3-1.12.2.jar                         | None                                     |
	| LCHIJA | fp                  | 26.3.488                 | Futurepack-1.12.2-26.3.488.jar                    | 3ad693059337b95c41b649ec9f29c4a6e8282586 |
	| LCHIJA | fpatcore            | Version.version          | Futurepack Addons 1.2.jar                         | None                                     |
	| LCHIJA | fpatarmory          | Version.version          | Futurepack Addons 1.2.jar                         | None                                     |
	| LCHIJA | fpatdecoration      | Version.version          | Futurepack Addons 1.2.jar                         | None                                     |
	| LCHIJA | fpatforestry        | Version.version          | Futurepack Addons 1.2.jar                         | None                                     |
	| LCHIJA | fp.api              | 1.1.0                    | Futurepack-1.12.2-26.3.488.jar                    | None                                     |
	| LCHIJA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jeresources         | 0.8.9.48                 | JustEnoughResources-1.12.2-0.8.9.48.jar           | None                                     |
	| LCHIJA | jeroreintegration   | 1.1.0                    | JEROreIntegration-1.12.2-1.1.0.jar                | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.5.3             | journeymap-1.12.2-5.5.3.jar                       | None                                     |
	| LCHIJA | justenoughbuttons   | 1.12-1.2                 | justenoughbuttons-1.12.2-1.2.3.jar                | None                                     |
	| LCHIJA | jee                 | 1.0.6                    | JustEnoughEnergistics-1.12.2-1.0.6.jar            | None                                     |
	| LCHIJA | librarianlib        | 4.15                     | librarianlib-1.12.2-4.15.jar                      | None                                     |
	| LCHIJA | mcmultipart         | 2.5.3                    | MCMultiPart-2.5.3.jar                             | None                                     |
	| LCHIJA | morpheus            | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                       | None                                     |
	| LCHIJA | mousetweaks         | 2.9                      | MouseTweaks-2.9-mc1.12.2.jar                      | None                                     |
	| LCHIJA | zaraklib            | 0.0.4                    | ZarakLIB.jar                                      | None                                     |
	| LCHIJA | multibags           | 0.0.4                    | MultiBags-0.0.5.jar                               | None                                     |
	| LCHIJA | obsdianarcanepatch  | 1.15                     | Obsdian_Arcane_Patch_[1.15].jar                   | None                                     |
	| LCHIJA | opencomputers       | 1.7.3.146                | OpenComputers-MC1.12.2-1.7.3.146.jar              | None                                     |
	| LCHIJA | parrotpower         | 1.12.2                   | parrotpower-1.3.3.jar                             | None                                     |
	| LCHIJA | reciperesearch      | 1.0                      | RecipeResearch-0.5.0.jar                          | None                                     |
	| LCHIJA | runecraft           | 2.0.2                    | RuneCraft-1.12.2-(v.2.0.2).jar                    | None                                     |
	| LCHIJA | rustic              | 1.0.15                   | rustic-1.0.15.jar                                 | None                                     |
	| LCHIJA | rusticthaumaturgy   | 1.0                      | Rustic Thaumaturgy-3.3.jar                        | None                                     |
	| LCHIJA | rusticbopwoods      | 1.0                      | rusticbopwoods-1.0.jar                            | None                                     |
	| LCHIJA | satako              | 2.23                     | Satako 1.12-2.23.jar                              | None                                     |
	| LCHIJA | sereneseasons       | 1.2.15                   | SereneSeasons-1.12.2-1.2.15-universal.jar         | None                                     |
	| LCHIJA | swiss               | 1.0.0                    | SwissArmyKnife_V1.2_MC1.12.2.jar                  | None                                     |
	| LCHIJA | thaumicbases        | 3.3.310.5r               | tb-3.3.310.5r.jar                                 | None                                     |
	| LCHIJA | tc6aspects4jei      | 0.0.2a                   | tc6aspects4jei-0.0.2a.jar                         | None                                     |
	| LCHIJA | thaumic_calculator  | 0.4                      | Thaumic Calculations-1.12.2-0.4.jar               | None                                     |
	| LCHIJA | tg                  | 0.1.5.0                  | Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar          | None                                     |
	| LCHIJA | thaumcomp           | 0.4.4                    | ThaumicComputers-MC1.12.2-0.4.4.jar               | None                                     |
	| LCHIJA | thaumicjei          | 1.2.1                    | ThaumicJEI-1.12.2-1.5.5-23.jar                    | None                                     |
	| LCHIJA | thaumicenergistics  | 2.1.0                    | thaumicenergistics-2.1.0.jar                      | None                                     |
	| LCHIJA | tcinventoryscan     | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar        | None                                     |
	| LCHIJA | thaumicperiphery    | 0.3.0                    | thaumicperiphery-0.3.0.jar                        | None                                     |
	| LCHIJA | thaumicrestoration  | 1.2.0                    | ThaumicRestoration-1.2.0.jar                      | None                                     |
	| LCHIJA | thaumictinkerer     | 1.12.2-5.0-353c71c       | thaumictinkerer-1.12.2-5.0-353c71c.jar            | None                                     |
	| LCHIJA | wct                 | 3.11.88                  | WirelessCraftingTerminal-1.12.2-3.11.88.jar       | None                                     |
	| LCHIJA | wizardry            | 0.9.9                    | wizardry-0.9.9.jar                                | None                                     |
	| LCHIJA | worldedit           | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LCHIJA | librarianliblate    | 4.15                     | librarianlib-1.12.2-4.15.jar                      | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ZarakLIBCore (ZarakLIB.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
AstralCore (astralsorcery-1.12.2-1.10.10.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (Reskillable-1.12.2-1.11.0.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
  DummyCore.ASM.DCASMManager
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
  li.cil.oc.common.asm.ClassTransformer
Wizardry Plugin (wizardry-0.9.9.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13521 Compatibility Profile Context 24.20.11020.2' Renderer: 'Radeon 550 Series'
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Futurepack Applied Energistics 2 Version: @aechannel@ @version@ for Forge 14.23.5.2784
	List of loaded APIs: 
		* ae2wtlib|api (1.1) from AE2WTLib-1.12.2-1.0.6.jar
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-6.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* betteradvancements|API (0.0.16.71) from BetterAdvancements-1.12.2-0.0.16.71.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
		* bloodmagic-api (2.0.0) from BloodMagic-1.12.2-2.3.3-101.jar
		* BotaniaAPI (92) from Botania r1.10-358.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.8-63.jar
		* jeresources|API (0.8.9.48) from JustEnoughResources-1.12.2-0.8.9.48.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.3.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.3.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.3.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.3.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.3.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.14.4.264.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.9-mc1.12.2.jar
		* opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.3.146.jar
		* opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.3.146.jar
		* opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.3.146.jar
		* opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.3.146.jar
		* opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.3.146.jar
		* opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.3.146.jar
		* opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.3.146.jar
		* opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.3.146.jar
		* opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.3.146.jar
		* opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.3.146.jar
		* opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.3.146.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12.2-2.0.36.jar
		* Thaumcraft|API (6.0.2) from Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.27.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.11.88.jar
	[DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''dummycore'
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: forge-14.23.5.2808
	LWJGL: 2.9.4
	OpenGL: Radeon 550 Series GL version 4.5.13521 Compatibility Profile Context 24.20.11020.2, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 1500X Quad-Core Processor

**Comment by mcenderdragon** [comment]
Should be fixed: [26.4.19](https://redsnake-games.de/Downloads/fp/fp.php?t=RUOV.QiJk01OYMpKwMK8jw--)
