### ISSUE TITLE
[1.12.2] [suggestion] Magnetite Block OreDict

### ISSUE THREAD

**Issue by ToMe25** [mcenderdragon/Futurepack-API#544]
Please register the Magnetite Block as OreDictionary "blockMagnetite" to prevent Mods like [JAOPCA](https://minecraft.curseforge.com/projects/jaopca) from adding their own Magnetite Blocks and make it compatible with some Stuff.

**Comment by mcenderdragon** [comment]
I could have sworn we did that...

**Comment by SkyProgs** [comment]
We don't support 1.12.2 anymore.
