### ISSUE TITLE
[1.12.2-26.4.57] Unused "fp:stone" with metadata 7 & 8 are missing and have oredict entries

### ISSUE THREAD

**Issue by Compegen** [mcenderdragon/Futurepack-API#555]
"fp:stone" with metadata 7 & 8 have "oreCobblestone" & "oreStone" as an oredict entry respectively, causing it to be visible in JEI with missing textures when looking at recipes that use cobblestone or stone.

![Capture](https://user-images.githubusercontent.com/8009507/54250693-d06c5800-4512-11e9-9798-fe3b472182b8.PNG)

**Comment by mcenderdragon** [comment]
do they have texture when placed ?

**Comment by Compegen** [comment]
They do. The main issue right now is that these blocks are completely unused/ unobtainable currently (not even showing in the item pane in JEI, had to use give command), but JEI still adds them to recipes.

**Comment by SkyProgs** [comment]
Unfortunately, we can no longer support the 1.12.2.
