### ISSUE TITLE
Server crash - IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#559]
https://gist.github.com/ProsperCraft/2be261112b720332ef5db500a39fb97f

**Comment by ProsperCraft** [comment]
Here is another one - 
https://paste.fedoraproject.org/paste/-WVQOmIKyqvHtfwv9HPn2A

**Comment by Reveter** [comment]
Just for reference, I was switching the chips in an absorption laser at a mob farm when this happened

**Comment by mcenderdragon** [comment]
Fixed in 26.4.59
