### ISSUE TITLE
[Feature Request] Sharing Research

### ISSUE THREAD

**Issue by litjohn50** [mcenderdragon/Futurepack-API#564]
Could you code in a way to Share my research with another person via some sort of mystical tablet. Or a command to join the same team so both you and your friend gets credit. 

Doing research with more then 1 person in a base is really laborious an tedious. Some research takes a lot of SP Power and Time to complete.

**Comment by mcenderdragon** [comment]
Honestly I have been waiting for someone to make an addon just to do that...

**Comment by mcenderdragon** [comment]
![1.14.4 research sharing](https://cdn.discordapp.com/attachments/501722590214225932/663373450324213790/2020-01-04_23.11.54.png)
