### ISSUE TITLE
Morpheus compatibility

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#57]
(Feature)
It would be nice to get Morpheus working on Menelaus and Tyros.

**Comment by mcenderdragon** [comment]
dunnio how they do this, these dimensions are completly undependent of the mayyn world, so if all sleep in menelaus the sleep in aktivated.

**Comment by mcenderdragon** [comment]
@Quetzi, you are currently working on Morpheus, right? Is this also working in other Dimensions ?

**Comment by Quetzi** [comment]
Dimensions are fully supported in Morpheus...to an extent. I have no way of knowing how long a day night cycle is on non vanilla dimensions so mods that add dimensions need to provide a method to advance to the next morning. The latest api can be downloaded from my build server http://Jenkins.qmunity.co.uk

**Comment by mcenderdragon** [comment]
Ahh okay thanks, thats a very good api. Are there any restrictions when I have to register my Handler (Pre,Init,Post) ?

**Comment by Quetzi** [comment]
At any point, most sensible is when the world is loaded

**Comment by mcenderdragon** [comment]
At the moment they get registered when the provider is created so I have the right world to manipulate.

**Comment by mcenderdragon** [comment]
@Wugand please check at our server if this is now working.

**Comment by Wugand** [comment]
No, Morpheus register sleeping, but don't trigger the "time manipulation" or wake up.
expect if Morpheus is installed everybody have to sleep.

**Comment by mcenderdragon** [comment]
But it doest crash? Does it work in 24.2.9 ?

**Comment by mcenderdragon** [comment]
is it working?

**Comment by mcenderdragon** [comment]
@Wugand an answer ?
