### ISSUE TITLE
A folder is created "ores"

### ISSUE THREAD

**Issue by kellixon** [mcenderdragon/Futurepack-API#573]
I'm using a portable version of Minecraft. Is it possible to change the path of the "ores" folder so that it is not created every time.
![Безымянный](https://user-images.githubusercontent.com/22012731/58800674-208a2080-8611-11e9-884b-b9181dca5c96.jpg)

**Comment by mcenderdragon** [comment]
This file is supposed to be in the world sub folder ores. Seems like something fucked up and wiped the directory name out of world and thus I was no longer able to locate the correct path.

**Comment by bvierra** [comment]
This also happens with packs installed from twitch. From the [latest.log](https://github.com/mcenderdragon/Futurepack-API/files/3261523/latest.log):

`[futurepack.api.resources.FuturepackDefaultResources:extractDefaults:163]: java.io.FileNotFoundException: C:\Users\<user>\AppData\Roaming\.minecraft\assets\objects\f2\f2e96e23bdf8ca19904ef8502ad0e9d1634b0512 (The system cannot find the path specified)`
 
The issue by what I can  see is that it should never be trying to access 
`C:\Users\<user>\AppData\Roaming\.minecraft`
But instead trying to write inside of:
`C:\Users\<user>\Documents\Curse\Minecraft\Instances\TownCraft`

Also:
`C:\Users\<user>\AppData\Roaming\.minecraft\assets\` is an empty directory.

**Comment by mcenderdragon** [comment]
@bvierra where is your assets folder located then?
It is normal created by the launcher and contains subfolders named `indexes`, `objects `and `skins`.

**Comment by bvierra** [comment]
@mcenderdragon I have approx 50 mod packs installed from twitch and about 10 in MultiMC (checked em both). It appears that the correct location is like so:

`<instance folder>\resources\<mod name>\`

<instance folder> is the java arg specified on startup `-Dminecraft.applet.TargetDirectory=c:\path\to\instance\folder`

Everything after the `<mod name>` is the path to file. For example

`<instance folder>\resources\fp\assets\textures\texture.jpg`

seems to be referenced as:

`fp:/assets/textures/texture.jpg`

I however may be incorrect as I dont make mods, this is just my observation.

I also noticed that they all seemed to have https://minecraft.curseforge.com/projects/resource-loader installed as well and the info re the resource loader mod seems to fit this correctly, I however may be way off on this.

**Comment by mcenderdragon** [comment]
the resources folder is made by the resource-loader mod, but assets is a vanilla thing. (they no longer store all their sounds & languages in the jar only textures). you never did use the vanilla lauchner right? this would explain why these folders do not exists, Seems like I need to make sure the folders exists so I can write to them.

**Comment by bvierra** [comment]
Sorry missed the reply :) That is correct I have not used the vanilla launcher directly since I reinstalled windows last.

**Comment by mcenderdragon** [comment]
I honstly did not expect that to happen ^^, so I need to check if all the folders exists.

**Comment by mcenderdragon** [comment]
Should be fixed [26.4.83](https://redsnake-games.de/Downloads/fp/fp.php?t=OM__ZHpnu34UNqyobRKvkg--)
