### ISSUE TITLE
Lime Neon Lamp and Plasma Lamp use Green Bulletproof Glass instead of Lime

### ISSUE THREAD

**Issue by TeetoKaziim** [mcenderdragon/Futurepack-API#575]
Result being that the Green and Lime Green Lamps have the same recipe.

**Comment by mcenderdragon** [comment]
Should be fixed: [26.4.84](https://redsnake-games.de/Downloads/fp/fp.php?t=4Epm2BVmSSt6NLmExvMyiQ--)

**Comment by TeetoKaziim** [comment]
Appears fixed :D

**Comment by mcenderdragon** [comment]
reopneing this until the fix is avaiable on curseforge
