### ISSUE TITLE
Player kicked when placing experience in to an experience module clicking +.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#576]
The player had 15 levels.

Relevant log section-
https://gist.github.com/ProsperCraft/980d5d8c3df141e119b5ce3c6b6e8ec2

Futurepack-1.12.2-26.4.82

[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/3412160/FP-Latest.log)
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/3412161/latest.log)
[CustomNPCs-latest.log](https://github.com/mcenderdragon/Futurepack-API/files/3412162/CustomNPCs-latest.log)

**Comment by mcenderdragon** [comment]
I see, sponge is stupid again...

**Comment by mcenderdragon** [comment]
Should be fixed [26.4.83](https://redsnake-games.de/Downloads/fp/fp.php?t=OM__ZHpnu34UNqyobRKvkg--)
