### ISSUE TITLE
Client crash No other mods on client

### ISSUE THREAD

**Issue by mitchngwen** [mcenderdragon/Futurepack-API#577]
Client crashes while loading with the only mod being FP. See attached crash report.
[crash-2019-07-20_15.35.16-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/3414008/crash-2019-07-20_15.35.16-client.txt)

**Comment by mcenderdragon** [comment]
Please update to the latest version: https://www.curseforge.com/minecraft/mc-mods/futurepack/files

**Comment by mitchngwen** [comment]
Still crashes, the reason I was trying an older version was because of the crashing, I thought if I went to an older version it would fix it. 
[crash-2019-07-21_09.38.46-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/3414769/crash-2019-07-21_09.38.46-client.txt)

**Comment by mcenderdragon** [comment]
Should be fixed [26.4.83](https://redsnake-games.de/Downloads/fp/fp.php?t=OM__ZHpnu34UNqyobRKvkg--)

**Comment by mitchngwen** [comment]
Awesome when does that come out?

**Comment by mcenderdragon** [comment]
when all as 'solved' marked issues are confirmed as fixed by their authors.

**Comment by mitchngwen** [comment]
lol I'm downloading now! Thank you

**Comment by mitchngwen** [comment]
No crash. Fixed
