### ISSUE TITLE
[Suggestion] Custom Planets

### ISSUE THREAD

**Issue by Trip-kun** [mcenderdragon/Futurepack-API#578]
My suggestion is to add a custom config file to add more planets (dimIDs) to futurepack without having to go through the hassle of making a whole separate mod for it

**Comment by mcenderdragon** [comment]
In 1.13/1.14 this migh be possible since we have fixed Dimension resource locations, other than that everything from [IPlanet](https://github.com/mcenderdragon/Futurepack-API/blob/1.12/futurepack/api/interfaces/IPlanet.java) has to be implemented.

**Comment by mcenderdragon** [comment]
In 1.14 you can use data pack to define custom planets like this:
data/ < modid >/planets/< dimension name >.
For example "data/futurepack/planets/envia.json"
```
{
	"texture": "futurepack:textures/gui/planet_envia.png",
	"name": "Envia",
	"upgrades": [
		"lifesupport"
	],
	"breathable_atmosphere": false,
	"oxygen_gravity_velocity": 0.4,
	"oxygen_spread_velocity": 0.2
}
```
