### ISSUE TITLE
[1.12.2-26.4.82][Albedo] Crash upon world load or creating new world

### ISSUE THREAD

**Issue by fuzzyfungi** [mcenderdragon/Futurepack-API#579]
Crashed upon loading into old world.
[crash-2019-08-30_15.47.39-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/3561969/crash-2019-08-30_15.47.39-client.txt)

Also tried creating new world and crashed upon load.
[crash-2019-08-30_15.51.44-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/3561970/crash-2019-08-30_15.51.44-client.txt)

**Comment by mcenderdragon** [comment]
Seems like the new Albedo versions made a breakign change with their API. try to downgrade to 0.1.3 https://www.curseforge.com/minecraft/mc-mods/albedo/files/2486523

**Comment by mcenderdragon** [comment]
In this version it should also work with the new API, please test: [26.4.87](https://redsnake-games.de/Downloads/fp/fp.php?t=FDvp3JW.wZUu.2rxqOdokg--)

**Comment by fuzzyfungi** [comment]
Able to load into existing world as well create and load new with 26.4.87.  Much appreciated!
