### ISSUE TITLE
Crash on Startup 

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#58]
http://pastebin.com/KGK6BhR4

**Comment by mcenderdragon** [comment]
This is a crashed caused by HardcoreQuesting, it is searching through the mod while still things get loaded... I am wokring on it.

**Comment by mcenderdragon** [comment]
OK try out this version: http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.3

**Comment by Divineaspect** [comment]
This does not crash on startup.
