### ISSUE TITLE
Error with Research recipes

### ISSUE THREAD

**Issue by DevTimur** [mcenderdragon/Futurepack-API#580]
https://pastebin.com/UQDVunu4

I made a test reserach to add, but get this error every time no matter what i do.

**Comment by DevTimur** [comment]
Example of research script
_[
	{
		"id":"util2",
		"x":-1,
		"y":-2,
		"parents":["techtabel"],
		"icon":{"name":"fp:spaceship", "meta":"<spaceship.IronStick>"},
		"enables":[],
		"need":[],
		"time":0
	}
]_

Example of Crafttweaker script
_mods.futurepack.research.addResearchFile("./FPCustomResearches/NSGen.json");_

**Comment by mcenderdragon** [comment]
The Bug is confirmed, waiting for the build to compile.

**Comment by DevTimur** [comment]
Hi, is it allowed to edit JAR file if i want to change something?
Or should i use only Crafttweaker?

**Comment by DevTimur** [comment]
For example i want to rework most of researches, add my own.
Also i want to change mobs that spawn in Boss rooms, i can change it using json in jar.

**Comment by mcenderdragon** [comment]
In theory everything should be possible without the need to edit the JAR file. If there is no other way do it, but I guess we could also try to improve the API then.
Please try with this version, it should work now: [26.4.88](https://redsnake-games.de/Downloads/fp/fp.php?t=Of_5EPeeGZHk5C7V188QiA--)

**Comment by DevTimur** [comment]
DEFFINETLY WORKS!
Thank you!

**Comment by DevTimur** [comment]
btw, does it ment to be so Dungeon Core does not drop anything when broken?

**Comment by mcenderdragon** [comment]
Yes, this block can only undo the while dungeon protection. So the loot of this block is more or less the whole dungeon.

**Comment by DevTimur** [comment]
ok... got this error when tryed to REPLACE existing research with my own.
https://pastebin.com/qcpu95eZ
If it ment to be so, then how do i remove/replace existing researches?

**Comment by mcenderdragon** [comment]
This is currently only possible via a mod. Or rather it is not directly possible at all. YOu would instead try to alter the reasearch instance and add/remove things there. What do you want to change from the "util" research?

**Comment by DevTimur** [comment]
Util was only a test, i want to edit many researches, shuffle them, add new, remove some of them.
I want to make modpack with research progression similar to Thaumcraft, but for tech, your mod fits perfectly.

BTW, how do i make "locked" recipe?

**Comment by mcenderdragon** [comment]
> MCenderdragonheute um 14:37 Uhr
 ```
 {
   "type": "fp:research_shaped",
   "group": "fp",
   "pattern": [
     "SLS",
    "PBP",
    "RCR"
  ],
  "key": {
    "S": {
      "item": "#ironcoil"
    },
    "P": {
      "item": "#biopolymer"
    },
    "C": {
      "item": "#mastermind_core"
    },
    "R": {
      "item": "#mastermind_ram"
    },
    "L": {
      "item": "#ventilation_block"
    },
    "B": {
      "item": "#white_board_computer"
    }
  },
  "result": {
    "data": 2,
    "item": "fp:advanced_boardcomputer"
  }
}
```
>  
> Timurheute um 14:37 Uhr
> So, crafttweaker integration lacks some parts.
> For example i wantto lock some custom recipes behind research
> ok
> how do i CALL this json? using Crafttweaker?
>  
> MCenderdragonheute um 14:38 Uhr
> This is the recipe JSON from the advanced board computer, because its type is "research_shaped" it requires you to have a research with the board computer in the "enables" section
> it is the normal vanilla system for crafting recipes. I thing they do that with data packs now
>  
> Timurheute um 14:40 Uhr
> but how do i call this  file?
> similar to
> mods.futurepack.research.addResearchFile("./scripts/example.json");?
>  
> MCenderdragonheute um 14:41 Uhr
> If I understnad it correctly you dont. All files under assets/<modid>/recipes/ get loaded.
>  
> Timurheute um 14:41 Uhr
> but i should not edit JAR
>  
> MCenderdragonheute um 14:42 Uhr
> data packs or resourcepacks also work outside the jar. Like good old texture packs did
> 
I put this here in case anyone else also searches this.
