### ISSUE TITLE
Industrial Neon Furnace not working

### ISSUE THREAD

**Issue by Tyncho22** [mcenderdragon/Futurepack-API#581]
does not work to create silicone wafer (quartz) and ingot quantanium, use the command to unlock everything but it doesn't work either.  Ver (26.4.82)

**Comment by mcenderdragon** [comment]
Did you place the indutrial neon furnace or someone else?

**Comment by Tyncho22** [comment]
Single Player,  https://imgur.com/a/cLMYmKv

**Comment by mcenderdragon** [comment]
The recipes displayes you need SP points (for example 2 for quarts to silicon) but it seems like the sp tank is empty

**Comment by Tyncho22** [comment]
Thank you very much I thought I gave 2 SP for every time you build an ingot
