### ISSUE TITLE
Chunk Generation Issue

### ISSUE THREAD

**Issue by Slammyyyy** [mcenderdragon/Futurepack-API#583]
I've been playing a pack I put together with futurepack in it, when I noticed that the more I was exploring the higher and higher my memory usage was, to the point where I'd need to restart Minecraft. I looked at the console to see if anything was popping up and sure enough it was flooded with messages like this:
https://pastebin.com/dV219TUP

I've noticed it only happens when generating new chunks, if I stick around a certain area the game runs perfectly smooth. Was wondering if anyone could reproduce this

**Comment by mcenderdragon** [comment]
This seems to be a bug in older java versions, try to update your java installation, you also need to check in the laucher if your installed java is used or an older one shiped with the vanilla launcher.

**Comment by Slammyyyy** [comment]
Hmm, odd, was there a recent update to java? I'll download Java again and see if its fixed.

**Comment by Slammyyyy** [comment]
Made sure my java was up to date and the error is still showing. Double checked to make sure it was using the right one as well, and it is.

**Comment by mcenderdragon** [comment]
What java do you use? Can you provide the full log. 
For FileSystem#newFileSystem to throw an unsupported operation exception is undocumented behavior, so we will need some poking around to find the issue.
You where in the the normal overworld correct? Can you make a screenshot of your saves/world name/ores/ folder ?

**Comment by Slammyyyy** [comment]
You can close this issue; it seems to have been actually unrelated to Futurepack after further testing. There was some strange world corruption going on, any attempts to reproduce it on clean installs of Futurepack or even within the same modpack have failed.

Thanks for the help, and I love the mod, keep up the awesome work!
