### ISSUE TITLE
[BUG 1.12.2] optibench dupe

### ISSUE THREAD

**Issue by DevTimur** [mcenderdragon/Futurepack-API#585]
https://i.gyazo.com/5598bf6a491a7063eb363cfe352ddb1f.gif
Optibench stacks un-stackable items, so you can open stack of satchels, put items inside, separate them and pull items out. Easy.

**Comment by SkyProgs** [comment]
Unfortunately, we can no longer support the 1.12.2. If this happens in a newer version please open a new issue.
