### ISSUE TITLE
Redstone Pipe research has stalled.

### ISSUE THREAD

**Issue by MuniversalRabat** [mcenderdragon/Futurepack-API#587]
https://imgur.com/aGklh7W

The research is working through the first stage with the redstone itself, but it will not research the second part of it, with the pipes. That is grayed out, and nothing I can do can seem to work right. If there is anything you can suggest to help with this, I'd be grateful.

**Comment by mcenderdragon** [comment]
the image link is not working.

**Comment by MuniversalRabat** [comment]
![SystemError](https://user-images.githubusercontent.com/55272259/66778524-c29ffc00-ee80-11e9-801d-5d5059dfb65b.png)


As an aside, I have found out that this is happening with any research that has two stages, the second stage starts off blue showing '100%' and then will later show it grayed out and the research will not continue.

**Comment by mcenderdragon** [comment]
grayout means the T1 modul has not enough neon energy.

**Comment by MuniversalRabat** [comment]
Oh! Huh. I... am not sure how to fix that. But thank you for the heads up.

**Comment by MuniversalRabat** [comment]
Needs a bit better read out, no offense, but I love the research behind this.

**Comment by mcenderdragon** [comment]
> If the border of a bar turns grey it means that the resource is not available.

How could we rephrase that ?

**Comment by MuniversalRabat** [comment]
I must have missed it in my eagerness. I'm sorry.

**Comment by MuniversalRabat** [comment]
I do admit, I have no idea how o get the Neon Energy into the dang device though.

**Comment by MuniversalRabat** [comment]
Okay, I think I got it now, sorry for the bother.

**Comment by mcenderdragon** [comment]
No worries, its fine.
