### ISSUE TITLE
Mysterious Document on each login

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#59]
Not a big problem, just a small bug.

**Comment by mcenderdragon** [comment]
On each öogin? not if you dies?

**Comment by Divineaspect** [comment]
hrm, I had died, but I had done corpse retrieval already.

**Comment by mcenderdragon** [comment]
Is this fixed in the 24.2.6 ?

**Comment by Divineaspect** [comment]
confirmed resolved!
