### ISSUE TITLE
Dungeon Key 4

### ISSUE THREAD

**Issue by DrakeOStorm** [mcenderdragon/Futurepack-API#590]
Curious about the 4th Dungeon Key. I'm playing Exoria atm and have searched many dungeons from Futurepack, but have yet to find a single blueprint for Key 4.

Is finding this blueprint the correct way to unlock Key 4 in my E-Scanner research? Or am I doing something wrong?

**Comment by mcenderdragon** [comment]
Did you need the 4th key to get to the end of a dungeon yet?

**Comment by DrakeOStorm** [comment]
I did not need it yet no, so I am assuming it'll just be a force field at some normal dungeon then.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
