### ISSUE TITLE
crash when loading a structure

### ISSUE THREAD

**Issue by matyklug18** [mcenderdragon/Futurepack-API#591]
crash report: https://paste.dimdev.org/eduhuviruk.sql
using 1.12.2 version 26.4.88

**Comment by mcenderdragon** [comment]
when did this crash happened/what where you doing at the time? it looks like the registry Ids of the blocks shifted.

**Comment by mcenderdragon** [comment]
Maybe JustEnoughIDs can cause this.

**Comment by SkyProgs** [comment]
We don't support 1.12.2 anymore. If this happens in a newer version please open a new issue.
