### ISSUE TITLE
[1.14] Needs a specific Forge version?

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#592]
I'm trying to run Futurepack 28.0.0, but Forge 28.1.107 and Forge 28.1.0 both fail (with different errors).

Does it need a specific Forge version, or perhaps something else?

**Comment by mcenderdragon** [comment]
In thorie 28.1.107 should work, what is the error/crash ?

**Comment by qrss** [comment]
I'm not sure which part of the Log file is relevant, so here is the whole thing:
[2019-12-22-3.log.gz](https://github.com/mcenderdragon/Futurepack-API/files/3994949/2019-12-22-3.log.gz)

In-game, this gives me
"Error loading mods", 
"Futurepack (futurepack) encountered an error during the common_setup event phase"

**Comment by mcenderdragon** [comment]
Yeah found it, I was able to fix that but now the Access tranformers wont work so you can not laucnh into a world. I am working on that now (great how things stop to work outside the dev env)

**Comment by mcenderdragon** [comment]
Fixed! https://www.patreon.com/posts/32563642

**Comment by qrss** [comment]
Thank you!

I don't have time to playtest right now, but at least I'm able to load into a world.

Oh, and Happy Holidays!

**Comment by mcenderdragon** [comment]
Your Welcome, and Happy Holidays to you too :)
