### ISSUE TITLE
[1.14] Lag and freezing with Composite Chests

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#593]
Forge version: 28.1.107, 28.1.109

Composite chests seem to have a few issues, not sure if related.

1) When you open a Composite Chest for the first time in a session, the game lags a bit. Opening Composite Chests after the first one does not lag the game.
Not serious, but lag seems unnecessary for such a simple device. Perhaps it is Minecraft/Forge's fault, no idea.

2) Shift + clicking an item out of (or into) a Composite Chest freezes the game, seemingly permanently.

**Comment by mcenderdragon** [comment]
the shift click is fixed.

**Comment by qrss** [comment]
This does seem to be fixed in 28.0.7
