### ISSUE TITLE
[1.14] Item drop issues (on breaking)

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#594]
Forge 28.1.109

The bug with a Composite Door dropping 2 Composite Doors seems to be back.

Composite Chests don't seem to drop. (although they drop their inventory)

**Comment by mcenderdragon** [comment]
fixed.

**Comment by mcenderdragon** [comment]
Also thank you for your help in finding bugs!

**Comment by qrss** [comment]
No problem.

It is one of my favorite mods, so I don't mind playing through it once in a while and remarking on the issues :)
