### ISSUE TITLE
[1.14] Entering a Futurepack dungeon crashed the game.

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#596]
Forge 28.1.109

Entering the dungeon dimension, I got the Menelaus and Tyros achivements and the game crashed with:

[crash-2019-12-25_01.34.22-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/3999191/crash-2019-12-25_01.34.22-server.txt)

EDIT: This created a Nether Portal in the dungeon dimension way below the dungeon portal. (I think this is a Forge issue)

The dungeon portals worked fine after that though.

**Comment by mcenderdragon** [comment]
Nether Portal is a Forge issue or rather a not implemented Feature: https://github.com/MinecraftForge/MinecraftForge/pull/6017

**Comment by mcenderdragon** [comment]
The crash should be fixed.

**Comment by qrss** [comment]
Entering dungeons has not crashed yet in 28.0.7.
