### ISSUE TITLE
[1.14] Crystal sands spawn in the nether

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#600]
Forge 28.1.109

Found a patch of crystal (Neon) sand in the nether.

**Comment by mcenderdragon** [comment]
could you send me your /config/futurepack-common.toml ?

**Comment by mcenderdragon** [comment]
never mind I found the problem

**Comment by mcenderdragon** [comment]
YOu may need to delete your configs as I changed the default value of world_generation.caves to the following:
```
[world_generation.caves]
wl_alutin_cave = ["minecraft:(?!nether|end|the_end)"]
wl_neon_cave = ["minecraft:(?!nether|end|the_end)"]
```

**Comment by qrss** [comment]
Alright, thanks :)
