### ISSUE TITLE
[1.14] The Part Press GUI is untextured and the recipes don't seem to work

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#601]
The Part Press GUI has no texture and the recipes don't seem to work (as far as I can remember them).

The Part Press research page also does not list any recipes.

![2019-12-26_15 18 47](https://user-images.githubusercontent.com/32312262/71477496-23d63b00-27f3-11ea-9f66-e1e5b2ebcc7d.png)

**Comment by mcenderdragon** [comment]
fixed
