### ISSUE TITLE
[1.14] The Research Scanner GUI has missing textures

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#602]
The aspect buttons have no textures.

The main screen has no textures for the scanning results.

**Comment by mcenderdragon** [comment]
Can you make a picture?

**Comment by qrss** [comment]
Sorry, here you go.

I'll note that the SOS screen works fine.

![2019-12-26_20 24 40](https://user-images.githubusercontent.com/32312262/71486191-d3c09e00-281d-11ea-8cf1-b12ca5ce2b4c.png)

**Comment by qrss** [comment]
The aspects now have icons, but the scanner still does not show scan results. (question marks, stars, ...)
