### ISSUE TITLE
[1.14] Crash when right clicking on a Research Scanner

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#603]
I can not reproduce this, but the client crashed when the first thing did (while the chunks around me were still loading) was open the Researcher GUI, close it, and right click on the Research Scanner.

[crash-2019-12-26_20.16.53-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/4003218/crash-2019-12-26_20.16.53-client.txt)

**Comment by mcenderdragon** [comment]
This should fix alot : https://www.patreon.com/posts/32635790

**Comment by qrss** [comment]
Thanks!

I'll try it out.
