### ISSUE TITLE
[1.14] Crash with ManagerGleiter

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#604]
After I took the screenshot for the other report, I forgot to close the game.

When I came back, the game had crashed. I think the Research Scanner GUI might have been open while the game was running.

[crash-2019-12-26_20.30.22-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/4003269/crash-2019-12-26_20.30.22-client.txt)

**Comment by mcenderdragon** [comment]
```
java.lang.NullPointerException: Ticking entity
	at futurepack.common.ManagerGleiter.isGleiterOpen(ManagerGleiter.java:130) ~[?:1.14.4-28.0.3] {re:classloading}
	at futurepack.common.ManagerGleiter.onPlayerTick(ManagerGleiter.java:30) ~[?:1.14.4-28.0.3] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_51_ManagerGleiter_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
```

**Comment by qrss** [comment]
I logged back into the world, and it seems that I died from a creeper while idling.

The game crashed again while I was on the death screen (the same error).

EDIT: Yeah, It looks like I can not enter that world, because it crashes immediately after loading. I just get a glimpse of the death screen.

**Comment by qrss** [comment]
Welp, lost another world to this bug, because of dying while idling.

Fortunately, I also figured out how to reproduce this.

You just need to die.

Then the game will crash and you won't be able to load the world without crashing.

**Comment by mcenderdragon** [comment]
OOOOH, I think I know what is going on. (A dead player has no capabilities!)

**Comment by qrss** [comment]
I'll note that changing the player from dead to alive using an NBTExplorer stops the crash when the world loads.

**Comment by mcenderdragon** [comment]
New Feature: every world is now hardcore.
