### ISSUE TITLE
[1.12] Crash on startup with Futurepack

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [mcenderdragon/Futurepack-API#609]
The game crashes instantly on startup. 

https://paste.dimdev.org/exocotucub.mccrash

**Comment by mcenderdragon** [comment]
I wish I had time to fix the 1.12 version...

**Comment by ErnestoPeroPezzi** [comment]
Bless your soul dont stretch yourself thin we love you anyways

**Comment by mcenderdragon** [comment]
In a few hours there will be a 26.4.89 on curse where this is fixed
