### ISSUE TITLE
Magnetic ore is incombatilbe with WaterPower

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#61]
WaterPower is adding magnetite ore too, but they ores are not compatible. (1.10.2 + any other?)

**Comment by Wugand** [comment]
Analysis with WaterPower-1.10.2-0.4.5. :
 Ore don't match: OreMagnetite vs OreMagnet
 Ingot and Dust use the same OreDict.
 FuturePack can work with both of them.
 Problem: WaterPower don't use OreDict for their Crafting or in their IC2-Recepies
 
Result:
 FuturePack make everything correctly. Problem is located at WaterPower!
 
I report it to them.

Can be closed!
