### ISSUE TITLE
[1.14] Research seems to be broken

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#610]
When I try to do the first Production research, the Researcher says that I need to provide 1 Furnace, but it does not seem to accept the furnace.

![researcher](https://user-images.githubusercontent.com/32312262/71583599-d241ef00-2b17-11ea-91df-25c3ba30621d.gif)

**Comment by mcenderdragon** [comment]
The amount of needed items is displayed wrong.

**Comment by mcenderdragon** [comment]
https://www.patreon.com/posts/32839150

**Comment by qrss** [comment]
This does seem to be fixed.
