### ISSUE TITLE
[1.12.2] Conflict with Ender IO

### ISSUE THREAD

**Issue by Charpis** [mcenderdragon/Futurepack-API#611]
The mod conflicts with Ender IO. When you hover over a block, a black border will appear around the Sun, a yellow bar will appear on the horizon, and the stars will turn black. I was removing one mod at a time from the build, and after I removed Ender IO, the error disappeared. After each mod, I created a new world.
Sorry about my English, I used a translator.
![2019-12-30_22 30 33](https://user-images.githubusercontent.com/46600166/71597560-c45e8f00-2b54-11ea-963d-d247e06cad1b.png)
![2019-12-30_22 30 34](https://user-images.githubusercontent.com/46600166/71597562-c9bbd980-2b54-11ea-87b6-4ed3117a1eec.png)

**Comment by mcenderdragon** [comment]
So only with EnderIO & Futurepack installed this is happening? This is no longer happening when Futurtepack is deinstalled?

**Comment by Charpis** [comment]
When you delete Futurepack or Ender IO, the error disappears. Also, I recently put the albedo Compat mod together with its Albedo core, everything was the same as with Ender IO, but the whole world lost the texture and it was just a light gray color, but I did not take a screenshot at that time.

**Comment by mcenderdragon** [comment]
Do you have optifine installed?

**Comment by Charpis** [comment]
Yes, installed.

**Comment by mcenderdragon** [comment]
Then deinstall optifine, this is most likely causing this. Also try to remove whatever mod is making this overlay when you look at a block and see if that changes something.

**Comment by Charpis** [comment]
I removed Optifine, added Ender IO and Albedo compact, there were no bugs with textures.

**Comment by mcenderdragon** [comment]
seems like optifine is causing this.
