### ISSUE TITLE
[1.12.2] The belowbedrock dim has the dim setting at 128 but builds over that.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#615]
We were having an issue where graves were not spawning in the mazes, and the author found the issue, the dim is set for 128 high but builds above this which means that the grave was looking for a place to put the grave below 128 but could not.

Please revise the getActualHeigth to reflect what the dim really is.

**Comment by mcenderdragon** [comment]
In a few hours there will be a 26.4.89 on curse where this is fixed

**Comment by mcenderdragon** [comment]
https://www.curseforge.com/minecraft/mc-mods/futurepack/files/2856874
