### ISSUE TITLE
[1.12.2] Dims register as the overworld.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#616]
![2020-01-11_09 17 50](https://user-images.githubusercontent.com/4427684/72207536-5751d000-3457-11ea-8074-888f7b443f70.png)

This causes issues with plugins that give protections the rely on dim names.  It protects the same areas in all of the dims labeled World-towncraft which is the name of the overworld.

Interestingly enough, the below bedrock dim is registered correctly, I suspect because it is the newest.

**Comment by mcenderdragon** [comment]
Only dim 0 is the overworld, and Dimension have to property to have a surface which all planets have. Also there is no name for dimeniosn in 1.12 only IDs so this is up to the plugin maker to fix.

**Comment by mcenderdragon** [comment]
I asume they use old mapping for name and thus got the wrong impression about some methods. we have hasSkyLight  and canRespawnHere both are ture for Menelaus,Tyros & Envia. But at some point around 1.9 one was called isOverworld. I hope you see disabling skylight will cover these planets in enternal darkness as if they were the nether and disabling respawning on them would steal your spaceship.
