### ISSUE TITLE
[1.14] Futurepack mod menu crashes the game

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#617]
Futurepack: 28.0.10
Forge: 28.1.115

In the Minecraft main menu, if you click on the Mods button and then click on Futurepack, the game crashes.

[crash-2020-01-17_21.49.24-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/4078759/crash-2020-01-17_21.49.24-client.txt)

**Comment by mcenderdragon** [comment]
Could be a forge bug.

**Comment by mcenderdragon** [comment]
ok no fixed.
