### ISSUE TITLE
[1.14.4]Future Pack has failed to load correctly.

### ISSUE THREAD

**Issue by Nephilim6** [mcenderdragon/Futurepack-API#618]
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/4111698/latest.log)
Using the latest version of forge and Future pack, I can't even load minecraft.
I have done a clean install of just minecraft forge and future pack but I receive this error. 
Future pack has failed to load correctly.

**Comment by mcenderdragon** [comment]
for some reasons it did not reobfuscate the jar...

**Comment by mcenderdragon** [comment]
PLease try this version: https://www.curseforge.com/minecraft/mc-mods/futurepack/files/2868848
