### ISSUE TITLE
Neon Furnace has Outage every few seconds

### ISSUE THREAD

**Issue by Houtenjin** [mcenderdragon/Futurepack-API#620]
Im using the Neon furnace pulling power from a full battery box. Every few seconds the neon furnace drains all its energy and does not take anymore from the box. After some waiting it will draw more power from the battery box.
But if i run another machine on the same cable the Neon furnace will pull power normally.
I am running latest 1.12.2 version on a Server

**Comment by mcenderdragon** [comment]
This is the by product of the optimisations we needed to do so even slow servers can handle large power girds. In 1.14 this should be solved (as it was completly rewritten)
