### ISSUE TITLE
Can't Use E-Scanner

### ISSUE THREAD

**Issue by Crazydude323** [mcenderdragon/Futurepack-API#626]
When I open the E-Scanner GUI, none of the buttons (tech tree, scan result, tech info, calculator) work. The screen for the scanner just keeps printing random text. The scanner still seems able to, well, scan things though.

**Comment by Crazydude323** [comment]
Nevermind; scanner fixed itself when I went into a small sized tec dungeon. I guess it broke because the first thing I did was go into one of the larger tec dungeons.

**Comment by mcenderdragon** [comment]
its not broken, the large tec dungeonds are transmitting something you can decode.
