### ISSUE TITLE
lag spikes on server when carrying Wardrobes with Wardrobe content

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#63]
This is only occurring on a server. I can't duplicate it in single player.

**Comment by mcenderdragon** [comment]
You mean if you have a Wardrobe in a Wardrobe or do you mean the spawned ones from the dungeon?

**Comment by Divineaspect** [comment]
Wardrobes with Wardrobes inside them.

**Comment by mcenderdragon** [comment]
But how do you carry them,? normaly they get droppet out of the wardrobe if you break them.

**Comment by Divineaspect** [comment]
they seem to be working as a portable inventory.

**Comment by mcenderdragon** [comment]
Yeah but normlay they should drop all filled Wardrobes/machines in the inventory, are they doing that not ? (We made this so bacause we crashed a wolrd with an wardrobe in wardrobe...)

**Comment by Divineaspect** [comment]
They are very much not doing that.

Unless you mean completely full, which I will have to check.

**Comment by mcenderdragon** [comment]
no they should turn green (the color of the name tag) and then be unable to carry around inside of a wardrobe.

**Comment by mcenderdragon** [comment]
please check if its fixed here: http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.7 (if the download is not working check if my post is older than 30mins,  the build is currently building)

**Comment by Divineaspect** [comment]
Confirmed resolved!
