### ISSUE TITLE
Dynamic Surroundings Compatibility issue

### ISSUE THREAD

**Issue by Robonics** [mcenderdragon/Futurepack-API#633]
Running DS ver 1.12.2-3.6.0.2
FP ver 1.12.2-26.4.89
Forge ver 1.12.2-14.23.5.2847

Attempting to load Dynamic Surroundings and FuturePack together causes an error within Dynamic Surroundings to crash. After talk with the mod author [here](https://github.com/OreCruncher/DynamicSurroundings/issues/550#issuecomment-595930466), the issue seems to be with how FP sets it blockstates within initialization. I’m not sure how easily this can be fixed. But I enjoy playing with DS so compatibly with FP would be nice. Thanks in advance.

**Comment by mcenderdragon** [comment]
Wow this ssemed like a very large & complicated issue but it seems like its quite easily fixable.

**Comment by mcenderdragon** [comment]
PLease try this: [26.4.90](https://redsnake-games.de/Downloads/fp/fp.php?t=f4rUe9_6nDdiO0p0ctDJ2g--)

**Comment by Robonics** [comment]
The Game Still Crashes, in stage 6 this time. I get [these](https://drive.google.com/drive/folders/1eaBrVkWpCU_84wd0clitHtlXQg3U2tgC?usp=sharing) error logs.

**Comment by mcenderdragon** [comment]
now is orecruncher causing the crash according to the log.

**Comment by lamoyrl90** [comment]
I'm also experiencing this issue.

**Comment by mcenderdragon** [comment]
@lamoyrl90  with what version of futurepack?

**Comment by lamoyrl90** [comment]
Futurepack 1.12.2-26.4.89 and Dynamic Surroundings 1.12.203.6.0.2

EDIT. Nvm. I was behind a version. Lemme update and get back to you.

**Comment by lamoyrl90** [comment]
Crash report:

https://paste.dimdev.org/egetucidal.mccrash

**Comment by mcenderdragon** [comment]
@lamoyrl90 this is not caused by futurepack, please report it to the dynamic surroundings dev.

**Comment by PauroDaburu** [comment]
Hello buddy! Sorry to say but latest updates of both mods still have this issue - crashing on finishing stage:

There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from пїЅ3Dynamic Surroundings (dsurround)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.orecruncher.dsurround.client.handlers.EnvironStateHandler$EnvironState

**Comment by mcenderdragon** [comment]
@PauroDaburu that crash is from OreCruncher
