### ISSUE TITLE
[1.12.2] Sever crash when player moves his ship lower on Melanus

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#639]
https://gist.github.com/ProsperCraft/b63c563ea408d2cd30fb2ee63457cfc1
Futurepack-1.12.2-26.4.89

" milkshake550: so i may have accidentally crashed towncraft by trying to move my futurepack ship lower on menelaus"

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/529

**Comment by mcenderdragon** [comment]
Basicly when it is attempted to set the ship outside the world it is aborted in order to prevent the loss of the ship.

**Comment by ProsperCraft** [comment]
Aborted by crashing the server?

**Comment by mcenderdragon** [comment]
Right now yes. This should be improved.

**Comment by SkyProgs** [comment]
Unfortunately, we can no longer support the 1.12.2. For newer version we keep track of this issue in #529.
