### ISSUE TITLE
Feature request minimum distance from spawn for structure config.

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#64]
Futurepack's structures are amazing, unfortunately they are a little too amazing for the pack I'm trying to build.
Ideally I'd like to be able to prevent them from occuring too close to world spawn, and / or be able to config the distance between them.

**Comment by mcenderdragon** [comment]
Wow, they are too amazing :D A config for the minimal distance around the spawn point, and custom spawn values. Well i thought of something like this bevor but was not sure because it could crash your world if they spawn to offen. And are we talking about the small or the huge dungeons?

**Comment by Divineaspect** [comment]
Both separately please.

**Comment by mcenderdragon** [comment]
Have fun: http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.8
