### ISSUE TITLE
Missing textures and names 1.14.4

### ISSUE THREAD

**Issue by dcandiah97** [mcenderdragon/Futurepack-API#640]
![2020-03-23_18 04 29](https://user-images.githubusercontent.com/60647565/77363669-e7eb3d00-6d31-11ea-9807-0860ee5ca0cd.png)
![2020-03-23_18 04 39](https://user-images.githubusercontent.com/60647565/77363678-ea4d9700-6d31-11ea-920a-f28637c1825f.png)
![2020-03-23_18 04 52](https://user-images.githubusercontent.com/60647565/77363681-eb7ec400-6d31-11ea-8fd4-9a8d67602466.png)
![2020-03-23_18 05 21](https://user-images.githubusercontent.com/60647565/77363688-ed488780-6d31-11ea-99dc-96764e8d2179.png)

I found all of this problems with textures and names, the first picture (in red) shows the items with missing names.

**Comment by mcenderdragon** [comment]
Should be fixed in 28.0.75
