### ISSUE TITLE
feature request, e-scannerto not be consumed when crafting scanner

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#65]
the escanner is one of my favorite tools atm, and I was bummed when I lost it making a scanner.

**Comment by mcenderdragon** [comment]
the scanner has button in its gui to open the research tree. ALso why dont you just search for a tec dungeon and use a new one ?

**Comment by Divineaspect** [comment]
scanning things in world is interesting. Also being able to get to the reserach tree, already a few clicks away doesn't need to be tied to one place. I want to ponder what  they want me to do  when I'm over where my resource caches are, or when out mining in the field.
