### ISSUE TITLE
Server crashes every time I enter my world after applying hologram on a pipe

### ISSUE THREAD

**Issue by artukn** [mcenderdragon/Futurepack-API#651]
Here's the crash report:
[crash-2020-04-18_19.21.18-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/4498567/crash-2020-04-18_19.21.18-client.txt)

My guess is I've managed to apply a hologram of a pipe onto itself. I've fixed my world by editing the BlockHologram.class so that it acts as though hasHologram always returns false and then applying the correct hologram.

Futurepack version: 1.14.4-28.0.75

**Comment by mcenderdragon** [comment]
IMO its quite funny you edited the class file when you alsso could use worldedit to edit the NBT of the block, aynway try this version it should be fixed: [28.0.103](https://redsnake-games.de/Downloads/fp/fp.php?t=p5XBJ0IE4BEkYwi8n8TmLw--)

**Comment by artukn** [comment]
Yeah, I'm a programmer first and MC player second :) I just figured I couldn't use worldedit, since I coudn't load my world without it crashing. I have no experience with worldedit, so I might be missing something.

Either way, that fixed it (tested with a copy of the save I had made for just this reason).
