### ISSUE TITLE
Menelaus dirt and sand not mined faster with a shovel

### ISSUE THREAD

**Issue by artukn** [mcenderdragon/Futurepack-API#652]
Neither shovel, nor pickaxe (both composite) makes it faster. Since I need a lot of the dirt, getting it basically by hand becomes annoying fast.

Futurepack version: 1.14.4-28.0.75

**Comment by mcenderdragon** [comment]
Should be fixed: [28.0.103](https://redsnake-games.de/Downloads/fp/fp.php?t=p5XBJ0IE4BEkYwi8n8TmLw--)

**Comment by artukn** [comment]
That fixed it. I can now get the dirt much faster, thank you.

I wanted to test Menelaus gravel as well, but couldn't find any by just running around on the surface.
