### ISSUE TITLE
Scanning some machines shows java error as a result

### ISSUE THREAD

**Issue by artukn** [mcenderdragon/Futurepack-API#653]
When scanning energy or support research modules I get a java error as a result. Here's the screenshot: 
![Scanning error](https://user-images.githubusercontent.com/52957521/79687896-0e2dcb00-8253-11ea-99b6-d012513c06d3.png)

Futurepack version: 1.14.4-28.0.75

**Comment by artukn** [comment]
I don't have this error any more in 1.14.4-28.0.109

**Comment by SkyProgs** [comment]
That's right, the bug was fixed in 1.14.4-28.0.104. @mcenderdragon please close this issue
