### ISSUE TITLE
Metal stair recipe

### ISSUE THREAD

**Issue by artukn** [mcenderdragon/Futurepack-API#654]
Making metal stair straight out of composite metal (recipe ID futurepack:metal_treppe_0) gives only 1 stair, while made out of metal blocks it gives 4. I think both should give 4.

Futurepack version: 1.14.4-28.0.103

**Comment by SkyProgs** [comment]
This should be fixed in [1.14.4-28.0.118](https://redsnake-games.de/Downloads/fp/fp.php?t=55cZyjyiHtJW8.r.hJ89nA--)
