### ISSUE TITLE
Game Crash upon trying to create "BeltTileEntity"

### ISSUE THREAD

**Issue by 88mmAufSfl8** [mcenderdragon/Futurepack-API#656]
So,
the support research module is causing the game to try to create/or is a "com.simibubi.create.modules.contraptions.relays.belt.BeltTileEntity" _i have no clue.wot_
can't even loade still
[crash-2020-04-23_V107SupportBogaloo-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/4523177/crash-2020-04-23_V107SupportBogaloo-server.txt)

**Comment by 88mmAufSfl8** [comment]
NOTE: This world was first affected by this in Version 1.14.4-28.0.32

**Comment by mcenderdragon** [comment]
this is a crash for the mod Create, please report it to their issue tracker.

**Comment by 88mmAufSfl8** [comment]
oh, sorry for the stupidity.

**Comment by mcenderdragon** [comment]
No problem ^^
