### ISSUE TITLE
redstone pipe is invisible

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#659]
https://imgur.com/a/URJFgFu
still connects properly and everything.

**Comment by mcenderdragon** [comment]
I would say optifine, a shader or mod is causing the rendering to break. Any steps to reproduce this?

**Comment by Divineaspect** [comment]
There are no shaders involved *shudders*
The pack we're playing can be reproduced via Curse or MMC with this file.
https://cdn.discordapp.com/attachments/196812376127832065/702519079478624296/Some_Miner_Arcana-1.0.8.zip

**Comment by Divineaspect** [comment]
apparently it was taking in items but not passing them along as well.

**Comment by mcenderdragon** [comment]
was this fixed with 126?
