### ISSUE TITLE
Placement rather then crafting of autotable, scanner, reserach etc

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#66]
While there's something to be said for understanding  something when you build it, there's also something to be said for already having piles of the things from crashed spaceships which we could afford to break trying to get it to work.

So please change the crafting achievements to placing achievements, after the prerequisite scanning has occured. I'd have no objection to  a chance of breaking machines into parts if you don't know what you're doing as a price.

**Comment by mcenderdragon** [comment]
wich are only crafting achievements?

**Comment by Divineaspect** [comment]
all of them,

**Comment by mcenderdragon** [comment]
This will be fixed in 1.12

**Comment by Divineaspect** [comment]
Sounds good, looking forward to building packs with this in 1.12
