### ISSUE TITLE
[1.14.4] Water Turbine production behavior 1.12 vs 1.14

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#666]
I had much success in 1.12 using the Water Turbine and 8 Industrial Chipsets values above 2.0. With the turbine near bedrock, and the source water near 255, it was generating about 1400 NE. I just switched over to 1.14 and have tried my source water at 162 with my turbine at 72, using 8 Industrial Chipsets near 2.6, at first I was getting ~500 NE, but now it only gives 88 NE, and I can't seem to restore useful NE production. Is this a user error, or a gameplay defect? ( I can provide more information if needed.)

**Comment by mcenderdragon** [comment]
THe formula is unchanged: ne output per machien tick = water blocks * (1 + Industrie_chip_power * 0.3). In 1.13 Minecraft changed the fluid system maybe not all block are counted anymore. but 162-72=90;1+8 * 2.4 * 0.3=6,76 ; 90 * 6,76=608.4; Keep in mind that heat is a VERY important factor and your chips will get very fast quite bad if you operate them near the maximum/burn temperature.

**Comment by Yirok42** [comment]
Thank you for the formula. I am also glad to see the RAM does not factor in.
My exact chips are 6 of the 2.8000002, and 2 of the 2.6 (22); 90 x ( 1 + ( 22 * 0.3 ) ) = 684
My other values are 24.6 C, 88 NE, RAM 39.5: 1 Torus RAM (Speed 8, Core 1) 1 Torus Core 26. I have External Coolers on three sides and Super Cable on the fourth side.

It flickers the higher value when I first enable it. I suspect the problem is the water below the unit. On 1.12.2 it would fall like a thin sheet, like lava does sometimes, and disappear. On 1.14.4 there is a continuous water hanging from the unit. I suspect it considers the bottom is blocked with this "sort of water block"
.
I cannot think of how to make it think the block below is "air".

**Comment by Yirok42** [comment]
I think I'll have to chalk this up to "negative glitch" unrelated to the upgrade, as it has been working fine for days.

**Comment by 7eggert** [comment]
Q: I do have the same flickering in the water turbine between full power and default power (59 vs. 126) until it now reached 124 at full temperature. IDK if this is a glitch or if I'm doing sth wrong. Edit: It does that while actually generating output.
