### ISSUE TITLE
got kicked from server some model missing(1.10.2)Futurepack-1.10.2-24.2.6

### ISSUE THREAD

**Issue by SDUBZ** [mcenderdragon/Futurepack-API#67]
server log:
[latest.txt](https://github.com/mcenderdragon/Futurepack-API/files/573156/latest.txt)

please help :/

reply asap

**Comment by mcenderdragon** [comment]
Thats the servers log right? I also need the Clients log.

**Comment by SDUBZ** [comment]
didnt crash client or spit out any wierd code just on server

**Comment by mcenderdragon** [comment]
try this: http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.9

**Comment by SDUBZ** [comment]
adding it to server and client now i'll let you know if it fixes anything

**Comment by SDUBZ** [comment]
hey it has been fixed on server now 
thanks for such a quick fix
you might wanna release that version so i can fix it in my pack aswell as other packs :D

**Comment by SDUBZ** [comment]
i will inform you if there is any other things i notice :D

**Comment by mcenderdragon** [comment]
okay 👍

**Comment by SDUBZ** [comment]
hey i was just wondering when the fixed update will be released so i can fix my pack of this bug?

**Comment by mcenderdragon** [comment]
as I had changes some stuff related to morpheus in our dimension we currentlx still test the stability of the build, sorry for keep you waiting
