### ISSUE TITLE
[Weird] Crawler's rain 1.14.4

### ISSUE THREAD

**Issue by dcandiah97** [mcenderdragon/Futurepack-API#670]
When I travel to Menelaus an infinite rain of crawlers start to spawn under my spaceship. It is normal? I'm playing the last version of the mod
![2020-05-18_04 38 34](https://user-images.githubusercontent.com/60647565/83216103-787d3980-a136-11ea-8b3a-9650a6e1229c.png)
![2020-05-28_23 41 06](https://user-images.githubusercontent.com/60647565/83216106-7adf9380-a136-11ea-89a3-e5bcbe719e77.png)

**Comment by mcenderdragon** [comment]
For seome reasons vanilla let therm spawn mid air. I dont know why (its kind of funny though)

**Comment by Yirok42** [comment]
I think you just got lucky. It didn't happen for me.
IMHO, use the obscure 'move the ship interface' and or light it up.

Free string!

**Comment by mcenderdragon** [comment]
Fixed in 1,15, aparently there is a ENtityxPlacementRegistry

**Comment by dcandiah97** [comment]
Thanks
