### ISSUE TITLE
[1.14.4] Breaking Deep Core Miner drops nothing

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#672]
I cannot say with absolute certainty as I do not remember completely, but I thought I was able to use a composite pickaxe to pickup a Deep Core Miner cube before finishing the assembly on 1.12.2. In 1.14.4 when I break the cube I get nothing. 

Somewhat related, is on 1.12.2 I was able to place a block breaker, and use a scrench to rotate it such that I could break a block under where I was going to put the Deep Core Minor, so that I could put a Cooler under it, as I wanted to put 3 Coolers and still be able to connect the Super Cable. I have not figured out a way to rotate the Block Breaker to point down against bedrock. Perhaps that was not supposed to have worked before, but it was nice. Now it only rotates horizontally, whereas it used to rotate in the direction of the clicking.

**Comment by mcenderdragon** [comment]
Solved in 1.15
