### ISSUE TITLE
[1.15.2-20.0.1] Spontaneous Lava

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#678]
I've never seen this but then I would mostly just cobblestone or gravel over lava before FuturePack.
I was emptying some lava pools and filling up some mk3 tanks. When I almost emptied a pool I filled cobble to remove the flow lava to see what was left of lava, then I removed the cobble to see if there was lava lower, and there wasn't. THEN! one spot of flow lava returned. No matter how many times I overplace it, when I remove the cobblestone, the flow lava returns.
There is no source lava in this area. The lava that returns is "level=2" 
4 block have this behavior in a pattern of
0X0  where the X are the ones that are either cobblestone or lava, but not air.
X0X  the other blocks are air.
0X0  this is happening at y=5.

Well, I mined up the lapis lazuli under these block and used cobblestone to get out of that hole and now the four special lava blocks have stopped spawning.

I was thinking it was a render problem but I couldn't figure out which block. I think it may have been the block 2 up from these and when I placed cobblestone to get out of the hole I may have "reset' that block to cobble and that "resolved' it.

**Comment by Yirok42** [comment]
This might not be unique to 1.15.2 but I have only seen it there.
it remind me of when the Miner digs up gravel but the gravel and gravel that falls is still there but invisible.

**Comment by mcenderdragon** [comment]
I guess this was a server client desync. SO server side there was the block, but client side not so it was returning.

**Comment by Yirok42** [comment]
I host a client world on my home's local network, and sometimes my son (or
sons) and daughter join that way.
I do not know if that is a difference to what you are saying. I have seen
"weirdness" with the mining drown taking out gravel that should cause the
gravel above to fall, which I assumed was the reason to have a claim
repeat, but the gravel doesn't fall and then I can place any block where
the gravel is, but is not rendering, and the gravel block will "appear". I
don't mind this but it would be considered a bug in someone's code (i am
allowing that it could be a fault in the mc base code), but it is easy to
resolve.
Now this, is less easy to resolve as flow lava is much more dangerous than
gravel. Also since my mining drown was just dancing around, the original
block of source lava that was being rendered as an air-block was not caused
by the mining drown. Also I don't think the mining drone can destroy lava
(flow or source) or water (flow or source), and the thing, when working,
just stops trying to destroy these liquids.

But yes, it was something like a block not rendering correctly on my
client, except my client is the server.

**Comment by Yirok42** [comment]
This is probably not related to v 20.0.1.
