### ISSUE TITLE
[1.15.2-20.0.1] something odd in the air

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#679]
On Menelaus (aka Mercury), I think whatever this is isn't rendering correctly.
![2020-06-14_12 07 53](https://user-images.githubusercontent.com/65392871/84599828-8ae7ba80-ae3a-11ea-9c23-c38abf7b576d.png)

**Comment by mcenderdragon** [comment]
Those are the fireflies
