### ISSUE TITLE
Client crash with Tinker's Lens from Embers and the Industrial Furnace

### ISSUE THREAD

**Issue by Maxwell-lt** [mcenderdragon/Futurepack-API#681]
When looking at the Industrial Furnace while holding a Tinker's Lens from Embers, the client crashes.

Environment:

- Minecraft 1.12.2
- Forge 14.23.5.2854
- EmbersRekindled 1.13-hotfix2
- Futurepack 26.4.89

Logs:
https://gist.github.com/Maxwell-lt/22a20dde0964548d1ac9e9854a443aa4

Extra Info:
When passing a null EnumFacing to the .getCapability() method of TileEntityIndustryalFurnace, `null` is returned.
https://gitlab.com/MCenderdragon/Futurepack/-/blob/1.12/src/main/java/futurepack/common/block/TileEntityIndustryalFurnace.java#L513

Returning `super.getCapability(capability, facing)` instead may fix the issue.

**Comment by mcenderdragon** [comment]
it already calls super.getgetCapability. Also hasCapability retured false for this case, so I guess this fix needs to be made in embers.

**Comment by Maxwell-lt** [comment]
After attaching a debugger to Embers, I've discovered that my initial analysis was incorrect. EnumFacing is not null in this case, and a valid capability is returned.

The real issue is this:
```java
	private class Tank implements IFluidHandler
	{
		@Override
		public IFluidTankProperties[] getTankProperties()
		{
			return null;
		}
```
https://gitlab.com/MCenderdragon/Futurepack/-/blob/1.12/src/main/java/futurepack/common/block/TileEntityIndustryalFurnace.java#L535

Here an empty array should be returned, not null. Replacing 
```java
return null;
```
with
```java
return new IFluidTankProperties[0];
```
fixes this bug.

**Comment by SkyProgs** [comment]
We don't support 1.12.2 anymore. If this happens in a newer version please open a new issue.
