### ISSUE TITLE
1.15.2 Mekanism steam not recognized

### ISSUE THREAD

**Issue by bloche1871** [mcenderdragon/Futurepack-API#682]
With Mekanism installed, water coolers do not produce steam.

**Comment by mcenderdragon** [comment]
steam is only produced if a mod which has steam is installed. Does Mekanism has steam ? (I dont know that mod so well ^^)

**Comment by bloche1871** [comment]
Yes, Mekanism has steam. It has 2 types: a "liquid steam" which uses the normal forge fluids system, and a "steam" gas which uses mekanism's own "gas" system. The two can be converted into each other using a mekanism block, so although it would be nice for the water cooler to produce "gas" steam if Mekanism is installed, at least liquid steam would be useful for compatibility.

**Comment by mcenderdragon** [comment]
Could you tell me how thier steam is named ? pressing F3+H should enabled advanced tooltips so this is displayed.

**Comment by bloche1871** [comment]
It seems like fluid names do not show up with F3+H in this version of the game. However if I look into the Mekanism jar it seems there is a "steam" tag in forge/tags/fluids/steam.json which contains this:
{"values":["mekanism:steam","mekanism:flowing_steam"]}

Could I have made the water cooler output steam using a datapack or crafttweaker script?

**Comment by mcenderdragon** [comment]
No, not yet but I have atleast the names. So in a future version this will most likley be possible.

**Comment by mcenderdragon** [comment]
in the next 1.15 version this will be fixed.
