### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kursted** [mcenderdragon/Futurepack-API#685]
When I enter the dungeon teleporter im fine to go up the stairs and up ladders but the main room with a lever when i walk towards it it crashes my minecraft but server stays running.
[Dungeoncrash-2020-07-15_19.58.28-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/4928767/Dungeoncrash-2020-07-15_19.58.28-client.txt)

**Comment by mcenderdragon** [comment]
this crash is from fairy lights
