### ISSUE TITLE
1.15.2 recursive wardrobes issue + mod compatibility request

### ISSUE THREAD

**Issue by bloche1871** [mcenderdragon/Futurepack-API#686]
It seems you can place filled wardrobes within wardrobes, and they do not drop when you break the containing wardrobe in the world.

Even if this was fixed there is also a problem with other similar movable containers from other mods. It would be useful to have a way through config to define a blacklist of items that can't be moved inside a wardrobe. (Or maybe a config to have wardrobes drop all items like a regular container, if that's easier?)

**Comment by mcenderdragon** [comment]
I dont quite get the Problem. If you are talking about creating "killer" items with a too large NBT Tag so the client crashes becuase the NBT is larger then the acket dont worry there is a protection for exactly that. Why making a incompletr list when I can simply ask the game to check and manage for itself. 

I dont know though if this feature still works or if porting broke it. Could you try to make a killer item? (allias alot of wardobe into each other)

**Comment by bloche1871** [comment]
I can try making a "killer" item if it helps. Would it work in single-player too, or do I need to test on an actual server?

However I reported this because i assumed that it wasn't intended that wardrobes can provide infinite portable storage through recursion. If that's intended then never mind! A config might still be nice to give the option for modpack devs to disable that feature or limit it.

**Comment by mcenderdragon** [comment]
It should work in signle player too. At some point the items in the ardrobe will all drop.

**Comment by bloche1871** [comment]
The protection feature seems to work: after making the NBT very large the wardrobe dropped the other wardrobes it contained when broken

**Comment by mcenderdragon** [comment]
Nice. OK I see this as resolved. As there is a data limit and also recursion prevention at a certain point. Feel free to reopen if you disagree.

**Comment by bloche1871** [comment]
I'd still be glad to have the config option to "nerf" the wardrobes by blacklisting items from being stored inside them or forcing them to drop items, but it's just a feature suggestion at this point so I'll leave this issue closed.

**Comment by Yirok42** [comment]
what! wardrobes being able to carry full wardrobes is a great feature of this modpack.

You don't have to use them if they bother you. You could use vanilla chests.

Also it isn't like you can make a wardrobe on day one. You have to research quite a bit just to get the thing.
