### ISSUE TITLE
startup crash with Astral Sorcery

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#687]
https://pastebin.com/NRF1jkEu

**Comment by mcenderdragon** [comment]
Please also open a issue at astral sorcery, maybe also quark. they add some hooks and they break together as the loop.

**Comment by Divineaspect** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/1322

**Comment by mcenderdragon** [comment]
Code in question is:
```
	@Override
	public int getMaxDamage(ItemStack stack)
	{
		int lvl = EnchantmentHelper.getEnchantmentLevel(Enchantments.UNBREAKING, stack);
		return super.getMaxDamage(stack) +(100 * lvl);
	}
```
I dont think I can change much here, so knowing what AstralSOrcery is doing would be nice.

**Comment by mcenderdragon** [comment]
I think I can not fix it from my side, as `ItemStack#isDamageable()` directly calls `Item#getMaxDamage` (and not the item method isDamageable - if this would be called instead we would not have this problem). Checking the enchantment list cheks if this item can have dynamic enchantments, which checks if its damegable & we are at the start.

**Comment by mcenderdragon** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/7222
