### ISSUE TITLE
Non complainant capability provider implementations causing null dereferences

### ISSUE THREAD

**Issue by pau101** [mcenderdragon/Futurepack-API#689]
The classes `TileEntityModulT1`, `TileEntityModulT2`, `TileEntityIndustrialFurnace`, and `TileEntityBlockPlacer` contain implementations of `ICapabilityProvider#getCapability` which erroneously return `null`, as opposed to the correct `LazyOptional.empty()`, resulting in null dereferences in mods querying capabilities of these blocks.

An instance which I have received of such a crash: pau101/Fairy-Lights#84

**Comment by mcenderdragon** [comment]
Most likely more machines are affected:
```
if(facing==null)
			return null;
```
This code is used for all machines with configureable sides.

**Comment by pau101** [comment]
When I checked most with the null facing check do actually return empty, but just some not, but do ensure I didn't miss any.

**Comment by oneandonlyjason** [comment]
I wanted to note that the Error is occuring in 1.14.4 as well.  Im here because Fairy-Lights crashes because of this Futurepack Error(?) in a Futurepack Dungeon in 1.14.4 as well
