### ISSUE TITLE
1.15.2 Menelaus fire flies

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#691]
Do the fire flies multiply on their own?
I use the grappling slime to shoot up to my ship and back down, and to travel.
There are so many fireflies below my ship that it is becoming difficult to shoot through them.

Was this intentional? I have on prior versions placed Menelaus plants in my base and they overran the base like Tribbles. Though I have not noticed them multiplying on Menelaus

By the way, the new Menelaus biomes are great! Mooshroom areas, disconnected arcs. seas of gravel. Though I recently died without a bed and had to run 4000 m back to my death spot and I saw zero other animals. The weird food animals of Menelaus were not seen. Are they gone? (I'm sorry for asking two questions on one issue)

**Comment by mcenderdragon** [comment]
I havent tested if all Menelaus Animals spawn yet.
THe Fireflies spawn constantly around players at night, but it seems that for some reasons it is considerate to be permanent night at menelaus, so they dont stop spawning, I though I fixed that...

**Comment by Yirok42** [comment]
That makes sense. On other dimensions sleeping in a bed causes morning to come faster, but not on Menelaus for 1.15.x. I considered that it might have been on purpose so I didn't mention it (or maybe I did before)

Also, I am now only playing with 2 clients on Windows, and the server running on Ubunto.

**Comment by mcenderdragon** [comment]
I was not able to reproduce firefly spawning at daytime on menelaus.

**Comment by Yirok42** [comment]
The multiple issues mentioned on this issue have been asked elsewhere. What is left is no longer related to fire flies, so I will consider this issue closed. I will open a separate issue about sleeping not bringing morning which may be intended. #693 covers the food mobs not spawning.
