### ISSUE TITLE
1.15.2 broken spawner chest

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#694]
you can pickup spawners, but dont place them down, from https://www.curseforge.com/minecraft/mc-mods/futurepack#c684

**Comment by Yirok42** [comment]
This was reported on 1.14.2 as Issue #667. Not sure if that helps you investigate it, but it sounded familiar.

**Comment by mcenderdragon** [comment]
fixed in 1.16.4
