### ISSUE TITLE
[1.15.2] (aka 20.0.2) Where are the ERSE?

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#697]
This might be user error but I'm reporting just in case.

I have found no erse in my world. I checked the overworld, Tyros, and Menelaus. I have not traveled the entire world but I have been to many grassy areas where I used to find them.

My server log mentions erse in warnings:
* Incorrect key common.erse_food_value was corrected from null to 3
* Incorrect key common.erse_food_saturation was corrected from null to 0.300 (it kept going)
* Incorrect world_generation.erse_count was corrected from null to 2.0

And some other lines with words like (the Reserach is how it is spelled in the log file)
* Add Research Reserach futurepack:story.erse(70)
* Completed Research Reserach futurepack:energy.infusion(140) ... (and more stuff) that says erse eventually 
* Completed Research Reserach futurepack:story.erse(70) (and more stuff)

In scanner the spot Needs {Erse for the world} is still black.

I have tried: Plains, River, Wooded Forest, Tiaga, (not the snowy places), Mountains, Forest, Birch Forest, Swamp.

I viewed the erse png files thinking maybe they look different, but no, they look the same. If they only appear under some conditions, I'll try to figure it out by playing, but perhaps something has happened that makes their chance of being generated to be zero.

I cannot think how any of these other mods could negatively affect erse but here's the list: 
* Bag-of-Yurting-Mod-1.15.2.jar (installed but not using; not exactly compatible with picking up research setup and placing)
* Chisel_DEV-MC1.15.2-0.0.1.12.jar (installed but not using; the 1.12.2 was much better)
* Futurepack-1.15.2-20.0.2.jar
* gravestone-1.17.5.jar
* jei-1.15.2-6.0.0.3.jar
* journeymap-1.15.2-5.7.0beta1.jar
* Neat-Mod-1.15.2.jar (puts status bar above mobs; very recommended if you are fighting The Emperor (not beating it but at least seeing his health regenerate))

**Comment by qrss** [comment]
I haven't found any Erse in 1.16.4 either (Futurepack 21.0.4), so this might still be an issue.

**Comment by mcenderdragon** [comment]
See https://github.com/mcenderdragon/Futurepack-API/issues/740

**Comment by Yirok42** [comment]
Woot! I just found my first erse on 1.16.4 (21.0.6)

**Comment by Yirok42** [comment]
Not sure if still missing on 1.15.2 but I no longer use 1.15.2, and erse is plentiful from 1.16.4 to 1.18.2.
