### ISSUE TITLE
{Server Crash} Minecraft server crashes when loading in new chunks.

### ISSUE THREAD

**Issue by TheStarlessBandit** [mcenderdragon/Futurepack-API#698]
Basically i own a small server with minimal mods, but sometimes when i load new chunks it crashes, tho it does not create a crash report for some reason, it spit's out alot of futurepack errors, Il give the latest.log and modlist
[modlist.txt](https://github.com/mcenderdragon/Futurepack-API/files/5212704/modlist.txt)
[latest (2).log](https://github.com/mcenderdragon/Futurepack-API/files/5212705/latest.2.log)

One thing i noticed in latest.log:

[11Sep2020 14:44:52.325] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
    Index: 1
    Listeners:
        0: NORMAL
        1: ASM: futurepack.common.dim.protection.FPDungeonProtection@1027f5ca onChunkOpen(Lnet/minecraftforge/event/world/ChunkDataEvent$Load;)V
java.lang.NullPointerException
    at futurepack.common.dim.protection.FPDungeonProtection.onChunkOpen(FPDungeonProtection.java:191)

**Comment by TheStarlessBandit** [comment]
Forgot to tell that the server and mod are in 1.14 ^

**Comment by mcenderdragon** [comment]
This is fixe din 1.15. seems like for some reason the event is posted with a null world (and in new version is a != null check)

**Comment by TheStarlessBandit** [comment]
Is there any fix or do i have to remove the mod?

**Comment by TheStarlessBandit** [comment]
Thanks, removed the mod in 1,14 Works great!

**Comment by mcenderdragon** [comment]
Dudders: I just pushed a version to 1.14.4 so just be patient and get the new version with the fix. I added the solved tag becuase its solved in dev. I will now rename this tag to make this clear.

**Comment by TheStarlessBandit** [comment]
Oh, Sorry.

**Comment by mcenderdragon** [comment]
hope this fixes it.

**Comment by mcenderdragon** [comment]
https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3057891
