### ISSUE TITLE
Dimensional blacklist/whitelist for various worldgen?

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#70]
We  found dungeons in the nether, which was a bit offputting for the whole crashed spaceship vibe.
Can we get config settings for dimensions where dungeons, holes, etc spawn?

**Comment by mcenderdragon** [comment]
well in the nether they are less and they are red. and they are kind of this-dimensions-was-explored-by-the-unreachables

**Comment by Divineaspect** [comment]
We could see three of them in the lava lake right by our portal.

**Comment by Divineaspect** [comment]
regardless, are we going to see these in every dimension added by every mod?
if we  can config  dimensions for them, and other such things, we can present variant narratives with them.

**Comment by mcenderdragon** [comment]
lol, this should not happen, but jej random and world seeds 💥

**Comment by Divineaspect** [comment]
https://cdn.discordapp.com/attachments/176845387431149568/245435373277282304/2016-11-08_01.31.54.png

Ignore the wireframe overlays, and this still makes no sense.

**Comment by mcenderdragon** [comment]
ohh you mean the huge ones :D, they should be NOT there

**Comment by mcenderdragon** [comment]
this should be fixed now

**Comment by kleshchevand** [comment]
>kind of this-dimensions-was-explored-by-the-unreachables
Would have been much better to disable nether portal and grant some kind of low level thruster capable of reaching nether (obviously with bedrock at the top of dimension removed)

**Comment by mcenderdragon** [comment]
well this is not realy possibe to block the nether and it is kind of a game breaker to disable the nether and insert own content there.

**Comment by kleshchevand** [comment]
>this is not realy possibe to block the nether
It was done multiple times by other mods. Also it not necessary to disable or modify nether, just the portal and then add own nether like planet-dimension that can be traveled to. 

>it is kind of a game breaker
Why? It will just change the means to reach certain mid-game resources, balance won't change except for a need of fuel to travel to Nether (but FP will have to get an alternate set of early-game thrusters and fuel to get to nether).
