### ISSUE TITLE
Entity-egger and offhand items

### ISSUE THREAD

**Issue by Cat940** [mcenderdragon/Futurepack-API#705]
If you release a mob from entity egger and you have something in your offhand ,it siply disappears.

**Comment by mcenderdragon** [comment]
it should drop nas item are you sure it disappears also what version are you using ?

**Comment by Cat940** [comment]
minecraft 1.15.2
Futurepack 20.1.0
Im sure items just disspear withut any trace

**Comment by Maxwell-lt** [comment]
I just reproduced the issue, though I think @Cat940's explanation was ambiguous.

#### Minimal environment:
* Minecraft 1.15.2
* Forge 31.2.45 (latest as of writing)
* Futurepack 1.15.2-20.1.0

#### Steps to reproduce:
1. Capture a mob with an Entity Egger
2. Hold the full Entity Egger in the main hand
3. Hold any other item in the offhand
4. Right click to place the entity

The expected result is that the entity will be placed, the empty Entity Egger will drop as an item, and the item in the offhand will remain without changes.
The actual result is that the entity will be placed, the empty Entity Egger will drop as an item, and the item in the offhand will be destroyed.

**Comment by mcenderdragon** [comment]
Fixed in 1.16.4

**Comment by qrss** [comment]
I tested this and it does seem to be resolved in 21.0.4
