### ISSUE TITLE
[1.16.4] Futurepack disables falling damage

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#709]
Forge version: 35.1.13
Futurepack version: 21.0.1

The player seems to be immune to falling damage when Futurepack is installed. You can still take damage from mobs, hunger and falling into the void.

I also tested this with just Forge and falling damage worked correctly, so it doesn't seem to be a Forge bug.

**Comment by mcenderdragon** [comment]
SO jsut joining a new world and this happens?

**Comment by qrss** [comment]
Yes, join an old world or make a new world and this happens.

Found out when I accidentally fell off a cliff and lived.

**Comment by mcenderdragon** [comment]
@qrss pleasse try this version [Futurepack-1.16.4-21.0.2](https://www.mediafire.com/file/fzoix8o0kejl9bf/Futurepack-1.16.4-21.0.2.jar/file)

**Comment by qrss** [comment]
Yup, seems to be fixed. Thank you!
