### ISSUE TITLE
[1.16.4] Futurepack ore generates exclusively in chunk corners

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#710]
Forge version: 35.1.13
Futurepack version: 21.0.1

Futurepack ore seems to only generate in chunk corners, meaning you get these columns of ore from bedrock to surface.

![2020-12-25_14 29 24](https://user-images.githubusercontent.com/32312262/103136111-cf8fc080-46bd-11eb-8e53-67e7881c7378.png)

**Comment by mcenderdragon** [comment]
ohh how awesome the new json worldgen system is...

**Comment by mcenderdragon** [comment]
@qrss pleasse try this version [Futurepack-1.16.4-21.0.2](https://www.mediafire.com/file/fzoix8o0kejl9bf/Futurepack-1.16.4-21.0.2.jar/file)

**Comment by qrss** [comment]
As far as I can tell, ore generation looks normal now. Thanks!
