### ISSUE TITLE
[1.16.4] Neon sand and Alutine sand pockets generate on top of each other

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#712]
Forge version: 35.1.13
Futurepack version: 21.0.2

Whenever there is a Neon sand pocket, in the same location there will be an overlapping Alutine sand pocket.

![2020-12-26_12 45 50](https://user-images.githubusercontent.com/32312262/103150944-81d88e00-4779-11eb-9cb2-af086558f461.jpg)

**Comment by qrss** [comment]
This was the case for the first 4 pockets I found, but actually this turns out to be a coincidence.

The pockets seem to generate exactly at chunk corners, which increases the chances of them overlapping.

**Comment by qrss** [comment]
Actually, perhaps this is still an issue? They still seem to overlap more often than would be natural, given the range of Y values they could take.

![2020-12-26_13 22 26](https://user-images.githubusercontent.com/32312262/103151340-93239980-477d-11eb-95c6-ebc8e1021e4c.png)

**Comment by mcenderdragon** [comment]
Yeah its an issue thew always generate at the chunk borders

**Comment by qrss** [comment]
This does seem to be fixed in 21.0.3!
