### ISSUE TITLE
[1.16.4] Industrial Furnace and Assembly Table recipes not working

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#713]
Forge version: 35.1.13
Futurepack version: 21.0.2

The Industrial Furnace and Assembly Table recipes do not seem to work and they don't show up in the Tech Tree.

![2020-12-26_14 22 54](https://user-images.githubusercontent.com/32312262/103152227-485a4f80-4786-11eb-9e8e-0eabbfbe8ee1.png)

**Comment by mcenderdragon** [comment]
For soem reason the recipes are nto send to the client.

**Comment by mcenderdragon** [comment]
Actully no recipes are loaded(?)

**Comment by mcenderdragon** [comment]
should e fixed in dev

**Comment by mcenderdragon** [comment]
PLease try this version [21.0.3](https://www.mediafire.com/file/nqyc5vmwp6rnjvk/Futurepack-1.16.4-21.0.3.jar/file)

**Comment by qrss** [comment]
The Industrial Furnace and the Industrial Neon furnace recipes work now, but Assembly Table recipes don't seem to work.

**Comment by mcenderdragon** [comment]
do they showup in JEI ?

**Comment by qrss** [comment]
They don't show up on the Tech Tree pages, but I don't know about JEI.

I'll install JEI and check if I can see the recipes there.

**Comment by qrss** [comment]
The items show up in JEI, but don't show a recipe when I click on them.

**Comment by qrss** [comment]
Wait, I loaded up my world again and now the Assembly Table recipes work.

I'll do some more testing to see what is up.

**Comment by qrss** [comment]
The first time I open my world after starting the game, the Assembly Table recipes do not work.

When I close the world and load it up again (without exiting the game), the recipes will work.

**Comment by qrss** [comment]
By the way, I noticed that when you load up the world for the second time in a session, then the Assembly Table, Industrial (Neon) Furnace, Centrifuge and Crusher recipes show up twice in JEI (each recipe is shown twice).

If you load up the world three times, then all the recipes show up three times and so on ...

If you load the world for the first time, then the recipes show up once, as intended (expect for the Assembly Table recipies, which are absent).

The Crafting Table recipes always show up only once in JEI.

This might be related to the recipe issues.

**Comment by qrss** [comment]
The Assembly Table recipes issue still present in 21.0.6 (see my two comments above).

**Comment by qrss** [comment]
I will emphasize that this is not just a JEI issue, the recipes actually don't function or show up in the E-scanner.

(Tested with Forge 35.1.37 and FP 21.0.6)

**Comment by mcenderdragon** [comment]
it works in the Dev enviroment. which means the bug is super weird...

**Comment by qrss** [comment]
Hmm, I did some testing just in case this is caused by some other mod.

Disabling the mod "Shutup Experimental Settings" fixed this.

**Comment by qrss** [comment]
I also tested updating to Minecraft 1.16.5, which has a newer version of "Shutup Experimental Settings", this also does not have this issue.

**Comment by mcenderdragon** [comment]
you dont need "Shutup Experimental Settings" when futurepack is installed.

**Comment by qrss** [comment]
Thanks, good to know!

In earlier versions of Futurepack I kept getting the experimental settings warnings, but I didn't know that was changed.
