### ISSUE TITLE
[1.16.4] The NE/Cycle value shown in the GUI of the Solar Panel is always zero

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#715]
Forge version: 35.1.13
Futurepack version: 21.0.2

The NE/Cycle value shown in the Screnching GUI of the Solar Panel is always shown to be 0, although it is generating energy as intended.

The Ion Collector does not have this issue.

![2020-12-27_00 26 54](https://user-images.githubusercontent.com/32312262/103160885-66519f80-47da-11eb-9c43-79676e9ef3a4.png)

**Comment by mcenderdragon** [comment]
PLease try this version [21.0.3](https://www.mediafire.com/file/nqyc5vmwp6rnjvk/Futurepack-1.16.4-21.0.3.jar/file)

**Comment by qrss** [comment]
The NE/Cycle number is now updated when you open the GUI of the Solar Panel!

However, it is only updated when you open the regular GUI of the Solar Panel.

When you place down a new Solar Panel and open its motherboard GUI without opening the regular GUI, then NE/Cycle is still shown as zero.

I think it would be best if the NE/Cycle number was instead updated when opening the motherboard GUI, since you can't see that number anyway in the regular GUI.

**Comment by mcenderdragon** [comment]
and doing that is insanly difficult with (my) current design sadly.

**Comment by qrss** [comment]
Alright, no worries! I would say that your fix works well enough!
