### ISSUE TITLE
Everything is invisible and glitching with optifine on.

### ISSUE THREAD

**Issue by PalpyTheFrog** [mcenderdragon/Futurepack-API#716]
Whenever i load up the mod with optifine 1.16.4 HD U G5, everything appears invisible at first then the world pops in and out of existence very quickly and makes the thing unplayable. in the video i have only futurecraft and optifine in my mods folder and i give a look into my optifine settings aswell.

https://user-images.githubusercontent.com/76658153/103175728-be67c080-4831-11eb-9bb1-0ea0df9f10cd.mov

**Comment by mcenderdragon** [comment]
Does futurepack even need to be installed? is forge + optifine enough? I am askign ebcuase optifine is known for render glitches with modding + they dont care about the modding community.. Forge has often offered the will for collaboration and fixing this but optifine never did.

**Comment by PalpyTheFrog** [comment]
Optifine with forge does not do this. its only when futurepack is added that everything goes wonky.

**Comment by PalpyTheFrog** [comment]
![image](https://user-images.githubusercontent.com/76658153/103204258-83f73580-48bc-11eb-9857-e0281be2a614.png)
i turned off these things it was acting normal. I dont know which option was the one to fix it but its one of them.

**Comment by PalpyTheFrog** [comment]
![image](https://user-images.githubusercontent.com/76658153/103205526-5cee3300-48bf-11eb-8bd9-d20090eb7976.png)
nvm it was anti aliasing that was messing with it. The other options can still be used, but anti aliasing needs to be off for some reason

**Comment by mcenderdragon** [comment]
I heard optifine had an update that fixed some render issues, does this work now ?
