### ISSUE TITLE
[1.16.4] Visual issues with the Laser Turret

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#717]
Forge version: 35.1.13
Futurepack version: 21.0.2

I noticed some visual weirdness when playing around with the Laser Turret. This doesn't really affect gameplay, so it is not important, but I thought I would document the behavior anyways.

1) When you modify the chip or RAM or CPU arrangement of a Turret (or even just click on an empty slot), the laser beam will remain after the Turret fires.

Opening the Motherboard GUI and closing it without interacting with anything will fix the issue.

![stuck_beam](https://user-images.githubusercontent.com/32312262/103179600-0288ae80-488e-11eb-8e4f-d023edb27b36.gif)

2) The laser turret does not visually track its targets, even if the entities are still being damaged by it. The turret only visually changes its orientation when locking onto a new target.

Also, the turret damages entities even after they exit its range (but not when they exit the line of sight of the turret). Not sure if this is intentional or a bug.

![turret_tracking](https://user-images.githubusercontent.com/32312262/103180071-9d838780-4892-11eb-991a-6407b64c7d6a.gif)

3) The laser beam renders behind turret blocks, but in front of other blocks. I'm guessing this is intentional because of efficiency reasons, but I'm making a note of it just in case.

![2020-12-27_22 07 13](https://user-images.githubusercontent.com/32312262/103179875-90659900-4890-11eb-8959-6ee187a2a691.png)

![2020-12-27_22 07 31](https://user-images.githubusercontent.com/32312262/103179877-90fe2f80-4890-11eb-9a71-d68db9644314.png)

**Comment by Wugand** [comment]
The see through problem is "Solved in Dev", the sync issue not.

Edit: Sync is also fixed (or looking better to be precisely)
