### ISSUE TITLE
[1.16.4] Battery box consumes energy, but does not fill the buffer

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#723]
Forge version: 35.1.28
Futurepack version: 21.0.3

If you connect a Battery Box to an NE generator, then NE flows into the Battery Box, but all that NE just disappears without filling the buffer.

**Comment by mcenderdragon** [comment]
I cannot reproduce this, did you check with a logistic editor if the sides were correctly configured?

**Comment by qrss** [comment]
Oh dear, I'm really sorry, you are right. The sides were configured as output by default and I didn't think to check with a logistics editor.

Even more stupidly, the generator was next to another consumer, which is why I thought the energy was draining (I can't believe I did not notice that).

However, the sides of the Battery Box should not be set to output be default, at least if the documentation is to be believed:
![2020-12-31_12 15 56](https://user-images.githubusercontent.com/32312262/103408408-a90cd200-4b62-11eb-8f7a-44cb495e85b7.png)

**Comment by mcenderdragon** [comment]
the default conbfig is now everythign is outout but the top is input, I ghave no idea which is betetr but considering that in the past + in the documentation its different I will fix that.

**Comment by qrss** [comment]
Well, either is fine, as long as documentation agrees with the actual defaults.

I think I recall being confused about the batbox a few years back when I last played Futurepack, but I've forgotten about the logistics editor. Sorry again.

**Comment by mcenderdragon** [comment]
DOnt worry its fine. Better to much reports as to little and everyone knoews about it but nobody tells the author.
