### ISSUE TITLE
[1.16.4] Spawner chest bug.

### ISSUE THREAD

**Issue by AjzaklijaStomaklija** [mcenderdragon/Futurepack-API#725]
I can pick up spawner but i cant place it.Same bug in 1.15.2 version.

**Comment by mcenderdragon** [comment]
this should be solved in the [21.0.3](https://www.mediafire.com/file/nqyc5vmwp6rnjvk/Futurepack-1.16.4-21.0.3.jar/file)

**Comment by qrss** [comment]
I tested this and it does seem to be working as intended in 21.0.4

(1.15.x version of the issue: #694)

(1.14.x version of the issue: #667)
