### ISSUE TITLE
[1.16.4] Emptying the input slot of the Crusher while it is working will keep it running and consuming NE

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#726]
Forge version: 35.1.28
Futurepack version: 21.0.3

If you remove the recipe ingredients in the Crusher while it is working, it will keep consuming NE forever (until you start a new recipe).
It will still be running after restarting the game.

I have not observed this issue with other devices.

![crusher_stuck_working](https://user-images.githubusercontent.com/32312262/103427487-9c6b9680-4bc1-11eb-9c28-1d008f3f2789.gif)

**Comment by mcenderdragon** [comment]
Should be fixed in [21.0.4 ](https://www.mediafire.com/file/mmmrw65ckdc34xn/Futurepack-1.16.4-21.0.4.jar/file)

**Comment by qrss** [comment]
This does appear to be solved!
