### ISSUE TITLE
[1.16.4] Right-clicking with a Scrench on a Teleporter with a metal block beneath dupes the Teleporter

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#728]
Forge version: 35.1.28
Futurepack version: 21.0.3

If a Teleporter (Up/Down) is on a metal block (for example, the floor of a ship), then right-clicking on it with a scrench to deploy the teleporter deploys the teleporter and a copy of the Teleporter (Up/Down) in item form pops off.

![teleporter_dupe](https://user-images.githubusercontent.com/32312262/103435352-30fbe600-4c0e-11eb-8bed-ef43ece6dec9.gif)

**Comment by mcenderdragon** [comment]
Should be fixed in [21.0.4 ](https://www.mediafire.com/file/mmmrw65ckdc34xn/Futurepack-1.16.4-21.0.4.jar/file)

**Comment by qrss** [comment]
Thanks! Seems to be working correctly now.
