### ISSUE TITLE
[1.16.4] Support Pipes don't always work with SP generators

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#729]
Forge version: 35.1.28
Futurepack version: 21.0.3

Support Pipes only pipe SP out of SP generators (Neon Furnace, Super Crusher, Opti Bench) when the last Support Pipe to complete the connection (to some other device) is placed next to the SP generator.

This only seems to happen with SP generators. Flash servers do not have this problem. Support cables also seems to work correctly.

![support_pipe_bug](https://user-images.githubusercontent.com/32312262/103446104-12cccf00-4c7c-11eb-88eb-250faf9eafaa.gif)

**Comment by mcenderdragon** [comment]
ohh thats an interesting but, thanks for findign it.

**Comment by mcenderdragon** [comment]
Should be fixed in [21.0.4 ](https://www.mediafire.com/file/mmmrw65ckdc34xn/Futurepack-1.16.4-21.0.4.jar/file)

**Comment by qrss** [comment]
It does seem to be fixed!
