### ISSUE TITLE
request: undead unreachable mob

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#73]
futurepack adds very well lit dungeons and ruins. 
It's however missing something key to those kind of structures, monsters.

I had the mental image of a retextured zombie, slightly transparent, which teleports like an enderman.
Might not fit where you're going, but we need something, especially without the ability to control their rarity, and I figured I'd throw this out there.

**Comment by Wugand** [comment]
It is not planed that you can find one of the Unrechables.
But the large dungons should be get more Content (Rooms, Informations, maybe Monsters or Traps) sometime in the future.

**Comment by mcenderdragon** [comment]
Well "Added evil horrors" was a commit message a few weeks back :P
