### ISSUE TITLE
[1.16.4] Can't use Entity-Egger on Horses or Donkeys or Mules

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#730]
Forge version: 35.1.28
Futurepack version: 21.0.4

Right-clicking or shift+right-clicking a horse (or donkey or mule) with an Entity-Egger does not Egg the entity.

Compare this with a saddled Pig or Strider, where right-clicking with an egger mounts the entity, but shift+right-clicking eggs it.

On horses the shift+right-click might instead be captured by the action of opening the chests mounted on a donkey or a mule (even though you can't mount chests on a horse).

When Shift+right-clicking with an Egger, the egging action should probably have priority over the mounted chest opening action (regardless of whether a chest is mounted on the entity).

**Comment by mcenderdragon** [comment]
Do it from father away, you can throw the entity egger.

**Comment by qrss** [comment]
Thanks for the tip!

I didn't even think of using it at long range. I've always just walked up to mobs and clicked on them.

Once again a case of me not reading the documentation closely enough.
