### ISSUE TITLE
[1.16.4] Copies of liquids on your ship get left behind when teleporting

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#733]
Forge version: 35.1.28
Futurepack version: 21.0.4

When you have liquids on your ship (such as an infinite water source or a cobblestone generator), then teleporting in the overworld leaves a copy of these liquids behind.

![liquid_teleport_bug](https://user-images.githubusercontent.com/32312262/103472002-16e61300-4d88-11eb-9789-bb5b0c7462d9.gif)

**Comment by Yirok42** [comment]
Wow! teleporting the ship in the same dimension is clearing working again! (after having to replace board computers multiple times, I stopped trying that feat)
