### ISSUE TITLE
[1.16.4] Config auto-regenerates incorrect dimension IDs for tech dungeon blacklist

### ISSUE THREAD

**Issue by Opulous** [mcenderdragon/Futurepack-API#734]
I'm using version 21.0.1 on 1.16.4 and I'm trying to edit the configs to stop the miniature 1-room tech dungeons from spawning in the nether and end. I still saw them spawning despite the config having the nether and the end in the auto-generated config list.

I checked the futurepack config, and the IDs it generated in the config are actually incorrect. It puts in "minecraft:nether" and "minecraft:end", when the actual correct IDs are  "minecraft:the_nether" and "minecraft:the_end"

I simply tried to edit the incorrect dimension IDs, but when I start the game it forcefully edits them back to the incorrect IDs and the dungeons continue spawning in the nether and end. I tried making the config file read-only so the mod couldn't do this, but then the game just crashes on startup. I also tried putting the futurepac common config into the defaultconfig folder too, but this didn't work.

Am I doing this incorrectly, or is this a bug?

**Comment by mcenderdragon** [comment]
those are not dimension IDs they are the biome ids. and yes they are not correct as the nether & end has now sub biomes

**Comment by mcenderdragon** [comment]
This should be the complete list: "minecraft:nether_wastes", "minecraft:crimson_forest", "minecraft:warped_forest", "minecraft:soul_sand_valey", "minecraft:basalt_deltas","minecraft:the_end", "minecraft:small_end_islands", "minecraft:end_midlands", "minecraft:end_highlands", "minecraft:end_barrens","minecraft:the_void" and it will eb added in the next verison
