### ISSUE TITLE
[1.16.4] Forcefields are not transparent when standing in them

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#735]
Forge version: 35.1.28
Futurepack version: 21.0.4

When standing in a force field (the ones in the dungeon dimension at the turret checkpoints), all you see is blackness.

Gave me a scare when first walking through it.

I'm guessing this is not intentional.

![forcefield](https://user-images.githubusercontent.com/32312262/103584731-2da07d00-4ee2-11eb-90f7-8484f09c0f02.gif)

**Comment by Yirok42** [comment]
When something is resolved, can you include which is the first version to have the fix? 
And perhaps a link to the latest version available?

**Comment by mcenderdragon** [comment]
https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3169539
