### ISSUE TITLE
[1.16.4] Tyros leaves dropping wrong items when broken with Silk Touch or Shears

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#738]
Forge version: 35.1.28
Futurepack version: 21.0.4

When Tyros leaves are broken with Silk Touch, they drop Mushroom Leaves.

When Tyros leaves are broken with Shears, they just break and sometimes drop saplings. Normally breaking leaves with shears would drop leaf blocks.

Other leaves from Futurepack work fine.

![tyros_leaves](https://user-images.githubusercontent.com/32312262/103630118-84896f00-4f41-11eb-8f7a-232ba6f6a5cf.gif)

![tyros_leaves_shears](https://user-images.githubusercontent.com/32312262/103631032-cc5cc600-4f42-11eb-9bca-c81ae01b6382.gif)

**Comment by qrss** [comment]
I'll note that Mushroom Leaves don't drop as blocks when sheared either. This is similar to how Mushroom Blocks behave in Vanilla.

I guess this means that Mushroom Leaves are more mushrooms than leaves, so I wouldn't count this as a bug, although either behavior would be fine.

**Comment by mcenderdragon** [comment]
Tyrso leaves now drop correctly
