### ISSUE TITLE
[1.16.4] Prismid not generating?

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#739]
Forge version: 35.1.28
Futurepack version: 21.0.4

I think I recall Prismid generating on the surface in the Deadlands on Tyros.

I have looked around a lot in this version, but have not found any. Might be a bug, or might be I'm looking in the wrong place.

![2021-01-05_13 04 14](https://user-images.githubusercontent.com/32312262/103644525-cec91b00-4f56-11eb-80a4-6dcb1a3edc31.png)

**Comment by mcenderdragon** [comment]
it genrated as ore, I added another layer at the top so its more visible again.

**Comment by qrss** [comment]
Hm, I also looked underground in 21.0.4 without finding any Prismid, but perhaps it was just very rare.

**Comment by Yirok42** [comment]
Solved in DEV sounds like a new version; any estimate of when it will be available?

**Comment by AjzaklijaStomaklija** [comment]
You can play DEV version now and try to find some bugs to report.
https://www.mediafire.com/file/mmmrw65ckdc34xn/Futurepack-1.16.4-21.0.4.jar/file
