### ISSUE TITLE
[1.16.4] Paraglider + Spectator mode + Liquid = Unable to fly up

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#743]
Forge version: 35.1.28
Futurepack version: 21.0.4

When you are in Spectator mode, wearing a Paraglider and in a liquid, then activating the paraglider makes unable to fly up forcing you to either swim or fall through the world indefinitely until you exit Spectator mode.

This happened while trying to find Prismid for the other issue in Spectator Mode.

**Comment by mcenderdragon** [comment]
funny bug.
