### ISSUE TITLE
MC 1.16.4 / FP 21.0.4 Researcher progress bars display 100 % until a change happens

### ISSUE THREAD

**Issue by 7eggert** [mcenderdragon/Futurepack-API#745]
@Futurepack-1.16.4-21.0.4.jar
When the researcher is opened, all progress bars will start at 100 %. Only if the setup is correct and if the progress isn't stalled, the value will be updated. E.g. if a research needs energy and the energy setup is incorrect, it will display that the research is completed.

It's even impossible to see progress on the support bar if you're using flash drives; by the time you open the researcher, the progress is stalled.

**Comment by qrss** [comment]
Thanks for figuring this out!

I also had the bars sometimes show 100% even though the research was not complete, but I didn't manage to pin down the reason.
