### ISSUE TITLE
Recycler repairs items (too OP)

### ISSUE THREAD

**Issue by MJRamon** [mcenderdragon/Futurepack-API#751]
So, here is the problem: recycler repairs almost everything, and this is wrong, cause it's too OP.
futurepack-1.16.4-21.0.6

![image](https://user-images.githubusercontent.com/2642227/106245130-a6aaa000-6214-11eb-8500-42aee7c64c62.png)

**Comment by Maxwell-lt** [comment]
Plenty of other mods can do the same thing, such as Cyclic's lava/diamond anvils and Thermal Expansion's Flux Reconstruction augment. This functionality of the recycler is gated behind almost the entire Futurepack progression tree, so it takes a long time to even have access to it. Personally, I thing the rewards for reaching the end of a long progression tree should be powerful enough to justify the time spent.

Are you asking for a config option to blacklist certain items, or do you have another solution in mind? Also, those are not great items to use as an example, as the Botania swords can be repaired very cheaply with mana. Which items do you think should not be repairable?

**Comment by mcenderdragon** [comment]
Yu need SP points though, also I check the item if its repairable so if the item was not meant to be repaired the mod author could do that.

**Comment by MJRamon** [comment]
Yes, whitelist/blacklist config would be great.

**Comment by mcenderdragon** [comment]
blacklist is in 31.2.6823
