### ISSUE TITLE
[1.16.5] Saplings don't grow on the Grass Sapling Holder

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#753]
Forge version: 36.0.7
Futurepack version: 21.0.7

I can't get saplings to grow on the Grass Sapling Holder. Neither Bone Meal or raising randomTickSpeed helps.

Using Bone Meal can put the sapling into stage:1, but it will not grow it into a tree.

On the other hand, Menelaus Saplings do grow into trees on Sand Sapling Holders.

**Comment by mcenderdragon** [comment]
turn out you need to add the sapling holder to the ``minecraft:dirt`` tag

**Comment by mcenderdragon** [comment]
edit forge:dirt
