### ISSUE TITLE
[1.16.5] Block Breaker can break Bedrock

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#754]
Forge version: 36.0.7
Futurepack version: 21.0.7

This is possibly intentional, but I'll report it just in case.

The Block Breaker can break Bedrock, Command Blocks and other stuff that probably shouldn't be breakable by players.

**Comment by Yirok42** [comment]
What?! That's one of the amazing things about block breaker. :( If you can point it the right way, you can break anything. Oh well.
We used to play nomadic tents and FP, and we'd use the block breakers to break out of the tent in the other dimension, and then use the tents as awkward teleport huts, sort of like the little ponds of the Narnia books.
