### ISSUE TITLE
[1.12.2] Red Focus lens is a impossible item to research

### ISSUE THREAD

**Issue by MosukaSan** [mcenderdragon/Futurepack-API#759]
I was playing, when only had one item to unlock, I could not, because I needed an item called "red focus lens" however as I had said, there was only one item to unlock, so how am I going to get this "red focus lens"? 

![Screenshot_6](https://user-images.githubusercontent.com/78869115/107543907-6bab5380-6ba8-11eb-9529-c1da59f37e1b.png)
i'm sorry for the bad translation, I'm using google translator.

**Comment by mcenderdragon** [comment]
there are other researches in the other tabs you need to research first.

**Comment by MosukaSan** [comment]
> there are other researches in the other tabs you need to research first.

what I need to scan?
![Screenshot_1](https://user-images.githubusercontent.com/78869115/107549649-d790ba80-6bae-11eb-820f-d5c63a69afd7.png)
![Screenshot_2](https://user-images.githubusercontent.com/78869115/107549658-dcee0500-6bae-11eb-8e74-c82d500155d5.png)
![Screenshot_3](https://user-images.githubusercontent.com/78869115/107549703-e9725d80-6bae-11eb-89c5-4bf54cf0d1f0.png)
![Screenshot_4](https://user-images.githubusercontent.com/78869115/107549721-ed05e480-6bae-11eb-828a-9d32d784863f.png)
![Screenshot_5](https://user-images.githubusercontent.com/78869115/107549739-f2632f00-6bae-11eb-98b5-4bd0656783a1.png)
![Screenshot_6](https://user-images.githubusercontent.com/78869115/107549756-f68f4c80-6bae-11eb-820d-e35a8d338c2c.png)
![Screenshot_7](https://user-images.githubusercontent.com/78869115/107549781-fbec9700-6bae-11eb-9d13-1d99c7ba1eb7.png)

**Comment by mcenderdragon** [comment]
![people](https://user-images.githubusercontent.com/6342933/107550990-00767700-6bd2-11eb-9bea-60a11ecda5dd.PNG)

**Comment by MosukaSan** [comment]
> there are other researches in the other tabs you need to research first.

I researched a lot, stayed a few hours off, however I did not understand: 
- How will I unlock the "red focus lens" 
- Which item should I scan?

**Comment by qrss** [comment]
You probably need to unlock that thing first. Not sure what you need to scan. Maybe the Network Cable?

![galactic!](https://user-images.githubusercontent.com/32312262/107615198-0741d000-6c4c-11eb-93b3-44370f997562.png)

**Comment by MosukaSan** [comment]
> You probably need to unlock that thing first. Not sure what you need to scan. Maybe the Network Cable?
> 
> ![galactic!](https://user-images.githubusercontent.com/32312262/107615198-0741d000-6c4c-11eb-93b3-44370f997562.png)

yes, but network cable is used to unlock the item that needs red focus lens. before this "thing"

**Comment by qrss** [comment]
I think the Network Cable is used to unlock multiple things. Are you sure you have tried all scanning possibilities?

**Comment by mcenderdragon** [comment]
as this is solved (you need netweork cables before you can do this and it is possible to research - maybe you neeed menelaus first)
