### ISSUE TITLE
Cannot make Cores and RAM and cannot see their recipes

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#761]
Server: MC 1.16.4; Forge 35.1.37; FP 21.0.6
Client: MC 1.16.4; Forge 35.1.37; FP 21.0.6 (yes the same, I host both.)

The recipe for RAM and Cores in the Tech Tree Circuits page have no items.
Using my knowledge from having completed this many times on prior versions and also on Client only instances ( I have not made a client instance of 21.0.6, but I did with 21.0.4) 

This sounds familiar, like someone else may have already reported it. Perhaps it was a different version. If this is a confirmed bug, I am interested in a workaround. Perhaps there is a way to use /give to get items which are not the absolute lowest Ram Speeds and Core Powers.

I believe this would have to be a user error of some kind. I just do not know what to reset or change to avoid it. I have restarted my server, and I have restarted my clients.  This is my first 21.0.6 server. My prior server was 20.1.0. I know it worked there.
BTW, I had to set online-mode to false because we could not connect to the server without using patch cables to a router (not on WiFi) and this router is connected to nothing. I hope this is not related to the problem. I cannot think of anything else we had to do to get the server working but perhaps there was more.

**Comment by mcenderdragon** [comment]
do you have mods like "go away experimental settings" installed ? if so please try without and see if it still happens, also try if /reload fixes the problem.

**Comment by Yirok42** [comment]
I suppose it's possible. The mods I have are
* forgemod VoxelMap 1.10.14 (because the map I wanted wasn't updated to 1.16)
* futurepack-1.16.4-21.0.6 (this one was obvious)
* gravestone 1.16.4-1.0.8 (to not drop items on death)
* jei 1.16.4-7.6.1.65 (for quick recipe)
* Neat+1.7-25 ( because it shows the mob's health)

**Comment by Yirok42** [comment]
Huzzah! the /reload fixed it!!

Some time I'd like to read what else that fixes.

**Comment by mcenderdragon** [comment]
reopening this since /relaod should "fix" this and we need to find out what is happening (or not happening)

**Comment by Zygus42** [comment]
I was finding this same issue on our server, so I did some testing, and the recipes do not show up, even when only futurepack and JEI are installed:
futurepack-1.16.4-31.1.8137
jei-1.16.4-7.6.1.71
forge 1.16.5-36.0.7

I set the config options to not need research, and started in creative, and everything on the Circuits tab under Cores, Memory & Chipsets has blank recipes in the description and JEI does not show the recipes for these.


Where do I use /reload ? on our server GUI ?

nm - tried it on server and it worked - can see the recipes now.

**Comment by mcenderdragon** [comment]
Update: this issue is server side: also when expericing this issue on the server putting the items into the assembly table did not work and after using /reload it did work

**Comment by mcenderdragon** [comment]
Industrial Furnace: dont see recipe but can make items

**Comment by Wugand** [comment]
Is fixed in Futurepack-1.16.4-31.1.8176.jar (Commit 245e6c9c5c579cdfd03e6e65c6ec462deed0fa9a)
