### ISSUE TITLE
[1.16.5] Server hard lock when clicking on a Dungeon Checkpoint

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#764]
**Describe the bug**
When you click on a Dungeon Checkpoint, the server locks up hard for 15 seconds to 10 minutes.

**To Reproduce**
Click on a Dungeon Checkpoint, the third and fourth time.

**Screenshots**
Warmroast-
![image](https://user-images.githubusercontent.com/4427684/108455053-c38e2e00-722a-11eb-8295-bff75007e996.png)
Warmroast 2
![image](https://user-images.githubusercontent.com/4427684/108455090-d7399480-722a-11eb-8060-e4fa14e984a4.png)

**Additional context**

**Logs**
Debug log-
https://gist.github.com/ProsperCraft/e21da9da4d2c836b3dbe47d447205f4d

**Comment by ProsperCraft** [comment]
This was in the console when it hard locked but then recovered.-
`·
![image](https://user-images.githubusercontent.com/4427684/110159983-a3bd4500-7da8-11eb-8d60-4e78adacb9bd.png)

[11:44:28] [Server thread/DEBUG] [futurepack/]: Create EScanner massage with {"extra":[{"extra":[{"bold":true,"color":"dark_gray","text":"Floor:1 Mantes shi│···············································································
vering Cave L:0"}],"text":"You are at: "},{"text":"Teleport to: "},{"underlined":true,"color":"dark_blue","clickEvent":{"action":"change_page","value":"dung│···············································································
eon_teleport=ffffa73ffe67a080"},"text":"Floor:0 Wugis polar Virtuality L:0"},{"underlined":true,"color":"dark_blue","clickEvent":{"action":"change_page","va│···············································································
lue":"dungeon_teleport=ffffb3bffe667094"},"text":"Floor:1 Wugis polar Virtuality L:0"}],"text":""}                                                          │···············································································
[11:44:28] [Server thread/DEBUG] [futurepack/]: Resived Research request from TextComponent{text='Dreminon', siblings=[], style=Style{ color=null, bold=null│···············································································
, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}             │···············································································
[11:44:28] [Server thread/DEBUG] [futurepack/]: Resived Research request from TextComponent{text='Dreminon', siblings=[], style=Style{ color=null, bold=null│···············································································
, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}             │···············································································[11:44:28] [Server thread/DEBUG] [futurepack/]: Resived Research request from TextComponent{text='Dreminon', siblings=[], style=Style{ color=null, bold=null│···············································································
, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}             │···············································································[11:44:28] [Server thread/DEBUG] [futurepack/]: Resived Research request from TextComponent{text='Dreminon', siblings=[], style=Style{ color=null, bold=null│···············································································
, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}   `

**Comment by ProsperCraft** [comment]
futurepack.common.block.misc.TileEntityDungeonCore.run()99.65%

![image](https://user-images.githubusercontent.com/4427684/110189153-645c1c00-7ddb-11eb-9654-0606adfb9f02.png)

**Comment by mcenderdragon** [comment]
There is something realy weird going on becuase, I never experienced that issue and also that method is called async and only chcks 1 chunk before sleeping again, so there literaly is no way for me to further scale it down. I wonder why the "chunkExist" check takes so long, it absolutly should not, its a simple yes no.

**Comment by mcenderdragon** [comment]
this was fixed by https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3420273 
sorry for the long wait.
