### ISSUE TITLE
Flower Forest biome on Menelaus

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#765]
I'm using FP 21.0.6 and we just made it to Menelaus.
We landed and wished we'd brought more neon dust to make more fuel, but that's how it goes.

My son was wandering around looking for a gravel pit when he found a Flower Forest. Is this intended?
I don't mind finding a "garden of Eden" in space but I thought I should let you know in case it is not intended.
It could be the mods I have (same list as before plus create mod)

Anyway, under the Flower Forest biome of course we found neon sand, so we can power our ship after all.
There are more than one, but they are small, so it does not get in the way of what we came to Menelaus for.

**Comment by mcenderdragon** [comment]
jup thats intended has been there for a long time - its as rare as mushroom islands.
