### ISSUE TITLE
Researching

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#766]
Is there any benefit of having more than one T1 (each connected to a different power supply) to speed up research?
Just wondering.
Connected via network cable.
Since prior to cable only one can be connected, I've gotten in my head that each Researcher should only have 1 T1, 1 T2, and 1 T3, but perhaps that's flawed logic on my side

**Comment by mcenderdragon** [comment]
You have a larger buffer of energy but besides that there is not realy a benefit.
