### ISSUE TITLE
Sponge compatibility

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#77]
We try to run FuturePack and Sponge on an server.

It crashs imidetly if dimension 73 (Menelaus) get loaded in server startup.

Report:
http://pastebin.com/qSXmXzU9

Please analyse the problem and see if we can do something ... otherwise we report it, detailed at possible to Sponge

**Comment by mcenderdragon** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1046

**Comment by mcenderdragon** [comment]
Seems like the sponge porblem is fixed.
