### ISSUE TITLE
[BUG] Something happen

### ISSUE THREAD

**Issue by DevTimur** [mcenderdragon/Futurepack-API#777]
**Not sure how this happens. It just happens randomly. It happend 3 times already, with different worlds.**
**Ok so... I'm using Misty World dimension to spawn and live in. (using mods) Time to time, when i quit game (by closing window, yes, harsh stop, but i'm still tinkering with mods for my modpack), and then change, delete or add mods, this bug can happen randomly, not all the time. After that i can not enter the world. I found no ways to fix this issue, only deleting world.**

[Crash Log](https://pastebin.com/kDhTFt4a)

Minecraft version 1.12.2
Futurepack-1.12.2-26.4.89
Forge 14.23.5.2847

**I made quite the mess with mods, resource loaders, crafttweaker and others, so if you can't find the reason for this issue, i don't blame you. All i wanted to know, is what am I doing wrong to get this issue, because it's quite rare and i blame myself.**

**Comment by mcenderdragon** [comment]
seems like this was cuased because the save file was corrupted as in it did not finish saving.

**Comment by DevTimur** [comment]
Ok... so harsh closing game is the problem, ok then. My fault, my problem.
Thanks!

**Comment by DevTimur** [comment]
Addition to that report.
I got this bug again, and now i managed to fix it by deleting this file "ores_1618836691336.tmp" from folder "Ores" in dimension save file.
I'm gona send this file you to just in case it meant something.
https://www.dropbox.com/s/si8xga3cqm7jov4/ores_1618836691336.tmp?dl=1
