### ISSUE TITLE
Research System corruption

### ISSUE THREAD

**Issue by metzen227** [mcenderdragon/Futurepack-API#78]
version 1.10.2-24.2.11
Yesterday I unlocked all of the aspects and was able to view the research system details and use the scanner block.  This morning the server admin upgraded Mekanism to the latest version (1.10.2-9.2.1) to fix a bug in universal pipes (the only change to the server he noted other than the removal of Rockhounding Mod:Chemistry) and now it appears that researching is disabled/corrupted for me.  The Future Pack, The Research System and Tech Table items in the tree are all grayed out like I haven't unlocked them yet, however several of their sub entries are still researched.  I can use generators, and other blocks that I did not research yet (and were not able to use yesterday) but not the base scanner.

I see there is a command line to cheat all the research, but is there an option to reset someones research/mod level back to nothing?
![researcherror](https://cloud.githubusercontent.com/assets/5871197/20465165/bb28c00c-af1c-11e6-8351-62e8b1e2977a.PNG)

**Comment by metzen227** [comment]
did a little more testing on our side.  We isolated what we think is my toon's FT profile in the FT_Research folder on the server.  We deleted that file and restarted the world, but it appeared to have no effect.  My research UI is still the same.  Attached the link just in case it is the correct one and could be helpful. (github wouldn't let me attach the file or it in zipped form for some reason).

https://files-na.curseapp.net/4100dd3e-def6-4fe4-82d9-e3d784b6d774/8c607eca-defd-4dbf-8e5a-8dc51a2f144e.dat

**Comment by mcenderdragon** [comment]
It is only stored in that fiel and the comment it /fp research reset

**Comment by metzen227** [comment]
Thanks.  The reset command worked.  It reset my account back to zero, and I was able to rescan all of the base 12 aspects and restart the research chain.  
Sorry about the file, when I closed my curse client, apparently it removed the upload.
