### ISSUE TITLE
[1.16.5 - 31.1.8229] Aribrush deletes Tank when empty

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#781]
Version 31.1.8229 (2396c9ca70cdcdd3e98f855605a86ae0bc473277)

Empty LackTank of Airbrush is not replaced by empty tank when going empty on usage.

Debug:
futurepack.common.item.misc.ItemLackTank (setDamage)
    DirtyHacks.replaceData works and ItemStack is overridden

net.minecraft.item.ItemStack (attemptDamageItem:332)
   setDamage is invoked in 332 and stack content is changed
   but: l (new damage amount) is calculated before in 331
   return value is determined by l >= this.getMaxDamage() and since MiscItems.lack_tank_empty is not damageable this will always be true (means "item destroyed")

net.minecraft.item.ItemStack (damageItem :341)   
   calls this.shrink(1); and destroys the Empty Tank

**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by mcenderdragon** [comment]
should be solved now right ?
