### ISSUE TITLE
Item Sorter deletes Items

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#782]
FP 21.0.7 on a MC 1.16.4 Single Player using Forge 35.1.4

I checked to see if this was already reported and it seems a resurrection of issue #14.
I have an Item Sorter with "green" set for Gravel.
I then put 33 Gravel in and I see it flow on the Normal Pipe to a Wardrobe but when it arrives I only have 17. Repeat this with 17 and I get 8 (or maybe 9). 
I tried again with a 64 stack of Menelaus Gravel and only 34 arrived in the Wardrobe.
Repeating this with 34 yields 18; 18 yields 10; 10 yields 10... seems to have hit a value that works.

Strangely the Item Sorter loss only occurs when I place the stack directly into the Item Sorter. If I use a Hopper to feed the Normal Pipe all works as expected; no item loss.

As I only place stacks of material when setting up the 4-Sorter/9-Centrifuge/1-Furnace/1-Crusher rig this is not a high priority and perhaps it has existed in past versions.

**Comment by Yirok42** [comment]
I did not add those labels. I saw that yesterday and assumed someone else did it, but now I see it has my name by the action.

**Comment by mcenderdragon** [comment]
Ohh this is actually a quite serious bug, becuase only if you insert stuff with a hope it will not get deleted.
