### ISSUE TITLE
[1.16.5] Server crash not fully then lockup - research tools.composite_fishingrod

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#785]
**Describe the bug**
The server stopped, said it was crashing, but didn't make a crash report, and didn't stop, it just hung.

The stacktrace said this- https://gist.github.com/ProsperCraft/d05f3a5daca779a84f7b16b390a2b770

**To Reproduce**
No idea- nobody on the server said they were doing anything with Futurepack.

**Logs**
Debug log- 
https://gist.github.com/ProsperCraft/e9f61842b6dcfbe019898d8d758fdc9e

**Comment by ProsperCraft** [comment]
Odd, I swear I added more bug reports here.

We figured out that if a research completes while the player is offline, the server crashes.

**Comment by ProsperCraft** [comment]
Crash today-
https://gist.github.com/ProsperCraft/60b88e7e3ae41b189f57e1588588f700

**Comment by ProsperCraft** [comment]
Another one today when an online player was unlocking research for an offline player with the shared researcher-
https://gist.github.com/ProsperCraft/0c96072eb236b33cc94b8104dc3fb66d

Server locked this time, didn't crash.

**Comment by mcenderdragon** [comment]
its offline players + checking if advancements.

**Comment by mcenderdragon** [comment]
Can you please test if this is fixed here: https://modmaven.k-4u.nl/artifactory/local-releases/redsnakegames/mcenderdragon/futurepack/1.16.4-31.1.8241/futurepack-1.16.4-31.1.8241.jar
