### ISSUE TITLE
[1.16.4-31.1.8226] Overflow with Experience Research Module

### ISSUE THREAD

**Issue by thebloxxer11** [mcenderdragon/Futurepack-API#787]
**Describe the bug**
When filling the Experience Research Module with XP, It will overflow at 65536, before it gets full.
**To Reproduce**
1. Place an Experience Research Module down in the world
2. Use the /xp command to retrieve tons of experience to put into the experience module
3. Spam-click the + button to add the experience.
4. Eventually, slightly less than half-way up, the overflow occurs.

**Screenshots**
No screenshots

**Additional context**
I presume you have a short for the held experience, so I'd suggest making that an int.
Mod Version: 31.1.8226
Forge Version: 35.1.37

**Logs**
No crash logs.

**Comment by mcenderdragon** [comment]
Its a int in storage,m but miencraft uses short for syncronisation which I can not edit unfortunetly. This is only a visual glitch so the XP is actually stored correctly but shown wrongly.

**Comment by mcenderdragon** [comment]
Can you please test if this is fixed here: https://modmaven.k-4u.nl/artifactory/local-releases/redsnakegames/mcenderdragon/futurepack/1.16.4-31.1.8241/futurepack-1.16.4-31.1.8241.jar
