### ISSUE TITLE
Crash with Futurepack and AR combined.

### ISSUE THREAD

**Issue by jelaw21** [mcenderdragon/Futurepack-API#788]
**Describe the bug**
When I build an Advanced Rocketry Rocket (which is an entity), it crashed the game. It appears as though its checking the entity for life support and creates a ticking entity.

**To Reproduce**
1. Install Futurepack and Advanced Rocketry
2. Build a Rocket in AR and attempt to build it using the Rocket Assembly
3. See error

**Screenshots**

**Additional context**

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:

https://pastebin.com/3BYRUVt7

https://pastebin.com/32kJRqEE

Link to the Advanced Rocketry issue report: https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2053

**Comment by mcenderdragon** [comment]
Umm I dont real know how to approach this,I call: (w is a World)
`SpaceshipRegistry.instance.getPlanetSafe(w.getDimensionKey());`
and this crashes with: (id is a RegistryKey<World> id)
`return getPlanetSafe(id.getLocation());`
so the world has no registry key yet? is that even possible ?

**Comment by mcenderdragon** [comment]
Do you create a fake world? looking at `zmaster587.advancedRocketry.util.StorageChunk.<init>` you do something for storage of the rocket right ?

**Comment by jelaw21** [comment]
The rocket can have chests as storage. But the main storage is the guidance
computer which stores a chip with the location to land the rocket.

I did not create a fake world, I was in a data pack created dimension of my
own making.

**Comment by jelaw21** [comment]
FP Version: 1.16.4-31.1.8226

Conflict with AR still causes a crash when a rocket is first built.
[crash-2021-05-12_08.39.19-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/6466209/crash-2021-05-12_08.39.19-server.txt)

**Comment by mcenderdragon** [comment]
should be solved in 31.8242
