### ISSUE TITLE
[1.16.5] Block placers with no range extenders places blocks to a full stack.

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#789]
**Describe the bug**
placing a block placers and putting a stack of 64 in the bottom left slot makes the placer place 64 blocks. 
No range extenders are added to it.

**Screenshots**
https://gyazo.com/57dd53263f3867029e8f35c5af2b69b1
https://cdn.discordapp.com/attachments/356951809572470786/830853765091033098/unknown.png
https://gyazo.com/00a72fcb4fa82ea0d1d60255bf8f303f

**Additional context**
Modpack - TownCraft TWO for 1.16.5

**Comment by mcenderdragon** [comment]
HOw did you manage to put a stack of wood into the range extender slot ?
