### ISSUE TITLE
Crafting Damage Control Chipset crashes client

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#791]
Futurepack-1.16.4-31.1.8176

Put the input pieces into a chip maker. (my has full support but I have not tried an less one)
Take the chip out of the chip maker (assembly?) and the client stops.
Restarting after this crash, crashes immediately.
Going back to a prior save, and making the Damage Control Chip and back to crash.

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:

**Comment by Yirok42** [comment]
https://pastebin.com/raw/MntK7Rvs

**Comment by mcenderdragon** [comment]
Seems like the same crash as https://github.com/mcenderdragon/Futurepack-API/issues/780

**Comment by Yirok42** [comment]
I 'gave' myself the damage control chip that I needed and later I was able to craft cores, ram, and industrial chips with no issues (this crafting was done on Menelaus, if that matters)

**Comment by mcenderdragon** [comment]
I added more debug output to this crash can you try to reproduce it with this version: [Futurepack 31.2.6856](http://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.16.4-31.2.6856/futurepack-1.16.4-31.2.6856.jar)

**Comment by Yirok42** [comment]
I didn't see that you provided a new version but sometime along the way I picked up version 31.1.8241 and I have not had any issues making this Chip Set.
