### ISSUE TITLE
Logistics Editor crash

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#793]
Futurepack-1.16.4-31.1.8176
on MC 1.16.5 with Forge 36.1 (the forge that breaks ladders)

I tried to find an existing bug report but failed. Though I know I have seen this before.

**To Reproduce**
1. Have a Logistics Editor in your hand
2. Notice that it is not highlighting the edges of your machines
3. Click in the air to change from whatever it is on to something else (like Energy, Support, Network, or the other ones)
4. Server Crash!

Fairly easy to reproduce.

**Comment by mcenderdragon** [comment]
plese include the crash report

**Comment by mcenderdragon** [comment]
probaply similar to #752 so try to update your java.

**Comment by SpendIce** [comment]
I have a similar issue, but not only does it crash when changing the mode, but also when just looking at some machines with the logistics editor in hand.
Here is the crash report.
[crash.txt](https://github.com/mcenderdragon/Futurepack-API/files/6557312/crash.txt)

**Comment by mcenderdragon** [comment]
@SpendIce update your java version. its horrible old (1.8.0_51)

**Comment by SpendIce** [comment]
Oh, I didn't notice there were new versions as the updater said I had the latest version. Thanks.

**Comment by Yirok42** [comment]
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

The latest is 1.8.0_301.

**Comment by Yirok42** [comment]
I did not realize I was using the Minecraft bundled JRE. That is resolved.
