### ISSUE TITLE
[1.16.5] Stuck with research asking for calculation module

### ISSUE THREAD

**Issue by Monrdhil** [mcenderdragon/Futurepack-API#794]
Forge 36.1.13 / Futurepack 31.1.8226

**Describe the bug**
I can't progress in research. 
I have analysed all items I can produce (after research on blueprints needing 1 type of items). 
I have about 10 research blueprint needing 2 types of items and energy to be executed. I have connected the "Research module - Energy" filled with power produced by the "Generator". But the research station won't execute any of the task, asking each time for "Calculation Module", wich I don't master yet.

**Comment by mcenderdragon** [comment]
You dont need calculate modules to finish researches, it just there so you know thry are working. What exactly are you stuck with ?

**Comment by Monrdhil** [comment]
You can close the 

Searching for solutions with my situation, I thought I did not need them but ...
When launching a research needing 2 types of items I encounter the following :
  - the first bar is surligned in blue and the research begins, while color filling ... until 100% is reached
  - the second bar stay grayed (even with a fully charged "Research Module - Energy" on the side and research doesn't begin.
  - when overing the second bar, a panel indicates "0% Calculation module : 0"

**Comment by Monrdhil** [comment]
I've just launched minecraft, trying to take a screenshot. The situation is resolved (nothing done). 
I have no explaination on this evolution.
Maybe your contact ? 👍
