### ISSUE TITLE
Block Placer not Placing Blocks

### ISSUE THREAD

**Issue by jelaw21** [mcenderdragon/Futurepack-API#796]
**Describe the bug**
Futurepack: 1.164.4-31.1.8226

Block placer is not placing blocks.

**To Reproduce**
1. Place a block placer
2. Place a redstone timer underneath it
3. Place a stack of cobble in the first slot
4. Placer does nothing.

**Screenshots**
![image](https://user-images.githubusercontent.com/21100827/118409308-d82a6880-b657-11eb-945c-913d9af6c76b.png)

![image](https://user-images.githubusercontent.com/21100827/118409323-e8424800-b657-11eb-857e-b3b884c6ef4c.png)

**Comment by mcenderdragon** [comment]
fixed in 31.2.6824
