### ISSUE TITLE
Stuck on Board Computer

### ISSUE THREAD

**Issue by DoctorBibble** [mcenderdragon/Futurepack-API#797]
Hello All! I'm currently progressed to the board computer and am stuck. I am unable to progress without a redstone pipe and penton 2 core. The ways I believe I would research it are blacked out. Finished gas turbine but cant do anything else.
Anyone have any idea how to progress further or have a link to the research requirements?

**Comment by mcenderdragon** [comment]
try to scan the opti bench, T1 and T2 module.

**Comment by DoctorBibble** [comment]
> try to scan the opti bench, T1 and T2 module
Dont have an opti bench so that might be the reason? Which section is it under?

**Comment by mcenderdragon** [comment]
opti bench is in production.

**Comment by DoctorBibble** [comment]
I have everything completed up until grenade launcher and the board computer. All the sections are filled out too. Cant scan music disc either cause I'm not far enough.

**Comment by DoctorBibble** [comment]
![2021-05-27_13 39 16](https://user-images.githubusercontent.com/84928341/119873275-602f2e80-bef2-11eb-9cae-545b84cbf1fd.png)
![2021-05-27_13 39 14](https://user-images.githubusercontent.com/84928341/119873296-658c7900-bef2-11eb-87e8-16e1b4831ced.png)
![2021-05-27_13 39 11](https://user-images.githubusercontent.com/84928341/119873313-6c1af080-bef2-11eb-8d2f-74fa26fc8e82.png)
![2021-05-27_13 39 07](https://user-images.githubusercontent.com/84928341/119873347-73da9500-bef2-11eb-83ff-e310f200de0e.png)
![2021-05-27_13 38 54](https://user-images.githubusercontent.com/84928341/119873371-789f4900-bef2-11eb-8768-17eb7a019df7.png)

**Comment by mcenderdragon** [comment]
the 1st tab is probaply what you need todo next.

**Comment by DoctorBibble** [comment]
So once I get normal pipes it'll start progressing? How do I unlock those?

**Comment by Yirok42** [comment]
Did you get past this?

**Comment by Wugand** [comment]
For the Pipe you need to put the Industrial Furnace into Scanner (at the very begining).
For the Penton Core you need AI Memory, which you need Water Turbine and Renewable Energy.
Both researches are on the first Page (scrench symbol).

To talk in internal names, following sub trees are importent for the problem:

"core.penton"
 - "core.alon",
 -  - "upgradeT2",
 -  - "aispeicher"
 -  -  -  "erneuerbare"
 -  -  - "energy.wasser_turbine"

"log.redstonepipe"
 - "log.itempipe"
 -  - "itemlogistik"
 -  -  - "production"
 -  -  - "production.industrieofen"

**Comment by mcenderdragon** [comment]
as this has been answered with a clear solution I will close this.
