### ISSUE TITLE
Tech tree not showing & Tablet info shows JSON format info

### ISSUE THREAD

**Issue by Wissi** [mcenderdragon/Futurepack-API#798]
**Describe the bug**
After a client/server update:
The tech tree is not showing up anymore, but mouse over still shows the name of the "tabs".
The e-scanner is showing the JSON format for some objects scanned.

**To Reproduce**

**Screenshots**
![Gui1](https://user-images.githubusercontent.com/23312242/120400079-d83a9180-c302-11eb-9adc-bdaa6dfdfceb.png)
![Gui2](https://user-images.githubusercontent.com/23312242/120400087-dbce1880-c302-11eb-9f8b-857fb0ca36d5.png)
![Gui3](https://user-images.githubusercontent.com/23312242/120400097-dffa3600-c302-11eb-81fa-52be891a50b9.png)
![Gui4](https://user-images.githubusercontent.com/23312242/120400108-e4265380-c302-11eb-9da8-ff902296fb0a.png)
![Gui5](https://user-images.githubusercontent.com/23312242/120400115-e7214400-c302-11eb-81c1-e4152ad947fa.png)
![Gui6](https://user-images.githubusercontent.com/23312242/120400124-eb4d6180-c302-11eb-9862-a2fd3d49b80e.png)
![Gui6](https://user-images.githubusercontent.com/23312242/120400132-ee485200-c302-11eb-8624-0fd5dbd472a8.png)
![Gui7](https://user-images.githubusercontent.com/23312242/120400141-f1434280-c302-11eb-8a9d-fd68508259e3.png)
![Gui8](https://user-images.githubusercontent.com/23312242/120400148-f4d6c980-c302-11eb-884f-28c28611f8bf.png)

**Additional context**
The server/client was updated to version: Futurepack-1.16.4-31.2.6826.jar
Using: Forge 36.1.24
Modpack is [Towncraft 2](https://www.curseforge.com/minecraft/modpacks/towncraft)

**Logs**
No server side logs, server owner might provide if requested.

**Comment by ArcaneSan** [comment]
This happened to me after researching Production 1 and or Industrial Furnace

**Comment by geddon7** [comment]
this has happened to me several times and I can send two world saves that have this error the first of which I only used future pack and maybe one other mod

**Comment by mcenderdragon** [comment]
@geddon7 please do this together with your installed mods.

**Comment by geddon7** [comment]
I believe for the world save called 1.16 modded I only used future pack and jei and jouneymap. sending you google doc link for that save now https://drive.google.com/file/d/17sp2QsyJX2zOtwjF65R07NOH0D5dTywp/view?usp=sharing

**Comment by geddon7** [comment]
here is the link for the whole folder I made for the saves I get with this bug https://drive.google.com/drive/folders/1krzfhHY0AlxBHAOP7pi9rQO7YXc00RTn?usp=sharing

**Comment by geddon7** [comment]
I messed with the no lag test files by transferring a copy of the file in the FP_Research folder from the 1.16 modded save

**Comment by geddon7** [comment]
I noticed this effect on my no lag test save only after the optibenches stopped working

**Comment by geddon7** [comment]
I just found something weird, the error appeared again as soon as I put in the command /futurepack research unlock toruscore

**Comment by geddon7** [comment]
have another I put all the world saves that have this issue in the google folder I linked before

**Comment by geddon7** [comment]
it seems whenever this problem pops up the optibench won't let me access the plans ui making it impossible to use them

**Comment by geddon7** [comment]
another one added, this time the glitch started when I randomly got a bunch of researches without using a command or any other method to get them

**Comment by geddon7** [comment]
every time I get the glitch I have either had disc research or had it given to me in some way

**Comment by geddon7** [comment]
I uploaded a before and after the glitch of the same world with less than 3 minutes between the times they were saved

**Comment by geddon7** [comment]
it seems putting the researcher down is the trigger for the last world save called newbie

**Comment by mcenderdragon** [comment]
ooooof, that problem is sooo stupid - I am so stupid. Yeah it just needs a research in the world to trigger this.

**Comment by mcenderdragon** [comment]
@geddon7 plese try if this version fixes this problem: [futurepack-1.16.4-31.2.6837.jar](http://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.16.4-31.2.6837/futurepack-1.16.4-31.2.6837.jar)

**Comment by ArcaneSan** [comment]
Your not stupid Mcenderdragon! We all make mistakes, I have been loving this mod. Also, tested the new version and replicating the same procedure I did before, it is working.
