### ISSUE TITLE
Crash while rocketjumping

### ISSUE THREAD

**Issue by Maexel12** [mcenderdragon/Futurepack-API#799]
<Futurepack-1.16.4-31.2.6826>
**Crash while entering  Menelaos **
I wanted to revisit Menelaos, after starting the rocket to "jump" to menelaos, the screen turned "blackish" for 10 seconds. After that i crashed. The server stayed on, while i crash with an null pointer exception.
My friends also crash with the same error.

**To Reproduce**
I can't repoduce, because the client crashes while entering the server.

**Logs**
https://pastebin.com/2Bt8Jw2h  crash-2021-06-08_00.24.32-client
https://pastebin.com/SQbxdFD9 crash-2021-06-08_00.36.03-client
https://pastebin.com/wU5pgzUC FP-Latest
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/6612356/latest.log) latest

**Comment by mcenderdragon** [comment]
Try o update you jav version, you are on 1.8.0_51 this version is known for these kind of problems

**Comment by Maexel12** [comment]
I updated the version, still doesnt work.

---Client Files---
crash - https://pastebin.com/Yr82J45E
[clientlatest.log](https://github.com/mcenderdragon/Futurepack-API/files/6624754/clientlatest.log)
---Server Files---
crash- https://pastebin.com/NLTb3Xu9
[serverdebug.log](https://github.com/mcenderdragon/Futurepack-API/files/6624765/serverdebug.log)
[serverlatest.log](https://github.com/mcenderdragon/Futurepack-API/files/6624771/serverlatest.log)
serverFP-Latest - https://pastebin.com/p515QTXR

**Comment by mcenderdragon** [comment]
the server crash is from refined storage

**Comment by mcenderdragon** [comment]
also try if this version fixes it:  http://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.16.4-31.2.6837/futurepack-1.16.4-31.2.6837.jar

**Comment by Maexel12** [comment]
heya, i now looked in the server crash, thanks for telling me - just thought about the jumping must be cause of FP. but that does not explain why the client crashes. I tried the new FP Modfile - didnt work same errors.
I tried even more. I deleted the regions of menelaos that the server can make a new one. I removed everything out of the rocket that wasnt from futurepack but yeah the planets are now unachievable...
Any tips?

**Comment by mcenderdragon** [comment]
the crash is cuased by the sky rendering failing. If it crashes again can you please include the new crash report?

**Comment by Maexel12** [comment]
Just wanted to add... it must be something with the world itself - i tried to /execute in futurepack:menelaus run tp @p 0 240 0 and it still crashes.

newest crash - https://pastebin.com/2f4rf22b
https://pastebin.com/wEvLtW4u

The crash also happens with an completly new world.

**Comment by mcenderdragon** [comment]
Try with the new futurepack version & the new Java version.

**Comment by Maexel12** [comment]
Uhh... ii did that already with java... maybe curselauncher resets them.

Now i tried it over multimc with Java and the new futurepack = It works :)
