### ISSUE TITLE
Crash with Loading LootTables

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#8]
http://pastebin.com/7jqtBkcJ
orginal : https://minecraft.curseforge.com/projects/futurepack?gameCategorySlug=mc-mods&projectID=237333#c74

**Comment by WenXin20** [comment]
I get this crash too with forge 2092
Here's a [crash report](http://pastebin.com/umHixxpG).

**Comment by mcenderdragon** [comment]
This is a confilic with EnchantingPlus. using this config file (http://pastebin.com/p42pUy8j) should fix it.

orginal: https://minecraft.curseforge.com/projects/futurepack?gameCategorySlug=mc-mods&projectID=237333#c86

**Comment by WenXin20** [comment]
Thanks
