### ISSUE TITLE
[1.16.5] Server crash - java.lang.AbstractMethodError: Method futurepack/common/block/inventory/TileEntityForscher

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#801]
Futurepack-1.16.4-31.2.6826
Modpack - [TownCraft TWO for 1.16.5](https://www.curseforge.com/minecraft/modpacks/towncraft) - https://www.curseforge.com/minecraft/modpacks/towncraft
**Describe the bug**

Dedicated server crash on player logging in after doing research.

**To Reproduce**
1. research with 2 pistons and 2 cables when the pistons are inserted the crash happens. Now when that player logs in every time the server crashes.

**Logs**
Crash report- https://gist.github.com/ProsperCraft/7dc2aabdb1fa0dd28dccad8f5d9396e5
Debug log- https://gist.github.com/ProsperCraft/933f586ec860dee10e0f0c9932f1bd96

**Comment by mcenderdragon** [comment]
Duplicate of #800 - a version with the fix should be ready in a few minutes

**Comment by mcenderdragon** [comment]
[1.16.4-31.2.6840](https://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.16.4-31.2.6840/futurepack-1.16.4-31.2.6840.jar)

**Comment by ProsperCraft** [comment]
We can confirm this fix works on the server, it no longer crashes.
