### ISSUE TITLE
"Errors in currently selected datapacks prevented world from loading"

### ISSUE THREAD

**Issue by TripConeHead** [mcenderdragon/Futurepack-API#803]
**Describe the bug**
After exiting and re-entering any world previously loaded with Futurepack, a mod incompatibility prevents the world from being loaded under the error of "Errors in currently selected datapacks prevented world from loading"

**To Reproduce**
1. Use unknown incompatible mod
2. Create new world 
3. Exit World
4. Re-Enter world
5. See error

**Screenshots**

**Additional context**
Have a very large mod list, likely an incompatibility. Potentially related to the backup system? 

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
FP Latest: https://pastebin.com/RK4AMwdr
Latest Log: https://gist.github.com/TripConeHead/e3cf167243f13fee964e545859992048

**Comment by mcenderdragon** [comment]
> Was this mod https://www.curseforge.com/minecraft/mc-mods/illagers
