### ISSUE TITLE
[1.16.5] Techtable deletes half of crafting results on r-click

### ISSUE THREAD

**Issue by Zarvera** [mcenderdragon/Futurepack-API#805]
**Describe the bug**
When crafting any recipe that has more than 1 item as a result (i.e. torches, wood to planks, etc.), right-clicking the crafting output to grab everything instead just crafts once and deletes half the items you were supposed to get.
i.e. place 4 of any wood into the techtable and right click on planks to get 16, instead one wood is consumed and you get 2 planks.

**To Reproduce**
- put any recipe that results in more than 1 item per craft in the Techtable
- recieve only half of intended amount per craft

**Screenshots**
![2021-07-09_04 15 42](https://user-images.githubusercontent.com/44240662/125009027-6b868580-e06c-11eb-9dfd-31f3abd003f2.png)

![2021-07-09_04 15 49](https://user-images.githubusercontent.com/44240662/125009045-73dec080-e06c-11eb-8842-06bd4b25ae8b.png)

**Additional context**
This might be something to do with either CraftingTweaks or MouseTweaks, i'm not entirely sure if r-clicking to masscraft is Vanilla feature or from on of those two mods

**Versions**
Futurepack - 1.16.4-31.2.6840
Forge - 36.1.16
MC - 1.16.5

**Comment by mcenderdragon** [comment]
COnfirmed & fixed.

**Comment by Yirok42** [comment]
Hurray! I just stopped using right click.
By the way, when "fixed" is announced, could you also indicate at which version the fix exists?
Thank you for all the support.

**Comment by mcenderdragon** [comment]
try https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3427287
