### ISSUE TITLE
Game crashes when using composite fishing rod

### ISSUE THREAD

**Issue by SkyProgs** [mcenderdragon/Futurepack-API#811]
**Describe the bug**
Game crashes when using composite fishing rod on our devtest server.
Futurepack 1.16.4 31.2.6840

**To Reproduce**
I used the Composite Fishing Rod on our DevTest Server and it crashed.

**Logs**
https://pastebin.com/HdZK3y57

**Comment by Yirok42** [comment]
#820 is duplicate of this. I'll close #820.
