### ISSUE TITLE
Issue when launching the game

### ISSUE THREAD

**Issue by tanustasu** [mcenderdragon/Futurepack-API#812]
**Describe the bug**
I receive 2 types of errors when launching Minecraft with the mod, NoClassDefFoundError and ExceptionInInitializerError

futurepack-1.16.4-31.2.6840

**To Reproduce**
Launch the game

**Screenshots**
![image](https://user-images.githubusercontent.com/88432387/128166057-cea7cb33-96d0-4050-9703-c68a13a9d0b7.png)

**Logs**
https://gist.github.com/tanustasu/e0f5ba2e4a7ec7d832a7a594f68ca295

**Comment by mcenderdragon** [comment]
I can start it without problems, does this always happen ?

**Comment by tanustasu** [comment]
> I can start it without problems, does this always happen ?

Yes, it happened every time when I launched the game, I even tried downloading Forge again. Could it be because I'm using the Windows 11 Preview?

**Comment by mcenderdragon** [comment]
try to reproduce this with win 10, java 8 update > 200 and forge

**Comment by tanustasu** [comment]
Nope, still doesn't work. I'm using 1.16.5, by the way.

**Comment by mcenderdragon** [comment]
yeah, I am also playing on a 1.16.5 server with friends and there is no problem, so I am a bit confused. Try Forge 36.1.66

**Comment by tanustasu** [comment]
I've managed to fix it by launching the mod on CurseForge launcher, idk how though. Thanks for helping
