### ISSUE TITLE
Atmossphere crashes game

### ISSUE THREAD

**Issue by SkyProgs** [mcenderdragon/Futurepack-API#814]
**Describe the bug**
Mantes was in asteroid belt and it crashed after a while when using oxades.

**Logs**
https://pastebin.com/P1ym5QjJ

**Comment by mcenderdragon** [comment]
Deadlock becuase Server thread waits for Atmosphere thread & Atmohsphere waits for Server.

**Comment by mcenderdragon** [comment]
should be fiyed now.

**Comment by Yirok42** [comment]
Asteroid belt? Is this accessible in survival?

**Comment by SkyProgs** [comment]
@Yirok42 I don't think so. It is work in progress at the moment, but we also use GitHub for internal Issues for upcoming features.
