### ISSUE TITLE
[1.16.5] Game Crashing While Joining World because of FP Chunk Scanning

### ISSUE THREAD

**Issue by Lushtub** [mcenderdragon/Futurepack-API#815]
[1.16.5]
**Describe the bug**
The game is crashing because of Futurepack when trying to join my Dev World. The crash report says it is an ArrayIndexOutOfBoundsException due to Futurepack chunk scanning. I'm not sure to get what that means, but I think it is a mod bug.

**Additional context**
If I create a new world, the game doesn't crash. The bug might have happened because of me, but I wanted to report it in case it was a mod bug.

**Logs**
https://pastebin.com/u4029Rvu

**Comment by mcenderdragon** [comment]
seems like something corrupted the save file - this has so far never happened to me.

**Comment by Lushtub** [comment]
I don't really know what could have caused it. I'm developping a modpack, and all I've done is modifying the worldgen, recipes, adding quests and features.

I guess I'll create a new dev world. If this issue happens again, I'll notice you, but for now, you could close the issue I think.
