### ISSUE TITLE
Reasearcher not working properly

### ISSUE THREAD

**Issue by kungstoffe08** [mcenderdragon/Futurepack-API#819]
![2021-08-28_20 07 03](https://user-images.githubusercontent.com/79698504/131226966-51afb34d-b1c7-41ea-9fc8-2fa1769e56f5.png)
![2021-08-28_20 07 28](https://user-images.githubusercontent.com/79698504/131226968-5c06764a-1c11-481d-84d2-052ca6a13d68.png)
![2021-08-28_20 07 38](https://user-images.githubusercontent.com/79698504/131226967-2134b5f0-7c54-493c-b987-7986dfda3232.png)
What in a God's sake is this?? why can't i research properly?? somebody help me please!!!

**Comment by mcenderdragon** [comment]
You dont have enough neon energy, thats why the 2nd bar is gray.

**Comment by kungstoffe08** [comment]
![2021-08-31_15 55 58](https://user-images.githubusercontent.com/79698504/131515579-529b6d65-7d0e-4692-85d3-e6e4fe2f71d4.png)
![2021-08-31_15 56 02](https://user-images.githubusercontent.com/79698504/131515596-b1f83f1e-9922-4e4f-b744-9f9b17477396.png)
![2021-08-31_15 56 09](https://user-images.githubusercontent.com/79698504/131515591-54be2e56-304a-4111-bf33-7e7045978e2f.png)
![2021-08-31_15 56 13](https://user-images.githubusercontent.com/79698504/131515586-8ab04a00-a690-49cf-91c7-fbefdf4a96a4.png)

**Comment by SkyProgs** [comment]
The new screenshots show a different recipe. Do you have an AI Module connected and filled with support points?

**Comment by kungstoffe08** [comment]
no, does it effect it that much?

**Comment by kungstoffe08** [comment]
@SkyProgs thank you very much, now just one bar needs to be filled but idk how to do it 
![2021-08-31_17 32 56](https://user-images.githubusercontent.com/79698504/131532249-ef86485e-1f3f-4ecc-bbd7-55b64edf049d.png)

**Comment by kungstoffe08** [comment]
its somehow filling (very slowly but filling) thanks you very much guys

**Comment by mcenderdragon** [comment]
no problem haha.
