### ISSUE TITLE
JEI shows wrong Item texture

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#82]
In all Recpies for "xxxx Colored Tank" , JEI shows an "Konstruktionkopierer"-Item. (instead of Tank)
The Name and Meta is correct, only the texture is wrong.

**Comment by mcenderdragon** [comment]
are the items in the creative tab correct

**Comment by Wugand** [comment]
Yes, also in the crafting recpie for empty tank

**Comment by mcenderdragon** [comment]
@mezz we have a realy weird problem here, our shapeless recipe displays an item as if it has meta 0, but the hover text is correct with meta 16 and also the filter works. Any idea what is possible wrong ?

**Comment by mezz** [comment]
I don't know sorry.
To debug weird items in dev, I sometimes add a `ItemTooltipEvent` and put a breakpoint in it so that I can hover over an item in the game and then inspect it closely in the debugger.

**Comment by mcenderdragon** [comment]
ok, i'll try that, thanks.

**Comment by mcenderdragon** [comment]
weird they are obsolutly fine. The wird thing is sometimes for only 1frame I I shiftclick in some machnies every "tools" Item is getting the texture from meta 0

**Comment by mcenderdragon** [comment]
The Empty tank is extacly meta 16, maybe some old logic to prevent to big metas is using % and changes it to 0
