### ISSUE TITLE
FP FIshing Rod Crash (Ticking player)

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#820]
Fairly recently new world using 31.2.6856.

Fishing with the FP Fishing Rod crashes LAN world.

**To Reproduce**
1. Either be in a boat or be on land (probably be anywhere)
2. Click to cast the line into the water.
3. The FP Fishing Rod goes "down" a bit, and the world locks up.

**Version**
Minecraft Version: 1.16.5
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_291, Oracle Corporation
forge-1.16.5-36.1.58-client.jar                   
forge-1.16.5-36.1.58-universal.jar                
futurepack-1.16.4-31.2.6856.jar                   

**Logs**
https://gist.github.com/Yirok42/a556ffba95e3829398de756bcf3ba85b

**Comment by Yirok42** [comment]
I updated some of my unrelated mods and removed one.
I tried again with a vanillia fishing rod.
I was able to cast the rod and catch a fish but as it came back to me, it still crashed in the same method

https://gist.github.com/Yirok42/a510f39b4fa4cecbb8f9f0b11b4d7d86

I'll update Forge next.

**Comment by Yirok42** [comment]
Using a vanilla fishing rod and casting over and over yields multiple deployed hooks. Very strange. Going back to the FP Rod still causes immediate crash.

**Comment by Yirok42** [comment]
Duplicate of 811. I searched for fishing issues before creating and somehow missed 811.

**Comment by mcenderdragon** [comment]
try https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3427287
