### ISSUE TITLE
Sorter Creates Items

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#821]
This is possibly a recently added bug.

**To Reproduce**
1. Have a Sorter connected to power; nothing is needed to be configured in the colored output.
2. Have pipe segment on the "bottom"; this pipe is connected to nothing.
3. Put any one item in the Sorter.
4. In seconds you will have 575 more of this item.

**Screenshots**
I recreated this in creative mode with only the Future Pack mode to ensure it was not cross-mod contamination.
I almost took a screenshot but I was trying to use a Scrench to alter the cables used to connect the Sorter but that caused a crash that I am not asking about today.

**Additional context**
I first saw this in my survival world where I have a mining base, 3 sorters, 10 centrifuges, and a neon industrial furnace (I call it 'the Machine'). I normally set this up (in each world) to receive the results of the mining drone. I was very surprised to find it full of cobblestone, then copper dust and sand, so much material. I hadn't even started the mining drone. I was just trying to feed some excess cobblestone from prior to building the Machine. Sigh. I think the Sorter should not accept items except on the "input" sides or bottom.

**Version**
Minecraft Version: 1.16.5
Java Version: 1.8.0_291, Oracle Corporation
FML: 36.2
Forge: net.minecraftforge:36.2.2
Mod List: 
 forge-1.16.5-36.2.2-client.jar    |Minecraft  |minecraft  |1.16.5
 forge-1.16.5-36.2.2-universal.jar |Forge      |forge      |36.2.2
 Futurepack-1.16.5-31.2.8465.jar   |Futurepack |futurepack |31.2.8465
Data Packs: vanilla, mod:forge, mod:futurepack

**Logs**
I will provide if desired, but it is very easy to reproduce, and if it is not. I am willing to download newer versions so as to match any setup (assume newer than the versions I have) to confirm a fix. I read through the debug.log, latest.log, FP-Latest.log, and ccyy-mm-dd-1.log.gz but nothing looked like 'oops creating matter out of nothing'.    

If this is resolved, please include a link the new download.

**Comment by Yirok42** [comment]
Normally I would not mind extra items but infinite a) feels like cheating, and b) clogs the Machine.

**Comment by mcenderdragon** [comment]
fixed https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3456392

**Comment by Yirok42** [comment]
Thank you for the quick response but it seems that (31.2.6976) is an older version that what I have (31.2.8465).

**Comment by mcenderdragon** [comment]
nope the 8xxx version are in fact buggy and older. 31.2.6976 is the latest
