### ISSUE TITLE
Cannot reseach iron ladder :( again ladder

### ISSUE THREAD

**Issue by Apollon-Theos** [mcenderdragon/Futurepack-API#829]
Receive ladder Blueprint, make 32 of iron stick (all my iron, at this moment) and insert all this into Reseacher and progress always is 0%. I wait game-day near home, no progress. I place 36 Iron Stick into Reseacher, same result.

**To Reproduce**
Normal play process. I read issue about second feature from Blueprint, but Ladder recipe not contain second capability.

**Screenshots**
![image](https://user-images.githubusercontent.com/46534073/140817188-d326485b-83c1-4557-b95f-37139f6ef01c.png)
![image](https://user-images.githubusercontent.com/46534073/140817263-4ef64182-b16a-4cf9-95be-9067bc3221fc.png)

**Additional context**
I think - again exist non compatibility with new version of Forge.

**Version**
1.16.5
Forge Version:
36.2.8
Futurepack Version: 
Futurepack-1.16.5-31.2.6976.jar

**Logs**
not exist

**Comment by mcenderdragon** [comment]
those are the wrong iron sticks, they are not from futurepack right?

**Comment by Apollon-Theos** [comment]
You are right! This is my inattention. Sorry.
