### ISSUE TITLE
Special AI mobs not respecting chunk protection

### ISSUE THREAD

**Issue by Divineaspect** [mcenderdragon/Futurepack-API#839]
**Describe the bug**
Special AI mobs not respecting chunk protection

**To Reproduce**
Install Special AI and Futurepack, go to dungeon dimension below bedrock and sit until a zombie spawns, watch them destroy their way through lots of blocks.

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.2.20
Futurepack Version: 1.16.5-31.3.7000

**Comment by mcenderdragon** [comment]
please open a issue in thw Special AI mob issue tracker and link it here.

**Comment by mcenderdragon** [comment]
Can you test if thsi version fixes it: [futurepack-1.16.5-31.3.7006.jar](https://modmaven.dev/artifactory/local-releases/redsnakegames/mcenderdragon/futurepack/1.16.5-31.3.7006/futurepack-1.16.5-31.3.7006.jar)
