### ISSUE TITLE
Client Side Spam - Unknown Cause

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mcenderdragon/Futurepack-API#84]
I was told to report this to you form the creators of Pokecube; Thutmose.
https://gist.github.com/P3rf3ctXZer0/8c6ee4f09046a98b21c75cdc9a85ec77

**Comment by Wugand** [comment]
Hi,
I analyse the log, but expecting the normal "errors" at startup (falsely missing models), **I am not able to see a relation to our mod.** 
* if he points to the "FPDustManager" execptions: This are normal, and absolutly no problem.

The problem itself looks very strange. I terms of your modpack-size, I think it is able that your Java runtime runs out of resources. But i'm not sure in this point.

So, sorry we are not able to help you.

**Comment by Wugand** [comment]
@Thutmose
Where do you see the relation to our mod?

**Comment by Wugand** [comment]
By the way, this error message points to "PlacementPreview":
fi.dy.masa.placementpreview.fake.FakeWorld@374c3a65
(https://github.com/maruohon/placementpreview/blob/master/src/main/java/fi/dy/masa/placementpreview/fake/FakeWorld.java)

In reletion to the code from Pokecube, i would say: The FakeWorld of PlacementPreview has a problem with "It is somehow ticking when not loaded"*

*https://github.com/Thutmose/Pokecube/blob/1.9/Pokecube%20Core/src/main/java/pokecube/core/moves/MoveQueue.java  Line 62 - 65

**Comment by Thutmose** [comment]
the major spam there was not related to this mod, it is entirely from placement preview ticking a world that is not loaded, which I had told him about.

I had pointed out that besides the continuous placement preview spam, that the only other spam (during initial load) was model loading errors, and this mod happened to be one of them, I agree that it is nothing critical at all, as it only happens during the model loading phase, it is also not just from this mod, there were like 5-10 mods in his pack that also gave large numbers of those.

**Comment by P3rf3ctXZer0** [comment]
Okay I didn't know.
