### ISSUE TITLE
[1.12.2]Placing a hopper below some machines crashes and locks the world

### ISSUE THREAD

**Issue by anonYes** [mcenderdragon/Futurepack-API#840]
**Describe the bug**
placing a research module over a hopper will crash your game instantly, and will crash again every time you open the world again.

**To Reproduce**
Step 1: take a research module
Step 2: take a hopper
Step 3: place the hopper under the research module
Step 4: hopefully you didn't do that on your survival world

**Additional context**
I'm 99% sure its all the research modules, but if not the the energy one is the one that i got a definite proof of it crashing.
i haven't tested all the blocks but i the log I put the ones that i tested and didn't crash

**Version**
Minecraft Version:1.12.2
Forge Version: 14.23.5.2859
Futurepack Version: 26.4.89

**Logs**
https://gist.github.com/anonYes/5f1a744c8d0bbb337f98bb9def5896e5
https://paste.atlauncher.com/view/6ee58c8c-7606-4f46-9541-b243c034dda6

**Comment by mcenderdragon** [comment]
does this also happen with only futurepack installed ? also 1.12 will no receive updates from me anymore sicne I have way to little time to even maintain 1 version.

**Comment by mcenderdragon** [comment]
thisa will be fixed in 1.16 and later versions.
