### ISSUE TITLE
Laser cutting stairs gives back too much composite metal

### ISSUE THREAD

**Issue by belathus** [mcenderdragon/Futurepack-API#842]
**Describe the bug**
Crafting metal stairs from composite metal gives you 4 stairs at the cost of 6 composite metal. Putting them in a recycler with a laser cutter gives back 6 or so composite metal each, resulting in a significant net gain.

**To Reproduce**
1. Craft metal stairs from composite metal
2. Put composite metal stairs in a recycler with a laser cutter
3. You should receive more composite metal than it took to craft the stairs

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.2.21
Futurepack Version: 31.3.7000

**Logs**
Available on request.

**Comment by mcenderdragon** [comment]
are you sure you will gain more in the long therm since the items dont have a 100% drop chance but rather a 25% chance if I see correctly.

**Comment by belathus** [comment]
I took 4 stairs (the result of crafting once, using 6 composite metal) and tossed them into the recycler, receiving 21 composite metal.

The second time I got 19. The third time 18. The fourth time 21 again. It consistently gives me more back than it took to craft.
