### ISSUE TITLE
Crash upon crafting with techtable

### ISSUE THREAD

**Issue by 5incerism** [mcenderdragon/Futurepack-API#843]
Crash upon crafting part press (anything i craft with tech table)

Craft a item from future pack in techtable

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.2.20
Futurepack Version: 1.16.5-31.3.7000

Crashlog:
https://pastebin.com/rJrGWmqR

**Comment by mcenderdragon** [comment]
can you also reproduce this crash with jsut futurepack installed ?
