### ISSUE TITLE
Optiassembler recipe assembler screen lets you get more outputs than expected

### ISSUE THREAD

**Issue by belathus** [mcenderdragon/Futurepack-API#844]
**Describe the bug**
At the recipe assembly screen for the Optiassembler, you can grab the resulting item from the output (which is probably fine, you always get the lowest quality of item when you do so), but if you shift-click (and there are no items left in the recipe input), you get two of that item.

**To Reproduce**
1. Click on the recipe assembly on an Optiassembler
2. Add ingredients for exactly one craft of one item.
3. Shift-click the recipe output.
4. you should have one item left in the recipe output, which you can shift-click again back into your inventory.

**Screenshots**
Video: https://youtu.be/w_vhF_vZJ0Y

**Additional context**

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.2.21
Futurepack Version: 31.3.7000

**Logs**
Available if needed.

**Comment by mcenderdragon** [comment]
wait you mean the reicpe creator screen right ?
