### ISSUE TITLE
[1.17.1] Crash opening Calc Module with Scrench

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#847]
**Version**
Operating System: Windows 10 version 10.0
Minecraft Version: 1.17.1
Java Version: 17.0.2, Oracle Corporation
client-1.17.1-20210706.113038-srg
forge-1.17.1-37.1.1-universal
create-mc1.17.1_v0.4
flywheel-forge-1.17-0.3.0
gravestone-1.17.1-1.0.4
Futurepack-1.17.1-32.1.7175
journeymap-1.17.1-5.8.0
jei-1.17.1-8.3.1.62

**To Reproduce**
I was needing Standard Core and Ram so I thought I'd take them out of the Calc Module, but when I tried to open it up the world crashed.

**Additional context**
I considered making the needed items but I also read where opening the Assembly also kills the server..

**Logs**
https://pastebin.com/zPF52D2f

**Comment by Yirok42** [comment]
The first time: it was raining and my researcher was active.
The second time: it was still raining but not connect to the researcher.
The third time: it was not raining and not connected to the researcher and the researcher was not active.

The Assembly Table can be opened but I have not tried to make chips yet. I do hope it works.

**Comment by Yirok42** [comment]
All that was about the Bonus item from doing research.
I also made one with just enough Core for my 8 RAM just in case it was immutable.
It didn't crash but when the jvm locked up, I chose to let it die.
No crash report from this one because I killed it.

**Comment by mcenderdragon** [comment]
is this always happening or only happened once ?

**Comment by Yirok42** [comment]
I know twice. Once with the bonus calc module and once with one I made. I think it may have been twice with the bonus calc module. I can try again, but I want to make sure i've done nothing "important" as when it locked up on trying to open the calc module I made, the last save was before I had made it.

**Comment by Yirok42** [comment]
Resolution confirmed in 1.17.1-32.1.7186
