### ISSUE TITLE
[1.17.1] Vanilla Copper compatible

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#848]
**Describe the bug**
Vanilla Copper is not parts pressable.
Vanilla Copper does not work in FuturePack recipes.

**To Reproduce**
1. Mine Vanilla Raw Copper 
2. Smelt Vanilla Raw Copper 
3. Store it because it is not usable.

**Screenshots**

**Version and Mods**
Operating System: Windows 10 version 10.0
Minecraft Version: 1.17.1
Java Version: 17.0.2, Oracle Corporation
client-1.17.1-20210706.113038-srg
forge-1.17.1-37.1.1-universal
create-mc1.17.1_v0.4 <--------------------  A prior version of this added Copper but Vanilla Copper now adds copper. FP and Create Copper were compatible. -- I also copied the working directory without this (and without flywheel) to see if Create was causing the problem, but not having Create/Flywheel had no affect.
flywheel-forge-1.17-0.3.0
gravestone-1.17.1-1.0.4
Futurepack-1.17.1-32.1.7175
journeymap-1.17.1-5.8.0
jei-1.17.1-8.3.1.62

**Logs**
I hope this is not needed.

**Comment by Yirok42** [comment]
I have advanced to having a Crusher and crushing Vanilla Raw Copper, and it does make Copper Dust, and cooking the dust in the Industrial Furnace does make FuturePack Copper Ingots which are usable. 
Very important to save all FuturePack Copper Ingots found in Dungeons until reaching Crusher tech. :)

**Comment by mcenderdragon** [comment]
it doesnt work because i  1.17 vanilla copper is not registered as a real ingot. I think 1.18 fixes this. YOu can also add a datapack and add copper to the forge:tags/items/ingot/copper tag

**Comment by Yirok42** [comment]
If anyone else has this problem, maybe they will read here that the fix is to crush it and bake it, and then they're fine.
