### ISSUE TITLE
[1.17.1] Gravestone and Tech Dungeon

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#849]
Operating System: Windows 10 version 10.0
Minecraft Version: 1.17.1
Java Version: 17.0.2, Oracle Corporation
client-1.17.1-20210706.113038-srg
forge-1.17.1-37.1.1-universal
create-mc1.17.1_v0.4
flywheel-forge-1.17-0.3.0
gravestone-1.17.1-1.0.4
Futurepack-1.17.1-32.1.7175
journeymap-1.17.1-5.8.0
jei-1.17.1-8.3.1.62

The significant mods are gravestone and futurepack.
Gravestone mod is a useful means of keeping 'your stuff' after death. It leaves it where you died so that a) it isn't lying about using up resources, b) your stuff doesn't fall into lava, c) anyone who comes along can tell that it is your gravestone, -- but it also has a drawback that it places a dirtblock (if it is not over dirt) which means it places a block in the protected area of the tech dungeon. This could be used to bypass the lava pools (but only an unethical player would do that).
However in 1.17 FuturePack the gravestone marker is places but the player cannot break it to get their stuff back.
This is not a bug, but it would be more consistent to either not be able to have the block created, or let the player break it. I do not know why it worked in prior versions (worked = let the player break the block. which should get rid of the magic dirt block too)
The workaround is to disable gravestone.

**Comment by mcenderdragon** [comment]
dont use gravestone use something like corpse instead.

in the past I added special stuff for that if it no longer works they have to reach out.

**Comment by Yirok42** [comment]
Seems fair.
