### ISSUE TITLE
Drop Torches on space Travel

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#85]
"It seems that any torches (I did not check other devices) that are mounted against two of the four walls fall down after traveling through space.",  (bradtroop822)

**Comment by mcenderdragon** [comment]
We need to ad glued Lamp, because spacetravel is just to fast for them :P

**Comment by mcenderdragon** [comment]
Cant confirm that, tested it worked perfectly fine in single player

**Comment by Wugand** [comment]
Testet in singleplayer:
All Thorches with Faceing "west" (on east wall) and Facing "north" (on south wall) everytime drops
