### ISSUE TITLE
[1.17.1] Grapling Slime crash

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#851]
**Describe the bug**
When I shoot the Grapling at any distance, the game freezes and then crashes.
I have done it twice.
First in the Nether with Fancy Graphics
Second in the Overworld with Fast Graphics

**To Reproduce**
1. Have Grapling Slime in your hand.
2. Click to shoot it out.
3. Wait for crash

**Additional context**
This one really hinders my 'steal the blaze spawn tactics' :(

**Version**
client-1.17.1-20210706.113038-srg.jar
forge-1.17.1-37.1.1-universal.jar
flywheel-forge-1.17-0.3.0.jar
create-mc1.17.1_v0.4.jar
gravestone-1.17.1-1.0.4.jar  -i'll remove this one soon. i'm being careful not to die for now.
Futurepack-1.17.1-32.1.7175.jar
journeymap-1.17.1-5.8.0.jar
jei-1.17.1-8.3.1.62.jar

**Logs**
https://pastebin.com/Tb6CWMjj

**Comment by mcenderdragon** [comment]
PLease test https://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.17.1-32.1.7182/Futurepack-1.17.1-32.1.7182.jar

**Comment by Yirok42** [comment]
Resolution confirmed.
