### ISSUE TITLE
[1.17.1] Mining Drone appears one block low

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#852]
**Describe the bug**
It is not real problem but I expect that it appears one block low is not desired.
I assume the Mining Drone I placed on top of the Mining Station appeared inside the Mining Station box but I was still able to task it.

**To Reproduce**
1. Place a Mining Drone 'on' a Mining Station. 
2. I appears one block lower than the station.
3. Task the Mining Drone.
4. The lasers of the drone appear correctly but the Drone appears one block lower the whole time it is mining.

**Screenshots**
![image](https://user-images.githubusercontent.com/65392871/160218479-7e9f7f6e-8980-489b-a1ae-6647a8af3c56.png)

**Additional context**
It works just fine.

**Version**
Operating System: Windows 10 version 10.0
Minecraft Version: 1.17.1
Java Version: 17.0.2, Oracle Corporation
client-1.17.1-20210706.113038-srg
forge-1.17.1-37.1.1-universal
create-mc1.17.1_v0.4
flywheel-forge-1.17-0.3.0
corpse-1.17.1-1.0.7
Futurepack-1.17.1-32.1.7175
journeymap-1.17.1-5.8.0
jei-1.17.1-8.3.1.62

**Comment by mcenderdragon** [comment]
PLease test https://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.17.1-32.1.7182/Futurepack-1.17.1-32.1.7182.jar

**Comment by Yirok42** [comment]
Resolution confirmed.
