### ISSUE TITLE
[1.17.1] Assembly Table has support leak

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#853]
**Describe the bug**
An unused Assembly Table looses support while it is not being watched.
I have not tried to keep the display open to see if it disappears while watching it.

**To Reproduce**
1. Use Simple Red stone Flash drive to transfer Support to the device.
2. See that the support was loaded.
3. Walk away and do some other mine-craft activities.
4. Come back and open the device and see that the support is gone.

**Screenshots**
![image](https://user-images.githubusercontent.com/65392871/160218573-8ffd6d7d-5901-4a39-9f87-34a1ff3c9f9a.png)

**Additional context**
I don't mind, once it is connected by Support pipe it will be interesting how often the support vanishes.

**Version**
Operating System: Windows 10 version 10.0
Minecraft Version: 1.17.1
Java Version: 17.0.2, Oracle Corporation
client-1.17.1-20210706.113038-srg
forge-1.17.1-37.1.1-universal
create-mc1.17.1_v0.4
flywheel-forge-1.17-0.3.0
corpse-1.17.1-1.0.7
Futurepack-1.17.1-32.1.7175
journeymap-1.17.1-5.8.0
jei-1.17.1-8.3.1.62

**Comment by mcenderdragon** [comment]
almost every machine is affected by this.

**Comment by mcenderdragon** [comment]
PLease test https://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.17.1-32.1.7186/Futurepack-1.17.1-32.1.7186.jar

**Comment by Yirok42** [comment]
Not resolved in 7186.
I do not recall the exact number but I put about 20 support in the table, then went to Menelaus twice; spending quite a bit of time on the second voyage (since it did not crash, I took tools).
When I returned, I started sorting my resources and then remembered to check this.

All support has vanished.

**Comment by Yirok42** [comment]
Resolved in 1.17.1-32.1.7186
