### ISSUE TITLE
[1.17.1] Crash loading Menelaus

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#854]
**Describe the bug**
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "com.mojang.blaze3d.vertex.VertexBuffer.m_166867_(com.mojang.math.Matrix4f, com.mojang.math.Matrix4f, net.minecraft.client.renderer.ShaderInstance)" because "this.skyVBO" is null
Exit Code: -1

**To Reproduce**
1. Make a ship
2. Use Menelaus coordinates
3. Click to travel
4. When the new dimension starts to load the game hangs and then crashes

**Version**
Operating System: Windows 10 version 10.0
Minecraft Version: 1.17.1
Java Version: 17.0.2, Oracle Corporation
client-1.17.1-20210706.113038-srg
forge-1.17.1-37.1.1-universal
create-mc1.17.1_v0.4
flywheel-forge-1.17-0.3.0
corpse-1.17.1-1.0.7
Futurepack-1.17.1-32.1.7175
journeymap-1.17.1-5.8.0
jei-1.17.1-8.3.1.62

**Logs**
https://pastebin.com/F6TDvuTA

**Comment by Yirok42** [comment]
Apparently I did make it to Menelaus because restarting the world after the crash only leads to another crash. Restarting from a prior backup in order to access world.

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "com.mojang.blaze3d.vertex.VertexBuffer.m_166867_(com.mojang.math.Matrix4f, com.mojang.math.Matrix4f, net.minecraft.client.renderer.ShaderInstance)" because "this.skyVBO" is null
Exit Code: -1

**Comment by Yirok42** [comment]
I opened a back up save where I was not on Menelaus, went to "cheats on" and created a way point on Menelaus using JourneyMap. When I teleported to there, without the ship, the game still crashes.

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "com.mojang.blaze3d.vertex.VertexBuffer.m_166867_(com.mojang.math.Matrix4f, com.mojang.math.Matrix4f, net.minecraft.client.renderer.ShaderInstance)" because "this.skyVBO" is null
Exit Code: -1

**Comment by mcenderdragon** [comment]
PLease test https://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.17.1-32.1.7182/Futurepack-1.17.1-32.1.7182.jar

**Comment by Yirok42** [comment]
I used the backup from when I went to Menelaus with this update and I was able to reach the dimension.
