### ISSUE TITLE
[1.17.1][vanilla bug] Crash loading Tyros

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#855]
**Describe the bug**
When attempting to "fly" to Tyros, the VM crashed with: Index 0 out of bounds for length 0

**To Reproduce**
1. Build an Advanced Board Computer controlled ship
2. Put the Tyros coordinates in the box
3. Select mystery planet, and click the 'go' button

**Screenshots**
N/A

**Additional context**
It is a different message from the crashes going to Menelaus

**Version**
Operating System: Windows 10 version 10.0
Minecraft Version: 1.17.1
Java Version: 17.0.2, Oracle Corporation
client-1.17.1-20210706.113038-srg
forge-1.17.1-37.1.1-universal
create-mc1.17.1_v0.4
flywheel-forge-1.17-0.3.0
corpse-1.17.1-1.0.7
Futurepack
        -1.17.1-32.1.7175 (mark_00) - world created with this version
        -1.17.1-32.1.7182 (mark_01) - this was just a few hours
        -1.17.1-32.1.7186 (mark_02) - currently used version
journeymap-1.17.1-5.8.0
jei-1.17.1-8.3.1.62

**Logs**
https://pastebin.com/hBKuMxdj

**Comment by mcenderdragon** [comment]
can you try it again? the cacao tree generator from vanilla is crashing and I have noticed that when you jsut ignore it and attempt to load the world again it usually works.

**Comment by Yirok42** [comment]
The game crashed whilst feature placement
Error: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
Exit Code: -1

After the crash I am back in my base under the ship and all I can tell is that I am missing an ION Collector that was in my inventory, and I have not 'travelled' yet. Last time it crashed it was a Solar panel which I had placed on the ship. I do not know if anything else is missing.

The game crashed whilst feature placement
Error: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
Exit Code: -1

The game crashed whilst feature placement
Error: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
Exit Code: -1073741510

**Comment by Yirok42** [comment]
I closed and reopened before doing this double crash test, so I now have my setup back and I can retry whatever you suggest from before these last two crashes.

**Comment by Yirok42** [comment]
Confirmed still an issue with 32.1.7190

**Comment by Yirok42** [comment]
> 

Are you suggesting that if I move my ship so that I do not arrive near Cacao that it will work?

**Comment by Yirok42** [comment]
I have been trying to teleport to various locations using JourneyMap.
The teleport takes me to the new dimension. I can see the planet in the sky (or through the moon since the land never loads), and then it crashes.

https://pastebin.com/tuNBLCDm

**Comment by mcenderdragon** [comment]
this weird error is fianlly fixed in 1.18
