### ISSUE TITLE
[1.17.1] Hologram pipe/cable lose state when returning to dimension

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#856]
**Describe the bug**
It seems when I reload the world, the blocks of cable I have hologrammed as 'color_glass_black' go back to just cable. I keep rehologramming them as color_glass_black where I can see the cable through it each time I visit this area.
Also I have some cable in my wall of machines which I hologram as deepslate_bricks, this also keeps reverting back to just cable. On this same wall of machines I have a normal pipe hologrammed as deepslate_bricks which keeps its hologram. At first it was only to be happening to cable, but through experimentation it is now also happening to my pipe, which used to have an item frame in front of it. Now with or without the item frame it still comes back as an empty block. I can click on the cable that was hologrammed in order to restore both blocks to being hologrammed, otherwise I cannot access the pipe block.

**To Reproduce**
1. Use the hologram to make pipe/cable into a solid block.
2. Leave and reenter the game, or leave and reenter the dimension
3. If the cable was visible while holding the controller, it is not just a cable. If it was not visible, the space is empty. For the pipe it is never visible through the solid block for me, but I think it was supposed to be visible, because it is either back to just a pipe or the space is empty.

**Screenshots**
I broke and re added the pipe and cable in order to get what the before looked like
![image](https://user-images.githubusercontent.com/65392871/160952569-1e45ff9e-f722-4b1a-b99b-8299898e5c8a.png)

This shows the wall after using the hologram. I circled the pipe and cable.
![image](https://user-images.githubusercontent.com/65392871/160951896-27377a9e-c447-4c38-b649-221f89016e05.png)

This is an older image where the pipe hologram works but the cable did not.
![image](https://user-images.githubusercontent.com/65392871/160951784-0eb7f346-d769-48a6-934d-61178a72f422.png)

This view is after I started getting the pipe hologram to fail also.
![image](https://user-images.githubusercontent.com/65392871/160952013-0b60fa00-5406-44fa-a404-9c9ea6cfa8c7.png)

This is what I believe it is supposed to look like when I am holding the hologram controller.
![image](https://user-images.githubusercontent.com/65392871/160952160-04cc309d-60a9-419b-86b1-9c02e0536c55.png)

**Additional context**

**Version**
Operating System: Windows 10 version 10.0
Minecraft Version: 1.17.1
Java Version: 17.0.2, Oracle Corporation
client-1.17.1-20210706.113038-srg
forge-1.17.1-37.1.1-universal
create-mc1.17.1_v0.4
flywheel-forge-1.17-0.3.0
corpse-1.17.1-1.0.7
Futurepack-1.17.1-32.1.7186
journeymap-1.17.1-5.8.0
jei-1.17.1-8.3.1.62

**Comment by Yirok42** [comment]
Perhaps it is related and so I will not write a separate issue.

This is an image of my lava tanks. They are near full.
![image](https://user-images.githubusercontent.com/65392871/160953140-a46eeec7-eafe-4f8c-9c98-fe0802971185.png)

and if I use them just a little.
![image](https://user-images.githubusercontent.com/65392871/160953274-9a46be3c-4244-4033-a1b4-2daf7e17a302.png)
![image](https://user-images.githubusercontent.com/65392871/160953293-1690e75b-5944-4b62-a1f6-f6a47d55c194.png)
![image](https://user-images.githubusercontent.com/65392871/160953313-c01f8a78-e129-45e9-ad50-7c6869b21bdf.png)
The lower left was not affected when the lower right lost "some lava" and then the upper two lost "some lava" and so it stayed looking empty.

If I travel to another dimension and return it goes back to looking empty.

I report it so as to help make a better product, but only the cables in the floor which I fall into and then get semi-stuck are annoying.

**Comment by mcenderdragon** [comment]
oof its a sync issue where the data is not synced on startup

**Comment by mcenderdragon** [comment]
SHold be fixed https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3732841

**Comment by Yirok42** [comment]
Confirm resolved in 32.1.7190
