### ISSUE TITLE
[1.17.1] Network Transmitter (laser_transmitter) workings

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#858]
Operating System: Windows 10 version 10.0
Minecraft Version: 1.17.1
Java Version: 17.0.2, Oracle Corporation
client-1.17.1-20210706.113038-srg
forge-1.17.1-37.1.1-universal
create-mc1.17.1_v0.4
flywheel-forge-1.17-0.3.0
corpse-1.17.1-1.0.7
Futurepack-1.17.1-32.1.7186
journeymap-1.17.1-5.8.0
jei-1.17.1-8.3.1.62

I have a Water Turbine/Calculation Module room connected to Research room via Network Cable. I have wanted to use the Laser Transmitters because they exist.
I have tried what I thought were the simplest setups to test them and nothing has ever worked. I gave up on them many versions ago and I asking now because I cannot reach Tyros.

I tried "both facing up"
![image](https://user-images.githubusercontent.com/65392871/161351639-d702740b-e2c7-4045-a4e4-90efb1e8a138.png)

I tried "both facing each other"
![image](https://user-images.githubusercontent.com/65392871/161351669-298c1f3c-53f2-4de6-a7ac-b903dac51359.png)

I tried them facing away but since the cable did not connect to the Transmitter, I did not take a photo.
I also tried them on top of each other separated by a distance of about 60 but that did not work either and I could not get a good photo.

For none of these did the Researcher indicate the 3 Calculation Modules were 'in use'. When the network is all cable, the Researcher indicates 3 Calculation Modules are in use.

I do not know if there is a bug here or if I just do not understand these lines in the E-Scanner
* transmitter and receiver have to be exactly on one line
* - line of sight (x & y or z & y being the same) ?
* - straight line with nothing between them?

**Comment by mcenderdragon** [comment]
it should work like in the 2d picture but it is not working. I am working on a fix.

**Comment by mcenderdragon** [comment]
YOu can now use the Escanner to check what stuff is connected to your network: 
![escanner with network blocks]( https://cdn.discordapp.com/attachments/712612283531919360/962671429931925544/unknown.png )

**Comment by mcenderdragon** [comment]
Please try [futurepack-1.18.2-33.0.7260.jar](https://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.18.2-33.0.7260/futurepack-1.18.2-33.0.7260.jar)

**Comment by Yirok42** [comment]
After I "learn" about this technology, I will retest. ;)

**Comment by Yirok42** [comment]
I have confirmed this works with 33.0.7260.
I did a further test with the two nodes separated vertically by placing ladders between them so as to traverse the span. Sadly iron ladders which do not appear to block the signal, do in fact, block the signal. I did not try wooden ladders of any kind. I am still happy to have it as it is.

**Comment by Yirok42** [comment]
I meant to say. I did expect the e-scanner to show what is connected to the entire network including both ends of the network transmitter, but as your image depicts, only each side is shown.
I will try at a later time having 4 transmitters in the path so that I can span horizontal as well as vertical distances.
