### ISSUE TITLE
[1.17.1] Dungeon Keys stopped working

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#859]
**Describe the bug**
The Dungeon Key and Security walls no longer work. 

**To Reproduce**
1. Hold the Level 1 and Level 2 Keys in your inventory ( I also tried 'in the hot bar' and 'in my hand')
2. Try to pass through the force wall.
3. Not be able to pass through.
4. Leave before the 60 seconds expires.

**Screenshots**
![image](https://user-images.githubusercontent.com/65392871/161406378-57773367-3f96-46a4-81c5-df079a0a6024.png)
![image](https://user-images.githubusercontent.com/65392871/161406385-fd7dd06c-5282-44b6-9410-cdd0f8ede70b.png)

**Additional context**
Sometimes the lasers are invisible but touching them makes them visible.
Also the Airlock doors are invisible when closed.

Futurepack-1.17.1-32.1.7175 - world created with this version. I am certain the Keys worked at this point.
Futurepack-1.17.1-32.1.7182 - this version was used for a few hours before reading that 7186 was available

**Version**
Operating System: Windows 10 version 10.0
Minecraft Version: 1.17.1
Java Version: 17.0.2, Oracle Corporation
client-1.17.1-20210706.113038-srg
forge-1.17.1-37.1.1-universal
create-mc1.17.1_v0.4
flywheel-forge-1.17-0.3.0
corpse-1.17.1-1.0.7
Futurepack-1.17.1-32.1.7186
journeymap-1.17.1-5.8.0
jei-1.17.1-8.3.1.62

**Comment by mcenderdragon** [comment]
this was caused by #856

**Comment by mcenderdragon** [comment]
SHold be fixed https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3732841

**Comment by Yirok42** [comment]
Confirm resolved by 32.1.7190
