### ISSUE TITLE
[1.18] Some ore related issues

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#861]
- [x] futurepack:ore_copper still spawns in the overworld.
- [x] None of the futurepack ores seem to spawn much below Y=0
- [x] Deepslate Bauxite ore doesn't work in the researcher when researching Aluminum.
- [x] Scanning Deepslate Redstone Ore doesn't give "Power Connection"
- [x] Scanning Deeplate Coal Ore doesn't give "Morphology"

**Version**
Minecraft Version: 1.18
Forge Version: 40.0.36
Futurepack Version: 33.0.7227

**Comment by mcenderdragon** [comment]
the copper ore spawning is intentional (for now atleast) everything else is a bug.

**Comment by Darkfiend009** [comment]
To add to this in a smaller capacity, Deepslate Bauxite Ore doesn't display it's name properly when looking at it in the world.
![image](https://user-images.githubusercontent.com/42146629/162348482-d054d3ed-fb95-450d-a03d-028f8f6b939e.png)

**Comment by Darkfiend009** [comment]
Upon further testing, it appears that all the deepslate ore variants display as the one shown above

**Comment by mcenderdragon** [comment]
- lang entries are fixed.
- ore will now spawn from world bottom to 64 (not 0 to 64 like beofre)
- added deepslate varaint to scanning manager
- added deepslate ore to to tiem ore tags (only did block tags before )

**Comment by mcenderdragon** [comment]
Please try [futurepack-1.18.2-33.0.7260.jar](https://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.18.2-33.0.7260/futurepack-1.18.2-33.0.7260.jar)

**Comment by qrss** [comment]
I tested this and it seems to be fixed. Thanks!
