### ISSUE TITLE
[1.18] Zooming out in the tech tree misaligns the "This research unlocks" icons

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#863]
If you zoom in or out while on a page in the tech tree (using the mouse scroll wheel), the "This research unlocks" icons get misaligned.

![icon_misalignment](https://user-images.githubusercontent.com/32312262/162090066-6a9c9c59-1ac1-4096-a666-650352a8d1c2.png)

Minecraft Version: 1.18
Forge Version: 40.0.41
Futurepack Version: 33.0.7227

**Comment by mcenderdragon** [comment]
yeah this one is hard to fix since miencraft isnsuper inconsistent with their use of their own matrixStack implementation. they even named it PoseStack which is even more wrong...
