### ISSUE TITLE
Empty Tag In Recipes (1.18.2)

### ISSUE THREAD

**Issue by Darkfiend009** [mcenderdragon/Futurepack-API#866]
Some crafting recipes are showing with an empty tag for a crafting component. It appears it may be a forge tag issue related to the block(s) needed for the recipe. The example provided is for the Researcher. It cycles through Zinc, Iron, and Tin blocks (all with the empty tag logo). It also shows White Colored Metal as an option and it shows normally.

**To Reproduce**
1. Open JEI
2. Pull up recipe for "Researcher"
3. See empty tag symbol for crafting component

**Screenshots**
Researcher recipe with "Empty Tag" crafting component:
![image](https://user-images.githubusercontent.com/42146629/163421847-2e53ac9e-4af8-43fc-ab12-8cf530ae9589.png)

Researcher recipe with "White Colored Metal" showing properly:
![image](https://user-images.githubusercontent.com/42146629/163422488-22abd588-a160-445e-bd5e-d8e528a756d8.png)

**Additional context**
This started after the newest update of Futurepack (1.18.2-33.0.7260)

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.0.45
Futurepack Version: 1.18.2-33.0.7260

**Comment by mcenderdragon** [comment]
please provide the server logs, something is calling the tags too early.

**Comment by Darkfiend009** [comment]
Here is the log for the server startup:

https://pastebin.com/44atCZaE

**Comment by mcenderdragon** [comment]
Does this happen on every server restart adn does this also ahppen with only futurepack installed ?

**Comment by Darkfiend009** [comment]
Yes and yes. I added JEI when i tested it alone to see the recipe.

**Comment by mcenderdragon** [comment]
actually the tag names are wrong. its not blocks but rather storage_blocks
