### ISSUE TITLE
1.18.2 Version Crashed No report

### ISSUE THREAD

**Issue by Daihok41** [mcenderdragon/Futurepack-API#867]
In version 1.18.2 -33.0.7260 When trying to use the laser bow game crashed. Was no crash report just crashed to desktop.

Try to use the Laser bow in said version

**Screenshots**

**Additional context**

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.0.52
Futurepack Version: 1.18.2 -33.0.7260

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
    https://pastebin.com/ 512KB
    https://hastebin.com/ 400KB
    https://gist.github.com/ 100MB Requires member (Free)

**Comment by mcenderdragon** [comment]
its rendering related, go to your minecraft folder/logs and add the logs. Without that itas hard to do special casing.
