### ISSUE TITLE
Game crash when i click on the rare earth metal research icon 

### ISSUE THREAD

**Issue by Najox** [mcenderdragon/Futurepack-API#868]
When i click on the "rare earth metal" research icon the game save the world and then crash.

**To Reproduce**
1. Open the e-scanner
2. Go to the production section 
3. Click on "rare earth metal"
4. Game crash 

**Screenshots**
![image_2022-04-18_155217811](https://user-images.githubusercontent.com/49323394/163818047-b49d8aac-0fe2-43cb-9fee-c0bd0ddbec00.png)

**Additional context**
It happened everytime i clicked on it (3 time in total) the bug seems to be consistant. 

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.0.54
Futurepack Version: 1.18.2-33.0.7260

**Logs**
Crash 1 : https://pastebin.com/UfXujCpu
Crash 2 : https://pastebin.com/C8b2KJDp

**Comment by Najox** [comment]
I forgot to add that multiple J.E mods were installed 

- J.E.I
- J.E.P
- J.E.R

**Comment by Najox** [comment]
Did a bit more testing and the bug seems to happend on every "centrifuge" subresearch

**Comment by mcenderdragon** [comment]
please also post the logs, this crash was cuased by another crash.

**Comment by Najox** [comment]
https://pastebin.com/CG47sSsa

**Comment by mcenderdragon** [comment]
> https://pastebin.com/CG47sSsa

thats another crash report I need logs. they are in the logs folder

**Comment by Najox** [comment]
oh my bad here are the logs :

FP Log : https://pastebin.com/xanbCuRp
Log : https://pastebin.com/0GZvN7sD
