### ISSUE TITLE
Something strange on the server...

### ISSUE THREAD

**Issue by mrAppleXZ** [mcenderdragon/Futurepack-API#87]
Yesterday, I researched the Part Press and successfully crafted it. Today, something strange happens.
Video: https://www.youtube.com/watch?v=m_HkX7BxDkk
The logs has not info about this.
Forge version: 12.18.2.2151
Futurepack version: 24.2.17
__
Sorry for my bad English.

**Comment by mcenderdragon** [comment]
parts of this were already postet, the bug with the crafting is because the no crafting conflicts mod.

But the part presss research is there at the wrong place.
@wugand any ideas?

**Comment by mcenderdragon** [comment]
it should be fixed: https://github.com/mcenderdragon/Futurepack-API/issues/24

**Comment by mrAppleXZ** [comment]
But... It works fine yesterday. I don't update any mods at this time.

**Comment by mcenderdragon** [comment]
did you restart the server?

**Comment by mrAppleXZ** [comment]
@mcenderdragon Yes.

**Comment by mcenderdragon** [comment]
this is strange but have you tried without noCraftingConflicts ?

**Comment by mrAppleXZ** [comment]
@mcenderdragon No. I try it tomorrow. I think, this is not NoMoreRecipeConflicts issue. I tried to open Part Press's GUI and got a chat message that I don't know how to use this object.

**Comment by mrAppleXZ** [comment]
I removed NoMoreRecipeConflicts and still have this issue.

**Comment by mcenderdragon** [comment]
If you cant open it then you have not researcht it. Have you the partpress research in the E-Scanner?

**Comment by mrAppleXZ** [comment]
@mcenderdragon Yes. You can see this in the video.

**Comment by mcenderdragon** [comment]
Yeah but in the videos you cant craft the partpress because of nocraftingconflicts, if you cant open the partpress you have not the research, your UUID changed, or the server lost the research data.

**Comment by mrAppleXZ** [comment]
@mcenderdragon but... I have the research in the E-Scanner.

**Comment by mrAppleXZ** [comment]
Any ideas?

**Comment by mcenderdragon** [comment]
THe latest version available at curse (24.2.45) does this also happen or is it fixed ?

**Comment by mrAppleXZ** [comment]
@mcenderdragon Still happens :(.

**Comment by mcenderdragon** [comment]
This is strange, if you have the research in the E-Scanner, you should be able to craft it and to open it.

**Comment by mrAppleXZ** [comment]
@mcenderdragon also, I tried to /fp research nickname reset and /fp research nickname unlock basics. Still not working.

**Comment by mcenderdragon** [comment]
Can you to craft and open the Partpress a few times and then give us the server and the client log ? (fml-client-latest.log and fml-server-latest.log)

**Comment by mrAppleXZ** [comment]
@mcenderdragon 
fml-client-latest.log: https://gist.github.com/mrAppleXZ/4921b771f2add0ffc400030ccd7f57ee
latest.log (from client): https://gist.github.com/mrAppleXZ/cc55dcdf3b8b71cdecbecb3ff9e659ee
FP-latest.log (from client): https://gist.github.com/mrAppleXZ/8ba31f6c607f5dbc368073593e000b17
fml-server-latest.log: https://gist.github.com/mrAppleXZ/4d99d56f31f19c45d4921cedc353f76c
latest.log (from server): https://gist.github.com/mrAppleXZ/895d4ef458fce250b2822c8053c1b200
FP-latest.log (from server): https://gist.github.com/mrAppleXZ/89f16b402c33173bcd2427409c5db084

**Comment by mcenderdragon** [comment]
Try out the [24.2.51](http://redsnake-games.de/Downloads/fp/fp.php?version=24.2.51)

**Comment by mrAppleXZ** [comment]
@mcenderdragon It works perfectly now! Thank you!
