### ISSUE TITLE
Interplanetary travel dosen't work (game version 1.18.2, mod version 33.0.7268, forge version 40.1.0)

### ISSUE THREAD

**Issue by NoNameToSeeHere** [mcenderdragon/Futurepack-API#871]
When I go in any ship that I've made, on the computer it shows that everything is checked off, I can move the ship around the overworld just fine, but when I put in coordinates for menelaus, I try to go there, and it just doesn't work.

1. Build a ship
2. Put coordinates in the computer
3. Select the bottom one of the three buttons
4. Click the check
5. it dosen't work

Minecraft Version: 1.18.2
Forge Version: 40.1.0
Futurepack Version: 33.0.7268

Logs:
[https://pastebin.com/CPDHRx9D](url)

**Comment by NoNameToSeeHere** [comment]
Oh, the link dosent work, just copy and paste this: https://pastebin.com/CPDHRx9D

**Comment by NoNameToSeeHere** [comment]
Oh nevermind it automatically made it a working link

**Comment by Yirok42** [comment]
They need custom biomes and worldgen and that broke completely.

**Comment by mcenderdragon** [comment]
the 1.18.2 doesnt has the planets Menelaus, Tyros & Envia implemented yet, that's why it does nothing.

**Comment by Yirok42** [comment]
Menelaus now works in 1.18.2 (Futurepack-1.18.2-33.0.7403) but not Tyros. Thank you for getting Menelaus!

**Comment by mcenderdragon** [comment]
Tyros is also back in so closing this now.
