### ISSUE TITLE
Changing Recipes

### ISSUE THREAD

**Issue by belathus** [mcenderdragon/Futurepack-API#88]
Are we able to change the recipes of FuturePack things? I wasn't able to see anything useful looking around.

Mostly, what I want to do right now is remove the ability to turn alutine crystals into aluminum; I'd rather aluminum not be so easily renewable, but I'd also like to have the ability to edit the recipes of some of the machines making them a bit harder to craft or making them out of different or more materials.

**Comment by mcenderdragon** [comment]
our aluminu should be different than that from other mods also, all recipes are as json files inside the mod jar

**Comment by belathus** [comment]
To your first point, I suppose I can remove your aluminum from the ore dictionary; seems Immersive Engineering, at least, latches onto "gemAluminum" and allows you to grind it into aluminum dust.

To the second, any chance you could make a sort of override folder that allows me to customize the recipes outside of editing the jar? If I have to, I will, but that is a bit more involved than distributing configs.

Inegrated Dynamics does this: https://github.com/CyclopsMC/IntegratedDynamics/wiki/Recipe-XML

EnderIO does similar, too, and mixes both JSONs and XML.

**Comment by mcenderdragon** [comment]
we dont have hash checks of the recipes so just edit the files in the jar.

**Comment by Wugand** [comment]
The system used by EnderIO, would be take so much time to implement, and port all of our recipes to it. Specially in multiplayer there are some possible problems. We currently don't have enough devolopers to spend so much time in it. Sorry.

For the Aluminium, we add an config entry for siple disableing.

**Comment by belathus** [comment]
Then, do I have permission to redistribute modified JAR files?

**Comment by Wugand** [comment]
Ok. we can't answer with a simple yes or no.

So here some cases:
- share a modifyed jar with your friends or a small group of players is ok
- publish a modpack containing a modifyed version is also ok, if you refer to our modpage and inform the useres that/what you changed
- writing a addon (your own mod that requires the orginal Futurepack to be installed) is also absolutly ok
   Note: this gives you the most options for changes, or you can export everything to config files by yourself ... of course this need some progrmming/modding skills
- publishing single files and a patch tutorial would be also ok

! that we not allow is the public and standalone redistribution of the whole mod.
  
How sayed our only problem is staff and time, for the feature you like to have .... so if you know somebody (or yourself), which have some modding experience. We can also try to work thogether and build in the external editable crafting recipes.

**Comment by belathus** [comment]
This is an understandable response. Just to be clear, it will be for a modpack that I plan on releasing on the AT Launcher either later this year or early next year.

As far as modding experience and helping with the mod, my experience specifically with modding and Minecraft is admittedly limited, but I do have a lot of experience with programming languages and code. I also know a decent amount of individuals who'd be willing to help. If I can, I'd love to see if I can assist with this.

**Comment by Wugand** [comment]
Yes, refer to our curse-page and a modified version in you modpack is no problem.
Also it would be nice, if you give us an link to the modpack after release.

Assistance would be nice, we discuss this in your team and talk to you again later. Thanks for the offer.

**Comment by Wugand** [comment]
@belathus Hi again,
we discussed how we can you integrate to the project. At first we like to give you pull rights to the real repository. (You will be able to experiment with our mod source).
For this please create an account at : https://gitlab.com/
And tell us your choosen Username

**Comment by belathus** [comment]
Alright, I created an account over there with the same username as I have here (belathus).

**Comment by mcenderdragon** [comment]
Ok I added you to the project

**Comment by mcenderdragon** [comment]
belathus, have you any questions or is there any way of PM you? because a conversion via github issues is... well it dont feels so good

**Comment by belathus** [comment]
I am on Discord and EsperNet, if you guys use either of those (same username).

**Comment by mcenderdragon** [comment]
I am on esper

**Comment by mcenderdragon** [comment]
lol, whois say you are iddle for over 900h

**Comment by belathus** [comment]
Yeah, I haven't been super active on it for a while. When I look for you, I keep finding that I missed you.

What I like about Discord is that I can leave you a message when you're offline. Alas, lets keep trying.

**Comment by mcenderdragon** [comment]
Yeah, we keep missing us, maybe because of the time shift
