### ISSUE TITLE
Tyros survey scan

### ISSUE THREAD

**Issue by Vitraalt** [mcenderdragon/Futurepack-API#880]
I cant complete tyros survey scan without entities(which entities are spawns on Tyros) and without research called something about topinambur (idk what is this)
https://i.imgur.com/ohlH30w.png

**Comment by Vitraalt** [comment]
Oh i found jerusalem artichoke? and cave spiders

**Comment by Yirok42** [comment]
This is closed but what version of FuturePack do you have?

**Comment by Vitraalt** [comment]
> This is closed but what version of FuturePack do you have?

Minecraft 1.16.5, FuturePack 31.3.7005
