### ISSUE TITLE
[Crash 1.18.2] Pressing keybinds crashed client

### ISSUE THREAD

**Issue by itsdinkd** [mcenderdragon/Futurepack-API#882]
**Describe the bug**
I had a building gadget; exchanging gadget out and was trying to increase range by pressing keybinds. i hit the wrong keybind (not sure which) and I crashed.

**To Reproduce**
1. Have Exchanging Gadget out from Building Gadgets
2. Press random keys (Q through V while holding ctrl or shift)
3. crash

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.1.19
Futurepack Version:  33.0.7268

**Logs**
https://pastebin.com/YuCx8aT3

**Comment by mcenderdragon** [comment]
a modular door crashed, did you tried to place mdoular doors with buildign gadgets ?

**Comment by itsdinkd** [comment]
Not place, no. I was trying to change the range pressing key binds. i never actually tried placing though.
