### ISSUE TITLE
[1.18.2/33.0.7268]Crash when clicking on Miscellaneous in Escanner

### ISSUE THREAD

**Issue by Zarkazm** [mcenderdragon/Futurepack-API#883]
**Describe the bug**
Something caused the game to crash when I clicked on the Miscellaneous in the Escanner

**To Reproduce**

1.  Open the scanner UI
2.  Click on 'Miscellaneous'
3.  Game crashed

**Screenshots**
N/A

**Additional context**
May or may not be related, but Iron Sticks do not seem to have a recipe in JEI at all.  I only mention since the entry for Iron Sticks is under Miscellaneous.

**Version**
Minecraft Version:  1.18.2
Forge Version:  40.1.20
Futurepack Version:  33.0.7268
Modpack:  FTB Present's Direwolf20 1.18 v1.2.0
^(I manually added Futurepack).

**Logs**
Crash Report + FP-Latest Log:
https://gist.github.com/Zarkazm/a1558fe80cf008ade3d21c1052e9e993

**Comment by mcenderdragon** [comment]
something removed the craftin recipe for the iron stick and thus its crashing. this is weird - is nodeJS / Crafttweaker also installed ?

**Comment by Zarkazm** [comment]
Going to hazard a guess that this is the issue:

![image](https://user-images.githubusercontent.com/10002661/170305539-e07f3be3-2d7a-4096-91dc-201a01f5b11f.png)

**Comment by Zarkazm** [comment]
Did some testing, and looks like this Unify script is part of the problem.  Not just the Unify part, but there is also a replace section:

![image](https://user-images.githubusercontent.com/10002661/170434048-56650efb-5bc5-45a9-9d83-3596ecdf6444.png)

I commented out this bit and tested again.  This restored the previous recipe and resolved the E-Scanner crash:

![image](https://user-images.githubusercontent.com/10002661/170434164-097f97f2-0eb0-4022-a625-9e90d93890f4.png)

**Comment by mcenderdragon** [comment]
if you can get the recipe ID of the mew reicpe and change the research text in lang/en_us/misc.json to use the new recipe then it should work. or you disable the script. is the other iron stick compatible as in can you use it in futurepak crafting ?

**Comment by Zarkazm** [comment]
I adjusted the Unify script a bit to re-enable the original Futurepack Iron Stick recipe.  Looks like the Iron Sticks and FTB's Iron Rods are interchangeable in all crafting and machine recipes.  But, the Researcher table requires Futurepack Iron Sticks specifically for some Blueprints and won't accept other iron rods.

**Comment by Zarkazm** [comment]
Just wanted to give an update.  I tried your suggestion of using the Recipe ID.  Appears to have worked like a charm:

![image](https://user-images.githubusercontent.com/10002661/170891584-e5476e50-c390-4ee1-9eb0-8849acec7766.png)

![image](https://user-images.githubusercontent.com/10002661/170891595-2fd214b3-50c1-4f0c-867d-e536317849d3.png)

![image](https://user-images.githubusercontent.com/10002661/170891600-0d538529-bb42-485a-a886-6a2d93c44955.png)

**Comment by Zarkazm** [comment]
@mcenderdragon did you want me to open a ticket for KubeJS compatibility for when the recipe is removed?

**Comment by mcenderdragon** [comment]
not realy no, the modpack author should be doing compatiblity work like this. and as datapacks/resourcepacks is all tghat is needed to fix this I see no bug.
