### ISSUE TITLE
Monocarts are not rendering.

### ISSUE THREAD

**Issue by Tobanyi** [mcenderdragon/Futurepack-API#884]
**Describe the bug**
Monocarts are not rendering.

**To Reproduce**
1. Create a monocart rail.
2. Place a monocart on the rail.
3. Observe.

**Screenshots**
https://imgur.com/a/Q65OFRN

**Additional context**
Fresh install - only futurepack and JEI.

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.1.25
Futurepack Version:  Futurepack-1.18.2-33.0.7268

**Logs**
N/A

**Comment by mcenderdragon** [comment]
can you check if they render into thw ground ? (checks best with glass blocks )

**Comment by Tobanyi** [comment]
Ah, yeah.  Like the Forestmaster, the entity is in the correct spot (in this case, I can interact with the cart on the monorail), however it is rendering the visual below the ground.

**Comment by mcenderdragon** [comment]
also a screenshot with F3+B enabled would be nice

**Comment by Tobanyi** [comment]
![image](https://user-images.githubusercontent.com/43660690/172031559-c64d2790-e4bb-4cfb-ac0c-d4a721565084.png)
