### ISSUE TITLE
Sapling holders break when a tree grows

### ISSUE THREAD

**Issue by Tobanyi** [mcenderdragon/Futurepack-API#887]
**Describe the bug**
When a sapling grows on top of a sapling holder, the holder will break (pop off) and be replaced by a dirt block.

**To Reproduce**
1. Place a grass sapling holder
2. place a sapling on it
3. grow the tree with bonemeal

**Screenshots**
https://imgur.com/a/QTtsbYL

**Additional context**

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.1.25
Futurepack Version: Futurepack-1.18.2-33.0.7268

**Logs**
https://pastebin.com/kcBuk5hq

**Comment by mcenderdragon** [comment]
I hate the new trees of mojang. seems like they repalce whatever they are standing on with dirt...
