### ISSUE TITLE
[1.18.2/33.0.7268]Disc Decryption Mincra Missing

### ISSUE THREAD

**Issue by Zarkazm** [mcenderdragon/Futurepack-API#888]
**Describe the bug**
"story.nav.mincra not found, report this to the mod author."

**To Reproduce**
1. Find Mincra disc in dungeon.
2. Scan Mincra disc in Scanner.
3. Research Mincra disc blueprint in Researcher.
4. Click on Mincra disc entry in E-Scanner.

**Screenshots**
![image](https://user-images.githubusercontent.com/10002661/170809019-45667001-d040-4327-9bff-963837212be1.png)

**Additional context**
N/A

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.1.20
Futurepack Version: 33.0.7268
Modpack: FTB Present's Direwolf20 1.18 v1.2.0
^(I manually added Futurepack).

**Logs**
FP-Latest.log - https://gist.github.com/Zarkazm/259acc8b5a4a09f23c7396614e2431e1

**Comment by Wugand** [comment]
Thank you for the report. Some features are not fully finished yet, so there are missing description. We try to complete that as sson as possible.
Your Issue was added to the collection thread. #962
