### ISSUE TITLE
Because very lost with very few researches left. Where to go from here

### ISSUE THREAD

**Issue by walksanatora** [mcenderdragon/Futurepack-API#889]
I am playing with futurepack v33.0.7268 for minecraft 1.18.2
And I have almost everything the only things I don't have researched (that are flashing) are (these are the item id's for the upgrade)
futurepack:upgrade1 - don't know what to research from
futurepack:kryptographite - also don't know what to research for this
Insert node - requires NE and idk how to get that or input it into the researcher I tried energy from the generator but it just shows a `Calculation Modules: 0` instead of a time remaining
Redstone pipe: same thing as with insert node but cables instead of hoppers
Redstone cable: same as above but cables instead of hoppers
Fluid pump: same message as the others but under copper coil

**Comment by mcenderdragon** [comment]
make a research modul energy, place it next to the researcher and fill it with NE.
upgrad1 and krytogrsphie are for dungeon exploring.

**Comment by walksanatora** [comment]
I can't craft a research module energy because it says I don't have it unlocked

**Comment by mcenderdragon** [comment]
the research it - with a right click you even see what to research in order to get to a research.

**Comment by walksanatora** [comment]
I can't right click I tem I don't have, and I don't see any research which will get me the energy research module

**Comment by walksanatora** [comment]
Okay I just opened the research menu, all the icons are off
As in icons are offset from the background

**Comment by mcenderdragon** [comment]
> I can't right click I tem I don't have, and I don't see any research which will get me the energy research module

the first tab the neon spark - if you still dont know what I mean make a screenshot of the first (scrench) tab

**Comment by walksanatora** [comment]
Finally found the research for energy module
