### ISSUE TITLE
Question about Flux Transformator and "dangerous effects"

### ISSUE THREAD

**Issue by Zarkazm** [mcenderdragon/Futurepack-API#891]
Not sure if this is a bug yet or not, so just starting off with a question.  The E-Scanner entry for the Flux Transformator says "Values below 400 RF/t do not produce any dangerous effects.", however when I turn it to 200 RF/t I start getting that blue paralyze effect as if i've been hit by a Cyber Zombie.  Is this the "dangerous effect" it's talking about, or have I missed reading something?  Thanks.

**Comment by mcenderdragon** [comment]
Dangeons effects are explosions or instant death to anything nearby.
