### ISSUE TITLE
Under Bedrock dungeon failed to generate

### ISSUE THREAD

**Issue by belathus** [mcenderdragon/Futurepack-API#892]
**Describe the bug**
Tried going to a Futurepack dungeon. A new one.

**To Reproduce**
1. I can consistently reproduce this by trying to go to dungeons

**Screenshots**

**Additional context**

**Version**
Minecraft Version: 1.18.2
Forge Version:40.1.20
Futurepack Version: 33.0.7268

**Logs**
https://gist.github.com/belathus/ad027f60187882b3773f6f9fe41cc96e
You can see me killing the soul chicken that spawns right after dungeon generation fails on line 5000.

**Comment by mcenderdragon** [comment]
in the log there is nothing noted why the dungeon failed or if at all. can xou rpovide the FP-latest.log

**Comment by belathus** [comment]
Pretty sure the specific log where I had the soul chicken spawn is lost, as the server restarted since then. I tried to recreate it by replacing the dungeon teleporter where the old one was. It did fail to generate the dungeon again, but it succeeded when I tried again. Here is the FP-Latest: https://gist.github.com/belathus/cb6dec55ed70c392aa7f7923a065bf31

I think the first time I tried entering the dungeon is on line 1776. It barely tried, it looks like. I'll try to recreate it again.

**Comment by belathus** [comment]
Just had the server crash while generating a dungeon. Here is the FP_Latest.log: https://gist.github.com/belathus/b6cacd36dfe79aeddfe6ed3ce8777717

It crashed on the server watchdog; a single tick took over 180 seconds. You can see that the dungeon generation took 133 seconds in the log.

Strangely, I saw a lot of stuff in the server log (stuff about improper protocol: modjar), but this didn't make it into the latest.log file or the FP_Latest.log file. When the server crashed, I didn't get a chance to copy those things that appeared in the log.
However, restarting the server, I did see this:
```
 java.net.MalformedURLException: unknown protocol: modjar
        at java.base/java.net.URL.<init>(URL.java:681)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.research.ResearchLoader$SimpleSupplierReader.get(ResearchLoader.java:84)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.research.ResearchLoader$SimpleSupplierReader.get(ResearchLoader.java:68)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.research.ResearchLoader$ReaderEntry.register(ResearchLoader.java:755)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.research.ResearchLoader.init(ResearchLoader.java:126)
        at TRANSFORMER/futurepack@033.0.7268/futurepack.common.FuturepackMain.serverStarted(FuturepackMain.java:291)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@40.1.20/net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:99)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:662)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

I tried rejoining the server after I saw that. I ended up on top of the bedrock in the Below Bedrock dimension, and this ended up in the server console: https://gist.github.com/belathus/ea42cb4e3c8bf3257b7057b96279d22e

**Comment by mcenderdragon** [comment]
modjar stuff can be ignored forge removed it for some reason... its strage the server crashed I even do the placing of the structures async so the server has enough time. What are the hardware specs of the server ?

**Comment by belathus** [comment]
OS: Debian 11 bullseye
Kernel: x86_64 Linux 5.10.0-13-amd64
Disk: 45G / 1.9T (3%)
CPU: Intel Xeon E3-1245 V2 @ 8x 3.8GHz [51.0°C]
RAM: 10512MiB / 32011MiB

**Comment by mcenderdragon** [comment]
the watchdog - where did it crash exactly ? I am asking becuase there where no "skipping x ticks" messages in the log.

**Comment by belathus** [comment]
Here is the crash report: https://gist.github.com/belathus/6a9710f7400da713a9a7cc29d3ed97ae

**Comment by mcenderdragon** [comment]
sadly it doesnt point to where it hung

**Comment by belathus** [comment]
Also, we were able to get the Soul chicken to spawn again. A couple more times. The first time I didn't see it put anything in the log, but the second time I saw this:
```
Cant gen Boss Room for Lvl 1
Cant gen Boss Room for Lvl 2
Cant gen Boss Room for Lvl 3
Cant gen Boss Room for Lvl 3
Cant gen Boss Room for Lvl 2
-------------------------------------------------
Fourth time? He just kept trying.
-------------------------------------------------
Cant gen Boss Room for Lvl 8
Cant gen Boss Room for Lvl 7
Cant gen Boss Room for Lvl 1
Cant gen Boss Room for Lvl 3
Cant gen Boss Room for Lvl 2
Could not spawn end room
Cant gen Boss Room for Lvl 3
Cant gen Boss Room for Lvl 5
Cant gen Boss Room for Lvl 5
Cant gen Boss Room for Lvl 8
```
The above did not appear in either log, but did appear in the server console.

Here is the log: [FP_Latest.log](https://gist.github.com/belathus/0a2f419a71bb619e2efee74bef0f6c16), [latest.log](https://gist.github.com/belathus/bd26650fd1b4f9bffcf231f6cbfc021e).

The first time he tried to enter the dungeon was sometime around 16:49. He tried several more times, using setblock to remake the dungeon teleporter. Each time he got a Soul chicken, though it didn't always delete the teleporter.

**Comment by mcenderdragon** [comment]
> Also, we were able to get the Soul chicken to spawn again. A couple more times. The first time I didn't see it put anything in the log, but the second time I saw this:
> 
> ```
> Cant gen Boss Room for Lvl 1
> Cant gen Boss Room for Lvl 2
> Cant gen Boss Room for Lvl 3
> Cant gen Boss Room for Lvl 3
> Cant gen Boss Room for Lvl 2
> -------------------------------------------------
> Fourth time? He just kept trying.
> -------------------------------------------------
> Cant gen Boss Room for Lvl 8
> Cant gen Boss Room for Lvl 7
> Cant gen Boss Room for Lvl 1
> Cant gen Boss Room for Lvl 3
> Cant gen Boss Room for Lvl 2
> Could not spawn end room
> Cant gen Boss Room for Lvl 3
> Cant gen Boss Room for Lvl 5
> Cant gen Boss Room for Lvl 5
> Cant gen Boss Room for Lvl 8
> ```
> 
> The above did not appear in either log, but did appear in the server console.
> 
> Here is the log: [FP_Latest.log](https://gist.github.com/belathus/0a2f419a71bb619e2efee74bef0f6c16), [latest.log](https://gist.github.com/belathus/bd26650fd1b4f9bffcf231f6cbfc021e).
> 
> The first time he tried to enter the dungeon was sometime around 16:49. He tried several more times, using setblock to remake the dungeon teleporter. Each time he got a Soul chicken, though it didn't always delete the teleporter.

seems just like bad/unluky random

**Comment by mcenderdragon** [comment]
I chnaged some stuff and think dungeons will now generate more often
