### ISSUE TITLE
[Crash] E-Scanner prevents world join - FPChunkScanner

### ISSUE THREAD

**Issue by itsdinkd** [mcenderdragon/Futurepack-API#894]
**Describe the bug**
Player of my modpack, Another Quality Modpack 3 used a E-Scanner and their world crashed. Upon trying to reconnect to the world, they are stuck in a loop of errors while the screen shows "100%" loading terrain. 

Looking at the logs it has something to do with a chunk and FPChunkScanner

**To Reproduce**
1. Use E-Scanner on another Player
2. Crash

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.1.20
Futurepack Version: Latest 33.0.7268

**Logs**
https://gist.github.com/itsdinkd/71ddb29ce20f3041e28133f2159f3b8e Latest log

**Comment by mcenderdragon** [comment]
the e-scanner crash would be interesting, this right now is most likely just caused becuse  file corruption

**Comment by itsdinkd** [comment]
can you give me a heads up when this is released on CF? would love to update my modpack, FuturePack has been causing a lot of crashes
