### ISSUE TITLE
[1.18.2 Bug] Advancement is not unlocking recipes

### ISSUE THREAD

**Issue by itsdinkd** [mcenderdragon/Futurepack-API#895]
**Describe the bug**
Player in AQM3 has unlocked the required advancement to start crafting items in FP, however, this is not the case . the items still say locked due to not having advancement 

**Version:**

Minecraft Version: 1.18.2
Forge Version: 40.1.20
Futurepack Version: Latest 33.0.7268

**Comment by mcenderdragon** [comment]
researches unlock recipes not advancements.

**Comment by mcenderdragon** [comment]
is there anything else or can this be closed ?
