### ISSUE TITLE
External Cooler is not rotateable by scrench

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#90]
It don't get changes when used with scrench.

**Comment by mcenderdragon** [comment]
scrench doesnt work in most times, but it should be fixed in version 

EDIT: this was in the 1.11 update

**Comment by mcenderdragon** [comment]
ehm this should be tested agin in 1.10 and 1.11

**Comment by Wugand** [comment]
Retest it (Version 1.11.2):
- [x] Wood
- [x] Staris
- [x] Slabs
- [x] Trapdoor (ok strange, but working)
- [x] Pistons, Furnace Dispenser, ... 
- [x] All other vanilla stuff
- [x] Futurepack deco blocks
- [x] Modular Door
- [ ] Thruster
- [ ] Fueltank
- [ ] Airlock
- [ ] All FP Machines
- [ ] Sorter
- [ ] Assembly Table
- [ ] Neonengine
- [ ] Generator
- [ ] Coller, WaterCooler, Externalcore, Pump
- [ ] Laser-Transmitter, Scanner, Researcher, Boardcomputer, Flashserver
- [ ] Blockbreaker, Blockplacer

**Comment by mcenderdragon** [comment]
is in x indicing it is working or it is tested ?

**Comment by Wugand** [comment]
[x] is working
[ ] is not working

**Comment by mcenderdragon** [comment]
Please test again in 1.11 _and_ 1.11
