### ISSUE TITLE
IllegalAccessError with the Optiassembler causes server crash

### ISSUE THREAD

**Issue by belathus** [mcenderdragon/Futurepack-API#900]
**Describe the bug**
Trying to create a recipe in the optiassembler for the tactic control chipset. I put the quartz parts in a slot and got a crash.

**To Reproduce**
1. Start headless server.
2. Join headless server with client.
3. Place an optiassembler.
4. Try to create an assembly recipe.

**Screenshots**

**Additional context**
I saw GUI errors, so I was wondering if this is related to it being a headless server. So I started a single-player world and was able to create the assembly recipe without a problem.

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.1.20
Futurepack Version: 33.0.7268

**Logs**
https://gist.github.com/belathus/42caecb4964e4f8aad03454f2ebd1d91

**Comment by mcenderdragon** [comment]
does a server restart fix this problem ?

**Comment by belathus** [comment]
Restarting the server works fine, but I still can't put anything into that GUI or else it crashes again.

**Comment by belathus** [comment]
I was able to spawn in the assembly recipe item though (copied the NBT tag from single-player) and using that worked fine.

**Comment by mcenderdragon** [comment]
ohh wow. the synthethic accessor classes got remvoed - becuase server/client classes and thus it crashed. will befixed in the next update.
