### ISSUE TITLE
problem with rendering the techtree in the E-scanner

### ISSUE THREAD

**Issue by EKLEA** [mcenderdragon/Futurepack-API#901]
description:
the problem is that the scanner interface is not rendered in the normal world, but there is no such problem in the flat world

Screenshots:
![image](https://user-images.githubusercontent.com/87899628/173362461-46c5e8ad-1d9f-4a5e-adad-9b142a905d04.png)
![image](https://user-images.githubusercontent.com/87899628/173362944-30de7898-b7b8-434e-a4a3-1489eb355ec4.png)

Minecraft Version: 1.16.5
Forge Version: 36.2.34
Futurepack Version: 31.3.7005

Logs:
  [log default world.txt](https://github.com/mcenderdragon/Futurepack-API/files/8891379/log.default.world.txt)
Link on modpack:  https://drive.google.com/file/d/1CobBf5qKf0f0T0PJJjnkBgphghVb-A9N/view?usp=sharing

**Comment by arlyn123** [comment]
напиши дискорд, я тоже на этой сборке

**Comment by EKLEA** [comment]
Никита Игоревич#9067

**Comment by EKLEA** [comment]
I found a solution, future pack conflicts with roadrunner

**Comment by mcenderdragon** [comment]
Lithium/roadrunner still hasnt fixed this ?

**Comment by EKLEA** [comment]
No, I think
