### ISSUE TITLE
Components can stack in the Silicon Scavenger

### ISSUE THREAD

**Issue by belathus** [mcenderdragon/Futurepack-API#910]
If you use automation (like a hopper) to insert identical (stacking) cores into the silicon scavenger, you can put them all into the same slot. When the machine goes to move the silicon from one component to the other, the silicon part gets applied to every core in the stack.

**To Reproduce**
1. Place silicon scavenger and power it
2. Place hopper on top of scavenger
3. Take a stack of cores and put it in the hopper. They should all end up in the input slot as a stack.
4. Insert a good core in the other good slot.
5. The good core is copied over to the stack.
6. Repeating this process by sacrificing one of the cores from the stack you just made allows you to refine your cores further.

**Screenshots**
![silicon scavenger issue](https://user-images.githubusercontent.com/3826783/175837515-548b5977-206c-41f0-9c95-82cc3e5c70a7.png)

**Additional context**
You can use this to duplicate the best "silicon" part of a core from the stack, leading to some rather insane increases in core power. Right now I have some dungeon heart cores with a core power of 45, allowing me to make torus cores with over 100 core power. It is a bit harder, though, to make an insanely good torus core on top of that since those rarely stack.

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.1.30
Futurepack Version: 33.0.7327

**Logs**
Maybe not applicable here.

**Comment by mcenderdragon** [comment]
I was opretty sure https://github.com/mcenderdragon/Futurepack-API/issues/846 fixed this...

**Comment by belathus** [comment]
Hm. I'm using a modded hopper that inserts a stack instead of a single item. Maybe that is what is breaking it?

**Comment by mcenderdragon** [comment]
possible it doesnt doo all needed checks... can a vanilla hopper or pipes or the pusher also do that ?

**Comment by belathus** [comment]
Yeah, I can put multiple items in the input slots using a vanilla hopper, so this problem can be created using nothing but Vanilla + FP.

**Comment by mcenderdragon** [comment]
the vanilla hopper seems to never check if the contiar has a custom StackSizeLimit

**Comment by mcenderdragon** [comment]
https://bugs.mojang.com/browse/MC-175090

**Comment by mcenderdragon** [comment]
I have a workaround for thia until mojang fixes this.
