### ISSUE TITLE
[1.18.2] Sidedness issue - Attempted to load class net/minecraft/client/gui/screens/inventory/AbstractContainerScreen for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#912]
**Describe the bug**
Client clicks on a small dungeon teleporter and the server scrolls tons of red lines but doesn't crash.

**Version**
Minecraft Version: 1.18.2
Forge Version: 1.18.2-40.1.51
Futurepack Version:  Futurepack-1.18.2-33.0.7403

**Logs**
https://gist.githubusercontent.com/ProsperCraft/8ad8d6939b94f990a66f5f63d67c84b2/raw/c2ab955aab0f4184fe3339ca3eaa2795c1c4130e/gistfile1.txt

**Comment by mcenderdragon** [comment]
published to curseforge

**Comment by MagisterXero** [comment]
I think this issue may have resurfaced:
https://pastebin.com/iZhtANxp
Minecraft: 1.18.2
Forge: 40.1.51
Using: Futurepack-1.18.2-33.0.7441.jar
