### ISSUE TITLE
Mandelberry seed bug

### ISSUE THREAD

**Issue by QuertzTheRealOne** [mcenderdragon/Futurepack-API#919]
**Describe the bug**
You can infinitely duplicate Mandelberry seeds, not a big problem, but it's there and it's probably simple to fix
I'm using 1.18.2-33.0.7441 (currently latest one)

**To Reproduce**
1 Plant one seed
2 Break it
3 Two seeds drop

**Screenshots**
![2022-07-13_21 07 12](https://user-images.githubusercontent.com/59313754/179079231-7b35af2d-26bc-47ab-b47c-195394310fc9.png)
![2022-07-13_21 07 14](https://user-images.githubusercontent.com/59313754/179079267-76ce8c05-4735-4f16-a411-14bb546c13b3.png)
![2022-07-13_21 07 17](https://user-images.githubusercontent.com/59313754/179079304-fdb83501-9c0b-4452-af6f-8e6d789d7ba4.png)
![2022-07-13_21 07 19](https://user-images.githubusercontent.com/59313754/179079325-2ceb4c4c-f55a-4ec1-9f8c-a92506b68047.png)

**Version**
Minecraft Version: 1.18.2
Forge Version: 1.18.2-40.1.52
Futurepack Version: 1.18.2-33.0.7441

**Comment by mcenderdragon** [comment]
its all loottable madness now so not so easy to fix

**Comment by mcenderdragon** [comment]
should be fixed https://www.curseforge.com/minecraft/mc-mods/futurepack/files/4555761
