### ISSUE TITLE
Fixes for next Release Version [List]

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#92]
- Optibench Gui texture broken
- Test GUI's
- Add Drop for Fireflies
- Fix Model-Errors Firelies
- Add JEI-Supercrusher to lang-files

!important

**Comment by Wugand** [comment]
Scanner Result Icons Broken

**Comment by mcenderdragon** [comment]
* the fireflies should drop (and they do when I tested it, have you destroed them in creative?) 
* test GUI's ?
