### ISSUE TITLE
[1.18.2] Underwater Dungeons deny progression

### ISSUE THREAD

**Issue by rbandboy** [mcenderdragon/Futurepack-API#921]
**Describe the bug**
As some of the dungeons (the teleporter dungeons) have segments underwater, if a boss room is underwater, the security zombies turn into Drowned, and killing the resulting drowned and stray does not cause the General to spawn.

**Screenshots**
![2022-07-16_13 04 47](https://user-images.githubusercontent.com/4001839/179368754-fe377a30-7303-4a91-85ad-782d196c6800.png)

**Additional context**

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.1.54
Futurepack Version: Futurepack-1.18.2-33.0.7414

**Comment by Yirok42** [comment]
What happens if you leave the dimension and return? I am not thinking as a resolution but as a work around. I have wondered if the higher order mobs drown or if they even know to get out of the water.
Another side question: these dungeons have a random number (I assume) as the seed for generation. If it was accessible or logged, it could help reproducing these situations in the development/testing environment. Are the dungeon seed values accessible? and would it help folks at redsnake?

**Comment by rbandboy** [comment]
Leaving the dimension and returning retains the state of this battle, as there have been times I have left and returned to fight these dungeons.  The seed for this dungeon is not available (as it is on a public server), and no teleporter was available before this fight.

**Comment by Yirok42** [comment]
The seed question was for mcenderdragon.
If the server is public will you provide the address and compatible mod list?
gmail.com is the rest of my email address.

**Comment by rbandboy** [comment]
The pack in question is TownCraft by Goshen_Ithilien, the public included server with its pack.  Version 0.21 is live as of this message.

https://www.curseforge.com/minecraft/modpacks/towncraft

**Comment by mcenderdragon** [comment]
pleasse try this jar: https://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.18.2-33.0.7458/Futurepack-1.18.2-33.0.7458.jar and see if ti fixes the issue

**Comment by rbandboy** [comment]
![image](https://puu.sh/Jn0VC/0dc929bb45.jpg)

Image taken from the dev jar with Journeymap and JEI, found in Enders gigantic Garden (double fight)

They also spawned on top of the dungeon spawner, causing them to start suffocating in the ceiling as well.

![image](http://puu.sh/Jn0Y8/a1553d2c75.jpg)

**Comment by rbandboy** [comment]
Is the resolution that the enemies start regenerating if they're drowning/suffocating?

**Comment by mcenderdragon** [comment]
> Is the resolution that the enemies start regenerating if they're drowning/suffocating?

can you still kill it and thus continue to progress in the dungeon ?

**Comment by mcenderdragon** [comment]
as this is pushed to curse I will close this as fixed, feel free to reopen.
