### ISSUE TITLE
[1.18.2] Loot chest on menelaus, spawner chest

### ISSUE THREAD

**Issue by shel2015** [mcenderdragon/Futurepack-API#922]
I'm using the release for mc 1.18.2 menelaus loot chest won't open, spawner chest will not pick up blaze spawner. How can you tell if you've updated to current but not beta version. I don't see the obvious beta tag.

**Comment by mcenderdragon** [comment]
can you provide screenshots ?

**Comment by mcenderdragon** [comment]
I tested the spawner chst and it works without problems, also oopening chests works fine - please amkle sure the configs dotn disable the loot chest.
