### ISSUE TITLE
[1.18.2] Forestmaster drone crashes the dedicated server

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#927]
**Describe the bug**
Server crashes.

**To Reproduce**
Start a drone on a dedicated server and the server crashes when trying to harvest a tree.
Player thinks the tree in question was a twilight forest sickly oak

**Version**
Minecraft Version: 1.18.2
Forge Version: forge-1.18.2-40.1.76-
Futurepack Version: Futurepack-1.18.2-33.0.7441

**Logs**
https://gist.github.com/ProsperCraft/de5c2e885e4dbae3b797e7c5673eac92

**Comment by mcenderdragon** [comment]
Does this always happen or only once ?

**Comment by ProsperCraft** [comment]
Confirmed resolved.
