### ISSUE TITLE
[1.18.2] Server crashloop - java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41720_()" because "it" is null

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#929]
**Describe the bug**
Player said this about what they set up that started the server in a crashloop - 
when you push items from an ultimate pipe (mekanism) into the futurepack item pipes the server can crash (probably because of too many items in the pipe) 

**Version**
Minecraft Version: 1.18.2
Forge Version: forge-1.18.2-40.1.76
Futurepack Version: Futurepack-1.18.2-33.0.7457

**Logs**
https://gist.github.com/ProsperCraft/6f45e4a67881a926d1466652beb21571

**Comment by mcenderdragon** [comment]
so whatever the InsertNode/theStöpsel is connected to is violating the IItemHandler interface nonNull contract and returning a null itemStack instead of empty.

**Comment by mcenderdragon** [comment]
I pushed a fix to curseforge; it will crash with more information why it crashed and then start again without deadlokign the server. as a inser node is used it can happen that it needs to crash and restart a few times if multiple connected containers are causing this.

**Comment by ProsperCraft** [comment]
https://gist.githubusercontent.com/ProsperCraft/24ac7e19d38cde988019948d057092af/raw/2c32fd66c9772ed58ae68c19ad525188e63d2485/gistfile1.txt

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/8b5d63868d580a3e50bc465809e59b46
https://gist.github.com/ProsperCraft/e7c4b38ef4b16f4119694a36b4892f20

**Comment by mcenderdragon** [comment]
ok then what is at {x=-1806, y=44, z=-16281} that is somehow cuasing issues.

**Comment by ProsperCraft** [comment]
Confirmed fixed.
