### ISSUE TITLE
Game crashes when I right click pressed while holding the object in his hand

### ISSUE THREAD

**Issue by KiraLinux** [mcenderdragon/Futurepack-API#93]
[crash-2016-12-08_18.51.00-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/639895/crash-2016-12-08_18.51.00-client.txt)

**Comment by mcenderdragon** [comment]
https://twitter.com/Vazkii/status/804802548427345921

**Comment by mcenderdragon** [comment]
Yeah this will be fixed in the next build.

**Comment by mcenderdragon** [comment]
And no this is just luck you have cliecked something, it was the monorail station
