### ISSUE TITLE
 Exception caught during firing event

### ISSUE THREAD

**Issue by Chydog376** [mcenderdragon/Futurepack-API#934]
Good morning,
Today I went to my server I run and was suprised to see messages in my server's discord about not being able to join the server.  I soon found out that the reason was from Futurepack. It won't show a crash log but shows many firing event errors in the log. Upon just trying to remove the mod (which I didn't want to do anyway!!) I just got other errors becuase the ores and dimensions couldn't be found yet still existed. Please help! Untill this can be fixed or I can safely remove it, my server is un usable. Whenever someone trys to join it just says that the server is still starting and to please wait before reconnecting!

N/A: Unique errors

Minecraft Version: 1.18.2
Forge Version: 40.1.80
Futurepack Version: 33.0.7482

Log:
https://gist.github.com/Chydog376/f6adb0cf6a921cfd0f441aa91b075a92

Thank you in advance,
Chydog376

**Comment by Chydog376** [comment]
I please need a reponce and hopefully a solution soon becuase my server is unsable untill then!

**Comment by mcenderdragon** [comment]
```
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.longs.LongSet.contains(long)" because the return value of "futurepack.world.scanning.FPChunkScanner.getOrLoadScannedChunks(net.minecraft.world.level.LevelAccessor)" is null
	at TRANSFORMER/futurepack@033.0.7482/futurepack.world.scanning.FPChunkScanner.isChunkScanned(FPChunkScanner.java:514)
	at TRANSFORMER/futurepack@033.0.7482/futurepack.world.scanning.FPChunkScanner.scanChunk(FPChunkScanner.java:313)
	at TRANSFORMER/futurepack@033.0.7482/futurepack.common.FuturepackEventHandler.onChunkLoad(FuturepackEventHandler.java:301)
	at net.minecraftforge.eventbus.ASMEventHandler_535_FuturepackEventHandler_onChunkLoad_Load.invoke(.dynamic)
```

I will fix this when I have time, which will be sadly at best next month.

**Comment by mcenderdragon** [comment]
does this also happen with jsut futurepack installed ?

Edit: try to remvoe BYG whatever that is, and see if that helps.

**Comment by Chydog376** [comment]
Ok thank you, I don't see BYG is it showing up as a mod?

**Comment by mcenderdragon** [comment]
Biomes Yoiu Go should be it

**Comment by Chydog376** [comment]
Oh oh oh, sorry lol, that could be a pain, okay I will test that, thanks!

**Comment by Chydog376** [comment]
Ok, I removed it and got mostly the same thing... Here is the log:
https://gist.github.com/Chydog376/126aed9eb6559e5416b60512c0945ec0

**Comment by mcenderdragon** [comment]
that log seems fien now. does a new world work ?

**Comment by Chydog376** [comment]
Um, yes it does, thank you. I never had a problem with a new world though, I guess my question would be is there any way to fix this without creating a new world. I would literally have to recreate the server from scratch and loose ALL player data if I create a new world...

**Comment by mcenderdragon** [comment]
should be fixed https://www.curseforge.com/minecraft/mc-mods/futurepack/files/4555761
