### ISSUE TITLE
No player documentation on the wiki

### ISSUE THREAD

**Issue by JadianRadiator** [mcenderdragon/Futurepack-API#937]
Could you please add a table-of-contents that you can use to easily navigate to the correct page for what you're wanting to look up?
Because it's really difficult for someone to navigate the notes to find what they're looking for, especially if they're not already familiar with the mod.

[Author said to check the wiki for documentation](https://www.curseforge.com/minecraft/mc-mods/futurepack?comment=902),
but there is no end-player documentation on the wiki.
https://imgur.com/a/DAHRuDz

**Comment by mcenderdragon** [comment]
you posted a picture showing a link to the fanmade wiki, go there .

**Comment by JadianRadiator** [comment]
[This is the wiki](https://github.com/mcenderdragon/Futurepack-API/wiki) you told me to use, and is the one shown in my pictures.
And as my pictures show, it doesn't contain documentation.
