### ISSUE TITLE
there is no documentation on the wiki. and this time, actually go over pictures before claiming them as proof

### ISSUE THREAD

**Issue by JadianRadiator** [mcenderdragon/Futurepack-API#938]
[This is the wiki](https://github.com/mcenderdragon/Futurepack-API/wiki) I was told to use.
And as my pictures show, it doesn't contain documentation.

Could you please add a table-of-contents that you can use to easily navigate to the correct page for what you're wanting to look up?
Because it's really difficult for someone to navigate the notes to find what they're looking for, especially if they're not already familiar with the mod.

[Author said to check the wiki for documentation](https://www.curseforge.com/minecraft/mc-mods/futurepack?comment=902),
but there is no end-player documentation on the wiki.
https://imgur.com/a/DAHRuDz

**Comment by mcenderdragon** [comment]
I told you to use this wiki: http://futurepack-minecraft-mod.wikia.com/wiki/Futurepack_Minecraft_mod_Wiki sorry if this was nto clear. and yeah the github wiki contains mod intenral specific stuff.

**Comment by JadianRadiator** [comment]
issue with you telling me to use it was that you originally hadn't actually told me where to find it.

**Comment by mcenderdragon** [comment]
> issue with you telling me to use it was that you originally hadn't actually told me where to find it.

I assumed you could read and not instantly created issues for non existing issues, my bad.
