### ISSUE TITLE
Experience module 2048 resets

### ISSUE THREAD

**Issue by Vitraalt** [mcenderdragon/Futurepack-API#940]
Experience module resets at 2048 XP

**To Reproduce**
1. Connect experience module to the network cables
2. Using any automatic way to get XP get 2048 XP in a module
3. See how it resets at 2048

**Screenshots**
No screenshots

**Additional context**
No context

**Version**
Minecraft Version:1.16.5
Forge Version:36.2.39
Futurepack Version: 31.3.7005

**Logs**
No logs i guess

**Comment by mcenderdragon** [comment]
ohh the network calculations are off by one, so this is only something visually on the client.

**Comment by mcenderdragon** [comment]
solved in 1.1.8.2

**Comment by mcenderdragon** [comment]
should be fixed https://www.curseforge.com/minecraft/mc-mods/futurepack/files/4555761
