### ISSUE TITLE
Crash report, shows FP as source of exception

### ISSUE THREAD

**Issue by Viola-Case** [mcenderdragon/Futurepack-API#941]
My world is crashing after just opening it for the second time.

1. Go to Any Already Created World
2. Observe Crash
3. Scroll down to end of latest.log
4. See Futurepack ExceptionInInitializerError

I'm trying to make a custom modpack; the exception shows it occurs in FP.

Minecraft Version: 1.16.5
Forge Version: 36.2.39
Futurepack Version: 31.3.7008

Latest.log: https://pastebin.com/Xb9G7BVD
FP-Latest.log: https://pastebin.com/X9XRvYTM

**Comment by mcenderdragon** [comment]
does this also happen with jsut futurepack installed ?

Edit: also upodatwe java youa re still using java 8u51 thats super old and has lots of issues (latest is soething around 8u250+)

**Comment by jayden315** [comment]
I had this problem too to fix this just use version 31.3.7005 of the mod.

**Comment by mcenderdragon** [comment]
> I had this problem too to fix this just use version 31.3.7005 of the mod.

whixh also emans you dotn ahve the fixes in 7008

**Comment by Viola-Case** [comment]
Downgrading from 7008 to 7005 fixed the problem; I'd love it if future versions also addressed this problem.

**Comment by mcenderdragon** [comment]
> Downgrading from 7008 to 7005 fixed the problem; I'd love it if future versions also addressed this problem.

well I cant fix this if everone who has the crash jsut backports and not further investigates the cause - its something java intenral so msot liley a mod interaction so I cant do that on my end.
