### ISSUE TITLE
Copper Ingot

### ISSUE THREAD

**Issue by pietru2004** [mcenderdragon/Futurepack-API#945]
Could mod don't register its own copper for MC 1.18.2?
it is already in the game in it.

**Comment by mcenderdragon** [comment]
its still in there to not break the item/block registry. spawning of the ore can be deactivated in the configs and the blocks shoiuld drop vanilla raw copper. via tags the copper tingot is fully compatible with vanilla.

**Comment by pietru2004** [comment]
It is I just ask is it possible to make it don't register it only for the 1.18.2

**Comment by mcenderdragon** [comment]
that would break all existtng worls as the registrieswould no longer match. what is the exact issue you are facing ?

**Comment by pietru2004** [comment]
My question is rather caused looking at Create that had only left textures for 1.18.2 version of mod
