### ISSUE TITLE
Daugon Turrets

### ISSUE THREAD

**Issue by pietru2004** [mcenderdragon/Futurepack-API#946]
**Is your feature request related to a problem? Please describe.**
Daungon turrets shot all people

**Describe the solution you'd like**
If person is holding enough clearance for passing it should not get that person as unauthorized.

With this there could be added security terminal that players could set turret clearances - for personal uses.

**Comment by mcenderdragon** [comment]
jsut deactiavtze the turrets then ?

**Comment by pietru2004** [comment]
for people that have key - I mean if somebody is followed via person with no key then it should still shoot them as they don't have clearance or something like ignore until clearance holder passes throu door or goes out of turret detection range

**Comment by mcenderdragon** [comment]
if you have the keys you can simply go trough the forcefields and the turrets wotn attack you after you passed - since you are behind blocks.

**Comment by pietru2004** [comment]
unless it is new daungon and you take too much time looting chests

**Comment by mcenderdragon** [comment]
even then it doesnt kill you so i see no issue here.

**Comment by pietru2004** [comment]
well lamps don't always get lit by default so monsters are spawned in daugon (in hole place, I don't count guarded gates)

**Comment by pietru2004** [comment]
![obraz](https://user-images.githubusercontent.com/51274570/201543142-722a4b71-f624-4381-b3f3-a397c53d3022.png)

**Comment by mcenderdragon** [comment]
> well lamps don't always get lit by default so monsters are spawned in daugon (in hole place, I don't count guarded gates)

yes this is intended. as soon as you walk on the blocks they light up.

**Comment by pietru2004** [comment]
is it intended for daungon to be in water?
![obraz](https://user-images.githubusercontent.com/51274570/201543216-dc8bfdf4-f0cc-46af-b9e5-b62ee9cd9524.png)

**Comment by mcenderdragon** [comment]
> is it intended for daungon to be in water? ![obraz](https://user-images.githubusercontent.com/51274570/201543216-dc8bfdf4-f0cc-46af-b9e5-b62ee9cd9524.png)

yes this is a feature that was recently added.

**Comment by pietru2004** [comment]
well that one happens too much I think cause checkpoint was in water
![obraz](https://user-images.githubusercontent.com/51274570/201543280-eb326f35-17f3-4bb5-8fe9-7b82e1ffe04c.png)

**Comment by mcenderdragon** [comment]
> well that one happens too much I think cause checkpoint was in water ![obraz](https://user-images.githubusercontent.com/51274570/201543280-eb326f35-17f3-4bb5-8fe9-7b82e1ffe04c.png)

its still fully functional so i dont see an issue.

**Comment by pietru2004** [comment]
should checkpoint be safe place ? I think player should be able to at least catch breath in it

**Comment by mcenderdragon** [comment]
> should checkpoint be safe place ? I think player should be able to at least catch breath in it

by default vanilla doenst spawn enough mosnter to be of any real issue - if you have trouble its most likoley another mod spawning more monsters - so nope there is no real save place in there, if there are too many monsters jsut go back from where you came from, there should be no mosntersd since there is light you actiavted and killed all monsters.

**Comment by pietru2004** [comment]
In theory it might be Quark stuff I guess
