### ISSUE TITLE
Portal gun

### ISSUE THREAD

**Issue by Ashwinaaaaaaahdt** [mcenderdragon/Futurepack-API#950]
Add a new portal gun 
Since there is no portal gun mod after forge 1.12.2 
Many players wanted a portal gun 
And this gun will be after the chipset, laser learning table 
I think obsidian and lens are important for crafting 
Obsidian is important for the nether portal so and lens for bending the image of the portal 

I think players will like this mod so great after adding the portal gun 

 Also, make this feature for all versions of Minecraft like 1.13x, 1.14x, 1.15x, and1.16x

**Comment by mcenderdragon** [comment]
this request is way out of scop for futurepack. and the old workspaces for 1.13 to 1-16 dont work anymore sadly.
