### ISSUE TITLE
add ibndustrial recipes to neon industrial furnace

### ISSUE THREAD

**Issue by AefRal** [mcenderdragon/Futurepack-API#952]
Playing:
Odyssey Space - A New Beginning

Versions:
Futurepack-1.16.5-31.3.7005
ExtremeReactors2-1.16.5-2.0.49

The pack contains Extreme Reactors mod, 
and when I try to make Tin Graphene Catalyst, it just makes Graphite.
How can I get the Tin Graphene Catalyst without removing Extreme Reactors mod?
Could a button be added to do alloys only? Like with EnderIO's Alloy Smelter?

![2022-12-05_22 08 06](https://user-images.githubusercontent.com/68062495/205825039-00da6483-2adc-40c5-add9-606771b55991.png)
![2022-12-05_22 09 11](https://user-images.githubusercontent.com/68062495/205825045-4cae22dd-563c-4580-835f-479662c8fdc5.png)

**Comment by AefRal** [comment]
For the time being, I found a setting in the Extreme Reactors Config.
I just turned off Coal, kept Charcoal on.
--Nevermind. Went to smelt the Tin Graphene Catalyst and still got Graphite. 
Turned all three settings off, still got graphite.
![2022-12-05_22 55 13](https://user-images.githubusercontent.com/68062495/205830153-4fba9c86-b831-4086-ac51-d97bede15fee.png)

**Comment by mcenderdragon** [comment]
all availabel recipes are done in parallel, so for soem reason its not accepting the items. are you sure you used the correct ingot ?

**Comment by AefRal** [comment]
It is tin. Made doubly sure. The recipe has a cycling image showing various
mods' version of tin. So I assume any and all tin is accepted.

**Comment by mcenderdragon** [comment]
try to add coal at once to see if it will run both recipes. (part will be processes to graphene , the other to the catalyst)

**Comment by AefRal** [comment]
I have added coal on it's own and it gave graphite.
I have had all necessary items inserted and coal was placed last, yet
graphite is all I got.

**Comment by AefRal** [comment]
Had stopped playing that pack for a while. Forgot why and came back to it.
Thought occurred to me, what if the Extreme Reactors config just needed a restart to take effect.
So upon loading my world I tried it again. This time however, nothing was being produced.
The recipe was not even starting. That got me thinking, that maybe it has to do with the 
Industrial NEON Furnace. So I crafted another regular Industrial Furnace and attempted the 
recipe. TA-DA! It works. 
![2022-12-18_11 19 59](https://user-images.githubusercontent.com/68062495/208313045-18f3f5e4-ae4b-4fa4-ba29-32df3d726139.png)
Now the issue I take up is that nowhere in the Life Support System page
does it specify using Industrial Furnace over Industrial Neon Furnace. We're just given an image.
![2022-12-18_11 26 17](https://user-images.githubusercontent.com/68062495/208313276-a63a0e83-301f-4838-b208-a8f7ade7fccd.png)
So I think either the Industrial Neon Furnace needs tweaking or the Tin Graphene Catalyst does.

**Comment by mcenderdragon** [comment]
ohh yeah, it seems like I forgot to add the recipe to the neon industrial furnace.

**Comment by AefRal** [comment]
Ah, so that was it.
Glad it came to light.

**Comment by mcenderdragon** [comment]
should be fixed https://www.curseforge.com/minecraft/mc-mods/futurepack/files/4555761
