### ISSUE TITLE
git push question

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#955]
I downloaded the project and compared the changed_date to see where the de_de was newer than the en_us, and updated the en_us with the de_de dates and German text translated to English (online tool and I checked it after).
Having had success with that, I examined more en_us files and made minor grammar updates.
I rewrote the Rocket page since guided rockets are called missiles.
I put this on its own branch but was not able to push it. 
Guidance can be made here, twitter, or patreon.

**Comment by mcenderdragon** [comment]
did you use a git client like GitExtensions so you dont have to use the command line? and pushign works by being authorized and linking your account to git via https or via a ssh key.

**Comment by Yirok42** [comment]
Alright. I so I have done a better attempt:
I tried with a bad password, and then my actual password.

1. with a bad password
20:36:16.632: [Futurepack] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/update_en_us:master
remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.com/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
fatal: Authentication failed for 'https://gitlab.com/MCenderdragon/Futurepack.git/'

2. with a good password
20:38:12.560: [Futurepack] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/update_en_us:master
remote: You are not allowed to push code to this project.
fatal: unable to access 'https://gitlab.com/MCenderdragon/Futurepack.git/': The requested URL returned error: 403

Perhaps I do not have permission.
Perhaps I have never asked, or it expired.
If it requires that you add my username to the project to allow pushing to the non-main branch, then I'd think you need to know my username. I provided that on the patreon side. :) 

Perhaps I should say I'm using IntelliJ IDEA and the prompt for push asked for my username (email address) and password.

**Comment by mcenderdragon** [comment]
you need to make a fork if the futrepack project on gitlab. push changes there and then open a merge request/pull request on gitlab from your branch.

**Comment by Yirok42** [comment]
Thank you for that. I believe I have done it. 
I think I now see I make changes to my fork and make merge requests to the base project.
