### ISSUE TITLE
In the latest update for 1.18.2 there are missing files??

### ISSUE THREAD

**Issue by WolfPoe2** [mcenderdragon/Futurepack-API#959]
There is actually a file that seems to be missing? I'm not sure if there are anymore but it seems to be missing the files called 'story.nav.mincra' or at least according to your mod after doing research on a music disc it says it is missing.
![story nav mincra missing](https://user-images.githubusercontent.com/124480994/216800643-4a1a6916-a7a7-4013-9f19-fb03c0fd4406.png)

**Comment by Wugand** [comment]
Thank you for the report. Some features are not fully finished yet, so there are missing description. We try to complete that as sson as possible.
Your Issue was added to the collection thread. #962
