### ISSUE TITLE
[1.16.5] Futurepack, Applied Energistics 2 and JAOPCA world creation crash

### ISSUE THREAD

**Issue by sirben99** [mcenderdragon/Futurepack-API#967]
**Describe the bug**
Hey!

I have a crash when creating a world, with only Futurepack, Applied Energistics 2 and JAOPCA (Just A Ore Processing Compatibility Attempt) mod installed.

Im not sure whos to blame here, so i made an issue about this to here and JAOPCA mods issue tracker (Applied automaticly closed the issue, since its unsupported version). You can find JAOPCA crash report [here](https://github.com/TheLMiffy1111/JAOPCA/issues/277)

**To Reproduce**
1. Install Futurepack, Applied Energistics 2 and JAOPCA mods
2. Create a world
3. Crash

**Versions**
Minecraft Version: 1.16.5
Forge Version: 36.2.39
Futurepack Version: Futurepack-1.16.5-31.3.7008
Applied Energistics 2 Version: appliedenergistics2-8.4.7
JAOPCA Version: JAOPCA-1.16.5-3.4.3.26

**Logs**
Latest.log: https://pastebin.com/PHzJTfHp
Crash report: https://pastebin.com/R1eRwPh6
Debug.log: https://pastebin.com/2QcGBgbm

**Comment by mcenderdragon** [comment]
thats JAOPCa crashing as it tries to call methods that arent part of the API
