### ISSUE TITLE
JVM Crash

### ISSUE THREAD

**Issue by I2pRandom** [mcenderdragon/Futurepack-API#974]
**Describe the bug**
JVM level Crash

**To Reproduce**
While in create I entered a Dungeon, Upon Leaving the Dungeon the JVM immediately crashed. 

**Screenshots**

**Additional context**
Several hundred mods loaded, cause unknown if incompatibility.

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.2.7
Futurepack Version: 033.0.7544

**Logs**
hs_err_pid5204_libjvmci.log: https://gist.github.com/I2pRandom/91a580ea314d8974be5cd7d00339f82b
hs_err_pid5204.log: https://gist.github.com/I2pRandom/a24d719bf4549377d467b71499056fda
Debug.log: https://gist.github.com/I2pRandom/3c1c0fa2c56a6242971c3f777f619381
FP-Latest.log: https://gist.github.com/I2pRandom/3b3c6b64e435d0acebfb1723d5d18897

**Comment by mcenderdragon** [comment]
`org.valkyrienskies.physics_api_krunch.KrunchNativePhysicsWorldReference.tick(`

Seems like valkyrien skeis cuased this, please report it to them.
