### ISSUE TITLE
World generation freezes tied to FPChunkScanner

### ISSUE THREAD

**Issue by EntityIridescent** [mcenderdragon/Futurepack-API#981]
**Describe the bug**
Upon creation of new worlds, world generation consistently freezes, leaving only a FPChunkScanner log message behind (similar to issue #515)

**To Reproduce**
1. Create a new world with Futurepack specified version installed
2. Game freezes before world loads, stuck at differing percentages with multiple trials.

**Additional context**
Futurepack is installed alongside other mods in a custom modpack, and the issue is resolved whenever Futurepack is disabled. 

**Version**
Minecraft Version:
1.16.5

Forge Version:
36.2.34

Futurepack Version: 
31.3.7005 (issue persists with 31.3.7008)

**Logs**
https://gist.github.com/EntityIridescent/2697cab0b31de944ac39ba7141190ff7

**Comment by mcenderdragon** [comment]
is the right log linked it cuts oiff at [23:36:58] [main/INFO]: Registering recipes: tardis:jei took 8.267 ms and looks perfectly normal.

**Comment by EntityIridescent** [comment]
The file is truncated, but can be viewed in full when directed to the link
provided.

**Comment by mcenderdragon** [comment]
Whjen did you close the game becuase it looks like ti was still generating.

[23:40:43] [main/INFO]: Preparing spawn area: 67%
[23:40:43] [main/INFO]: Preparing spawn area: 68%

**Comment by EntityIridescent** [comment]
It froze at 68%, and I waited around 5 hours to force shut it down.

**Comment by mcenderdragon** [comment]
sadly there is not much I can do as that all deep dowen in mojang json hell. aka there is no code executed only jsons. this also means there is almsot no information to debug. can you reproduce this with sut futzurepack ?

**Comment by EntityIridescent** [comment]
Upon further testing, it seemed like one of the other mods installed was attempting to call upon Terraforged for world generation, but couldn’t find it and thus froze. I tried looking at related dependencies on the Terraforged curseforge page, but I could not figure it out. The issue can be resolved by simply not generating a default world, but installing and using the Terraforged option or Quark’s Realistic. I suppose Futurepack just happened to throw a ChunkScanner message while the world was generating. I will see about reopening if the issue continues. Thanks!

**Comment by mcenderdragon** [comment]
Thanks god I did not broke another world haha
