### ISSUE TITLE
Dungeons monster spawner bug

### ISSUE THREAD

**Issue by Ashwinaaaaaaahdt** [mcenderdragon/Futurepack-API#987]
The monsters would despawn if the player died, and the monsters would despawn in a peaceful mode in which no fight is made and the player's health would be the same
The monsters shouldn't despawn in peaceful mode like from Mowzie's mods' 'Barako the sun chief' is a hostile mob that doesn't despawn to keep the fight running and for the vindicator better to add a separate code to make the vindicator aggressive in the dungeon only but not in the mansion

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to dungeon monster spawner and spawn the monsters
2. Click on peaceful mode and monsters will despawn
3. Leave the world and rejoin it
4. The 'The wave is cleared' or 'general will be sent' message will come and allow the player to go forward.

**Additional context**
I couldn't play 1.17 and above as I have open gl 3.2 and my computer is incompatible with the graphics card and 7008 isn't working fine😟
Please keep the 1.16.5 mc version of that mod upgraded every time 😊

**Version**
Minecraft Version:older than 1.16.5 + 1.16.5
Forge Version:36 and older
Futurepack Version: 7005 and older

**Comment by Ashwinaaaaaaahdt** [comment]
> The monsters would despawn if the player died, and the monsters would despawn in a peaceful mode in which no fight is made and the player's health would be the same
> The monsters shouldn't despawn in peaceful mode like from 'Mowzie's mods 'Barako the sun chief' is a hostile mob that doesn't despawn in peaceful mode. to keep the fight running and for the vindicator better to add a separate code to make the vindicator aggressive in the dungeon only but not in the mansion
> 
> **To Reproduce**
> Steps to reproduce the behaviour:
> 1. GGo to the  dungeon monster spawner and spawn the monsters
> 2. Click on peaceful mode and monsters will despawn
> 3. Leave the world and rejoin it
> 4. The 'The wave is cleared' or 'General will be sent' message will come and allow the player to go forward.
> 
> **Additional context**
> I couldn't play 1.17 and above as I have open gl 3.0 and my computer is incompatible with the graphics card and 7008 isn't working fine😟
> Please keep the 1.16.5 mc version of that mod upgraded every time 😊
> 
> **Version**
> Minecraft Version:older than 1.16.5 + 1.16.5
> Forge Version:36 and older
> Futurepack Version: 7005 and older

**Comment by Ashwinaaaaaaahdt** [comment]
Please update and implement Asteroid , entros, envia as the unknown music disk voice of envia says to wait for updates

**Comment by mcenderdragon** [comment]
> Please update and implement Asteroid , entros, envia as the unknown music disk voice of envia says to wait for updates

why do you think I have the time to support 2 version when I dont even have the time to support one ? 

if its incompatible this would mean it also can not run any other games and can be fixed by installing the correct drivers, so I would suggest its easier to jsut fix the main issue here, your GPU.

**Comment by Ashwinaaaaaaahdt** [comment]
> > Please update and implement Asteroid , entros, envia as the unknown music disk voice of envia says to wait for updates
> 
> why do you think I have the time to support 2 version when I dont even have the time to support one ? 
> 
> if its incompatible this would mean it also can not run any other games and can be fixed by installing the correct drivers, so I would suggest its easier to jsut fix the main issue here, your GPU.

Ok what about mobs of dungeon if you can't be able to code vindicator then make a separate entity as tech vindicator  like tech zombie

**Comment by Ashwinaaaaaaahdt** [comment]
> > Please update and implement Asteroid , entros, envia as the unknown music disk voice of envia says to wait for updates
> 
> why do you think I have the time to support 2 version when I dont even have the time to support one ? 
> 
> if its incompatible this would mean it also can not run any other games and can be fixed by installing the correct drivers, so I would suggest its easier to jsut fix the main issue here, your GPU.

the driver is in the latest version but it is old integrated graphics 
The name of graphics is Intel hd 2000
but it is still unsupported to open gl above 3.4
